import { World } from "../types";

export const BUNKER_EXCECOES_WORLD: World = {
  id: "bunker-excecoes",
  title: "Bunker de Exceções",
  subtitle: "Manejo de Erros e Módulos",
  icon: "alert-triangle",
  color: "#EF4444",
  bgImage: "/assets/images/worlds/exceptions.png",
  lore: "Em sistemas críticos da CorpHQ, um único erro pode travar todo o núcleo e disparar alarmes. No Bunker de Exceções, você aprenderá a capturar erros (Try/Except) graciosamente e usar Módulos externos para estender suas capacidades.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-exc-01",
      worldId: "bunker-excecoes",
      title: "Contenção de Falhas (Try/Except)",
      description: "Tente dividir 10 por 0 usando o bloco try/except. No except, imprima 'Erro Detectado'.",
      narrative: "Uma divisão por zero causa pânico fatal no Kernel. Use o escudo Try/Except para capturar a explosão matemática e manter o sistema rodando.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Erro Detectado",
      testCode: "assert 'try:' in code and 'except:' in code and output.strip() == 'Erro Detectado'",
      starterCode: "# Crie o bloco try e o bloco except\n",
      hints: [
        { text: "A estrutura é:\ntry:\n    print(10 / 0)\nexcept:\n    print('Erro Detectado')", cost: 15 },
      ],
      xpReward: 400,
      concept: "Tratamento de Exceções",
      conceptExplanation: "O bloco `try` tenta executar um código perigoso. Se algo quebrar (como dividir por zero ou buscar uma variável que não existe), o programa não trava! Ele pula direto para o bloco `except`, permitindo que você lide com a falha educadamente.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Pânico evitado. O Kernel se manteve estável apesar do ataque aritmético.",
      solution: "try:\n    print(10 / 0)\nexcept:\n    print('Erro Detectado')",
    },
    {
      id: "py-exc-02",
      worldId: "bunker-excecoes",
      title: "Captura Específica",
      description: "A variável 'dado' contém a string 'Texto'. Tente convertê-la para int() no bloco try. Use 'except ValueError:' e imprima 'Dado Invalido'.",
      narrative: "Sempre capture a anomalia exata que você espera. O parser está lidando com strings sujas, preveja o erro de conversão de valor (ValueError).",
      difficulty: "avancado",
      setupCode: "dado = 'Texto'",
      expectedOutput: "Dado Invalido",
      testCode: "assert 'except ValueError' in code and output.strip() == 'Dado Invalido'",
      starterCode: "dado = 'Texto'\n# Tente converter para int e capture o ValueError\n",
      hints: [
        { text: "except ValueError: captura apenas erros relacionados a valores incorretos, deixando outros erros passarem para auditoria.", cost: 20 },
      ],
      xpReward: 500,
      concept: "Exceções Específicas",
      conceptExplanation: "Um simples `except:` captura TODOS os erros (até erros de digitação seus). Capturar erros específicos como `ValueError` (conversões erradas), `KeyError` (chaves de dicionário) e `IndexError` (índices de listas) é a marca de um Operador de Elite.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Sanitização robusta. O sistema filtrou os dados corruptos sem afetar o fluxo principal.",
      solution: "try:\n    numero = int(dado)\nexcept ValueError:\n    print('Dado Invalido')",
    },
    {
      id: "py-exc-03",
      worldId: "bunker-excecoes",
      title: "O Falso Alarme",
      description: "Use a instrução 'raise Exception(\"Invasor\")' para forçar um erro intencionalmente.",
      narrative: "Para despistar os rastreadores, force uma interrupção bruta no script para simular um falso ataque, mascarando sua assinatura real.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Traceback",
      testCode: "assert 'raise Exception' in code and error != ''",
      starterCode: "# Force um erro levantando uma Exception\n",
      hints: [
        { text: "Basta escrever: raise Exception('Invasor')", cost: 20 },
      ],
      xpReward: 550,
      concept: "Levantamento de Erros (raise)",
      conceptExplanation: "Às vezes VOCÊ quer que o programa pare. A instrução `raise` permite que você jogue um erro propositalmente quando detectar que algo está gravemente errado no estado da sua aplicação.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Alarme forjado com sucesso. A equipe de resposta a incidentes está caçando fantasmas.",
      solution: "raise Exception('Invasor')",
    },
    {
      id: "py-exc-04",
      worldId: "bunker-excecoes",
      title: "Armamento Externo (Imports)",
      description: "Importe o módulo 'math'. Use a função 'math.sqrt()' para calcular a raiz quadrada de 144 e imprima o resultado convertido para inteiro (int).",
      narrative: "O núcleo básico do Python não possui todas as ferramentas matemáticas avançadas. Importe o pacote de aritmética pesada para resolver essa criptografia de 2º grau.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "12",
      testCode: "assert 'import math' in code and output.strip() == '12'",
      starterCode: "# Importe o math e calcule a raiz quadrada\n",
      hints: [
        { text: "import math\nprint(int(math.sqrt(144)))", cost: 15 },
      ],
      xpReward: 450,
      concept: "Módulos (Imports)",
      conceptExplanation: "O Python possui uma 'Biblioteca Padrão' imensa de códigos já prontos. Com o comando `import`, você puxa essas ferramentas externas (como `math` para matemática complexa, `random` para aleatoriedade e `datetime` para datas) para dentro do seu script.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Arsenal importado. A barreira de criptografia foi dissolvida pelo pacote aritmético.",
      solution: "import math\nprint(int(math.sqrt(144)))",
    },
    {
      id: "py-exc-05",
      worldId: "bunker-excecoes",
      title: "Criptografia Aleatória",
      description: "Importe a função 'randint' do módulo 'random'. Gere e imprima um número aleatório entre 1 e 10. (Não precisamos validar o teste exato, apenas rode o código).",
      narrative: "Precisamos de um número semente (seed) imprevisível para gerar uma assinatura limpa. O import específico garante um payload pequeno e eficiente.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "",
      testCode: "assert 'from random import randint' in code and 'randint(1, 10)' in code",
      starterCode: "# Faça 'from random import randint' e chame a função\n",
      hints: [
        { text: "A sintaxe específica é: from random import randint", cost: 20 },
        { text: "from random import randint\nprint(randint(1, 10))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Imports Específicos",
      conceptExplanation: "Em vez de importar um módulo inteiro (pesado), você pode usar `from modulo import funcao` para puxar apenas o que você realmente precisa para a memória. O código fica mais limpo e rápido.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Aleatoriedade injetada. Seu rastro agora é completamente imprevisível.",
      solution: "from random import randint\nprint(randint(1, 10))",
    },
    {
      id: "py-exc-06",
      worldId: "bunker-excecoes",
      title: "Captura da Mensagem (as)",
      description: "No bloco try, tente acessar 'lista[10]' onde lista é [1,2,3]. No except IndexError as e, imprima a mensagem do erro convertida para string: str(e).",
      narrative: "Capturar o erro é apenas metade do trabalho. O Operador precisa LER a mensagem para diagnosticar a causa raiz da falha.",
      difficulty: "intermediario",
      setupCode: "lista = [1, 2, 3]",
      expectedOutput: "list index out of range",
      testCode: "assert 'except IndexError as' in code and 'out of range' in output",
      starterCode: "lista = [1, 2, 3]\n# Use 'except IndexError as e' e print(str(e))\n",
      hints: [
        { text: "A sintaxe é: except TipoDoErro as variavel:", cost: 10 },
        { text: "try:\n    lista[10]\nexcept IndexError as e:\n    print(str(e))", cost: 20 },
      ],
      xpReward: 500,
      concept: "except ... as",
      conceptExplanation: "A cláusula 'as' captura o OBJETO da exceção em uma variável, permitindo extrair a mensagem, atributos e fazer logging detalhado. Sem ela, você sabe que algo quebrou, mas não o quê.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Mensagem capturada. O diagnóstico foi enviado para o painel de auditoria com detalhes precisos.",
      solution: "lista = [1, 2, 3]\ntry:\n    lista[10]\nexcept IndexError as e:\n    print(str(e))",
    },
    {
      id: "py-exc-07",
      worldId: "bunker-excecoes",
      title: "Bloco Finally (Limpeza)",
      description: "Use try/except/finally. No try, force ZeroDivisionError com 1/0. No except, imprima 'erro'. No finally, imprima 'limpeza'. Saída esperada: erro / limpeza.",
      narrative: "Algumas rotinas precisam fechar conexões, liberar arquivos ou desligar drones — independente de ter dado erro ou não. O 'finally' garante essa execução.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "erro\nlimpeza",
      testCode: "assert 'finally:' in code and output.strip() == 'erro\\nlimpeza'",
      starterCode: "# Estrutura: try / except / finally\n",
      hints: [
        { text: "O finally roda SEMPRE — com ou sem erro. Ideal para liberar recursos.", cost: 15 },
        { text: "try:\n    1/0\nexcept:\n    print('erro')\nfinally:\n    print('limpeza')", cost: 25 },
      ],
      xpReward: 550,
      concept: "Cláusula finally",
      conceptExplanation: "O bloco 'finally' é executado SEMPRE após o try, dê erro ou não. É o lugar canônico para liberar recursos: fechar arquivos, encerrar conexões, devolver locks. Pense nele como 'o que precisa rodar antes de sair, custe o que custar'.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Procedimento de desligamento executado. Os recursos foram liberados mesmo após a falha.",
      solution: "try:\n    1/0\nexcept:\n    print('erro')\nfinally:\n    print('limpeza')",
    },
    {
      id: "py-exc-08",
      worldId: "bunker-excecoes",
      title: "Caminho Feliz (else)",
      description: "Use try/except/else. No try, faça 'valor = int(\"42\")' (sem erro). No except ValueError, imprima 'falha'. No else, imprima o valor convertido. Saída esperada: 42.",
      narrative: "O bloco else só roda se o try TIVER SUCESSO. Ele isola o código pós-sucesso do código de risco, deixando a intenção clara.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "42",
      testCode: "assert 'else:' in code and 'except' in code and output.strip() == '42'",
      starterCode: "# Estrutura: try / except ValueError / else\n",
      hints: [
        { text: "O else roda só se NÃO houve exceção no try. Vem ANTES do finally.", cost: 15 },
        { text: "try:\n    valor = int('42')\nexcept ValueError:\n    print('falha')\nelse:\n    print(valor)", cost: 25 },
      ],
      xpReward: 600,
      concept: "Cláusula else no try",
      conceptExplanation: "O 'else' em try/except roda quando NADA falhou. Útil para separar o código que 'continua o caminho feliz' do código arriscado dentro do try, deixando explícito o que depende do sucesso.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Conversão bem-sucedida. O fluxo pós-validação executou no caminho limpo.",
      solution: "try:\n    valor = int('42')\nexcept ValueError:\n    print('falha')\nelse:\n    print(valor)",
    },
    {
      id: "py-exc-09",
      worldId: "bunker-excecoes",
      title: "Múltiplos Vetores de Erro",
      description: "No try, faça int(\"abc\"). Tenha DOIS excepts separados: 'except ValueError:' imprime 'valor' e 'except KeyError:' imprime 'chave'. Saída esperada: valor.",
      narrative: "Cada tipo de ataque requer uma resposta diferente. Estruture múltiplos handlers para reagir adequadamente a cada vetor.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "valor",
      testCode: "assert 'except ValueError' in code and 'except KeyError' in code and output.strip() == 'valor'",
      starterCode: "# Dois blocos except, em ordem do mais específico ao mais genérico\n",
      hints: [
        { text: "Você pode encadear vários except. O Python pega o primeiro que casa.", cost: 15 },
        { text: "try:\n    int('abc')\nexcept ValueError:\n    print('valor')\nexcept KeyError:\n    print('chave')", cost: 25 },
      ],
      xpReward: 650,
      concept: "Múltiplos except",
      conceptExplanation: "Você pode ter quantos 'except' quiser depois de um try. O Python testa de cima para baixo e executa só o primeiro que combinar com o erro. Coloque os mais específicos primeiro para evitar que um genérico engula tudo.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Roteamento de erros ativo. Cada categoria de falha tem seu handler dedicado.",
      solution: "try:\n    int('abc')\nexcept ValueError:\n    print('valor')\nexcept KeyError:\n    print('chave')",
    },
    {
      id: "py-exc-10",
      worldId: "bunker-excecoes",
      title: "Captura Agrupada (Tupla)",
      description: "No try, faça int(\"abc\"). Em um ÚNICO except, capture tanto ValueError quanto TypeError usando uma tupla. Imprima 'erro_dado'.",
      narrative: "Quando vários tipos de falha pedem o mesmo tratamento, agrupe-os em um único handler usando uma tupla.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "erro_dado",
      testCode: "assert '(ValueError' in code and 'TypeError)' in code and output.strip() == 'erro_dado'",
      starterCode: "# except (ValueError, TypeError): ...\n",
      hints: [
        { text: "Use parênteses: except (ValueError, TypeError):", cost: 15 },
        { text: "try:\n    int('abc')\nexcept (ValueError, TypeError):\n    print('erro_dado')", cost: 25 },
      ],
      xpReward: 700,
      concept: "Tupla de Exceções",
      conceptExplanation: "Quando múltiplos tipos de erro pedem o MESMO tratamento, agrupe-os em uma tupla dentro do except. Economiza repetição de código e deixa a intenção clara: 'qualquer um desses, mesma resposta'.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Handler unificado. Múltiplos vetores convergem para o mesmo protocolo de resposta.",
      solution: "try:\n    int('abc')\nexcept (ValueError, TypeError):\n    print('erro_dado')",
    },
    {
      id: "py-exc-11",
      worldId: "bunker-excecoes",
      title: "Falha de Chave (KeyError)",
      description: "Dado 'config = {\"host\": \"local\"}', tente acessar config['porta'] no try. Capture 'except KeyError:' e imprima 'chave_ausente'.",
      narrative: "Pacotes mal-formados podem omitir campos essenciais. Capture KeyError especificamente para falhas de configuração.",
      difficulty: "intermediario",
      setupCode: "config = {'host': 'local'}",
      expectedOutput: "chave_ausente",
      testCode: "assert 'except KeyError' in code and output.strip() == 'chave_ausente'",
      starterCode: "config = {'host': 'local'}\n# Tente acessar config['porta'] e capture KeyError\n",
      hints: [
        { text: "Acessar uma chave inexistente dispara KeyError automaticamente.", cost: 10 },
        { text: "try:\n    config['porta']\nexcept KeyError:\n    print('chave_ausente')", cost: 20 },
      ],
      xpReward: 550,
      concept: "KeyError",
      conceptExplanation: "KeyError é disparado quando você tenta acessar uma chave que não existe em um dicionário. Diferente do .get() que retorna None, o acesso direto com [] explode se a chave não existir.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Configuração incompleta detectada. O sistema operou em modo seguro.",
      solution: "config = {'host': 'local'}\ntry:\n    config['porta']\nexcept KeyError:\n    print('chave_ausente')",
    },
    {
      id: "py-exc-12",
      worldId: "bunker-excecoes",
      title: "Índice Fora dos Limites (IndexError)",
      description: "Dada 'lista = [10, 20]', tente acessar lista[5]. Capture 'except IndexError:' e imprima 'fora_dos_limites'.",
      narrative: "Listas pequenas e índices grandes resultam em explosão. Antecipe esse vetor de falha em loops sobre dados de origem desconhecida.",
      difficulty: "intermediario",
      setupCode: "lista = [10, 20]",
      expectedOutput: "fora_dos_limites",
      testCode: "assert 'except IndexError' in code and output.strip() == 'fora_dos_limites'",
      starterCode: "lista = [10, 20]\n# Tente lista[5] e capture IndexError\n",
      hints: [
        { text: "Acessar índice maior que len(lista)-1 dispara IndexError.", cost: 10 },
        { text: "try:\n    lista[5]\nexcept IndexError:\n    print('fora_dos_limites')", cost: 20 },
      ],
      xpReward: 550,
      concept: "IndexError",
      conceptExplanation: "IndexError surge quando você tenta acessar uma posição que não existe em uma lista, tupla ou string. É comum em loops mal calibrados e em parsing de dados externos sem validação prévia.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Tentativa de leitura fora do buffer bloqueada. Possível overflow neutralizado.",
      solution: "lista = [10, 20]\ntry:\n    lista[5]\nexcept IndexError:\n    print('fora_dos_limites')",
    },
    {
      id: "py-exc-13",
      worldId: "bunker-excecoes",
      title: "Tipos Incompatíveis (TypeError)",
      description: "No try, tente somar 'len(5)' (len não aceita int). Capture 'except TypeError:' e imprima 'tipo_invalido'.",
      narrative: "Operações com tipos errados são causa frequente de crashes em produção. Detecte-os antes que escalem.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "tipo_invalido",
      testCode: "assert 'except TypeError' in code and output.strip() == 'tipo_invalido'",
      starterCode: "# Tente len(5) e capture TypeError\n",
      hints: [
        { text: "len() só aceita objetos iteráveis — passar int dispara TypeError.", cost: 10 },
        { text: "try:\n    len(5)\nexcept TypeError:\n    print('tipo_invalido')", cost: 20 },
      ],
      xpReward: 600,
      concept: "TypeError",
      conceptExplanation: "TypeError é o aviso do Python de que uma operação não faz sentido para os tipos passados: somar string com int, chamar len() em número, multiplicar listas por listas. Em sistemas dinâmicos, esse erro aparece em runtime — capture cedo.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Mismatch de tipos isolado. O pipeline continua sem propagar o erro para os módulos a jusante.",
      solution: "try:\n    len(5)\nexcept TypeError:\n    print('tipo_invalido')",
    },
    {
      id: "py-exc-14",
      worldId: "bunker-excecoes",
      title: "Divisão Aritmética Inválida",
      description: "No try, faça 100/0. Capture 'except ZeroDivisionError:' e imprima 'div_zero'. Logo após o try, imprima 'continuou' — para provar que o programa não travou.",
      narrative: "Demonstre que o sistema sobrevive ao colapso aritmético e segue executando os próximos passos.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "div_zero\ncontinuou",
      testCode: "assert 'except ZeroDivisionError' in code and output.strip() == 'div_zero\\ncontinuou'",
      starterCode: "# try com 100/0, except ZeroDivisionError, e depois print('continuou')\n",
      hints: [
        { text: "try:\n    100/0\nexcept ZeroDivisionError:\n    print('div_zero')\nprint('continuou')", cost: 20 },
      ],
      xpReward: 550,
      concept: "ZeroDivisionError",
      conceptExplanation: "ZeroDivisionError protege seu sistema da matemática impossível. Cubra qualquer cálculo onde o denominador venha de input externo — é o exemplo clássico de erro previsível em produção.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Núcleo aritmético preservado. O sistema continuou o pipeline após neutralizar a divisão impossível.",
      solution: "try:\n    100/0\nexcept ZeroDivisionError:\n    print('div_zero')\nprint('continuou')",
    },
    {
      id: "py-exc-15",
      worldId: "bunker-excecoes",
      title: "Exceção Customizada",
      description: "Crie uma classe 'AcessoNegadoError' que herda de Exception. No try, faça 'raise AcessoNegadoError(\"sem permissao\")'. Capture-a e imprima a mensagem com str(e).",
      narrative: "Erros genéricos não comunicam a natureza específica da falha. Crie tipos próprios para erros do seu domínio — autenticação, regras de negócio, validação.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "sem permissao",
      testCode: "assert 'class AcessoNegadoError' in code and 'Exception' in code and output.strip() == 'sem permissao'",
      starterCode: "# Defina a classe, dispare com raise, capture com except\n",
      hints: [
        { text: "class AcessoNegadoError(Exception):\n    pass", cost: 15 },
        { text: "try:\n    raise AcessoNegadoError('sem permissao')\nexcept AcessoNegadoError as e:\n    print(str(e))", cost: 25 },
      ],
      xpReward: 850,
      concept: "Exceções Customizadas",
      conceptExplanation: "Você pode criar suas próprias exceções herdando de Exception. Isso permite criar uma hierarquia de erros específica do seu domínio (AcessoNegadoError, SaldoInsuficienteError, etc.), tornando o tratamento muito mais expressivo do que usar Exception genérica.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Categoria de erro registrada no protocolo. A taxonomia interna agora distingue falhas por domínio.",
      solution: "class AcessoNegadoError(Exception):\n    pass\n\ntry:\n    raise AcessoNegadoError('sem permissao')\nexcept AcessoNegadoError as e:\n    print(str(e))",
    },
    {
      id: "py-exc-16",
      worldId: "bunker-excecoes",
      title: "Re-lançar Após Logar (raise)",
      description: "No try, faça int('xyz'). No except, imprima 'logado' e DEPOIS use 'raise' (sem argumentos) para repropagar o erro. O programa deve quebrar com traceback.",
      narrative: "Às vezes você só quer registrar a falha mas deixar que ela continue subindo na pilha. O 'raise' nu reenvia o erro original sem perder o contexto.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "logado",
      testCode: "assert 'raise' in code and 'logado' in output and error != ''",
      starterCode: "# try / except / log / raise (sem argumento)\n",
      hints: [
        { text: "Dentro do except, basta 'raise' sem nada para repropagar.", cost: 15 },
        { text: "try:\n    int('xyz')\nexcept ValueError:\n    print('logado')\n    raise", cost: 25 },
      ],
      xpReward: 800,
      concept: "Re-raise",
      conceptExplanation: "Dentro de um except, 'raise' sem argumentos repropaga o erro original — preservando stack trace e tipo. Ideal quando você quer logar/auditar mas não suprimir: o handler superior ainda pode tratar.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Falha registrada no log e devolvida ao escalonamento superior. Auditoria intacta.",
      solution: "try:\n    int('xyz')\nexcept ValueError:\n    print('logado')\n    raise",
    },
    {
      id: "py-exc-17",
      worldId: "bunker-excecoes",
      title: "Timestamp do Sistema (datetime)",
      description: "Importe 'datetime' do módulo 'datetime'. Chame datetime.now() e armazene em 'agora'. Imprima o type(agora) — deve aparecer datetime.datetime.",
      narrative: "Toda operação precisa de timestamp para registro. Use o módulo padrão para obter o horário atual com precisão.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "<class 'datetime.datetime'>",
      testCode: "assert 'from datetime import datetime' in code and 'datetime.datetime' in output",
      starterCode: "# from datetime import datetime ; agora = datetime.now()\n",
      hints: [
        { text: "from datetime import datetime", cost: 15 },
        { text: "agora = datetime.now()\nprint(type(agora))", cost: 20 },
      ],
      xpReward: 600,
      concept: "Módulo datetime",
      conceptExplanation: "O módulo datetime fornece as classes para manipular datas e horários. datetime.now() retorna o instante atual. Outras úteis: date.today(), timedelta para diferenças, strftime para formatar.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Carimbo temporal aplicado. Toda operação agora carrega o instante exato de execução.",
      solution: "from datetime import datetime\nagora = datetime.now()\nprint(type(agora))",
    },
    {
      id: "py-exc-18",
      worldId: "bunker-excecoes",
      title: "Escolha Aleatória (random.choice)",
      description: "Importe 'choice' do módulo 'random'. Use choice(['a','b','c']) para escolher um item da lista e imprima. (O teste apenas valida que o código está correto, não o item específico).",
      narrative: "Selecione uma rota de fuga aleatória dentre as opções disponíveis. Para evitar padrões previsíveis, deixe que o gerador escolha.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "",
      testCode: "assert 'from random import choice' in code and 'choice([' in code",
      starterCode: "# from random import choice e use em uma lista\n",
      hints: [
        { text: "choice(lista) devolve um elemento aleatório dela.", cost: 15 },
        { text: "from random import choice\nprint(choice(['a', 'b', 'c']))", cost: 20 },
      ],
      xpReward: 600,
      concept: "random.choice",
      conceptExplanation: "choice() é a forma mais simples de escolher um item aleatório de uma sequência. Combinada com sample() (vários itens sem repetir) e shuffle() (embaralha lista in-place), forma o trio principal do módulo random para sorteios.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Rota selecionada aleatoriamente. O padrão de exfiltração permanece imprevisível.",
      solution: "from random import choice\nprint(choice(['a', 'b', 'c']))",
    },
    {
      id: "py-exc-19",
      worldId: "bunker-excecoes",
      title: "Alias de Módulo (import as)",
      description: "Importe 'math' com o apelido 'm' (import math as m). Use m.pi para imprimir o valor de pi.",
      narrative: "Para nomes longos ou conflitos de namespace, use aliases. Mantém o código legível e expressivo.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "3.141592653589793",
      testCode: "assert 'import math as' in code and '3.14' in output",
      starterCode: "# import math as m e imprima m.pi\n",
      hints: [
        { text: "Sintaxe: import modulo as apelido", cost: 15 },
        { text: "import math as m\nprint(m.pi)", cost: 20 },
      ],
      xpReward: 600,
      concept: "Aliases de Import",
      conceptExplanation: "'import X as Y' renomeia o módulo no escopo atual. Usado por convenção em algumas libs ('import numpy as np', 'import pandas as pd'). Também resolve conflitos quando dois módulos têm o mesmo nome.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Namespace abreviado. O código ganhou densidade sem perder clareza.",
      solution: "import math as m\nprint(m.pi)",
    },
    {
      id: "py-exc-20",
      worldId: "bunker-excecoes",
      title: "Inspeção do Runtime (sys)",
      description: "Importe o módulo 'sys'. Imprima o type(sys.version) — deve aparecer 'str' (já que sys.version é uma string com a versão do interpretador).",
      narrative: "Sistemas profissionais precisam conhecer seu próprio ambiente. O módulo sys expõe o estado do interpretador Python ativo.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "<class 'str'>",
      testCode: "assert 'import sys' in code and 'sys.version' in code and \"<class 'str'>\" in output",
      starterCode: "# import sys e print(type(sys.version))\n",
      hints: [
        { text: "sys.version é uma string com a versão completa do Python.", cost: 15 },
        { text: "import sys\nprint(type(sys.version))", cost: 20 },
      ],
      xpReward: 700,
      concept: "Módulo sys",
      conceptExplanation: "O módulo sys dá acesso a aspectos internos do interpretador: sys.version, sys.argv (argumentos da linha de comando), sys.exit() (encerrar), sys.path (onde o Python busca módulos). Essencial para scripts que precisam se adaptar ao ambiente.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Diagnóstico de runtime concluído. O sistema documentou seu próprio ambiente de execução.",
      solution: "import sys\nprint(type(sys.version))",
    },
  ],
};
