import { World } from "../types";

export const BUNKER_EXCECOES_WORLD: World = {
  id: "bunker-excecoes",
  title: "Bunker de Exceções",
  subtitle: "Manejo de Erros e Módulos",
  icon: "alert-triangle",
  color: "#EF4444",
  bgImage: "/assets/images/worlds/exception_bunker.png",
  lore: "Em sistemas críticos da CorpHQ, um único erro pode travar todo o núcleo e disparar alarmes. No Bunker de Exceções, você aprenderá a capturar erros (Try/Except) graciosamente e usar Módulos externos para estender suas capacidades.",
  unlockRequirement: 25000,
  challenges: [
    {
      id: "py-exc-01",
      worldId: "bunker-excecoes",
      title: "Contenção de Falhas (Try/Except)",
      description: "Tente dividir 10 por 0 usando o bloco try/except. No except, imprima 'Erro Detectado'.",
      narrative: "Uma divisão por zero causa pânico fatal no Kernel. Use o escudo Try/Except para capturar a explosão matemática e manter o sistema rodando.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Erro Detectado",
      testCode: "assert 'try:' in code and 'except:' in code and output.strip() == 'Erro Detectado'",
      starterCode: "# Crie o bloco try e o bloco except\n",
      hints: [
        { text: "A estrutura é:\ntry:\n    print(10 / 0)\nexcept:\n    print('Erro Detectado')", cost: 15 },
      ],
      xpReward: 400,
      concept: "Tratamento de Exceções",
      conceptExplanation: "O bloco `try` tenta executar um código perigoso. Se algo quebrar (como dividir por zero ou buscar uma variável que não existe), o programa não trava! Ele pula direto para o bloco `except`, permitindo que você lide com a falha educadamente.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Pânico evitado. O Kernel se manteve estável apesar do ataque aritmético.",
      solution: "try:\n    print(10 / 0)\nexcept:\n    print('Erro Detectado')",
    },
    {
      id: "py-exc-02",
      worldId: "bunker-excecoes",
      title: "Captura Específica",
      description: "A variável 'dado' contém a string 'Texto'. Tente convertê-la para int() no bloco try. Use 'except ValueError:' e imprima 'Dado Invalido'.",
      narrative: "Sempre capture a anomalia exata que você espera. O parser está lidando com strings sujas, preveja o erro de conversão de valor (ValueError).",
      difficulty: "avancado",
      setupCode: "dado = 'Texto'",
      expectedOutput: "Dado Invalido",
      testCode: "assert 'except ValueError' in code and output.strip() == 'Dado Invalido'",
      starterCode: "dado = 'Texto'\n# Tente converter para int e capture o ValueError\n",
      hints: [
        { text: "except ValueError: captura apenas erros relacionados a valores incorretos, deixando outros erros passarem para auditoria.", cost: 20 },
      ],
      xpReward: 500,
      concept: "Exceções Específicas",
      conceptExplanation: "Um simples `except:` captura TODOS os erros (até erros de digitação seus). Capturar erros específicos como `ValueError` (conversões erradas), `KeyError` (chaves de dicionário) e `IndexError` (índices de listas) é a marca de um Operador de Elite.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Sanitização robusta. O sistema filtrou os dados corruptos sem afetar o fluxo principal.",
      solution: "try:\n    numero = int(dado)\nexcept ValueError:\n    print('Dado Invalido')",
    },
    {
      id: "py-exc-03",
      worldId: "bunker-excecoes",
      title: "O Falso Alarme",
      description: "Use a instrução 'raise Exception(\"Invasor\")' para forçar um erro intencionalmente.",
      narrative: "Para despistar os rastreadores, force uma interrupção bruta no script para simular um falso ataque, mascarando sua assinatura real.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Traceback",
      testCode: "assert 'raise Exception' in code and error != ''",
      starterCode: "# Force um erro levantando uma Exception\n",
      hints: [
        { text: "Basta escrever: raise Exception('Invasor')", cost: 20 },
      ],
      xpReward: 550,
      concept: "Levantamento de Erros (raise)",
      conceptExplanation: "Às vezes VOCÊ quer que o programa pare. A instrução `raise` permite que você jogue um erro propositalmente quando detectar que algo está gravemente errado no estado da sua aplicação.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Alarme forjado com sucesso. A equipe de resposta a incidentes está caçando fantasmas.",
      solution: "raise Exception('Invasor')",
    },
    {
      id: "py-exc-04",
      worldId: "bunker-excecoes",
      title: "Armamento Externo (Imports)",
      description: "Importe o módulo 'math'. Use a função 'math.sqrt()' para calcular a raiz quadrada de 144 e imprima o resultado convertido para inteiro (int).",
      narrative: "O núcleo básico do Python não possui todas as ferramentas matemáticas avançadas. Importe o pacote de aritmética pesada para resolver essa criptografia de 2º grau.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "12",
      testCode: "assert 'import math' in code and output.strip() == '12'",
      starterCode: "# Importe o math e calcule a raiz quadrada\n",
      hints: [
        { text: "import math\nprint(int(math.sqrt(144)))", cost: 15 },
      ],
      xpReward: 450,
      concept: "Módulos (Imports)",
      conceptExplanation: "O Python possui uma 'Biblioteca Padrão' imensa de códigos já prontos. Com o comando `import`, você puxa essas ferramentas externas (como `math` para matemática complexa, `random` para aleatoriedade e `datetime` para datas) para dentro do seu script.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Arsenal importado. A barreira de criptografia foi dissolvida pelo pacote aritmético.",
      solution: "import math\nprint(int(math.sqrt(144)))",
    },
    {
      id: "py-exc-05",
      worldId: "bunker-excecoes",
      title: "Criptografia Aleatória",
      description: "Importe a função 'randint' do módulo 'random'. Gere e imprima um número aleatório entre 1 e 10. (Não precisamos validar o teste exato, apenas rode o código).",
      narrative: "Precisamos de um número semente (seed) imprevisível para gerar uma assinatura limpa. O import específico garante um payload pequeno e eficiente.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "",
      testCode: "assert 'from random import randint' in code and 'randint(1, 10)' in code",
      starterCode: "# Faça 'from random import randint' e chame a função\n",
      hints: [
        { text: "A sintaxe específica é: from random import randint", cost: 20 },
        { text: "from random import randint\nprint(randint(1, 10))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Imports Específicos",
      conceptExplanation: "Em vez de importar um módulo inteiro (pesado), você pode usar `from modulo import funcao` para puxar apenas o que você realmente precisa para a memória. O código fica mais limpo e rápido.",
      successNpc: "Mestre da Resiliência",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Aleatoriedade injetada. Seu rastro agora é completamente imprevisível.",
      solution: "from random import randint\nprint(randint(1, 10))",
    },
  ],
};
