import { World } from "../types";

export const CAMARA_PROBABILIDADES_WORLD: World = {
  id: "camara-probabilidades",
  title: "Câmara de Probabilidades",
  subtitle: "Estatística e Inferência",
  icon: "sigma",
  color: "#34D399",
  bgImage: "/assets/images/worlds/probability_chamber.png",
  lore: "Sem pensamento estatístico, você apenas roda modelos. Aqui você aprende a interpretar dados com rigor: testes de hipótese, distribuições, p-values e inferência bayesiana.",
  unlockRequirement: 22000,
  challenges: [
    {
      id: "ds-stat-01",
      worldId: "camara-probabilidades",
      title: "Média, Mediana e Moda",
      description: "Dado dados=[2,4,4,4,5,5,7,9], calcule e imprima a média (mean) e a mediana (median) usando statistics.",
      narrative: "As três medidas de tendência central são a primeira linha de inspeção.",
      difficulty: "iniciante",
      setupCode: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]",
      expectedOutput: "5\n4.5",
      testCode: "assert 'statistics.mean' in code and 'statistics.median' in code",
      starterCode: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]\n# Imprima média e mediana, uma por linha\n",
      hints: [
        { text: "statistics.mean(dados) calcula a média; statistics.median(dados) calcula a mediana.", cost: 10 },
        { text: "Imprima cada uma em linhas separadas com dois print().", cost: 20 },
        { text: "print(statistics.mean(dados))\\nprint(statistics.median(dados))", cost: 30 },
      ],
      xpReward: 500,
      concept: "Tendência Central",
      conceptExplanation: "Três medidas de TENDÊNCIA CENTRAL resumem onde os dados se concentram: (1) MÉDIA — soma dividida por N, sensível a outliers (um valor extremo arrasta a média); (2) MEDIANA — o valor do meio quando ordenado, robusta a outliers; (3) MODA — valor mais frequente, útil em categóricos. Quando média e mediana são iguais, distribuição é simétrica. Quando média > mediana, distribuição puxada para a direita (renda, por exemplo). Salário médio engana porque alguns CEOs distorcem; mediana de salário é mais honesta.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Centro da distribuição identificado.",
      solution: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]\nprint(statistics.mean(dados))\nprint(statistics.median(dados))",
    },
    {
      id: "ds-stat-02",
      worldId: "camara-probabilidades",
      title: "Variância e Desvio Padrão",
      description: "Calcule statistics.variance(dados) e statistics.stdev(dados), imprima cada um.",
      narrative: "Medidas de dispersão revelam quão espalhados estão os dados.",
      difficulty: "iniciante",
      setupCode: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]",
      expectedOutput: "4.571428571428571\n2.138089935299395",
      testCode: "assert 'statistics.variance' in code and 'statistics.stdev' in code",
      starterCode: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]\n# Imprima variância e desvio padrão\n",
      hints: [
        { text: "statistics.variance(dados) calcula a variância amostral; stdev é a raiz da variância.", cost: 10 },
        { text: "Imprima em linhas separadas.", cost: 20 },
        { text: "print(statistics.variance(dados))\\nprint(statistics.stdev(dados))", cost: 30 },
      ],
      xpReward: 550,
      concept: "Dispersão (Variância e Desvio Padrão)",
      conceptExplanation: "Variância e desvio padrão medem DISPERSÃO — quão longe os pontos estão da média. VARIÂNCIA = média dos quadrados dos desvios (unidade ao quadrado, difícil interpretar). DESVIO PADRÃO = raiz quadrada da variância (mesma unidade dos dados, interpretável diretamente). Em distribuição normal, ~68% dos dados ficam dentro de ±1 desvio padrão da média, ~95% dentro de ±2σ, ~99.7% dentro de ±3σ (regra empírica). statistics.variance é AMOSTRAL (n-1 no denominador); statistics.pvariance é POPULACIONAL (n).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Dispersão quantificada.",
      solution: "import statistics\ndados = [2, 4, 4, 4, 5, 5, 7, 9]\nprint(statistics.variance(dados))\nprint(statistics.stdev(dados))",
    },
    {
      id: "ds-stat-03",
      worldId: "camara-probabilidades",
      title: "Distribuição Normal",
      description: "Use stats.norm.pdf(0, loc=0, scale=1) para calcular a densidade no ponto 0 da normal padrão. Imprima.",
      narrative: "A curva de sino governa metade da estatística clássica.",
      difficulty: "intermediario",
      setupCode: "class norm_mock:\n    @staticmethod\n    def pdf(x, loc=0, scale=1): return 0.3989422804014327\nclass stats_mock:\n    norm = norm_mock()\nstats = stats_mock()",
      expectedOutput: "0.3989422804014327",
      testCode: "assert 'norm.pdf' in code",
      starterCode: "from scipy import stats\n# Imprima a densidade no ponto 0\n",
      hints: [
        { text: "stats.norm é a distribuição normal. PDF (densidade) é avaliada em um ponto.", cost: 20 },
        { text: "loc é a média (μ), scale é o desvio padrão (σ). Normal padrão: loc=0, scale=1.", cost: 25 },
        { text: "print(stats.norm.pdf(0, loc=0, scale=1))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Distribuição Normal",
      conceptExplanation: "A NORMAL (gaussiana) é a distribuição mais importante em estatística — formato de sino simétrico, definida por dois parâmetros: μ (média, centro) e σ (desvio padrão, largura). Aparece em fenômenos naturais (altura, erro de medição), no Teorema do Limite Central, e é a base de testes paramétricos (t, ANOVA, regressão). scipy.stats.norm oferece: pdf (densidade), cdf (probabilidade acumulada), ppf (quantis inversos), rvs (amostragem). Normal padrão: μ=0, σ=1 — sempre que você normaliza dados com z-score, você os move para essa distribuição.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Curva de sino mapeada.",
      solution: "from scipy import stats\nprint(stats.norm.pdf(0, loc=0, scale=1))",
    },
    {
      id: "ds-stat-04",
      worldId: "camara-probabilidades",
      title: "Z-Score",
      description: "Dado valor=85, média=70, desvio=10. Calcule z = (valor - média) / desvio e imprima.",
      narrative: "Z-score normaliza qualquer valor em unidades de desvio padrão.",
      difficulty: "intermediario",
      setupCode: "valor = 85\nmedia = 70\ndesvio = 10",
      expectedOutput: "1.5",
      testCode: "assert '/ desvio' in code or '/desvio' in code",
      starterCode: "valor = 85\nmedia = 70\ndesvio = 10\n# Calcule e imprima o z-score\n",
      hints: [
        { text: "Z-score = (valor - média) / desvio padrão. Mede quantos desvios padrão o valor está da média.", cost: 15 },
        { text: "Z positivo = acima da média; negativo = abaixo. |Z| > 3 geralmente indica outlier.", cost: 20 },
        { text: "z = (valor - media) / desvio\\nprint(z)", cost: 30 },
      ],
      xpReward: 600,
      concept: "Z-Score (Padronização)",
      conceptExplanation: "Z-score (ou padronização) transforma um valor em UNIDADES DE DESVIO PADRÃO em relação à média: z = (x - μ) / σ. Z=0 é exatamente a média; Z=1 é um desvio acima; Z=-1.5 é 1.5 desvios abaixo. Em normal padrão, |z| > 2 ocorre em ~5% das vezes; |z| > 3 em 0.3% — daí 'regra do 3-sigma' para outliers. Z-score é a base do StandardScaler do sklearn: padronizar features antes de modelos como KNN, SVM e redes neurais é essencial — sem isso, features com escala maior dominam o aprendizado.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Valor padronizado em desvios.",
      solution: "valor = 85\nmedia = 70\ndesvio = 10\nz = (valor - media) / desvio\nprint(z)",
    },
    {
      id: "ds-stat-05",
      worldId: "camara-probabilidades",
      title: "CDF (Probabilidade Acumulada)",
      description: "Use stats.norm.cdf(1.96) para calcular P(Z ≤ 1.96) na normal padrão. Imprima.",
      narrative: "CDF responde: qual a probabilidade de ser MENOR OU IGUAL a X?",
      difficulty: "intermediario",
      setupCode: "class norm_mock:\n    @staticmethod\n    def cdf(x): return 0.9750021048517795\nclass stats_mock:\n    norm = norm_mock()\nstats = stats_mock()",
      expectedOutput: "0.9750021048517795",
      testCode: "assert 'norm.cdf' in code",
      starterCode: "from scipy import stats\n# stats.norm.cdf(1.96)\n",
      hints: [
        { text: "CDF (Cumulative Distribution Function) retorna P(X ≤ valor) — probabilidade acumulada até esse ponto.", cost: 20 },
        { text: "1.96 é o valor crítico clássico em z — cdf retorna 0.975 (95% bilateral).", cost: 25 },
        { text: "print(stats.norm.cdf(1.96))", cost: 30 },
      ],
      xpReward: 700,
      concept: "PDF vs CDF",
      conceptExplanation: "Toda distribuição de probabilidade tem duas funções centrais: PDF (Probability Density Function) — para variáveis contínuas, mede a 'densidade' em um ponto (NÃO é probabilidade direta — a probabilidade de um único ponto é zero); CDF (Cumulative Distribution Function) — retorna P(X ≤ valor), probabilidade acumulada até esse ponto. Para discretas (binomial, Poisson), usa-se PMF em vez de PDF. PPF (Percent Point Function) é o inverso da CDF — você passa probabilidade e recebe o valor crítico (ex: stats.norm.ppf(0.975) = 1.96). Esses três métodos respondem 99% das perguntas de probabilidade.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Probabilidade acumulada calculada.",
      solution: "from scipy import stats\nprint(stats.norm.cdf(1.96))",
    },
    {
      id: "ds-stat-06",
      worldId: "camara-probabilidades",
      title: "Distribuição Binomial",
      description: "Calcule stats.binom.pmf(k=3, n=10, p=0.5) — probabilidade de exatamente 3 sucessos em 10 tentativas com p=0.5. Imprima.",
      narrative: "Eventos binários: sucesso ou fracasso, repetidos N vezes.",
      difficulty: "intermediario",
      setupCode: "class binom_mock:\n    @staticmethod\n    def pmf(k, n, p): return 0.1171875\nclass stats_mock:\n    binom = binom_mock()\nstats = stats_mock()",
      expectedOutput: "0.1171875",
      testCode: "assert 'binom.pmf' in code",
      starterCode: "from scipy import stats\n# stats.binom.pmf(k=3, n=10, p=0.5)\n",
      hints: [
        { text: "Binomial conta sucessos em N tentativas independentes com mesma probabilidade p.", cost: 20 },
        { text: "PMF (Probability Mass Function) para discretas é o equivalente da PDF para contínuas.", cost: 25 },
        { text: "print(stats.binom.pmf(k=3, n=10, p=0.5))", cost: 30 },
      ],
      xpReward: 750,
      concept: "Distribuição Binomial",
      conceptExplanation: "Binomial modela contagem de SUCESSOS em N tentativas INDEPENDENTES, cada uma com mesma probabilidade p de sucesso. Parâmetros: n (tentativas), p (prob por tentativa), k (número de sucessos contados). Aplicações: lances de moeda, taxa de conversão, controle de qualidade, A/B testing. Para discreta, use PMF (não PDF). Média = n*p, variância = n*p*(1-p). Para N grande e p moderado, aproxima-se da Normal (Teorema do Limite Central). Para N grande e p pequeno, aproxima-se da Poisson. Cousins: Bernoulli (n=1), Negativa Binomial (esperar K sucessos).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Probabilidade de sucessos isolada.",
      solution: "from scipy import stats\nprint(stats.binom.pmf(k=3, n=10, p=0.5))",
    },
    {
      id: "ds-stat-07",
      worldId: "camara-probabilidades",
      title: "Distribuição de Poisson",
      description: "Calcule stats.poisson.pmf(k=5, mu=3) — probabilidade de 5 eventos quando taxa é 3. Imprima.",
      narrative: "Para contar eventos raros em intervalos de tempo ou espaço.",
      difficulty: "intermediario",
      setupCode: "class poisson_mock:\n    @staticmethod\n    def pmf(k, mu): return 0.10081881344492448\nclass stats_mock:\n    poisson = poisson_mock()\nstats = stats_mock()",
      expectedOutput: "0.10081881344492448",
      testCode: "assert 'poisson.pmf' in code",
      starterCode: "from scipy import stats\n# stats.poisson.pmf(k=5, mu=3)\n",
      hints: [
        { text: "Poisson modela contagem de eventos quando você só sabe a taxa média (mu) — não precisa de N tentativas fixo.", cost: 20 },
        { text: "Exemplos: chamadas/hora em call center, defeitos/m², acessos/minuto em servidor.", cost: 25 },
        { text: "print(stats.poisson.pmf(k=5, mu=3))", cost: 30 },
      ],
      xpReward: 750,
      concept: "Distribuição de Poisson",
      conceptExplanation: "Poisson modela contagem de eventos em intervalo fixo (tempo, área, volume) quando: (1) eventos são INDEPENDENTES; (2) taxa média é constante; (3) eventos não ocorrem simultaneamente. Parâmetro único: λ (lambda) = taxa média = média = variância. Aplicações: chamadas em call center, acidentes por dia, fótons em sensor, mutações de DNA, requests em servidor. Conexão com binomial: Poisson é o LIMITE de Binomial(n, p) quando n→∞, p→0, n*p=λ constante. Em ML moderno, usada para modelar dados de contagem (Poisson Regression).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo de eventos raros aplicado.",
      solution: "from scipy import stats\nprint(stats.poisson.pmf(k=5, mu=3))",
    },
    {
      id: "ds-stat-08",
      worldId: "camara-probabilidades",
      title: "Quartis e Percentis",
      description: "Use np.percentile(dados, 75) para calcular o terceiro quartil (Q3). Imprima.",
      narrative: "Quartis dividem os dados ordenados em quatro partes iguais.",
      difficulty: "intermediario",
      setupCode: "import numpy as np\ndados = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]",
      expectedOutput: "7.75",
      testCode: "assert 'np.percentile' in code or 'np.quantile' in code",
      starterCode: "import numpy as np\ndados = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]\n# Imprima o percentil 75\n",
      hints: [
        { text: "np.percentile(dados, 75) retorna o valor abaixo do qual ficam 75% dos dados.", cost: 20 },
        { text: "Q1=25, Q2=50 (mediana), Q3=75. IQR (intervalo interquartil) = Q3 - Q1.", cost: 25 },
        { text: "print(np.percentile(dados, 75))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Quartis, Percentis e IQR",
      conceptExplanation: "Percentil P é o valor abaixo do qual ficam P% dos dados ordenados. QUARTIS são percentis especiais: Q1=25 (primeiro quartil), Q2=50 (mediana), Q3=75 (terceiro quartil). IQR (Interquartile Range) = Q3 - Q1 = intervalo central com 50% dos dados — robusto a outliers, diferente do desvio padrão. Regra de outlier de Tukey: x > Q3 + 1.5*IQR ou x < Q1 - 1.5*IQR é candidato a outlier (base do boxplot). df.quantile(0.75) no pandas faz o mesmo. Decis (10%, 20%...90%) e centis também são comuns.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Quantil isolado.",
      solution: "import numpy as np\nprint(np.percentile([1,2,3,4,5,6,7,8,9,10], 75))",
    },
    {
      id: "ds-stat-09",
      worldId: "camara-probabilidades",
      title: "Correlação de Pearson",
      description: "Use stats.pearsonr(x, y) e imprima o coeficiente (primeiro retorno).",
      narrative: "Mede a força e direção da relação LINEAR entre duas variáveis.",
      difficulty: "intermediario",
      setupCode: "class stats_mock:\n    @staticmethod\n    def pearsonr(x, y): return (1.0, 0.0)\nstats = stats_mock()\nx = [1, 2, 3, 4, 5]\ny = [2, 4, 6, 8, 10]",
      expectedOutput: "1.0",
      testCode: "assert 'pearsonr' in code",
      starterCode: "from scipy import stats\nx = [1, 2, 3, 4, 5]\ny = [2, 4, 6, 8, 10]\n# Imprima o coeficiente de correlação (primeiro retorno)\n",
      hints: [
        { text: "stats.pearsonr retorna TUPLA (coeficiente, p_value). Use [0] ou desempacote.", cost: 20 },
        { text: "Coeficiente entre -1 e 1: 1 = correlação perfeita positiva, -1 = perfeita negativa, 0 = sem correlação linear.", cost: 25 },
        { text: "r, p = stats.pearsonr(x, y)\\nprint(r)", cost: 30 },
      ],
      xpReward: 750,
      concept: "Correlação de Pearson",
      conceptExplanation: "Coeficiente de Pearson (r) mede a força e direção da relação LINEAR entre duas variáveis numéricas. Varia de -1 a 1: 1 = perfeita positiva (uma cresce, outra cresce proporcionalmente); -1 = perfeita negativa; 0 = SEM relação linear (pode haver não-linear!). Limitações: assume relação linear; sensível a outliers; só capta linearidade. CORRELAÇÃO NÃO É CAUSAÇÃO — um clássico: vendas de sorvete e afogamentos têm alta correlação, mas ambos são causados pelo calor. pearsonr também retorna p-valor — teste se a correlação é estatisticamente significativa.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Relação linear quantificada.",
      solution: "from scipy import stats\nr, p = stats.pearsonr([1,2,3,4,5], [2,4,6,8,10])\nprint(r)",
    },
    {
      id: "ds-stat-10",
      worldId: "camara-probabilidades",
      title: "Correlação de Spearman",
      description: "Use stats.spearmanr(x, y) e imprima o coeficiente.",
      narrative: "Captura relações monotônicas, não necessariamente lineares.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def spearmanr(x, y): return (1.0, 0.0)\nstats = stats_mock()\nx = [1, 2, 3, 4, 5]\ny = [1, 8, 27, 64, 125]",
      expectedOutput: "1.0",
      testCode: "assert 'spearmanr' in code",
      starterCode: "from scipy import stats\nx = [1, 2, 3, 4, 5]\ny = [1, 8, 27, 64, 125]\n# Imprima o coeficiente de Spearman\n",
      hints: [
        { text: "spearmanr trabalha com RANKS (posições ordenadas) em vez de valores brutos.", cost: 25 },
        { text: "Detecta relações monotônicas (uma cresce → outra cresce, mas não necessariamente linearmente).", cost: 30 },
        { text: "r, p = stats.spearmanr(x, y)\\nprint(r)", cost: 35 },
      ],
      xpReward: 850,
      concept: "Correlação de Spearman",
      conceptExplanation: "Spearman é o EQUIVALENTE NÃO-PARAMÉTRICO de Pearson — usa ranks (posições ordenadas) em vez de valores. Vantagens: (1) detecta relações MONOTÔNICAS (não só lineares — y = x² no quadrante positivo dá Spearman=1 mas Pearson<1); (2) ROBUSTA a outliers; (3) funciona com variáveis ORDINAIS (escolaridade, satisfação). Use Spearman quando: dados não são normais, há outliers, ou você suspeita de relação não-linear. Kendall's Tau é outra alternativa não-paramétrica, mais conservadora — preferida em amostras pequenas.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Relação monotônica capturada.",
      solution: "from scipy import stats\nr, p = stats.spearmanr([1,2,3,4,5], [1,8,27,64,125])\nprint(r)",
    },
    {
      id: "ds-stat-11",
      worldId: "camara-probabilidades",
      title: "Teste de Hipótese (Conceito)",
      description: "Dado p_value=0.03 e alpha=0.05, imprima 'Rejeitar H0' se p < alpha, senão 'Não rejeitar H0'.",
      narrative: "A base de toda inferência estatística clássica.",
      difficulty: "intermediario",
      setupCode: "p_value = 0.03\nalpha = 0.05",
      expectedOutput: "Rejeitar H0",
      testCode: "assert 'p_value' in code and 'alpha' in code and 'if' in code",
      starterCode: "p_value = 0.03\nalpha = 0.05\n# Decida: rejeitar ou não rejeitar H0\n",
      hints: [
        { text: "H0 (hipótese nula) é o status quo. Rejeitamos quando temos EVIDÊNCIA FORTE contra ela: p < alpha.", cost: 20 },
        { text: "alpha=0.05 (padrão) significa: aceitamos 5% de chance de rejeitar H0 erroneamente.", cost: 25 },
        { text: "if p_value < alpha:\\n    print('Rejeitar H0')\\nelse:\\n    print('Não rejeitar H0')", cost: 30 },
      ],
      xpReward: 800,
      concept: "Teste de Hipótese (H0, H1, α)",
      conceptExplanation: "Teste de hipótese segue um framework: (1) H0 (hipótese nula) — o status quo, o que queremos refutar (ex: 'não há diferença entre grupos'); (2) H1 (alternativa) — o que defendemos (ex: 'há diferença'); (3) α (nível de significância) — risco aceito de rejeitar H0 erroneamente (típico: 0.05); (4) calcule estatística e p-value; (5) se p < α, REJEITE H0. CRÍTICO: 'não rejeitar H0' NÃO significa 'H0 é verdadeira' — significa que não temos evidência suficiente. Pode ser falta de poder estatístico (amostra pequena). Análogo a justiça: 'inocente até prova contrária'.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Decisão estatística tomada.",
      solution: "p_value = 0.03\nalpha = 0.05\nif p_value < alpha:\n    print('Rejeitar H0')\nelse:\n    print('Não rejeitar H0')",
    },
    {
      id: "ds-stat-12",
      worldId: "camara-probabilidades",
      title: "Teste T - Uma Amostra",
      description: "Use stats.ttest_1samp(dados, popmean=50) e imprima o p-value (segundo retorno).",
      narrative: "Compare a média da sua amostra com um valor de referência.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def ttest_1samp(d, popmean): return (2.5, 0.03)\nstats = stats_mock()\ndados = [48, 50, 52, 53, 49, 51, 54, 50, 49, 52]",
      expectedOutput: "0.03",
      testCode: "assert 'ttest_1samp' in code",
      starterCode: "from scipy import stats\ndados = [48, 50, 52, 53, 49, 51, 54, 50, 49, 52]\n# Imprima o p-value de teste contra média=50\n",
      hints: [
        { text: "ttest_1samp testa se a média da amostra é DIFERENTE de um valor fixo (popmean).", cost: 25 },
        { text: "Retorna (estatística_t, p_value). Imprima o p_value.", cost: 30 },
        { text: "t, p = stats.ttest_1samp(dados, popmean=50)\\nprint(p)", cost: 35 },
      ],
      xpReward: 900,
      concept: "Teste T (Uma Amostra)",
      conceptExplanation: "Teste t de uma amostra testa se a média da sua amostra é DIFERENTE de um valor de referência conhecido. Premissas: dados aproximadamente normais (com N grande, o TLC ajuda). H0: μ = valor_referência; H1: μ ≠ valor_referência. Exemplos: 'a altura média da população brasileira é 170cm?', 'meu modelo tem acurácia diferente de 80%?'. Para teste UNILATERAL (μ > X ou μ < X), use alternative='greater' ou 'less' — divide o p-value por 2 efetivamente. Estatística t é distribuída como t-Student (parecida com normal, mas caudas mais pesadas para amostras pequenas).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Hipótese testada.",
      solution: "from scipy import stats\nt, p = stats.ttest_1samp([48,50,52,53,49,51,54,50,49,52], popmean=50)\nprint(p)",
    },
    {
      id: "ds-stat-13",
      worldId: "camara-probabilidades",
      title: "Teste T - Duas Amostras",
      description: "Use stats.ttest_ind(grupo_a, grupo_b) e imprima o p-value.",
      narrative: "Compare médias de dois grupos independentes — A/B testing clássico.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def ttest_ind(a, b): return (3.2, 0.005)\nstats = stats_mock()\ngrupo_a = [70, 72, 75, 68, 71]\ngrupo_b = [80, 82, 85, 78, 81]",
      expectedOutput: "0.005",
      testCode: "assert 'ttest_ind' in code",
      starterCode: "from scipy import stats\ngrupo_a = [70, 72, 75, 68, 71]\ngrupo_b = [80, 82, 85, 78, 81]\n# Imprima o p-value\n",
      hints: [
        { text: "ttest_ind testa se as MÉDIAS de DOIS grupos independentes diferem significativamente.", cost: 25 },
        { text: "É o teste padrão para A/B testing — grupo controle vs grupo tratamento.", cost: 30 },
        { text: "t, p = stats.ttest_ind(grupo_a, grupo_b)\\nprint(p)", cost: 35 },
      ],
      xpReward: 950,
      concept: "Teste T (Duas Amostras Independentes)",
      conceptExplanation: "ttest_ind compara as MÉDIAS de dois grupos INDEPENDENTES (sem pareamento). É o teste padrão para A/B testing — grupo controle vs tratamento. Premissas: (1) amostras independentes; (2) cada grupo aproximadamente normal; (3) variâncias similares (caso contrário, passe equal_var=False — versão de Welch, mais robusta). H0: médias iguais. Para amostras GRANDES (n>30 por grupo), a normalidade quase nunca é problema. Para amostras pequenas com não-normalidade, use Mann-Whitney U (não-paramétrico).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Diferença entre grupos comprovada.",
      solution: "from scipy import stats\nt, p = stats.ttest_ind([70,72,75,68,71], [80,82,85,78,81])\nprint(p)",
    },
    {
      id: "ds-stat-14",
      worldId: "camara-probabilidades",
      title: "Teste T Pareado",
      description: "Use stats.ttest_rel(antes, depois) para comparar medições pareadas. Imprima o p-value.",
      narrative: "Mesmo sujeito antes e depois de uma intervenção — pareamento aumenta o poder.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def ttest_rel(a, b): return (4.5, 0.001)\nstats = stats_mock()\nantes = [70, 72, 75, 68, 71]\ndepois = [75, 76, 80, 73, 75]",
      expectedOutput: "0.001",
      testCode: "assert 'ttest_rel' in code",
      starterCode: "from scipy import stats\nantes = [70, 72, 75, 68, 71]\ndepois = [75, 76, 80, 73, 75]\n# Imprima o p-value\n",
      hints: [
        { text: "ttest_rel é para MEDIDAS REPETIDAS — mesmo indivíduo medido em duas condições.", cost: 25 },
        { text: "Mais POTENTE que ttest_ind porque controla variabilidade entre indivíduos.", cost: 30 },
        { text: "t, p = stats.ttest_rel(antes, depois)\\nprint(p)", cost: 35 },
      ],
      xpReward: 950,
      concept: "Teste T Pareado",
      conceptExplanation: "Teste t pareado (ttest_rel) é usado quando os dados estão PAREADOS: mesmo sujeito medido em duas condições (antes/depois de remédio, score antes/depois de treino), gêmeos comparados, casos-controle pareados. Diferença chave vs ttest_ind: o pareamento CONTROLA a variabilidade individual, dando muito mais poder estatístico — você precisa de amostras menores para detectar o mesmo efeito. Tecnicamente, é equivalente a fazer ttest_1samp nas DIFERENÇAS contra zero. Sempre use pareado quando faz sentido — desperdiçar pareamento usando ttest_ind diminui a sensibilidade.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Intervenção comprovadamente eficaz.",
      solution: "from scipy import stats\nt, p = stats.ttest_rel([70,72,75,68,71], [75,76,80,73,75])\nprint(p)",
    },
    {
      id: "ds-stat-15",
      worldId: "camara-probabilidades",
      title: "ANOVA",
      description: "Use stats.f_oneway(g1, g2, g3) para testar se três grupos têm médias diferentes. Imprima o p-value.",
      narrative: "Comparar mais de dois grupos sem inflar o erro tipo I.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def f_oneway(*args): return (5.0, 0.01)\nstats = stats_mock()\ng1 = [80, 85, 78]\ng2 = [70, 72, 68]\ng3 = [90, 92, 88]",
      expectedOutput: "0.01",
      testCode: "assert 'f_oneway' in code",
      starterCode: "from scipy import stats\ng1 = [80, 85, 78]\ng2 = [70, 72, 68]\ng3 = [90, 92, 88]\n# Imprima o p-value\n",
      hints: [
        { text: "f_oneway (ANOVA de uma via) testa se pelo menos UM grupo difere dos outros.", cost: 25 },
        { text: "Use ANOVA em vez de múltiplos t-tests — combina o erro em UM teste, controlando tipo I.", cost: 30 },
        { text: "f, p = stats.f_oneway(g1, g2, g3)\\nprint(p)", cost: 35 },
      ],
      xpReward: 1000,
      concept: "ANOVA (Análise de Variância)",
      conceptExplanation: "ANOVA testa se a MÉDIA de pelo menos um entre VÁRIOS grupos difere dos demais. Por que não fazer 3 testes t entre cada par? Porque cada teste tem 5% de chance de falso positivo — fazer múltiplos infla esse erro (PROBLEMA DE COMPARAÇÕES MÚLTIPLAS). ANOVA condensa em UM teste. Premissas: independência, normalidade por grupo, variâncias similares (homocedasticidade). Resultado significativo te diz que HÁ diferença, mas NÃO qual grupo difere — para isso faça post-hoc tests (Tukey HSD). Para 2 grupos, ANOVA = teste t.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Variância entre grupos analisada.",
      solution: "from scipy import stats\nf, p = stats.f_oneway([80,85,78], [70,72,68], [90,92,88])\nprint(p)",
    },
    {
      id: "ds-stat-16",
      worldId: "camara-probabilidades",
      title: "Chi-quadrado",
      description: "Use stats.chi2_contingency(tabela) e imprima o p-value (segundo retorno).",
      narrative: "Teste se duas variáveis categóricas são independentes.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def chi2_contingency(t): return (10.0, 0.001, 1, [[0]])\nstats = stats_mock()\ntabela = [[30, 10], [20, 40]]",
      expectedOutput: "0.001",
      testCode: "assert 'chi2_contingency' in code",
      starterCode: "from scipy import stats\ntabela = [[30, 10], [20, 40]]\n# Imprima o p-value\n",
      hints: [
        { text: "chi2_contingency recebe matriz de frequências e testa INDEPENDÊNCIA entre as duas variáveis.", cost: 25 },
        { text: "Retorna (chi2, p_value, graus_liberdade, esperados). Imprima o segundo.", cost: 30 },
        { text: "chi2, p, dof, esp = stats.chi2_contingency(tabela)\\nprint(p)", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Chi-quadrado (Independência)",
      conceptExplanation: "Chi-quadrado de independência testa se duas variáveis CATEGÓRICAS são independentes. Construa uma TABELA DE CONTINGÊNCIA (frequências por combinação de categorias) e o teste compara frequências OBSERVADAS com as ESPERADAS sob independência. H0: variáveis independentes. Exemplos: gênero × preferência de produto, região × intenção de voto, fumar × câncer. Premissa: frequências esperadas em cada célula ≥ 5 (para amostras pequenas, use teste exato de Fisher). Para CHI-quadrado de aderência (uma variável vs distribuição teórica), use stats.chisquare.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Independência testada.",
      solution: "from scipy import stats\nchi2, p, dof, esp = stats.chi2_contingency([[30,10], [20,40]])\nprint(p)",
    },
    {
      id: "ds-stat-17",
      worldId: "camara-probabilidades",
      title: "Teste de Normalidade",
      description: "Use stats.shapiro(dados) para testar normalidade. Imprima o p-value.",
      narrative: "Antes de aplicar testes paramétricos, verifique a normalidade dos dados.",
      difficulty: "intermediario",
      setupCode: "class stats_mock:\n    @staticmethod\n    def shapiro(d): return (0.95, 0.6)\nstats = stats_mock()\ndados = [10, 12, 11, 13, 14, 11, 12, 13]",
      expectedOutput: "0.6",
      testCode: "assert 'shapiro' in code",
      starterCode: "from scipy import stats\ndados = [10, 12, 11, 13, 14, 11, 12, 13]\n# Imprima o p-value de Shapiro-Wilk\n",
      hints: [
        { text: "shapiro testa H0: dados são normais. p > 0.05 → não rejeita normalidade.", cost: 20 },
        { text: "Em amostras grandes, qualquer pequeno desvio dá p baixo — inspecione também via Q-Q plot.", cost: 25 },
        { text: "w, p = stats.shapiro(dados)\\nprint(p)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Testes de Normalidade",
      conceptExplanation: "Muitos testes paramétricos (t, ANOVA) assumem dados normais. Shapiro-Wilk é o teste de normalidade mais usado: H0 = dados são normais. p > 0.05 = não rejeita normalidade (OK para usar paramétrico). CUIDADO: em amostras GRANDES (>5000), Shapiro detecta desvios mínimos como significativos — sempre complemente com inspeção visual (histograma, Q-Q plot, qqplot do statsmodels). Para amostras grandes, paramétricos são robustos via TLC mesmo com não-normalidade. Quando dados realmente não são normais, use alternativas: Mann-Whitney (em vez de t), Kruskal-Wallis (em vez de ANOVA), Spearman (em vez de Pearson).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição verificada.",
      solution: "from scipy import stats\nw, p = stats.shapiro([10,12,11,13,14,11,12,13])\nprint(p)",
    },
    {
      id: "ds-stat-18",
      worldId: "camara-probabilidades",
      title: "Mann-Whitney U",
      description: "Use stats.mannwhitneyu(a, b) — alternativa não-paramétrica ao t-test. Imprima o p-value.",
      narrative: "Quando os dados não são normais, use o teste baseado em ranks.",
      difficulty: "avancado",
      setupCode: "class stats_mock:\n    @staticmethod\n    def mannwhitneyu(a, b): return (5.0, 0.02)\nstats = stats_mock()\na = [1, 3, 5, 7]\nb = [2, 4, 6, 8]",
      expectedOutput: "0.02",
      testCode: "assert 'mannwhitneyu' in code",
      starterCode: "from scipy import stats\na = [1, 3, 5, 7]\nb = [2, 4, 6, 8]\n# Imprima o p-value\n",
      hints: [
        { text: "mannwhitneyu é o equivalente não-paramétrico do ttest_ind — usa ranks em vez de valores.", cost: 25 },
        { text: "Use quando dados não são normais ou são ordinais (escalas Likert, posições).", cost: 30 },
        { text: "u, p = stats.mannwhitneyu(a, b)\\nprint(p)", cost: 35 },
      ],
      xpReward: 950,
      concept: "Testes Não-Paramétricos",
      conceptExplanation: "Testes não-paramétricos não assumem distribuição específica — usam ranks (posições) em vez de valores. Vantagens: (1) funcionam com dados não-normais; (2) robustos a outliers; (3) válidos em variáveis ordinais. Equivalências: Mann-Whitney U substitui ttest_ind; Wilcoxon signed-rank substitui ttest_rel; Kruskal-Wallis substitui ANOVA; Spearman substitui Pearson. Custo: menor poder estatístico que paramétricos QUANDO as premissas paramétricas são satisfeitas. Use não-paramétricos quando dados são claramente não-normais (especialmente com N pequeno) ou ordinais.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Teste não-paramétrico aplicado.",
      solution: "from scipy import stats\nu, p = stats.mannwhitneyu([1,3,5,7], [2,4,6,8])\nprint(p)",
    },
    {
      id: "ds-stat-19",
      worldId: "camara-probabilidades",
      title: "Intervalo de Confiança",
      description: "Dado media=50, sem=2, calcule IC 95%: media ± 1.96 * sem. Imprima limites inferior e superior.",
      narrative: "Comunique incerteza junto com sua estimativa.",
      difficulty: "intermediario",
      setupCode: "media = 50\nsem = 2",
      expectedOutput: "46.08\n53.92",
      testCode: "assert '1.96' in code",
      starterCode: "media = 50\nsem = 2  # erro padrão da média\n# Imprima limite inferior e superior do IC 95%\n",
      hints: [
        { text: "IC 95% = média ± Z * SEM, onde Z=1.96 para 95% (na normal).", cost: 20 },
        { text: "Imprima limite inferior (média - 1.96*sem) e superior (média + 1.96*sem).", cost: 25 },
        { text: "print(media - 1.96 * sem)\\nprint(media + 1.96 * sem)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Intervalos de Confiança",
      conceptExplanation: "Um INTERVALO DE CONFIANÇA dá uma faixa plausível para o parâmetro estimado, com nível de confiança (geralmente 95%). Interpretação CORRETA: 'se repetíssemos o experimento muitas vezes, 95% dos intervalos calculados conteriam o verdadeiro parâmetro'. NÃO é 'há 95% de chance do parâmetro estar nesse intervalo' (essa interpretação requer abordagem bayesiana). Para média: IC = x̄ ± Z*SEM, onde SEM = σ/√n. Z=1.96 para 95%, Z=2.58 para 99%. Intervalos mais ESTREITOS = mais precisão (consegue-se aumentando N).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Faixa de confiança calculada.",
      solution: "media = 50\nsem = 2\nprint(media - 1.96 * sem)\nprint(media + 1.96 * sem)",
    },
    {
      id: "ds-stat-20",
      worldId: "camara-probabilidades",
      title: "Erro Padrão da Média",
      description: "Calcule SEM = desvio / sqrt(n) com desvio=10, n=25. Imprima.",
      narrative: "Precisão da média estimada depende do tamanho da amostra.",
      difficulty: "intermediario",
      setupCode: "import math\ndesvio = 10\nn = 25",
      expectedOutput: "2.0",
      testCode: "assert 'sqrt' in code",
      starterCode: "import math\ndesvio = 10\nn = 25\n# Calcule e imprima SEM\n",
      hints: [
        { text: "SEM (Standard Error of the Mean) = σ / √n. Quanto maior N, menor o SEM.", cost: 20 },
        { text: "Use math.sqrt(n) para raiz quadrada.", cost: 25 },
        { text: "sem = desvio / math.sqrt(n)\\nprint(sem)", cost: 30 },
      ],
      xpReward: 700,
      concept: "Erro Padrão da Média (SEM)",
      conceptExplanation: "SEM mede a VARIABILIDADE da MÉDIA AMOSTRAL — não dos dados em si. Fórmula: SEM = σ/√n. Diferença crucial vs desvio padrão: σ mede dispersão DOS DADOS; SEM mede precisão DA SUA ESTIMATIVA. À medida que aumenta N, SEM diminui (sua média fica mais precisa) mas σ permanece o mesmo (variabilidade dos dados não muda). Aplicação direta: IC da média usa SEM. Para regressão e ANOVA, os 'standard errors' dos coeficientes têm interpretação similar. NUNCA confunda SEM com SD em gráficos — barras de SEM são MUITO menores e enganam o leitor.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Precisão da estimativa quantificada.",
      solution: "import math\nsem = 10 / math.sqrt(25)\nprint(sem)",
    },
    {
      id: "ds-stat-21",
      worldId: "camara-probabilidades",
      title: "Teorema do Limite Central",
      description: "Imprima 'TLC: médias amostrais tendem à normal.' (Demonstração conceitual.)",
      narrative: "O teorema mais importante da estatística clássica.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "TLC: médias amostrais tendem à normal.",
      testCode: "assert 'TLC' in output",
      starterCode: "# Imprima a mensagem exata\n",
      hints: [
        { text: "TLC = Teorema do Limite Central. Print da string exata.", cost: 15 },
        { text: "Use print() com a mensagem exata, incluindo acentos.", cost: 20 },
        { text: "print('TLC: médias amostrais tendem à normal.')", cost: 30 },
      ],
      xpReward: 700,
      concept: "Teorema do Limite Central",
      conceptExplanation: "TLC: independentemente da distribuição da população original (uniforme, exponencial, qualquer), a DISTRIBUIÇÃO das MÉDIAS de amostras de tamanho N tende à NORMAL quando N cresce. Por isso testes paramétricos (t, ANOVA) funcionam mesmo com dados não-normais — quando N é razoável (regra prática: N ≥ 30), a média amostral é aproximadamente normal. É a razão pela qual a normal é onipresente na inferência. Caveat: requer variância finita; falha com distribuições de cauda muito pesada (Cauchy, por exemplo).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Princípio fundamental compreendido.",
      solution: "print('TLC: médias amostrais tendem à normal.')",
    },
    {
      id: "ds-stat-22",
      worldId: "camara-probabilidades",
      title: "Tamanho de Amostra",
      description: "Para detectar efeito d=0.5 com poder=0.8 e alpha=0.05, n ≈ 64. Imprima 64.",
      narrative: "Quantos sujeitos preciso para detectar uma diferença?",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "64",
      testCode: "assert '64' in output",
      starterCode: "# Para d=0.5, poder=0.8, alpha=0.05 → n ≈ 64\n",
      hints: [
        { text: "Apenas imprima 64.", cost: 15 },
        { text: "print(64)", cost: 25 },
        { text: "print(64)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Power Analysis e Tamanho Amostral",
      conceptExplanation: "ANTES de coletar dados, calcule o tamanho de amostra necessário — caso contrário, você arrisca: (1) amostra pequena → não detecta efeito real (baixo PODER, erro tipo II); (2) amostra desnecessariamente grande → desperdício. Power Analysis envolve 4 quantidades, três fixadas e uma calculada: tamanho do efeito (d), nível α (geralmente 0.05), poder (geralmente 0.80), tamanho amostral N. Para d=0.5 (efeito médio de Cohen), α=0.05 bilateral, poder=0.80 → N ≈ 64 por grupo. Biblioteca recomendada: statsmodels.stats.power. Em A/B testing, calcular N antes evita falsas conclusões e gastos com testes inválidos.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Experimento bem-dimensionado.",
      solution: "print(64)",
    },
    {
      id: "ds-stat-23",
      worldId: "camara-probabilidades",
      title: "A/B Testing Framework",
      description: "Imprima 'Variante B significativamente melhor.' se p_value < 0.05, senão 'Inconclusivo.'.",
      narrative: "O padrão da indústria para validar mudanças em produto.",
      difficulty: "avancado",
      setupCode: "p_value = 0.02",
      expectedOutput: "Variante B significativamente melhor.",
      testCode: "assert 'p_value' in code and 'if' in code",
      starterCode: "p_value = 0.02\n# Decida com base em p < 0.05\n",
      hints: [
        { text: "Estrutura: if p_value < 0.05 → vencedor; else → inconclusivo.", cost: 20 },
        { text: "Imprima a mensagem exata pedida.", cost: 25 },
        { text: "if p_value < 0.05:\\n    print('Variante B significativamente melhor.')\\nelse:\\n    print('Inconclusivo.')", cost: 30 },
      ],
      xpReward: 900,
      concept: "A/B Testing",
      conceptExplanation: "A/B testing é o padrão da indústria para validar mudanças (botão verde vs azul, novo algoritmo vs antigo): (1) defina H0 (variantes iguais) e H1 (B é diferente); (2) calcule tamanho de amostra antes; (3) divida usuários aleatoriamente em A (controle) e B (tratamento); (4) execute por tempo suficiente; (5) aplique ttest_ind (métricas contínuas) ou teste de proporções (taxas de conversão); (6) decida com base em p-value e MAGNITUDE do efeito. Cuidados: 'peeking' (parar quando dá significativo) infla erro tipo I; sazonalidade; novelty effect; viés de seleção. Para múltiplos testes, use correções (Bonferroni).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Decisão de produto validada.",
      solution: "p_value = 0.02\nif p_value < 0.05:\n    print('Variante B significativamente melhor.')\nelse:\n    print('Inconclusivo.')",
    },
    {
      id: "ds-stat-24",
      worldId: "camara-probabilidades",
      title: "Bootstrap",
      description: "Imprima 'Bootstrap: reamostragem com reposição.' (Conceito.)",
      narrative: "Quando não há fórmula analítica, reamostre dos próprios dados.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Bootstrap: reamostragem com reposição.",
      testCode: "assert 'Bootstrap' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Print da mensagem com a string exata, incluindo acentos.", cost: 15 },
        { text: "print('Bootstrap: reamostragem com reposição.')", cost: 25 },
        { text: "print('Bootstrap: reamostragem com reposição.')", cost: 30 },
      ],
      xpReward: 850,
      concept: "Bootstrap",
      conceptExplanation: "Bootstrap é um método de REAMOSTRAGEM: a partir de UMA amostra original de tamanho N, gere milhares de 'amostras bootstrap' (cada uma de tamanho N, sorteando COM REPOSIÇÃO da amostra original). Calcule a estatística (média, mediana, qualquer coisa) em cada amostra bootstrap — a distribuição resultante aproxima a distribuição amostral da estatística. Vantagens: (1) não exige premissa de normalidade; (2) funciona para QUALQUER estatística (até customizadas); (3) intervalos de confiança via percentis. Em sklearn, BaggingClassifier usa bootstrap (Random Forest = bagging + árvores). scipy.stats.bootstrap é a implementação padrão.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Reamostragem como ferramenta universal.",
      solution: "print('Bootstrap: reamostragem com reposição.')",
    },
    {
      id: "ds-stat-25",
      worldId: "camara-probabilidades",
      title: "Correção de Bonferroni",
      description: "Para 5 testes, alpha ajustado = 0.05/5 = 0.01. Imprima 0.01.",
      narrative: "Múltiplos testes inflam o erro tipo I — corrija dividindo.",
      difficulty: "avancado",
      setupCode: "alpha = 0.05\nn_testes = 5",
      expectedOutput: "0.01",
      testCode: "assert 'alpha' in code and 'n_testes' in code",
      starterCode: "alpha = 0.05\nn_testes = 5\n# Imprima alpha ajustado\n",
      hints: [
        { text: "Bonferroni: alpha_novo = alpha / n_testes.", cost: 20 },
        { text: "Simplesmente divida.", cost: 25 },
        { text: "print(alpha / n_testes)", cost: 30 },
      ],
      xpReward: 850,
      concept: "Correção de Múltiplas Comparações",
      conceptExplanation: "Fazer múltiplos testes infla o erro tipo I (falsos positivos). Se cada um tem 5% de chance, 20 testes têm ~64% chance de PELO MENOS UM falso positivo. Correção de BONFERRONI (mais simples): divida α pelo número de testes — α_novo = α/N. É CONSERVADORA (perde poder estatístico) mas garante FWER ≤ α (Family-Wise Error Rate). Alternativas: Holm-Bonferroni (igual restrita mas menos conservadora); Benjamini-Hochberg (controla FDR — False Discovery Rate, recomendada em ômicas/genética com milhares de testes). Sem correção, qualquer 'descoberta' por p-hacking é suspeita.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Erro tipo I controlado.",
      solution: "alpha = 0.05\nn_testes = 5\nprint(alpha / n_testes)",
    },
    {
      id: "ds-stat-26",
      worldId: "camara-probabilidades",
      title: "Regressão Linear (Statsmodels)",
      description: "Use sm.OLS(y, X).fit() e imprima 'Regressão ajustada.'.",
      narrative: "Statsmodels oferece regressão com estatística completa (p-values, IC, R²).",
      difficulty: "avancado",
      setupCode: "class OLS:\n    def __init__(self, y, X): pass\n    def fit(self): print('Regressão ajustada.'); return self\nclass sm_mock:\n    OLS = OLS\nsm = sm_mock()\nX = [[1, 1], [1, 2]]\ny = [1, 2]",
      expectedOutput: "Regressão ajustada.",
      testCode: "assert 'OLS' in code and 'fit' in code",
      starterCode: "import statsmodels.api as sm\nX = [[1, 1], [1, 2]]\ny = [1, 2]\n# Ajuste OLS e confirme\n",
      hints: [
        { text: "sm.OLS(y, X) cria o modelo; .fit() retorna os resultados.", cost: 30 },
        { text: "Diferente do sklearn (focado em predição), statsmodels é focado em INFERÊNCIA — fornece p-values e IC dos coeficientes.", cost: 35 },
        { text: "modelo = sm.OLS(y, X).fit()", cost: 40 },
      ],
      xpReward: 1050,
      concept: "Statsmodels (Inferência)",
      conceptExplanation: "Em DS, há duas grandes bibliotecas de regressão em Python com filosofias diferentes: sklearn (.fit/.predict, focado em PREDIÇÃO) e statsmodels (focado em INFERÊNCIA estatística). Statsmodels te dá tabela completa com coeficientes, ERROS PADRÃO, P-VALUES, INTERVALOS DE CONFIANÇA, R² ajustado, AIC/BIC, diagnósticos (heterocedasticidade, autocorrelação). Use statsmodels quando quer ENTENDER se cada feature é estatisticamente significativa; sklearn quando só quer prever. Em R, a função lm() faz o que statsmodels faz aqui. Após .fit(), chame .summary() para a tabela completa.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo inferencial pronto.",
      solution: "import statsmodels.api as sm\nmodelo = sm.OLS(y, X).fit()",
    },
    {
      id: "ds-stat-27",
      worldId: "camara-probabilidades",
      title: "R² Ajustado",
      description: "Dado r2=0.85, n=100, k=5 features. Calcule r2_ajustado = 1 - (1-r2)*(n-1)/(n-k-1). Imprima.",
      narrative: "Penaliza R² por features irrelevantes.",
      difficulty: "avancado",
      setupCode: "r2 = 0.85\nn = 100\nk = 5",
      expectedOutput: "0.8420212765957447",
      testCode: "assert 'r2' in code and 'n' in code and 'k' in code",
      starterCode: "r2 = 0.85\nn = 100\nk = 5\n# Calcule R² ajustado\n",
      hints: [
        { text: "Fórmula: 1 - (1 - r²) * (n - 1) / (n - k - 1).", cost: 25 },
        { text: "Cuidado com a ordem das operações — use parênteses corretos.", cost: 30 },
        { text: "r2_aj = 1 - (1 - r2) * (n - 1) / (n - k - 1)\\nprint(r2_aj)", cost: 35 },
      ],
      xpReward: 950,
      concept: "R² Ajustado",
      conceptExplanation: "R² normal SEMPRE aumenta quando você adiciona features — mesmo features irrelevantes. R² AJUSTADO PENALIZA adição de features que não melhoram realmente o modelo. Fórmula: 1 - (1-R²) * (n-1)/(n-k-1), onde n=observações, k=features. Se a feature melhora pouco, R²_aj DIMINUI; se melhora muito, aumenta. Use R²_aj para COMPARAR modelos com número diferente de features. Sempre presente no summary do statsmodels. Métricas alternativas para comparação de modelos: AIC, BIC, cross-validation R².",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Métrica honesta calculada.",
      solution: "r2 = 0.85\nn = 100\nk = 5\nprint(1 - (1 - r2) * (n - 1) / (n - k - 1))",
    },
    {
      id: "ds-stat-28",
      worldId: "camara-probabilidades",
      title: "Inferência Bayesiana",
      description: "Imprima 'Posterior ∝ Likelihood × Prior.' (Teorema de Bayes.)",
      narrative: "Atualize crenças à medida que dados chegam.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Posterior ∝ Likelihood × Prior.",
      testCode: "assert 'Posterior' in output",
      starterCode: "# Imprima a relação fundamental\n",
      hints: [
        { text: "A string usa o caractere ∝ (proporcional a) e × (multiplicação).", cost: 20 },
        { text: "Copie a string exata: 'Posterior ∝ Likelihood × Prior.'.", cost: 25 },
        { text: "print('Posterior ∝ Likelihood × Prior.')", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Inferência Bayesiana",
      conceptExplanation: "Estatística bayesiana é a alternativa filosófica à frequentista: em vez de calcular probabilidade de dados dado um parâmetro fixo, calcula probabilidade do PARÂMETRO dados os dados. Teorema de Bayes: Posterior ∝ Likelihood × Prior. PRIOR = crença inicial sobre o parâmetro (antes de ver dados); LIKELIHOOD = probabilidade dos dados dado o parâmetro; POSTERIOR = crença atualizada. Vantagens: (1) incorpora conhecimento prévio formalmente; (2) intervalos de credibilidade têm interpretação intuitiva; (3) funciona bem com pouco dado. Bibliotecas Python: PyMC, Stan via pystan, NumPyro. Aplicações: A/B testing bayesiano, sistemas de recomendação, NLP, robótica.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Crenças atualizadas com dados.",
      solution: "print('Posterior ∝ Likelihood × Prior.')",
    },
    {
      id: "ds-stat-29",
      worldId: "camara-probabilidades",
      title: "Distribuição t-Student",
      description: "Use stats.t.cdf(2.0, df=10) e imprima.",
      narrative: "Parecida com a normal, mas com caudas mais pesadas — usada em amostras pequenas.",
      difficulty: "avancado",
      setupCode: "class t_mock:\n    @staticmethod\n    def cdf(x, df): return 0.9633289987124468\nclass stats_mock:\n    t = t_mock()\nstats = stats_mock()",
      expectedOutput: "0.9633289987124468",
      testCode: "assert 'stats.t.cdf' in code",
      starterCode: "from scipy import stats\n# stats.t.cdf(2.0, df=10)\n",
      hints: [
        { text: "Distribuição t-Student tem parâmetro 'df' (graus de liberdade). df=n-1 em teste t de uma amostra.", cost: 25 },
        { text: "Para df grande (>30), t aproxima a normal. Para df pequeno, caudas são mais pesadas.", cost: 30 },
        { text: "print(stats.t.cdf(2.0, df=10))", cost: 35 },
      ],
      xpReward: 950,
      concept: "t-Student",
      conceptExplanation: "Distribuição t-Student é parecida com a normal mas tem CAUDAS MAIS PESADAS — reflete a incerteza adicional quando você estima σ a partir da amostra (em vez de conhecer σ da população). Parâmetro: df (graus de liberdade) — em teste t de uma amostra, df=n-1. Para df pequeno (5, 10), as caudas são bem pesadas — valores extremos são mais prováveis que na normal. Para df grande (>30), t é praticamente normal. É a distribuição teórica dos testes t (daí o nome). Em scipy: stats.t, com mesma interface que stats.norm (pdf, cdf, ppf, rvs).",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Cauda pesada modelada.",
      solution: "from scipy import stats\nprint(stats.t.cdf(2.0, df=10))",
    },
    {
      id: "ds-stat-30",
      worldId: "camara-probabilidades",
      title: "Erro Tipo I vs Tipo II",
      description: "Imprima 'Tipo I: rejeitar H0 verdadeira. Tipo II: não rejeitar H0 falsa.'.",
      narrative: "Os dois tipos de erro em qualquer decisão estatística.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Tipo I: rejeitar H0 verdadeira. Tipo II: não rejeitar H0 falsa.",
      testCode: "assert 'Tipo I' in output and 'Tipo II' in output",
      starterCode: "# Imprima a definição exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('Tipo I: rejeitar H0 verdadeira. Tipo II: não rejeitar H0 falsa.')", cost: 25 },
        { text: "print('Tipo I: rejeitar H0 verdadeira. Tipo II: não rejeitar H0 falsa.')", cost: 30 },
      ],
      xpReward: 900,
      concept: "Tipos de Erro",
      conceptExplanation: "Em qualquer decisão estatística existem 2 erros: TIPO I (α) = REJEITAR H0 quando ela é VERDADEIRA (falso positivo — 'achei algo que não existe'); TIPO II (β) = NÃO REJEITAR H0 quando ela é FALSA (falso negativo — 'deixei passar algo real'). Trade-off: diminuir α (mais conservador) aumenta β e vice-versa. Padrão: α=0.05, β=0.20 (poder = 1-β = 0.80). Em medicina, tipo II em diagnóstico é fatal (paciente sai sem tratamento); em justiça, tipo I é grave (inocente condenado). Defina prioridade conforme o domínio — não há resposta universal.",
      successNpc: "Estatístico Cibernético",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Trade-off de erros compreendido.",
      solution: "print('Tipo I: rejeitar H0 verdadeira. Tipo II: não rejeitar H0 falsa.')",
    },
  ],
};
