import { World } from "../types";

export const CRIPTA_DICIONARIOS_WORLD: World = {
  id: "cripta-dicionarios",
  title: "Cripta Hash",
  subtitle: "Mapeamento Chave-Valor",
  icon: "database",
  color: "#14B8A6",
  bgImage: "/assets/images/worlds/hash_vault.png",
  lore: "Na Cripta Hash, as informações não são sequenciais. Aqui, os dados são mapeados em pares de chave e valor, garantindo acesso instantâneo. Domine Dicionários e Conjuntos para otimizar a velocidade de busca na rede.",
  unlockRequirement: 12000,
  challenges: [
    {
      id: "py-dict-01",
      worldId: "cripta-dicionarios",
      title: "Inicialização do Cofre",
      description: "Crie um dicionário chamado 'usuario' com as chaves 'nome' (valor 'Neo') e 'nivel' (valor 5). Imprima o dicionário.",
      narrative: "Para armazenar os atributos de um operador de forma estruturada, inicialize um dicionário que mapeie cada atributo ao seu respectivo valor.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "{'nome': 'Neo', 'nivel': 5}",
      testCode: "assert type(usuario) is dict and usuario['nome'] == 'Neo' and usuario['nivel'] == 5",
      starterCode: "# Crie o dicionário 'usuario' e imprima-o\n",
      hints: [
        { text: "Dicionários usam chaves {}. A sintaxe é {'chave': 'valor'}.", cost: 10 },
        { text: "usuario = {'nome': 'Neo', 'nivel': 5}", cost: 20 },
      ],
      xpReward: 300,
      concept: "Dicionários (dict)",
      conceptExplanation: "Um dicionário é uma estrutura de dados que guarda pares de chave e valor. Em vez de usar números para acessar os itens (como nas listas), você usa um nome (a chave).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Cofre de dados estabelecido. Os atributos do operador foram mapeados com sucesso.",
      solution: "usuario = {'nome': 'Neo', 'nivel': 5}\nprint(usuario)",
    },
    {
      id: "py-dict-02",
      worldId: "cripta-dicionarios",
      title: "Acesso Indexado",
      description: "Dado o dicionário 'config', acesse o valor da chave 'porta' e imprima-o.",
      narrative: "Um arquivo de configuração foi interceptado. Extraia o número da porta para que possamos iniciar a varredura.",
      difficulty: "iniciante",
      setupCode: "config = {'ip': '192.168.0.1', 'porta': 8080, 'seguro': True}",
      expectedOutput: "8080",
      testCode: "assert output.strip() == '8080'",
      starterCode: "config = {'ip': '192.168.0.1', 'porta': 8080, 'seguro': True}\n# Imprima apenas o valor da porta\n",
      hints: [
        { text: "Para acessar um valor, use colchetes com o nome da chave: dicionario['chave'].", cost: 10 },
        { text: "print(config['porta'])", cost: 20 },
      ],
      xpReward: 320,
      concept: "Acesso por Chave",
      conceptExplanation: "Acesse itens de um dicionário usando `nome_do_dicionario['chave']`. Se a chave não existir, o Python dará um erro (KeyError).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Porta extraída. A conexão direta pode ser estabelecida agora.",
      solution: "print(config['porta'])",
    },
    {
      id: "py-dict-03",
      worldId: "cripta-dicionarios",
      title: "Acesso Seguro (Get)",
      description: "Use o método .get() para acessar a chave 'token' do dicionário 'auth'. Se a chave não existir, retorne 'Nao Encontrado' e imprima o resultado.",
      narrative: "Nem todos os pacotes vêm com as chaves esperadas. Use o método seguro para evitar que o sistema trave caso a chave esteja ausente.",
      difficulty: "intermediario",
      setupCode: "auth = {'user': 'admin', 'status': 'ativo'}",
      expectedOutput: "Nao Encontrado",
      testCode: "assert 'get' in code and output.strip() == 'Nao Encontrado'",
      starterCode: "auth = {'user': 'admin', 'status': 'ativo'}\n# Use .get() para buscar 'token' de forma segura\n",
      hints: [
        { text: "dicionario.get('chave', 'valor_padrao') tenta pegar o valor. Se falhar, devolve o valor padrão.", cost: 10 },
        { text: "print(auth.get('token', 'Nao Encontrado'))", cost: 20 },
      ],
      xpReward: 350,
      concept: "Método get()",
      conceptExplanation: "O método `.get('chave', 'padrao')` é a forma segura de acessar dicionários. Ele evita o erro fatal `KeyError` devolvendo o valor padrão especificado (ou `None` se omitido).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Crash evitado. O sistema lidou com a ausência do token graciosamente.",
      solution: "print(auth.get('token', 'Nao Encontrado'))",
    },
    {
      id: "py-dict-04",
      worldId: "cripta-dicionarios",
      title: "Adição de Metadados",
      description: "Adicione a chave 'role' com o valor 'admin' ao dicionário 'perfil' e imprima o dicionário inteiro.",
      narrative: "O perfil interceptado não possui nível de privilégio. Injete a chave de administrador diretamente na estrutura em memória.",
      difficulty: "iniciante",
      setupCode: "perfil = {'nome': 'Trinity'}",
      expectedOutput: "{'nome': 'Trinity', 'role': 'admin'}",
      testCode: "assert 'role' in perfil and perfil['role'] == 'admin'",
      starterCode: "perfil = {'nome': 'Trinity'}\n# Adicione a nova chave e imprima o perfil\n",
      hints: [
        { text: "Você pode adicionar ou modificar chaves apenas fazendo: dicionario['nova_chave'] = valor.", cost: 10 },
      ],
      xpReward: 350,
      concept: "Adição/Atualização de Itens",
      conceptExplanation: "Dicionários são mutáveis. Se você atribuir um valor a uma chave que já existe, ele é atualizado. Se a chave não existir, ela é criada instantaneamente.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Injeção bem-sucedida. O perfil agora possui privilégios máximos.",
      solution: "perfil['role'] = 'admin'\nprint(perfil)",
    },
    {
      id: "py-dict-05",
      worldId: "cripta-dicionarios",
      title: "Extrator de Chaves",
      description: "Dado o dicionário 'dados', use .keys() para pegar todas as chaves, converta para uma lista e imprima.",
      narrative: "Precisamos mapear a estrutura do pacote, mas não nos importamos com os valores agora. Extraia apenas as chaves (os nomes dos campos).",
      difficulty: "intermediario",
      setupCode: "dados = {'id': 101, 'hash': 'a1b2', 'valido': True}",
      expectedOutput: "['id', 'hash', 'valido']",
      testCode: "assert 'keys' in code and 'list' in code and output.strip() == \"['id', 'hash', 'valido']\"",
      starterCode: "dados = {'id': 101, 'hash': 'a1b2', 'valido': True}\n# Obtenha as chaves como uma lista e imprima\n",
      hints: [
        { text: "Use list(dados.keys()) para transformar as chaves em uma lista tradicional.", cost: 10 },
      ],
      xpReward: 400,
      concept: "Método keys()",
      conceptExplanation: "O método `.keys()` retorna uma visualização de todas as chaves do dicionário. Convertendo para lista, você pode fazer indexação ou modificações.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Estrutura do pacote mapeada. As chaves foram extraídas para análise.",
      solution: "print(list(dados.keys()))",
    },
    {
      id: "py-dict-06",
      worldId: "cripta-dicionarios",
      title: "Varredura de Pares",
      description: "Use um loop for junto com o método .items() para imprimir 'Chave: [c] -> Valor: [v]' para cada item do dicionário 'sistema'.",
      narrative: "Para auditoria completa, você precisa exibir ambos, a etiqueta e o dado correspondente, em um formato padronizado e legível para humanos.",
      difficulty: "intermediario",
      setupCode: "sistema = {'os': 'linux', 'ram': '16GB', 'cpu': '8-core'}",
      expectedOutput: "Chave: os -> Valor: linux\nChave: ram -> Valor: 16GB\nChave: cpu -> Valor: 8-core",
      testCode: "assert 'items()' in code and 'linux' in output",
      starterCode: "sistema = {'os': 'linux', 'ram': '16GB', 'cpu': '8-core'}\n# Itere sobre chave e valor ao mesmo tempo\n",
      hints: [
        { text: "O método dicionario.items() devolve pares (chave, valor).", cost: 10 },
        { text: "for chave, valor in sistema.items():", cost: 20 },
      ],
      xpReward: 450,
      concept: "Método items()",
      conceptExplanation: "O `.items()` é a forma mais 'pythônica' de iterar sobre um dicionário. Ele te entrega tanto a chave quanto o valor a cada volta do loop, economizando consultas extras.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Auditoria finalizada. Todos os atributos do sistema foram listados com precisão.",
      solution: "for chave, valor in sistema.items():\n    print(f'Chave: {chave} -> Valor: {valor}')",
    },
    {
      id: "py-dict-07",
      worldId: "cripta-dicionarios",
      title: "Conjunto Único (Sets)",
      description: "A lista 'ips' possui endereços duplicados. Converta-a para um conjunto (set) para remover as duplicatas e imprima o tamanho do conjunto usando len().",
      narrative: "O log de conexões capturou o mesmo IP várias vezes. Filtre as redundâncias usando a estrutura de Conjuntos do Python para saber exatamente quantos alvos únicos existem.",
      difficulty: "intermediario",
      setupCode: "ips = ['1.1.1.1', '8.8.8.8', '1.1.1.1', '10.0.0.1', '8.8.8.8']",
      expectedOutput: "3",
      testCode: "assert 'set' in code and output.strip() == '3'",
      starterCode: "ips = ['1.1.1.1', '8.8.8.8', '1.1.1.1', '10.0.0.1', '8.8.8.8']\n# Use set() para criar um conjunto de valores únicos\n",
      hints: [
        { text: "A função set(lista) cria um conjunto. Um conjunto nunca tem itens duplicados.", cost: 10 },
        { text: "unicos = set(ips)\nprint(len(unicos))", cost: 20 },
      ],
      xpReward: 420,
      concept: "Conjuntos (set)",
      conceptExplanation: "Um `set` em Python é como um conjunto matemático. Ele guarda elementos desordenados, mas o mais importante: ele NÃO permite elementos repetidos. É a forma mais eficiente de remover duplicatas de uma lista.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Redundâncias eliminadas. O número real de atacantes é menor do que parecia.",
      solution: "unicos = set(ips)\nprint(len(unicos))",
    },
    {
      id: "py-dict-08",
      worldId: "cripta-dicionarios",
      title: "Interseção de Redes",
      description: "Dados os conjuntos 'rede_a' e 'rede_b', use o operador de interseção '&' para descobrir quais IPs estão presentes em AMBAS as redes. Imprima o resultado.",
      narrative: "Para encontrar o computador ponte (bridge) entre dois sub-setores, compare as listas de IPs conhecidos e veja quem frequenta as duas redes.",
      difficulty: "avancado",
      setupCode: "rede_a = {'10.0.0.1', '10.0.0.2', '10.0.0.3'}\nrede_b = {'10.0.0.3', '10.0.0.4', '10.0.0.5'}",
      expectedOutput: "{'10.0.0.3'}",
      testCode: "assert '&' in code or 'intersection' in code",
      starterCode: "rede_a = {'10.0.0.1', '10.0.0.2', '10.0.0.3'}\nrede_b = {'10.0.0.3', '10.0.0.4', '10.0.0.5'}\n# Encontre a interseção e imprima\n",
      hints: [
        { text: "O operador & (ou o método intersection()) devolve apenas o que existe em ambos os conjuntos.", cost: 10 },
      ],
      xpReward: 500,
      concept: "Operações de Conjunto",
      conceptExplanation: "Sets suportam operações matemáticas hiper-rápidas:\n`&` (Interseção): O que tem nos dois?\n`|` (União): Junta tudo.\n`-` (Diferença): O que tem no primeiro, mas não no segundo?",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Computador ponte localizado. É por aí que faremos o pivô de rede.",
      solution: "print(rede_a & rede_b)",
    },
  ],
};
