import { World } from "../types";

export const CRIPTA_DICIONARIOS_WORLD: World = {
  id: "cripta-dicionarios",
  title: "Cripta Hash",
  subtitle: "Mapeamento Chave-Valor",
  icon: "database",
  color: "#14B8A6",
  bgImage: "/assets/images/worlds/dictionaries.png",
  lore: "Na Cripta Hash, as informações não são sequenciais. Aqui, os dados são mapeados em pares de chave e valor, garantindo acesso instantâneo. Domine Dicionários e Conjuntos para otimizar a velocidade de busca na rede.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-dict-01",
      worldId: "cripta-dicionarios",
      title: "Inicialização do Cofre",
      description: "Crie um dicionário chamado 'usuario' com as chaves 'nome' (valor 'Neo') e 'nivel' (valor 5). Imprima o dicionário.",
      narrative: "Para armazenar os atributos de um operador de forma estruturada, inicialize um dicionário que mapeie cada atributo ao seu respectivo valor.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "{'nome': 'Neo', 'nivel': 5}",
      testCode: "assert type(usuario) is dict and usuario['nome'] == 'Neo' and usuario['nivel'] == 5",
      starterCode: "# Crie o dicionário 'usuario' e imprima-o\n",
      hints: [
        { text: "Dicionários usam chaves {}. A sintaxe é {'chave': 'valor'}.", cost: 10 },
        { text: "usuario = {'nome': 'Neo', 'nivel': 5}", cost: 20 },
      ],
      xpReward: 300,
      concept: "Dicionários (dict)",
      conceptExplanation: "Um dicionário é uma estrutura de dados que guarda pares de chave e valor. Em vez de usar números para acessar os itens (como nas listas), você usa um nome (a chave).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Cofre de dados estabelecido. Os atributos do operador foram mapeados com sucesso.",
      solution: "usuario = {'nome': 'Neo', 'nivel': 5}\nprint(usuario)",
    },
    {
      id: "py-dict-02",
      worldId: "cripta-dicionarios",
      title: "Acesso Indexado",
      description: "Dado o dicionário 'config', acesse o valor da chave 'porta' e imprima-o.",
      narrative: "Um arquivo de configuração foi interceptado. Extraia o número da porta para que possamos iniciar a varredura.",
      difficulty: "iniciante",
      setupCode: "config = {'ip': '192.168.0.1', 'porta': 8080, 'seguro': True}",
      expectedOutput: "8080",
      testCode: "assert output.strip() == '8080'",
      starterCode: "config = {'ip': '192.168.0.1', 'porta': 8080, 'seguro': True}\n# Imprima apenas o valor da porta\n",
      hints: [
        { text: "Para acessar um valor, use colchetes com o nome da chave: dicionario['chave'].", cost: 10 },
        { text: "print(config['porta'])", cost: 20 },
      ],
      xpReward: 320,
      concept: "Acesso por Chave",
      conceptExplanation: "Acesse itens de um dicionário usando `nome_do_dicionario['chave']`. Se a chave não existir, o Python dará um erro (KeyError).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Porta extraída. A conexão direta pode ser estabelecida agora.",
      solution: "print(config['porta'])",
    },
    {
      id: "py-dict-03",
      worldId: "cripta-dicionarios",
      title: "Acesso Seguro (Get)",
      description: "Use o método .get() para acessar a chave 'token' do dicionário 'auth'. Se a chave não existir, retorne 'Nao Encontrado' e imprima o resultado.",
      narrative: "Nem todos os pacotes vêm com as chaves esperadas. Use o método seguro para evitar que o sistema trave caso a chave esteja ausente.",
      difficulty: "intermediario",
      setupCode: "auth = {'user': 'admin', 'status': 'ativo'}",
      expectedOutput: "Nao Encontrado",
      testCode: "assert 'get' in code and output.strip() == 'Nao Encontrado'",
      starterCode: "auth = {'user': 'admin', 'status': 'ativo'}\n# Use .get() para buscar 'token' de forma segura\n",
      hints: [
        { text: "dicionario.get('chave', 'valor_padrao') tenta pegar o valor. Se falhar, devolve o valor padrão.", cost: 10 },
        { text: "print(auth.get('token', 'Nao Encontrado'))", cost: 20 },
      ],
      xpReward: 350,
      concept: "Método get()",
      conceptExplanation: "O método `.get('chave', 'padrao')` é a forma segura de acessar dicionários. Ele evita o erro fatal `KeyError` devolvendo o valor padrão especificado (ou `None` se omitido).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Crash evitado. O sistema lidou com a ausência do token graciosamente.",
      solution: "print(auth.get('token', 'Nao Encontrado'))",
    },
    {
      id: "py-dict-04",
      worldId: "cripta-dicionarios",
      title: "Adição de Metadados",
      description: "Adicione a chave 'role' com o valor 'admin' ao dicionário 'perfil' e imprima o dicionário inteiro.",
      narrative: "O perfil interceptado não possui nível de privilégio. Injete a chave de administrador diretamente na estrutura em memória.",
      difficulty: "iniciante",
      setupCode: "perfil = {'nome': 'Trinity'}",
      expectedOutput: "{'nome': 'Trinity', 'role': 'admin'}",
      testCode: "assert 'role' in perfil and perfil['role'] == 'admin'",
      starterCode: "perfil = {'nome': 'Trinity'}\n# Adicione a nova chave e imprima o perfil\n",
      hints: [
        { text: "Você pode adicionar ou modificar chaves apenas fazendo: dicionario['nova_chave'] = valor.", cost: 10 },
      ],
      xpReward: 350,
      concept: "Adição/Atualização de Itens",
      conceptExplanation: "Dicionários são mutáveis. Se você atribuir um valor a uma chave que já existe, ele é atualizado. Se a chave não existir, ela é criada instantaneamente.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Injeção bem-sucedida. O perfil agora possui privilégios máximos.",
      solution: "perfil['role'] = 'admin'\nprint(perfil)",
    },
    {
      id: "py-dict-05",
      worldId: "cripta-dicionarios",
      title: "Extrator de Chaves",
      description: "Dado o dicionário 'dados', use .keys() para pegar todas as chaves, converta para uma lista e imprima.",
      narrative: "Precisamos mapear a estrutura do pacote, mas não nos importamos com os valores agora. Extraia apenas as chaves (os nomes dos campos).",
      difficulty: "intermediario",
      setupCode: "dados = {'id': 101, 'hash': 'a1b2', 'valido': True}",
      expectedOutput: "['id', 'hash', 'valido']",
      testCode: "assert 'keys' in code and 'list' in code and output.strip() == \"['id', 'hash', 'valido']\"",
      starterCode: "dados = {'id': 101, 'hash': 'a1b2', 'valido': True}\n# Obtenha as chaves como uma lista e imprima\n",
      hints: [
        { text: "Use list(dados.keys()) para transformar as chaves em uma lista tradicional.", cost: 10 },
      ],
      xpReward: 400,
      concept: "Método keys()",
      conceptExplanation: "O método `.keys()` retorna uma visualização de todas as chaves do dicionário. Convertendo para lista, você pode fazer indexação ou modificações.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Estrutura do pacote mapeada. As chaves foram extraídas para análise.",
      solution: "print(list(dados.keys()))",
    },
    {
      id: "py-dict-06",
      worldId: "cripta-dicionarios",
      title: "Varredura de Pares",
      description: "Use um loop for junto com o método .items() para imprimir 'Chave: [c] -> Valor: [v]' para cada item do dicionário 'sistema'.",
      narrative: "Para auditoria completa, você precisa exibir ambos, a etiqueta e o dado correspondente, em um formato padronizado e legível para humanos.",
      difficulty: "intermediario",
      setupCode: "sistema = {'os': 'linux', 'ram': '16GB', 'cpu': '8-core'}",
      expectedOutput: "Chave: os -> Valor: linux\nChave: ram -> Valor: 16GB\nChave: cpu -> Valor: 8-core",
      testCode: "assert 'items()' in code and 'linux' in output",
      starterCode: "sistema = {'os': 'linux', 'ram': '16GB', 'cpu': '8-core'}\n# Itere sobre chave e valor ao mesmo tempo\n",
      hints: [
        { text: "O método dicionario.items() devolve pares (chave, valor).", cost: 10 },
        { text: "for chave, valor in sistema.items():", cost: 20 },
      ],
      xpReward: 450,
      concept: "Método items()",
      conceptExplanation: "O `.items()` é a forma mais 'pythônica' de iterar sobre um dicionário. Ele te entrega tanto a chave quanto o valor a cada volta do loop, economizando consultas extras.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Auditoria finalizada. Todos os atributos do sistema foram listados com precisão.",
      solution: "for chave, valor in sistema.items():\n    print(f'Chave: {chave} -> Valor: {valor}')",
    },
    {
      id: "py-dict-07",
      worldId: "cripta-dicionarios",
      title: "Conjunto Único (Sets)",
      description: "A lista 'ips' possui endereços duplicados. Converta-a para um conjunto (set) para remover as duplicatas e imprima o tamanho do conjunto usando len().",
      narrative: "O log de conexões capturou o mesmo IP várias vezes. Filtre as redundâncias usando a estrutura de Conjuntos do Python para saber exatamente quantos alvos únicos existem.",
      difficulty: "intermediario",
      setupCode: "ips = ['1.1.1.1', '8.8.8.8', '1.1.1.1', '10.0.0.1', '8.8.8.8']",
      expectedOutput: "3",
      testCode: "assert 'set' in code and output.strip() == '3'",
      starterCode: "ips = ['1.1.1.1', '8.8.8.8', '1.1.1.1', '10.0.0.1', '8.8.8.8']\n# Use set() para criar um conjunto de valores únicos\n",
      hints: [
        { text: "A função set(lista) cria um conjunto. Um conjunto nunca tem itens duplicados.", cost: 10 },
        { text: "unicos = set(ips)\nprint(len(unicos))", cost: 20 },
      ],
      xpReward: 420,
      concept: "Conjuntos (set)",
      conceptExplanation: "Um `set` em Python é como um conjunto matemático. Ele guarda elementos desordenados, mas o mais importante: ele NÃO permite elementos repetidos. É a forma mais eficiente de remover duplicatas de uma lista.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Redundâncias eliminadas. O número real de atacantes é menor do que parecia.",
      solution: "unicos = set(ips)\nprint(len(unicos))",
    },
    {
      id: "py-dict-08",
      worldId: "cripta-dicionarios",
      title: "Interseção de Redes",
      description: "Dados os conjuntos 'rede_a' e 'rede_b', use o operador de interseção '&' para descobrir quais IPs estão presentes em AMBAS as redes. Imprima o resultado.",
      narrative: "Para encontrar o computador ponte (bridge) entre dois sub-setores, compare as listas de IPs conhecidos e veja quem frequenta as duas redes.",
      difficulty: "avancado",
      setupCode: "rede_a = {'10.0.0.1', '10.0.0.2', '10.0.0.3'}\nrede_b = {'10.0.0.3', '10.0.0.4', '10.0.0.5'}",
      expectedOutput: "{'10.0.0.3'}",
      testCode: "assert '&' in code or 'intersection' in code",
      starterCode: "rede_a = {'10.0.0.1', '10.0.0.2', '10.0.0.3'}\nrede_b = {'10.0.0.3', '10.0.0.4', '10.0.0.5'}\n# Encontre a interseção e imprima\n",
      hints: [
        { text: "O operador & (ou o método intersection()) devolve apenas o que existe em ambos os conjuntos.", cost: 10 },
      ],
      xpReward: 500,
      concept: "Operações de Conjunto",
      conceptExplanation: "Sets suportam operações matemáticas hiper-rápidas:\n`&` (Interseção): O que tem nos dois?\n`|` (União): Junta tudo.\n`-` (Diferença): O que tem no primeiro, mas não no segundo?",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Computador ponte localizado. É por aí que faremos o pivô de rede.",
      solution: "print(rede_a & rede_b)",
    },
    {
      id: "py-dict-09",
      worldId: "cripta-dicionarios",
      title: "Extrator de Valores",
      description: "Dado o dicionário 'estoque', use .values() para pegar todos os valores, converta para uma lista e imprima.",
      narrative: "O inventário do servidor precisa ser somado — você só quer as quantidades, não os nomes dos itens. Extraia apenas os valores da estrutura.",
      difficulty: "iniciante",
      setupCode: "estoque = {'CPU': 4, 'RAM': 16, 'SSD': 2}",
      expectedOutput: "[4, 16, 2]",
      testCode: "assert 'values' in code and output.strip() == '[4, 16, 2]'",
      starterCode: "estoque = {'CPU': 4, 'RAM': 16, 'SSD': 2}\n# Use list(estoque.values())\n",
      hints: [
        { text: "O método .values() devolve uma visualização de todos os valores do dicionário.", cost: 10 },
        { text: "print(list(estoque.values()))", cost: 20 },
      ],
      xpReward: 450,
      concept: "Método values()",
      conceptExplanation: "Enquanto .keys() pega os nomes das chaves, .values() devolve apenas os valores. Útil quando você só se importa com os dados em si, não com as etiquetas. Pode ser combinado com sum(), max(), min().",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Quantidades extraídas. O inventário pode ser somado para análise de capacidade.",
      solution: "estoque = {'CPU': 4, 'RAM': 16, 'SSD': 2}\nprint(list(estoque.values()))",
    },
    {
      id: "py-dict-10",
      worldId: "cripta-dicionarios",
      title: "Purga de Registro (pop)",
      description: "Use o método .pop() para remover a chave 'senha' do dicionário 'credenciais' e imprima o dicionário restante.",
      narrative: "Antes de salvar o log em disco, você precisa expurgar dados sensíveis. Use pop() para remover a entrada e capturar o valor removido em uma só operação.",
      difficulty: "iniciante",
      setupCode: "credenciais = {'user': 'root', 'senha': '12345', 'token': 'abc'}",
      expectedOutput: "{'user': 'root', 'token': 'abc'}",
      testCode: "assert 'pop' in code and 'senha' not in credenciais and output.strip() == \"{'user': 'root', 'token': 'abc'}\"",
      starterCode: "credenciais = {'user': 'root', 'senha': '12345', 'token': 'abc'}\n# Use credenciais.pop('senha') e imprima o dicionário\n",
      hints: [
        { text: "credenciais.pop('senha') remove a chave e retorna o valor que estava lá.", cost: 10 },
      ],
      xpReward: 470,
      concept: "Método pop()",
      conceptExplanation: "O .pop('chave') remove o item e devolve seu valor — ótimo quando você precisa do dado E quer apagá-lo. Diferente do 'del', que só apaga sem retornar nada.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Credencial sensível purgada. O log pode agora ser salvo em armazenamento não criptografado.",
      solution: "credenciais = {'user': 'root', 'senha': '12345', 'token': 'abc'}\ncredenciais.pop('senha')\nprint(credenciais)",
    },
    {
      id: "py-dict-11",
      worldId: "cripta-dicionarios",
      title: "Verificação de Acesso (in)",
      description: "Verifique se a chave 'admin' existe no dicionário 'perms'. Imprima 'autorizado' se existir, 'negado' caso contrário. A chave NÃO existe neste cenário.",
      narrative: "Antes de conceder acesso, sempre verifique se o operador está na ACL. Use o operador 'in' para evitar erros ao consultar chaves inexistentes.",
      difficulty: "iniciante",
      setupCode: "perms = {'user': 'r', 'guest': 'r'}",
      expectedOutput: "negado",
      testCode: "assert 'in perms' in code and output.strip() == 'negado'",
      starterCode: "perms = {'user': 'r', 'guest': 'r'}\n# Use 'if \"admin\" in perms:' para checar\n",
      hints: [
        { text: "O operador 'in' devolve True/False ao testar uma chave em um dicionário.", cost: 10 },
        { text: "if 'admin' in perms: print('autorizado')\nelse: print('negado')", cost: 20 },
      ],
      xpReward: 480,
      concept: "Operador in",
      conceptExplanation: "'chave in dicionario' é a forma rápida e segura de checar existência sem disparar KeyError. Por padrão, ele verifica apenas as chaves (não os valores). É a checagem que você faz ANTES de acessar.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tentativa de elevação de privilégio bloqueada. O cofre não permitiu o acesso indevido.",
      solution: "perms = {'user': 'r', 'guest': 'r'}\nif 'admin' in perms:\n    print('autorizado')\nelse:\n    print('negado')",
    },
    {
      id: "py-dict-12",
      worldId: "cripta-dicionarios",
      title: "Mesclagem de Configurações (update)",
      description: "Use o método .update() para mesclar o dicionário 'extra' dentro de 'base'. Imprima o resultado final.",
      narrative: "Dois pacotes de configuração precisam ser fundidos antes de aplicar no servidor. Use update() para sobrescrever e adicionar entradas em uma única chamada.",
      difficulty: "intermediario",
      setupCode: "base = {'host': 'localhost', 'porta': 80}\nextra = {'porta': 8080, 'ssl': True}",
      expectedOutput: "{'host': 'localhost', 'porta': 8080, 'ssl': True}",
      testCode: "assert 'update' in code and base.get('porta') == 8080 and base.get('ssl') == True",
      starterCode: "base = {'host': 'localhost', 'porta': 80}\nextra = {'porta': 8080, 'ssl': True}\n# Mescle extra dentro de base e imprima base\n",
      hints: [
        { text: "base.update(extra) modifica 'base' adicionando/sobrescrevendo as chaves de 'extra'.", cost: 10 },
      ],
      xpReward: 500,
      concept: "Método update()",
      conceptExplanation: "O .update(outro_dict) é a fusão definitiva: chaves novas são adicionadas, chaves existentes são sobrescritas. Modifica o dicionário original (não cria um novo). Equivalente moderno: dict_a | dict_b.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Configurações fundidas. O servidor agora opera com a porta 8080 e SSL ativo.",
      solution: "base = {'host': 'localhost', 'porta': 80}\nextra = {'porta': 8080, 'ssl': True}\nbase.update(extra)\nprint(base)",
    },
    {
      id: "py-dict-13",
      worldId: "cripta-dicionarios",
      title: "Navegação Profunda (Dicionário Aninhado)",
      description: "Dado 'rede' com um servidor aninhado, acesse e imprima o IP do servidor 'web' (rede['web']['ip']).",
      narrative: "Estruturas reais são hierárquicas — dicionários dentro de dicionários. Para chegar ao dado profundo, encadeie os acessos por chave.",
      difficulty: "intermediario",
      setupCode: "rede = {'web': {'ip': '10.0.0.1', 'porta': 443}, 'db': {'ip': '10.0.0.2', 'porta': 5432}}",
      expectedOutput: "10.0.0.1",
      testCode: "assert output.strip() == '10.0.0.1'",
      starterCode: "rede = {'web': {'ip': '10.0.0.1', 'porta': 443}, 'db': {'ip': '10.0.0.2', 'porta': 5432}}\n# Acesse o IP do servidor 'web'\n",
      hints: [
        { text: "Use colchetes em sequência: dicionario['nivel1']['nivel2'].", cost: 10 },
        { text: "print(rede['web']['ip'])", cost: 20 },
      ],
      xpReward: 520,
      concept: "Dicionários Aninhados",
      conceptExplanation: "Dicionários podem guardar outros dicionários como valores. Para acessar dados internos, encadeie colchetes. Essa é a estrutura por trás do JSON — formato universal de comunicação entre APIs.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Coordenada extraída do nó profundo. O servidor web foi identificado na hierarquia da rede.",
      solution: "rede = {'web': {'ip': '10.0.0.1', 'porta': 443}, 'db': {'ip': '10.0.0.2', 'porta': 5432}}\nprint(rede['web']['ip'])",
    },
    {
      id: "py-dict-14",
      worldId: "cripta-dicionarios",
      title: "Construtor Compacto (Dict Comprehension)",
      description: "Dada a lista 'nums = [1, 2, 3, 4]', use uma dict comprehension para criar um dicionário onde cada número é a chave e seu quadrado é o valor. Imprima o resultado.",
      narrative: "Construir tabelas hash manualmente é lento. Use a sintaxe compacta para gerar pares chave-valor em uma única linha, direto de uma fonte iterável.",
      difficulty: "avancado",
      setupCode: "nums = [1, 2, 3, 4]",
      expectedOutput: "{1: 1, 2: 4, 3: 9, 4: 16}",
      testCode: "assert 'for' in code and ':' in code and '{' in code and output.strip() == '{1: 1, 2: 4, 3: 9, 4: 16}'",
      starterCode: "nums = [1, 2, 3, 4]\n# Sintaxe: {chave: valor for item in iteravel}\n",
      hints: [
        { text: "Dict comprehension: {n: n**2 for n in nums}", cost: 10 },
        { text: "print({n: n**2 for n in nums})", cost: 20 },
      ],
      xpReward: 550,
      concept: "Dict Comprehension",
      conceptExplanation: "Mesma ideia das list comprehensions, mas gerando dicionários. Sintaxe: {chave: valor for item in iteravel}. Pode incluir 'if' para filtrar. Forma idiomática de transformar listas em mapas de lookup.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tabela hash construída em uma linha. Performance máxima, código mínimo.",
      solution: "nums = [1, 2, 3, 4]\nprint({n: n**2 for n in nums})",
    },
    {
      id: "py-dict-15",
      worldId: "cripta-dicionarios",
      title: "Censo do Cofre (len)",
      description: "Use a função len() para descobrir quantas chaves o dicionário 'usuarios' possui e imprima esse número.",
      narrative: "Quantos operadores estão registrados? Use a função built-in para contar instantaneamente, sem precisar iterar.",
      difficulty: "iniciante",
      setupCode: "usuarios = {'neo': 5, 'trinity': 7, 'morpheus': 9, 'oracle': 10}",
      expectedOutput: "4",
      testCode: "assert 'len' in code and output.strip() == '4'",
      starterCode: "usuarios = {'neo': 5, 'trinity': 7, 'morpheus': 9, 'oracle': 10}\n# Use len(usuarios)\n",
      hints: [
        { text: "len(dicionario) devolve a quantidade de pares chave-valor.", cost: 10 },
      ],
      xpReward: 470,
      concept: "len() em Dicionários",
      conceptExplanation: "A função len() funciona em qualquer coleção: listas, strings, sets, dicionários. Em dicionários, ela conta o número de pares chave-valor — operação em tempo constante O(1).",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Censo concluído. 4 operadores registrados no cofre.",
      solution: "usuarios = {'neo': 5, 'trinity': 7, 'morpheus': 9, 'oracle': 10}\nprint(len(usuarios))",
    },
    {
      id: "py-dict-16",
      worldId: "cripta-dicionarios",
      title: "Ordenação Alfabética",
      description: "Dado 'ranking', use sorted() em suas chaves para imprimir uma lista das chaves em ordem alfabética.",
      narrative: "O relatório final precisa exibir os operadores em ordem alfabética para auditoria. Ordene as chaves antes de exibir.",
      difficulty: "intermediario",
      setupCode: "ranking = {'zeta': 10, 'alpha': 5, 'gamma': 7}",
      expectedOutput: "['alpha', 'gamma', 'zeta']",
      testCode: "assert 'sorted' in code and output.strip() == \"['alpha', 'gamma', 'zeta']\"",
      starterCode: "ranking = {'zeta': 10, 'alpha': 5, 'gamma': 7}\n# Use sorted(ranking) ou sorted(ranking.keys())\n",
      hints: [
        { text: "sorted(dicionario) ordena as chaves automaticamente.", cost: 10 },
        { text: "print(sorted(ranking))", cost: 20 },
      ],
      xpReward: 580,
      concept: "sorted() em Dicionários",
      conceptExplanation: "sorted() devolve uma lista ordenada. Aplicado num dicionário, ele ordena as chaves. Para ordenar por valor, use sorted(dict.items(), key=lambda x: x[1]). Não modifica o dicionário original.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Lista alfabetizada. O relatório segue agora o padrão exigido pela auditoria.",
      solution: "ranking = {'zeta': 10, 'alpha': 5, 'gamma': 7}\nprint(sorted(ranking))",
    },
    {
      id: "py-dict-17",
      worldId: "cripta-dicionarios",
      title: "Detecção do Pico (max)",
      description: "Dado 'trafego', use max() com o argumento 'key' para descobrir QUAL chave possui o maior valor. Imprima essa chave.",
      narrative: "Qual servidor está sob ataque mais pesado? Encontre a entrada com maior valor de tráfego e identifique o alvo principal.",
      difficulty: "avancado",
      setupCode: "trafego = {'srv1': 120, 'srv2': 890, 'srv3': 340}",
      expectedOutput: "srv2",
      testCode: "assert 'max' in code and 'key' in code and output.strip() == 'srv2'",
      starterCode: "trafego = {'srv1': 120, 'srv2': 890, 'srv3': 340}\n# Use max(trafego, key=trafego.get)\n",
      hints: [
        { text: "max(dicionario, key=dicionario.get) retorna a chave com maior valor.", cost: 10 },
        { text: "print(max(trafego, key=trafego.get))", cost: 20 },
      ],
      xpReward: 600,
      concept: "max() com key",
      conceptExplanation: "max() e min() aceitam um parâmetro 'key' — uma função que diz QUAL critério usar na comparação. Passar dicionario.get faz com que ele compare pelos VALORES e retorne a CHAVE correspondente ao pico.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Alvo prioritário identificado: srv2. Mobilizando contramedidas para o servidor sob maior pressão.",
      solution: "trafego = {'srv1': 120, 'srv2': 890, 'srv3': 340}\nprint(max(trafego, key=trafego.get))",
    },
    {
      id: "py-dict-18",
      worldId: "cripta-dicionarios",
      title: "União de Inteligência (Sets)",
      description: "Dados 'alvos_a' e 'alvos_b', use o operador '|' para criar a união (todos os alvos de ambas as listas, sem duplicar). Imprima o tamanho do conjunto resultante.",
      narrative: "Duas equipes catalogaram alvos separadamente. Combine as listas em um único conjunto consolidado, eliminando duplicatas no processo.",
      difficulty: "intermediario",
      setupCode: "alvos_a = {'srv1', 'srv2', 'srv3'}\nalvos_b = {'srv3', 'srv4', 'srv5'}",
      expectedOutput: "5",
      testCode: "assert ('|' in code or 'union' in code) and output.strip() == '5'",
      starterCode: "alvos_a = {'srv1', 'srv2', 'srv3'}\nalvos_b = {'srv3', 'srv4', 'srv5'}\n# Una com | e imprima o len()\n",
      hints: [
        { text: "O operador | (ou .union()) combina dois sets removendo duplicatas.", cost: 10 },
        { text: "print(len(alvos_a | alvos_b))", cost: 20 },
      ],
      xpReward: 580,
      concept: "União de Sets (|)",
      conceptExplanation: "A união de dois conjuntos contém todos os elementos de ambos, sem repetição. O operador '|' é equivalente ao método .union(). Mais rápido que iterar e adicionar manualmente.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Listas consolidadas: 5 alvos únicos no total. A operação combinada pode prosseguir.",
      solution: "alvos_a = {'srv1', 'srv2', 'srv3'}\nalvos_b = {'srv3', 'srv4', 'srv5'}\nprint(len(alvos_a | alvos_b))",
    },
    {
      id: "py-dict-19",
      worldId: "cripta-dicionarios",
      title: "Diferença Tática (Sets)",
      description: "Dados 'todos_ips' e 'ips_seguros', use o operador '-' para encontrar os IPs que estão em 'todos_ips' mas NÃO estão em 'ips_seguros'. Imprima o conjunto resultante (em ordem ordenada para garantir consistência).",
      narrative: "Você tem a lista completa de IPs detectados e a whitelist de seguros. A diferença entre os dois é exatamente o conjunto de alvos suspeitos a investigar.",
      difficulty: "avancado",
      setupCode: "todos_ips = {'10.0.0.1', '10.0.0.2', '10.0.0.3', '10.0.0.4'}\nips_seguros = {'10.0.0.1', '10.0.0.4'}",
      expectedOutput: "['10.0.0.2', '10.0.0.3']",
      testCode: "assert '-' in code and '10.0.0.2' in output and '10.0.0.3' in output and '10.0.0.1' not in output",
      starterCode: "todos_ips = {'10.0.0.1', '10.0.0.2', '10.0.0.3', '10.0.0.4'}\nips_seguros = {'10.0.0.1', '10.0.0.4'}\n# Diferença com '-' e print(sorted(...))\n",
      hints: [
        { text: "O operador '-' devolve os elementos do primeiro set que NÃO estão no segundo.", cost: 10 },
        { text: "Use sorted() para garantir uma ordem consistente na saída: print(sorted(todos_ips - ips_seguros))", cost: 20 },
      ],
      xpReward: 600,
      concept: "Diferença de Sets (-)",
      conceptExplanation: "A diferença A - B contém os elementos que estão em A mas não em B. É a operação de 'subtração de conjuntos', útil para encontrar exceções, anomalias ou itens não autorizados.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Alvos suspeitos isolados. Os 2 IPs não-whitelistados serão analisados em profundidade.",
      solution: "todos_ips = {'10.0.0.1', '10.0.0.2', '10.0.0.3', '10.0.0.4'}\nips_seguros = {'10.0.0.1', '10.0.0.4'}\nprint(sorted(todos_ips - ips_seguros))",
    },
    {
      id: "py-dict-20",
      worldId: "cripta-dicionarios",
      title: "Contador de Frequência",
      description: "Dada a lista 'eventos', crie um dicionário 'contagem' onde cada chave é um evento e cada valor é quantas vezes ele aparece. Use um loop. Imprima o dicionário.",
      narrative: "O log de eventos tem entradas repetidas. Construa uma tabela de frequência para descobrir qual tipo de alerta dispara com mais intensidade.",
      difficulty: "avancado",
      setupCode: "eventos = ['login', 'erro', 'login', 'login', 'erro', 'logout']",
      expectedOutput: "{'login': 3, 'erro': 2, 'logout': 1}",
      testCode: "assert 'contagem' in locals() and contagem.get('login') == 3 and contagem.get('erro') == 2 and contagem.get('logout') == 1",
      starterCode: "eventos = ['login', 'erro', 'login', 'login', 'erro', 'logout']\ncontagem = {}\n# Itere e use .get(evento, 0) + 1\n",
      hints: [
        { text: "Para cada evento na lista: contagem[evento] = contagem.get(evento, 0) + 1", cost: 10 },
        { text: "for evento in eventos:\n    contagem[evento] = contagem.get(evento, 0) + 1\nprint(contagem)", cost: 20 },
      ],
      xpReward: 650,
      concept: "Padrão Counter Manual",
      conceptExplanation: "Contar frequências é o caso de uso clássico de dicionários. O truque é usar .get(chave, 0) — se a chave ainda não existe, começa em 0; senão, pega o valor atual e soma 1. Existe também a classe collections.Counter, que faz isso pronto.",
      successNpc: "Guardião da Cripta",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tabela de frequência gerada. O evento 'login' lidera com 3 ocorrências — investigação priorizada.",
      solution: "eventos = ['login', 'erro', 'login', 'login', 'erro', 'logout']\ncontagem = {}\nfor evento in eventos:\n    contagem[evento] = contagem.get(evento, 0) + 1\nprint(contagem)",
    },
  ],
};
