import { World } from "../types";

export const CRONOGRAMA_TEMPORAL_WORLD: World = {
  id: "cronograma-temporal",
  title: "Cronograma Temporal",
  subtitle: "Séries Temporais e Forecasting",
  icon: "clock",
  color: "#FB923C",
  bgImage: "/assets/images/worlds/temporal_chronograph.png",
  lore: "Dados que dependem do tempo precisam de técnicas próprias. Aqui você aprende a decompor séries, detectar sazonalidade e prever o futuro com ARIMA, Prophet e LSTM.",
  unlockRequirement: 24000,
  challenges: [
    {
      id: "ds-ts-01",
      worldId: "cronograma-temporal",
      title: "Datetime no Pandas",
      description: "Converta a string '2024-03-15' para Timestamp com pd.to_datetime e imprima.",
      narrative: "Tudo em séries temporais começa convertendo strings para objetos de data.",
      difficulty: "iniciante",
      setupCode: "class pd_mock:\n    @staticmethod\n    def to_datetime(s): return f'Timestamp(\"{s} 00:00:00\")'\npd = pd_mock()",
      expectedOutput: 'Timestamp("2024-03-15 00:00:00")',
      testCode: "assert 'to_datetime' in code",
      starterCode: "import pandas as pd\n# Converta '2024-03-15' e imprima\n",
      hints: [
        { text: "pd.to_datetime(string) converte qualquer formato comum em Timestamp.", cost: 10 },
        { text: "Para formato custom: pd.to_datetime(s, format='%d/%m/%Y').", cost: 20 },
        { text: "print(pd.to_datetime('2024-03-15'))", cost: 30 },
      ],
      xpReward: 500,
      concept: "pd.to_datetime",
      conceptExplanation: "pd.to_datetime é o canivete suíço para converter strings em objetos Timestamp do pandas. Aceita variedade de formatos automaticamente (ISO, americano, brasileiro). Para formatos custom não-óbvios, passe format='%Y-%m-%d %H:%M:%S' (sintaxe strftime). Para LISTAS, retorna DatetimeIndex (índice eficiente para séries temporais). Parâmetro errors='coerce' converte valores inválidos para NaT (Not-a-Time) em vez de quebrar. Sem datetime adequado, você perde acesso a operações temporais críticas (resample, rolling, dt accessors).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Data parseada com sucesso.",
      solution: "import pandas as pd\nprint(pd.to_datetime('2024-03-15'))",
    },
    {
      id: "ds-ts-02",
      worldId: "cronograma-temporal",
      title: "DatetimeIndex",
      description: "Crie datas = pd.date_range('2024-01-01', periods=5, freq='D') e imprima.",
      narrative: "Sequências de datas regulares são a base de qualquer série temporal.",
      difficulty: "iniciante",
      setupCode: "class pd_mock:\n    @staticmethod\n    def date_range(start, periods=None, freq='D'):\n        return f'DatetimeIndex of {periods} days from {start}'\npd = pd_mock()",
      expectedOutput: "DatetimeIndex of 5 days from 2024-01-01",
      testCode: "assert 'date_range' in code",
      starterCode: "import pandas as pd\n# Crie 5 datas diárias a partir de 2024-01-01 e imprima\n",
      hints: [
        { text: "pd.date_range(start, periods, freq) gera sequência de datas. freq='D' = diário, 'H' = horário, 'M' = mensal.", cost: 15 },
        { text: "periods define quantas; alternativa é passar end em vez de periods.", cost: 20 },
        { text: "datas = pd.date_range('2024-01-01', periods=5, freq='D')\\nprint(datas)", cost: 30 },
      ],
      xpReward: 550,
      concept: "date_range",
      conceptExplanation: "pd.date_range gera sequência regular de datas — base de séries temporais sintéticas e índices. Parâmetros: start, end (ou periods), freq. Frequências comuns: 'D' (diário), 'H' (horário), 'T' ou 'min' (minuto), 'S' (segundo), 'W' (semanal), 'M' (fim de mês), 'MS' (início de mês), 'Q' (trimestre), 'Y' (anual), 'B' (dias úteis). Use como índice de DataFrame: df.index = pd.date_range(...). Isso libera operações temporais avançadas (resample, rolling, shift). Para zonas de tempo: tz='America/Sao_Paulo' converte para timestamp consciente.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Sequência temporal gerada.",
      solution: "import pandas as pd\ndatas = pd.date_range('2024-01-01', periods=5, freq='D')\nprint(datas)",
    },
    {
      id: "ds-ts-03",
      worldId: "cronograma-temporal",
      title: "Componentes da Data",
      description: "Dado dt = pd.to_datetime('2024-03-15'), imprima dt.year e dt.month em linhas separadas.",
      narrative: "Acesso direto a ano, mês, dia, hora — sem regex nem split.",
      difficulty: "iniciante",
      setupCode: "class TS:\n    year = 2024\n    month = 3\nclass pd_mock:\n    @staticmethod\n    def to_datetime(s): return TS()\npd = pd_mock()",
      expectedOutput: "2024\n3",
      testCode: "assert '.year' in code and '.month' in code",
      starterCode: "import pandas as pd\ndt = pd.to_datetime('2024-03-15')\n# Imprima ano e mês\n",
      hints: [
        { text: "Timestamp tem atributos: .year, .month, .day, .hour, .minute, .second, .dayofweek, .quarter.", cost: 15 },
        { text: "Use dois print() para cada um em linha separada.", cost: 20 },
        { text: "print(dt.year)\\nprint(dt.month)", cost: 30 },
      ],
      xpReward: 500,
      concept: "Atributos de Datetime",
      conceptExplanation: "Objetos Timestamp/datetime têm atributos diretos para componentes: .year, .month, .day, .hour, .minute, .second, .microsecond, .dayofweek (0=segunda), .dayofyear, .quarter, .weekday(). Em SERIES de datas, use o accessor .dt: df['data'].dt.year, df['data'].dt.month_name(), df['data'].dt.is_weekend. Essenciais para FEATURE ENGINEERING TEMPORAL: extrair 'dia da semana', 'mês', 'é feriado', 'hora do dia' frequentemente são as features mais preditivas em modelos de demanda, energia, tráfego.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Componentes extraídos.",
      solution: "import pandas as pd\ndt = pd.to_datetime('2024-03-15')\nprint(dt.year)\nprint(dt.month)",
    },
    {
      id: "ds-ts-04",
      worldId: "cronograma-temporal",
      title: "Resample (Downsample)",
      description: "Dado série diária 'serie', agrupe por mês com .resample('M').sum() e imprima 'Resample OK.'.",
      narrative: "Converta dados diários em mensais — agregação temporal.",
      difficulty: "intermediario",
      setupCode: "class Serie:\n    def resample(self, freq):\n        class R:\n            def sum(self): return 'mensal'\n        return R()\nserie = Serie()",
      expectedOutput: "Resample OK.",
      testCode: "assert 'resample' in code",
      starterCode: "# Aplique resample mensal com .sum() e imprima 'Resample OK.'\n",
      hints: [
        { text: "serie.resample(freq) agrupa por intervalo; encadeie com .sum(), .mean(), .max(), etc.", cost: 20 },
        { text: "Freq: 'D' diário, 'W' semanal, 'M' fim de mês, 'Q' trimestre, 'Y' anual.", cost: 25 },
        { text: "serie.resample('M').sum()\\nprint('Resample OK.')", cost: 30 },
      ],
      xpReward: 750,
      concept: "Resampling (Downsampling)",
      conceptExplanation: "Resample agrupa série temporal em intervalos de tempo maiores (downsampling) ou menores (upsampling). DOWNSAMPLING: dados diários → mensais. Após resample, escolha uma agregação: .sum() (vendas totais por mês), .mean() (temperatura média), .max() (pico), .last() (preço de fechamento). UPSAMPLING: mensais → diários — gera NaN nos pontos novos; preencha com .ffill(), .bfill() ou interpolate(). Resample exige DatetimeIndex no DataFrame. Diferente do groupby (categórico), resample entende intervalos de tempo — incluindo fim de mês, fins de semana, fim de quarter.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Granularidade agregada.",
      solution: "serie.resample('M').sum()\nprint('Resample OK.')",
    },
    {
      id: "ds-ts-05",
      worldId: "cronograma-temporal",
      title: "Média Móvel (Rolling)",
      description: "Aplique média móvel de 7 dias: serie.rolling(window=7).mean(). Imprima 'Rolling OK.'.",
      narrative: "Suavize ruído para revelar a tendência subjacente.",
      difficulty: "intermediario",
      setupCode: "class Serie:\n    def rolling(self, window):\n        class R:\n            def mean(self): return 'suavizado'\n        return R()\nserie = Serie()",
      expectedOutput: "Rolling OK.",
      testCode: "assert 'rolling' in code and '.mean' in code",
      starterCode: "# Aplique rolling(window=7).mean() e imprima 'Rolling OK.'\n",
      hints: [
        { text: "serie.rolling(window=N) cria janela deslizante de tamanho N; encadeie agregação.", cost: 20 },
        { text: "Janela de 7 = média da semana. Outras agregações: .std(), .sum(), .max().", cost: 25 },
        { text: "serie.rolling(window=7).mean()\\nprint('Rolling OK.')", cost: 30 },
      ],
      xpReward: 800,
      concept: "Rolling Windows",
      conceptExplanation: "Rolling (janela deslizante) calcula estatísticas em uma janela móvel ao longo da série. MÉDIA MÓVEL de 7 dias suaviza ruído de curto prazo e revela tendência semanal. Parâmetros: window=N (tamanho), min_periods=K (mínimo para calcular), center=True (janela centrada vs trailing). Os primeiros N-1 valores ficam NaN. Agregações úteis: .mean (suavização), .std (volatilidade), .sum (acumulado), .max/min (extremos da janela). Em finanças, médias móveis (MA50, MA200) são indicadores clássicos. Para janela exponencialmente ponderada (mais peso aos valores recentes), use .ewm() em vez de .rolling().",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ruído suavizado.",
      solution: "serie.rolling(window=7).mean()\nprint('Rolling OK.')",
    },
    {
      id: "ds-ts-06",
      worldId: "cronograma-temporal",
      title: "Diferenciação",
      description: "Calcule diff = serie.diff() e imprima 'Diferenciada.'.",
      narrative: "Remova a tendência subtraindo cada valor do anterior.",
      difficulty: "intermediario",
      setupCode: "class Serie:\n    def diff(self): print('Diferenciada.')\nserie = Serie()",
      expectedOutput: "Diferenciada.",
      testCode: "assert '.diff' in code",
      starterCode: "# Diferencie a série e a impressão acontece dentro do mock\n",
      hints: [
        { text: "serie.diff() subtrai cada valor do anterior (lag 1). Para lag N: diff(N).", cost: 20 },
        { text: "Útil para tornar série estacionária — pré-requisito de ARIMA.", cost: 25 },
        { text: "serie.diff()", cost: 30 },
      ],
      xpReward: 800,
      concept: "Diferenciação",
      conceptExplanation: "Diferenciação subtrai cada observação da anterior (y_t - y_{t-1}) — operação crítica para tornar séries não-estacionárias em ESTACIONÁRIAS (média e variância constantes ao longo do tempo). Estacionariedade é PRÉ-REQUISITO de ARIMA. Para sazonalidade, use diff sazonal: serie.diff(12) para mensal anual. Em ARIMA(p,d,q), o 'd' é o número de diferenciações aplicadas. Após diferenciar, faça teste ADF (Augmented Dickey-Fuller) para confirmar estacionariedade. Em finanças, log-retornos (diff de log) são preferidos a diferenças absolutas — capturam variação proporcional.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tendência removida.",
      solution: "serie.diff()",
    },
    {
      id: "ds-ts-07",
      worldId: "cronograma-temporal",
      title: "Shift / Lag",
      description: "Crie feature lag1 = serie.shift(1) e imprima 'Lag criado.'.",
      narrative: "Use valores passados como features — a base de feature engineering temporal.",
      difficulty: "intermediario",
      setupCode: "class Serie:\n    def shift(self, n): print('Lag criado.')\nserie = Serie()",
      expectedOutput: "Lag criado.",
      testCode: "assert '.shift' in code",
      starterCode: "# Crie lag de 1 período\n",
      hints: [
        { text: "serie.shift(N) move os valores N posições para frente — y[t] vira y[t-N].", cost: 20 },
        { text: "Lag negativo (shift(-1)) move para trás — usado para criar TARGET futuro.", cost: 25 },
        { text: "serie.shift(1)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Shift / Lag",
      conceptExplanation: "shift(N) cria 'lag features' — usa valores PASSADOS como features para prever o presente. Em modelos clássicos (ARIMA, AR) e ML temporal: y[t] = f(y[t-1], y[t-2], y[t-7], y[t-30]). Cuidado com VAZAMENTO TEMPORAL: nunca use shift NEGATIVO em features (isso seria 'ver o futuro'). shift(-N) é usado para criar TARGETS futuros (prever próximos N períodos). Em pandas, pct_change() = (serie/serie.shift(1))-1, retorna variação percentual. Combinação típica: lag features + rolling features + datetime components.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Memória de passado armada.",
      solution: "serie.shift(1)",
    },
    {
      id: "ds-ts-08",
      worldId: "cronograma-temporal",
      title: "Decomposição Sazonal",
      description: "Use seasonal_decompose(serie, period=12) e imprima 'Decomposta.'.",
      narrative: "Separe tendência, sazonalidade e ruído.",
      difficulty: "avancado",
      setupCode: "def seasonal_decompose(s, period): print('Decomposta.'); return None\nserie = [1, 2, 3]",
      expectedOutput: "Decomposta.",
      testCode: "assert 'seasonal_decompose' in code",
      starterCode: "from statsmodels.tsa.seasonal import seasonal_decompose\n# Decomponha com period=12\n",
      hints: [
        { text: "seasonal_decompose retorna objeto com .trend, .seasonal, .resid (resíduo).", cost: 30 },
        { text: "period é o ciclo sazonal: 12 para mensal/anual, 7 para diário/semanal, 24 para horário/diário.", cost: 35 },
        { text: "seasonal_decompose(serie, period=12)\\nprint('Decomposta.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Decomposição de Séries Temporais",
      conceptExplanation: "Toda série temporal pode ser decomposta em 3 componentes: TENDÊNCIA (movimento de longo prazo, crescimento/declínio), SAZONALIDADE (padrões cíclicos regulares — picos no Natal, ciclos semanais), e RESÍDUO (o que sobra, ruído ou eventos não-explicados). Decomposição ADITIVA: y = tendência + sazonal + resíduo (sazonalidade de magnitude constante). MULTIPLICATIVA: y = tendência × sazonal × resíduo (sazonalidade proporcional à tendência — comum em vendas crescentes). Use seasonal_decompose ou STL (mais flexível, recomendada em séries modernas). Visualize as 4 componentes (original + 3) para diagnóstico — revela padrões, outliers e mudanças de regime.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Componentes isolados.",
      solution: "from statsmodels.tsa.seasonal import seasonal_decompose\nseasonal_decompose(serie, period=12)\nprint('Decomposta.')",
    },
    {
      id: "ds-ts-09",
      worldId: "cronograma-temporal",
      title: "ACF (Autocorrelação)",
      description: "Use plot_acf(serie) e imprima 'ACF plotada.'.",
      narrative: "Quanta correlação há com valores passados?",
      difficulty: "avancado",
      setupCode: "def plot_acf(s): print('ACF plotada.')\nserie = [1, 2, 3]",
      expectedOutput: "ACF plotada.",
      testCode: "assert 'plot_acf' in code",
      starterCode: "from statsmodels.graphics.tsaplots import plot_acf\n# Plote ACF e confirme\n",
      hints: [
        { text: "plot_acf desenha a autocorrelação em diferentes lags.", cost: 30 },
        { text: "Picos altos em lags específicos indicam sazonalidade ou ordens AR/MA.", cost: 35 },
        { text: "plot_acf(serie)\\nprint('ACF plotada.')", cost: 40 },
      ],
      xpReward: 1000,
      concept: "ACF / Autocorrelação",
      conceptExplanation: "ACF (Autocorrelation Function) mede a CORRELAÇÃO de uma série com versões DEFASADAS de si mesma. Para cada lag k, calcula correlação entre y[t] e y[t-k]. Lag 0 = 1 (correlação consigo mesma). Padrões: queda exponencial sugere AR; corte abrupto sugere MA; picos em múltiplos de 12 sugerem sazonalidade anual em dados mensais. Use plot_acf para diagnóstico visual. PACF (Partial ACF) é o equivalente removendo efeitos de lags intermediários — mais útil para identificar ordem AR. ACF e PACF são CRUCIAIS para escolher os parâmetros (p, q) do ARIMA.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Memória da série revelada.",
      solution: "from statsmodels.graphics.tsaplots import plot_acf\nplot_acf(serie)\nprint('ACF plotada.')",
    },
    {
      id: "ds-ts-10",
      worldId: "cronograma-temporal",
      title: "PACF",
      description: "Use plot_pacf(serie) e imprima 'PACF plotada.'.",
      narrative: "Autocorrelação parcial — remove influência de lags intermediários.",
      difficulty: "avancado",
      setupCode: "def plot_pacf(s): print('PACF plotada.')\nserie = [1, 2, 3]",
      expectedOutput: "PACF plotada.",
      testCode: "assert 'plot_pacf' in code",
      starterCode: "from statsmodels.graphics.tsaplots import plot_pacf\n# Plote PACF\n",
      hints: [
        { text: "plot_pacf — autocorrelação parcial, controlando lags intermediários.", cost: 30 },
        { text: "Útil para identificar a ordem p do AR/ARIMA: corte abrupto após lag p.", cost: 35 },
        { text: "plot_pacf(serie)\\nprint('PACF plotada.')", cost: 40 },
      ],
      xpReward: 1000,
      concept: "PACF / Autocorrelação Parcial",
      conceptExplanation: "PACF (Partial ACF) é como ACF, mas REMOVE a influência de lags INTERMEDIÁRIOS. Exemplo: a correlação entre y[t] e y[t-3] na ACF inclui efeitos transitando por y[t-1] e y[t-2]; a PACF isola o efeito DIRETO de y[t-3]. Padrões clássicos: PACF corta abruptamente após lag p → modelo AR(p); ACF cai exponencialmente. PACF cai exponencialmente, ACF corta após q → modelo MA(q). Os dois cortam → ARMA. Combinação de ACF + PACF é o método clássico (Box-Jenkins) para escolher parâmetros de ARIMA antes de auto_arima existir.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Correlação direta isolada.",
      solution: "from statsmodels.graphics.tsaplots import plot_pacf\nplot_pacf(serie)\nprint('PACF plotada.')",
    },
    {
      id: "ds-ts-11",
      worldId: "cronograma-temporal",
      title: "Teste de Estacionariedade",
      description: "Use adfuller(serie) e imprima o p-value (segundo elemento).",
      narrative: "Antes de ARIMA, confirme que a série é estacionária.",
      difficulty: "avancado",
      setupCode: "def adfuller(s): return (-3.5, 0.008, 0, 0)\nserie = [1, 2, 3]",
      expectedOutput: "0.008",
      testCode: "assert 'adfuller' in code",
      starterCode: "from statsmodels.tsa.stattools import adfuller\n# Imprima o p-value (segundo elemento da tupla)\n",
      hints: [
        { text: "adfuller (Augmented Dickey-Fuller) retorna tupla. Segundo elemento é o p-value.", cost: 25 },
        { text: "H0: série NÃO é estacionária. p < 0.05 → REJEITA → série é estacionária.", cost: 30 },
        { text: "resultado = adfuller(serie)\\nprint(resultado[1])", cost: 35 },
      ],
      xpReward: 950,
      concept: "Estacionariedade e ADF Test",
      conceptExplanation: "ESTACIONARIEDADE: propriedade onde média, variância e autocorrelação não variam ao longo do tempo. Pré-requisito da maioria dos modelos clássicos (ARIMA, VAR). Tendência → não-estacionária; sazonalidade → não-estacionária. AUGMENTED DICKEY-FULLER (ADF): teste mais usado. H0: série tem raiz unitária (NÃO estacionária); H1: estacionária. Resultado: p < 0.05 → REJEITA H0 → série é ESTACIONÁRIA. Se não-estacionária, aplique diferenciação (.diff()) e teste novamente — número de diff necessárias é o 'd' do ARIMA. Alternativa: teste KPSS (hipótese oposta — mais conservador). Use os dois em conjunto para diagnóstico robusto.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Estacionariedade verificada.",
      solution: "from statsmodels.tsa.stattools import adfuller\nresultado = adfuller(serie)\nprint(resultado[1])",
    },
    {
      id: "ds-ts-12",
      worldId: "cronograma-temporal",
      title: "ARIMA (Conceito)",
      description: "Crie um dicionario params com p=1, d=1, q=1 e imprima a tupla (p, d, q).",
      narrative: "O modelo clássico de séries temporais — entenda os 3 componentes.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "(1, 1, 1)",
      testCode: "assert 'params' in code and all(k in code for k in ['p', 'd', 'q'])\nassert output.strip() == '(1, 1, 1)'",
      starterCode: "# Monte params = {p, d, q} e imprima a tupla na ordem correta\n",
      hints: [
        { text: "Use um dict: params = {'p': 1, 'd': 1, 'q': 1}.", cost: 20 },
        { text: "A tupla final deve ser (params['p'], params['d'], params['q']).", cost: 30 },
        { text: "params = {'p': 1, 'd': 1, 'q': 1}\nprint((params['p'], params['d'], params['q']))", cost: 40 },
      ],
      xpReward: 900,
      concept: "ARIMA",
      conceptExplanation: "ARIMA(p, d, q) é o modelo clássico de séries temporais — combina três componentes: AR(p) — AutoRegressive: y[t] depende linearmente de p valores passados (y[t-1], y[t-2]...y[t-p]); I(d) — Integrated: aplica d DIFERENCIAÇÕES para tornar estacionária; MA(q) — Moving Average: y[t] depende de q erros passados (resíduos). Workflow: (1) plote a série, identifique tendência/sazonalidade; (2) diferencie até estacionária (define d); (3) analise ACF/PACF para escolher p e q; (4) ajuste com auto_arima ou statsmodels; (5) valide resíduos (devem parecer ruído branco). Para sazonalidade: SARIMA(p,d,q)(P,D,Q,s).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Trindade do ARIMA compreendida.",
      solution: "params = {'p': 1, 'd': 1, 'q': 1}\nprint((params['p'], params['d'], params['q']))",
    },
    {
      id: "ds-ts-13",
      worldId: "cronograma-temporal",
      title: "Treinar ARIMA",
      description: "Crie ARIMA(serie, order=(1,1,1)).fit() e imprima 'ARIMA treinado.'.",
      narrative: "Ajuste o modelo aos dados históricos.",
      difficulty: "avancado",
      setupCode: "class ARIMA:\n    def __init__(self, s, order): pass\n    def fit(self):\n        print('ARIMA treinado.')\n        return self\nserie = [1, 2, 3]",
      expectedOutput: "ARIMA treinado.",
      testCode: "assert 'ARIMA' in code and 'order' in code and 'fit' in code",
      starterCode: "from statsmodels.tsa.arima.model import ARIMA\n# ARIMA(serie, order=(1,1,1)).fit() e imprima\n",
      hints: [
        { text: "ARIMA(dados, order=(p, d, q)). Encadeie .fit() para treinar.", cost: 30 },
        { text: "order=(1,1,1) é o ARIMA mais simples não-trivial: 1 AR, 1 diff, 1 MA.", cost: 35 },
        { text: "modelo = ARIMA(serie, order=(1,1,1)).fit()", cost: 40 },
      ],
      xpReward: 1050,
      concept: "Ajuste de ARIMA",
      conceptExplanation: "ARIMA(serie, order=(p,d,q)).fit() ajusta o modelo aos dados. Saída: modelo treinado pronto para forecast. Métodos úteis após fit: .summary() (estatísticas completas, AIC/BIC, significância dos parâmetros), .forecast(steps=N) (previsão para próximos N períodos), .predict(start, end), .resid (resíduos para diagnóstico). DIAGNÓSTICO DE RESÍDUOS é obrigatório: resíduos devem parecer ruído branco (sem autocorrelação, distribuição normal aproximada, variância constante). Use plot_diagnostics() do statsmodels — gera 4 gráficos automaticamente. Para escolha automática de (p,d,q), use pmdarima.auto_arima.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo histórico calibrado.",
      solution: "from statsmodels.tsa.arima.model import ARIMA\nmodelo = ARIMA(serie, order=(1,1,1)).fit()\nprint('ARIMA treinado.')",
    },
    {
      id: "ds-ts-14",
      worldId: "cronograma-temporal",
      title: "Forecast ARIMA",
      description: "Use modelo.forecast(steps=5) e imprima 'Previsão de 5 passos.'.",
      narrative: "Use o modelo treinado para olhar adiante.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def forecast(self, steps): print(f'Previsão de {steps} passos.')\nmodelo = Modelo()",
      expectedOutput: "Previsão de 5 passos.",
      testCode: "assert 'forecast' in code and 'steps' in code",
      starterCode: "# modelo.forecast(steps=5)\n",
      hints: [
        { text: "modelo.forecast(steps=N) retorna previsões para N períodos futuros.", cost: 25 },
        { text: "Para intervalos de confiança junto: get_forecast(steps=N).summary_frame().", cost: 30 },
        { text: "modelo.forecast(steps=5)", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Forecast",
      conceptExplanation: "modelo.forecast(steps=N) gera previsão para os próximos N períodos. ATENÇÃO: previsões ficam progressivamente menos confiáveis quanto mais à frente — intervalos de confiança alargam exponencialmente. Para visualizar incerteza, use get_forecast(steps=N) que retorna previsão central + intervalos de confiança (95% padrão). Em produção, monitore continuamente o erro de previsão — quando ele aumenta consistentemente, retreine o modelo (CONCEPT DRIFT). Para forecasting de longo prazo (>12 períodos sazonais), ARIMA tende a 'pisar fundo' na média de longo prazo — outros métodos (Prophet, LSTM) podem performar melhor.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Futuro projetado.",
      solution: "modelo.forecast(steps=5)",
    },
    {
      id: "ds-ts-15",
      worldId: "cronograma-temporal",
      title: "SARIMA Sazonal",
      description: "Monte a tupla seasonal_order=(1,1,1,12), guarde em seasonal_order e imprima o ultimo valor s.",
      narrative: "ARIMA com sazonalidade explícita — para padrões anuais, mensais, semanais.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "12",
      testCode: "assert 'seasonal_order' in code and '12' in code\nassert output.strip() == '12'",
      starterCode: "# SARIMA usa seasonal_order=(P,D,Q,s). Crie a tupla e imprima s\n",
      hints: [
        { text: "A ordem sazonal tem quatro valores: P, D, Q e periodo s.", cost: 20 },
        { text: "O ultimo item da tupla pode ser acessado com seasonal_order[-1].", cost: 30 },
        { text: "seasonal_order = (1, 1, 1, 12)\nprint(seasonal_order[-1])", cost: 40 },
      ],
      xpReward: 950,
      concept: "SARIMA",
      conceptExplanation: "SARIMA = Seasonal ARIMA. Adiciona componentes SAZONAIS aos parâmetros do ARIMA: (P, D, Q, s) onde P,D,Q têm papéis análogos a p,d,q mas APLICADOS à sazonalidade, e s é o período sazonal (12 para mensal-anual, 4 para trimestral-anual, 7 para diário-semanal). Exemplo: vendas mensais com sazonalidade anual e padrão AR(1) → SARIMA(1,1,0)(1,1,0,12). Em statsmodels: SARIMAX (que também aceita variáveis exógenas via parâmetro exog — útil quando você tem features adicionais como preço, temperatura). Para escolha automática, pmdarima.auto_arima(serie, seasonal=True, m=12).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Sazonalidade modelada.",
      solution: "seasonal_order = (1, 1, 1, 12)\nprint(seasonal_order[-1])",
    },
    {
      id: "ds-ts-16",
      worldId: "cronograma-temporal",
      title: "Prophet (Meta)",
      description: "Crie modelo = Prophet() e imprima 'Prophet inicializado.'.",
      narrative: "Biblioteca da Meta — forecast simples e robusto para séries empresariais.",
      difficulty: "intermediario",
      setupCode: "class Prophet: pass",
      expectedOutput: "Prophet inicializado.",
      testCode: "assert 'Prophet' in code",
      starterCode: "from prophet import Prophet\n# modelo = Prophet() e imprima confirmação\n",
      hints: [
        { text: "Prophet (da Meta) é otimizado para séries de negócios com sazonalidade e feriados.", cost: 25 },
        { text: "Funciona com pouco tuning — robusto a outliers e dados faltantes.", cost: 30 },
        { text: "modelo = Prophet()\\nprint('Prophet inicializado.')", cost: 35 },
      ],
      xpReward: 950,
      concept: "Facebook Prophet",
      conceptExplanation: "Prophet é a biblioteca da Meta (ex-Facebook) para forecast de séries temporais — projetada para 'analistas leigos' produzirem forecasts de qualidade sem expertise em séries temporais. Decompõe a série em: tendência (linear ou logística), sazonalidade (Fourier), efeitos de feriados, e regressores adicionais. Vantagens: lida automaticamente com missing data, outliers, mudanças de regime; suporte explícito a feriados (BR inclusos); intervalos de confiança bayesianos. Formato esperado: DataFrame com colunas 'ds' (datetime) e 'y' (valor). Workflow simples: m = Prophet(); m.fit(df); future = m.make_future_dataframe(periods=30); forecast = m.predict(future).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Profeta corporativo invocado.",
      solution: "from prophet import Prophet\nmodelo = Prophet()\nprint('Prophet inicializado.')",
    },
    {
      id: "ds-ts-17",
      worldId: "cronograma-temporal",
      title: "Prophet com Feriados",
      description: "Crie Prophet(holidays=feriados) e imprima 'Feriados configurados.'.",
      narrative: "Datas especiais distorcem a série — declare-as explicitamente.",
      difficulty: "avancado",
      setupCode: "class Prophet:\n    def __init__(self, holidays=None): pass\nferiados = []",
      expectedOutput: "Feriados configurados.",
      testCode: "assert 'holidays' in code",
      starterCode: "from prophet import Prophet\n# Prophet com holidays=feriados\n",
      hints: [
        { text: "Prophet(holidays=df_feriados) — DataFrame com colunas 'holiday', 'ds', 'lower_window', 'upper_window'.", cost: 30 },
        { text: "Inclui também feriados nacionais embutidos: model.add_country_holidays(country_name='BR').", cost: 35 },
        { text: "modelo = Prophet(holidays=feriados)\\nprint('Feriados configurados.')", cost: 40 },
      ],
      xpReward: 1050,
      concept: "Feriados no Prophet",
      conceptExplanation: "Feriados causam grandes desvios em séries de negócios (Black Friday, Natal, Páscoa). Prophet permite declará-los explicitamente — em vez de o modelo tentar 'absorvê-los' como ruído. DataFrame de feriados: colunas 'holiday' (nome), 'ds' (data), 'lower_window' (dias antes afetados), 'upper_window' (dias depois). Alternativa: model.add_country_holidays(country_name='BR') usa biblioteca holidays para feriados nacionais automaticamente. Após fit, model.train_holiday_names mostra quais foram detectados. Importante quando dados têm mais de 1 ano (Prophet precisa de pelo menos uma repetição do feriado para aprender o efeito).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Eventos especiais declarados.",
      solution: "from prophet import Prophet\nmodelo = Prophet(holidays=feriados)\nprint('Feriados configurados.')",
    },
    {
      id: "ds-ts-18",
      worldId: "cronograma-temporal",
      title: "Exponential Smoothing",
      description: "Crie config = {'trend':'add', 'seasonal':'add', 'seasonal_periods':12} e imprima config['seasonal_periods'].",
      narrative: "Família de modelos clássicos baseada em médias ponderadas exponencialmente.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "12",
      testCode: "assert 'config' in code and 'trend' in code and 'seasonal_periods' in code\nassert output.strip() == '12'",
      starterCode: "# Configure Holt-Winters com tendencia e sazonalidade aditivas\n",
      hints: [
        { text: "Use strings 'add' para trend e seasonal.", cost: 25 },
        { text: "O periodo sazonal mensal anual e 12.", cost: 30 },
        { text: "config = {'trend': 'add', 'seasonal': 'add', 'seasonal_periods': 12}\nprint(config['seasonal_periods'])", cost: 40 },
      ],
      xpReward: 900,
      concept: "Exponential Smoothing (Holt-Winters)",
      conceptExplanation: "Família de métodos baseados em médias ponderadas EXPONENCIALMENTE: valores recentes pesam mais que antigos. Hierarquia: SIMPLE EXPONENTIAL SMOOTHING (só nível — sem tendência nem sazonalidade); HOLT (adiciona tendência linear); HOLT-WINTERS (adiciona sazonalidade — aditiva ou multiplicativa). Parâmetros aprendíveis (alpha, beta, gamma) — taxas de decaimento. Vantagens: simples, rápido, robusto, exige pouca configuração. Desvantagens: menos flexível que ARIMA ou Prophet em séries complexas. Em statsmodels: ExponentialSmoothing(serie, trend='add', seasonal='add', seasonal_periods=12).fit(). É frequentemente baseline competitivo.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Suavização exponencial explicada.",
      solution: "config = {'trend': 'add', 'seasonal': 'add', 'seasonal_periods': 12}\nprint(config['seasonal_periods'])",
    },
    {
      id: "ds-ts-19",
      worldId: "cronograma-temporal",
      title: "RMSE em Forecast",
      description: "Dado y_real=[100,102,105], y_pred=[101,100,107]. Calcule rmse usando np.sqrt(np.mean((y_real-y_pred)**2)). Imprima.",
      narrative: "Métrica padrão de erro em forecasting numérico.",
      difficulty: "intermediario",
      setupCode: "import numpy as np\ny_real = np.array([100, 102, 105])\ny_pred = np.array([101, 100, 107])",
      expectedOutput: "1.7320508075688772",
      testCode: "assert 'sqrt' in code and 'mean' in code",
      starterCode: "import numpy as np\ny_real = np.array([100, 102, 105])\ny_pred = np.array([101, 100, 107])\n# Calcule RMSE\n",
      hints: [
        { text: "RMSE = sqrt(mean((real - pred)²)). Use np.sqrt e np.mean.", cost: 20 },
        { text: "Diferença, elevar ao quadrado, média, raiz. Pode usar parênteses ou variáveis intermediárias.", cost: 25 },
        { text: "rmse = np.sqrt(np.mean((y_real - y_pred)**2))\\nprint(rmse)", cost: 30 },
      ],
      xpReward: 800,
      concept: "RMSE",
      conceptExplanation: "RMSE (Root Mean Squared Error) é a métrica padrão de erro em forecasting numérico: RMSE = sqrt(mean((real - pred)²)). Vantagens: mesma unidade dos dados (interpretável diretamente); penaliza erros grandes mais que pequenos. Comparação: MAE (Mean Absolute Error) usa valor absoluto em vez de quadrado — mais robusto a outliers, mas não amplifica erros grandes. MAPE (Mean Absolute Percentage Error): erro em PERCENTUAL — útil para comparar séries de escalas diferentes, mas falha quando real ≈ 0. Em produção, escolha a métrica conforme o domínio: penalizar grandes erros (RMSE) ou robustez (MAE).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Erro de previsão mensurado.",
      solution: "import numpy as np\ny_real = np.array([100, 102, 105])\ny_pred = np.array([101, 100, 107])\nprint(np.sqrt(np.mean((y_real - y_pred)**2)))",
    },
    {
      id: "ds-ts-20",
      worldId: "cronograma-temporal",
      title: "MAPE",
      description: "Dado y_real=[100,200] e y_pred=[110,180]. Calcule MAPE = mean(|real-pred|/|real|) * 100. Imprima.",
      narrative: "Erro em PERCENTUAL — interpretável e comparável entre séries.",
      difficulty: "intermediario",
      setupCode: "import numpy as np\ny_real = np.array([100, 200])\ny_pred = np.array([110, 180])",
      expectedOutput: "10.0",
      testCode: "assert 'mean' in code and 'abs' in code",
      starterCode: "import numpy as np\ny_real = np.array([100, 200])\ny_pred = np.array([110, 180])\n# Calcule MAPE em porcentagem\n",
      hints: [
        { text: "MAPE = mean(|real - pred| / |real|) * 100. Use np.abs e np.mean.", cost: 25 },
        { text: "Atenção: se y_real tem zeros, MAPE explode. Cuidado em séries com valores próximos de zero.", cost: 30 },
        { text: "mape = np.mean(np.abs((y_real - y_pred) / y_real)) * 100\\nprint(mape)", cost: 35 },
      ],
      xpReward: 850,
      concept: "MAPE",
      conceptExplanation: "MAPE (Mean Absolute Percentage Error) expressa erro em PERCENTUAL — interpretação intuitiva ('erro médio de 5%') e comparável entre séries de escalas diferentes (vendas em milhões vs unidades em centenas). Fórmula: mean(|real - pred| / |real|) * 100. LIMITAÇÕES SÉRIAS: (1) explode com y_real ≈ 0; (2) ASSIMÉTRICA — penaliza superestimativas e subestimativas de forma desigual; (3) não definido em y_real = 0. Alternativas: SMAPE (Symmetric MAPE) usa (|real|+|pred|)/2 no denominador; MASE compara com previsão ingênua. Em séries com valores positivos longe de zero, MAPE é confiável e amplamente reportado.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Erro percentual reportado.",
      solution: "import numpy as np\ny_real = np.array([100, 200])\ny_pred = np.array([110, 180])\nprint(np.mean(np.abs((y_real - y_pred) / y_real)) * 100)",
    },
    {
      id: "ds-ts-21",
      worldId: "cronograma-temporal",
      title: "Train/Test Temporal",
      description: "Divida split=int(len(serie)*0.8). train=serie[:split], test=serie[split:]. Imprima len(train).",
      narrative: "EM SÉRIES TEMPORAIS, jamais embaralhe — divisão é sempre cronológica.",
      difficulty: "intermediario",
      setupCode: "serie = list(range(100))",
      expectedOutput: "80",
      testCode: "assert ':split' in code or '[:split]' in code",
      starterCode: "serie = list(range(100))\n# Divida 80/20 cronologicamente e imprima tamanho do treino\n",
      hints: [
        { text: "NÃO use train_test_split do sklearn — ele embaralha, criando vazamento temporal.", cost: 20 },
        { text: "Use slicing: serie[:80] para treino, serie[80:] para teste.", cost: 25 },
        { text: "split = int(len(serie) * 0.8)\\ntrain = serie[:split]\\nprint(len(train))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Divisão Cronológica",
      conceptExplanation: "Em séries temporais, a divisão treino/teste DEVE ser cronológica — treino é tudo até data X, teste é tudo depois. NUNCA EMBARALHE: misturar passado e futuro causa VAZAMENTO TEMPORAL (modelo 'vê o futuro' durante treino, score artificialmente alto). Por isso train_test_split do sklearn é PROIBIDO em séries temporais. Para validação mais robusta com múltiplos folds, use sklearn.model_selection.TimeSeriesSplit — gera folds expansivos onde treino sempre precede teste. Em produção real, faça WALK-FORWARD VALIDATION: simule a passagem do tempo, retreinando periodicamente. É o único método honesto.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Divisão temporal correta.",
      solution: "serie = list(range(100))\nsplit = int(len(serie) * 0.8)\ntrain = serie[:split]\nprint(len(train))",
    },
    {
      id: "ds-ts-22",
      worldId: "cronograma-temporal",
      title: "Walk-Forward Validation",
      description: "Implemente walk-forward simples: para serie=[10,12,13,15], gere previsoes naive usando o ultimo valor observado antes de cada ponto de teste. Imprima previsoes.",
      narrative: "Simule produção: a cada novo dado, retreine o modelo.",
      difficulty: "avancado",
      setupCode: "serie = [10, 12, 13, 15]",
      expectedOutput: "[12, 13]",
      testCode: "assert 'for' in code and 'previsoes' in code and 'append' in code\nassert output.strip() == '[12, 13]'",
      starterCode: "serie = [10, 12, 13, 15]\nprevisoes = []\n# Para i=2..fim, preveja serie[i-1]\n",
      hints: [
        { text: "No baseline naive, a previsao para o proximo periodo e o ultimo valor observado.", cost: 25 },
        { text: "Use range(2, len(serie)) para gerar previsoes para os dois ultimos pontos.", cost: 30 },
        { text: "for i in range(2, len(serie)):\n    previsoes.append(serie[i - 1])\nprint(previsoes)", cost: 40 },
      ],
      xpReward: 1000,
      concept: "Walk-Forward Validation",
      conceptExplanation: "Walk-forward validation é a forma MAIS HONESTA de avaliar modelos de séries temporais. Simula como o modelo será usado em produção: (1) treina com dados até T; (2) prevê T+1; (3) compara com real; (4) AVANÇA — agora treina com dados até T+1; (5) prevê T+2; e assim por diante. Variantes: 'expanding window' (treino cresce a cada passo) ou 'sliding window' (treino mantém tamanho fixo, descartando os mais antigos). Caro computacionalmente (retreina N vezes) mas dá estimativa realista de performance. Em sklearn: TimeSeriesSplit implementa versão simplificada.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Validação honesta planejada.",
      solution: "serie = [10, 12, 13, 15]\nprevisoes = []\nfor i in range(2, len(serie)):\n    previsoes.append(serie[i - 1])\nprint(previsoes)",
    },
    {
      id: "ds-ts-23",
      worldId: "cronograma-temporal",
      title: "Feature Engineering Temporal",
      description: "Dado df com coluna 'data' como datetime, crie df['dia_semana'] = df['data'].dt.dayofweek. Imprima 'Features criadas.'.",
      narrative: "Extrair componentes da data como features é o primeiro passo de ML temporal.",
      difficulty: "avancado",
      setupCode: "class DTAccessor:\n    @property\n    def dayofweek(self): return None\nclass Col:\n    dt = DTAccessor()\nclass DF:\n    def __init__(self): self.cols = {}\n    def __getitem__(self, k): return Col()\n    def __setitem__(self, k, v): print('Features criadas.')\ndf = DF()",
      expectedOutput: "Features criadas.",
      testCode: "assert '.dt.dayofweek' in code",
      starterCode: "# Crie df['dia_semana'] usando .dt.dayofweek\n",
      hints: [
        { text: "Use o accessor .dt em Series de datetime: df['data'].dt.dayofweek.", cost: 25 },
        { text: "Outros componentes: .dt.month, .dt.day, .dt.hour, .dt.quarter, .dt.is_weekend, .dt.is_month_end.", cost: 30 },
        { text: "df['dia_semana'] = df['data'].dt.dayofweek", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Datetime Features",
      conceptExplanation: "FEATURE ENGINEERING TEMPORAL é frequentemente o que mais melhora modelos de demanda, energia, tráfego. Extraia: dayofweek (0=segunda), day, month, quarter, year, weekofyear, is_weekend, is_month_start/end, is_quarter_end. Para HORA do dia (sazonalidade circadiana): hour, sin/cos do hour (codificação circular preservando 'hora 23 próxima de hora 0'). FERIADOS: use a biblioteca holidays. LAGS e ROLLING: y[t-1], y[t-7], média_7_dias — capturam memória temporal explicitamente. Combinação de datetime features + lags + variáveis externas (clima, eventos) é a fórmula clássica de ML temporal.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Features temporais extraídas.",
      solution: "df['dia_semana'] = df['data'].dt.dayofweek",
    },
    {
      id: "ds-ts-24",
      worldId: "cronograma-temporal",
      title: "Sazonalidade Circular",
      description: "Para hora=23 e periodo=24, calcule hora_sin e hora_cos com math.sin/math.cos. Imprima round(hora_sin, 3) e round(hora_cos, 3).",
      narrative: "Para hora do dia, codifique circularmente — hora 23 é próxima de hora 0.",
      difficulty: "avancado",
      setupCode: "import math\nhora = 23\nperiodo = 24",
      expectedOutput: "-0.259\n0.966",
      testCode: "assert 'math.sin' in code and 'math.cos' in code and '2' in code\nassert output.strip().splitlines() == ['-0.259', '0.966']",
      starterCode: "import math\nhora = 23\nperiodo = 24\n# Calcule sin/cos de 2*pi*hora/periodo\n",
      hints: [
        { text: "O angulo e 2 * math.pi * hora / periodo.", cost: 25 },
        { text: "Calcule duas features: math.sin(angulo) e math.cos(angulo).", cost: 30 },
        { text: "angulo = 2 * math.pi * hora / periodo\nhora_sin = math.sin(angulo)\nhora_cos = math.cos(angulo)", cost: 40 },
      ],
      xpReward: 1000,
      concept: "Encoding Circular",
      conceptExplanation: "Variáveis cíclicas (hora do dia, dia da semana, mês do ano) têm problema com encoding linear: hora 0 e 23 ficam DISTANTES numericamente, mas são VIZINHAS na realidade. Solução: encoding CIRCULAR — sin(2π*x/período) e cos(2π*x/período) geram duas features que juntas preservam a circularidade. Para hora: x/24; para mês: x/12; para dia da semana: x/7. Modelos lineares e árvores se beneficiam. Para redes neurais, embeddings aprendidos podem ser superiores. Sem encoding circular, modelos lineares tratam hora 23→0 como salto de 23 unidades, prejudicando aprendizado.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ciclos preservados em features.",
      solution: "import math\nhora = 23\nperiodo = 24\nangulo = 2 * math.pi * hora / periodo\nhora_sin = math.sin(angulo)\nhora_cos = math.cos(angulo)\nprint(round(hora_sin, 3))\nprint(round(hora_cos, 3))",
    },
    {
      id: "ds-ts-25",
      worldId: "cronograma-temporal",
      title: "Detecção de Anomalias",
      description: "Para serie com média=50, std=10, marque anomalia se |x - 50| > 3*10. Imprima 'Anomalia' para x=85.",
      narrative: "Z-score básico para detectar outliers temporais.",
      difficulty: "avancado",
      setupCode: "x = 85\nmedia = 50\nstd = 10",
      expectedOutput: "Anomalia",
      testCode: "assert 'if' in code and '3' in code",
      starterCode: "x = 85\nmedia = 50\nstd = 10\n# Imprima 'Anomalia' se |x - media| > 3*std\n",
      hints: [
        { text: "Anomalia clássica: |z-score| > 3. Calcule |x - media| e compare com 3*std.", cost: 25 },
        { text: "abs(x - media) > 3 * std → imprime 'Anomalia'.", cost: 30 },
        { text: "if abs(x - media) > 3 * std:\\n    print('Anomalia')", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Anomaly Detection em Séries",
      conceptExplanation: "Detecção de anomalias é uma das aplicações principais de séries temporais — detectar valores atípicos em logs, sensores, vendas. MÉTODOS: (1) Z-score: |x - μ|/σ > 3 (clássico, exige normalidade); (2) IQR-based: x < Q1 - 1.5*IQR ou x > Q3 + 1.5*IQR; (3) ROLLING z-score: z-score com média/std de janela móvel — adapta a mudanças de regime; (4) Modelos preditivos: anomalia = grande resíduo de ARIMA/Prophet; (5) Isolation Forest: ML para alta dimensionalidade; (6) Autoencoders: reconstrução ruim = anomalia. Em produção, anomalias triggam alertas, mas exigem TRIAGEM — nem toda anomalia é problema (eventos legítimos).",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Outlier temporal isolado.",
      solution: "x = 85\nmedia = 50\nstd = 10\nif abs(x - media) > 3 * std:\n    print('Anomalia')",
    },
    {
      id: "ds-ts-26",
      worldId: "cronograma-temporal",
      title: "Pct_change",
      description: "Calcule serie.pct_change() — variação percentual período a período. Imprima 'Variações calculadas.'.",
      narrative: "Em finanças, retornos importam mais que preços absolutos.",
      difficulty: "intermediario",
      setupCode: "class Serie:\n    def pct_change(self): print('Variações calculadas.')\nserie = Serie()",
      expectedOutput: "Variações calculadas.",
      testCode: "assert 'pct_change' in code",
      starterCode: "# serie.pct_change()\n",
      hints: [
        { text: "serie.pct_change() retorna (serie[t] / serie[t-1]) - 1 = variação percentual.", cost: 25 },
        { text: "Equivalente a serie.diff() / serie.shift(1).", cost: 30 },
        { text: "serie.pct_change()", cost: 35 },
      ],
      xpReward: 900,
      concept: "Variação Percentual",
      conceptExplanation: "pct_change() calcula a variação percentual de um período para o próximo. Em finanças, é a base de RETORNOS — preço de fechamento é não-estacionário mas retornos geralmente são (boa premissa para modelos). Cuidado: pct_change em valor próximo de zero explode; em valores negativos pode dar resultados não-intuitivos. ALTERNATIVA SUPERIOR: LOG-RETORNOS — np.log(serie/serie.shift(1)). Vantagens: (1) aditivos no tempo (log-retorno mensal = soma dos diários); (2) simétricos (retorno -50% seguido de +100% volta ao zero, em log-retorno isso é -0.69 + 0.69 = 0); (3) aproximam normal para retornos pequenos.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Retornos extraídos.",
      solution: "serie.pct_change()",
    },
    {
      id: "ds-ts-27",
      worldId: "cronograma-temporal",
      title: "LSTM para Séries",
      description: "Crie janelas para LSTM: serie=[1,2,3,4,5], janela=3. Monte X e y, onde cada X tem 3 pontos e y e o proximo valor. Imprima X e y.",
      narrative: "Quando modelos clássicos falham, redes recorrentes assumem.",
      difficulty: "avancado",
      setupCode: "serie = [1, 2, 3, 4, 5]\njanela = 3",
      expectedOutput: "[[1, 2, 3], [2, 3, 4]]\n[4, 5]",
      testCode: "assert 'for' in code and 'X' in code and 'y' in code and 'append' in code\nassert output.strip().splitlines() == ['[[1, 2, 3], [2, 3, 4]]', '[4, 5]']",
      starterCode: "serie = [1, 2, 3, 4, 5]\njanela = 3\nX = []\ny = []\n# Crie janelas deslizantes\n",
      hints: [
        { text: "Para cada i, X recebe serie[i:i+janela] e y recebe serie[i+janela].", cost: 30 },
        { text: "O loop deve ir ate len(serie) - janela.", cost: 35 },
        { text: "for i in range(len(serie) - janela):\n    X.append(serie[i:i+janela])\n    y.append(serie[i+janela])", cost: 45 },
      ],
      xpReward: 1100,
      concept: "LSTM para Forecasting",
      conceptExplanation: "LSTMs (e GRUs) são redes neurais recorrentes que mantêm 'memória' entre passos da sequência — adequadas quando: (1) há padrões complexos não-lineares; (2) há múltiplas variáveis interagindo (multivariada); (3) há longas dependências; (4) você tem muitos dados de treino (LSTMs precisam de mais dados que ARIMA). Workflow: (1) crie janelas deslizantes (X = sequência de N períodos, y = próximo); (2) normalize features (MinMaxScaler); (3) construa modelo: Sequential([LSTM(50), Dense(1)]); (4) treine; (5) preveja iterativamente. Em séries simples, ARIMA/Prophet frequentemente igualam ou superam LSTM com muito menos dados.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Deep learning temporal invocado.",
      solution: "serie = [1, 2, 3, 4, 5]\njanela = 3\nX = []\ny = []\nfor i in range(len(serie) - janela):\n    X.append(serie[i:i+janela])\n    y.append(serie[i+janela])\nprint(X)\nprint(y)",
    },
    {
      id: "ds-ts-28",
      worldId: "cronograma-temporal",
      title: "Janelas para LSTM",
      description: "Para serie de tamanho 100 com janela=5, n_amostras = 100 - 5 = 95. Imprima 95.",
      narrative: "Antes de treinar LSTM, crie janelas deslizantes de entrada.",
      difficulty: "avancado",
      setupCode: "tamanho = 100\njanela = 5",
      expectedOutput: "95",
      testCode: "assert 'tamanho' in code and 'janela' in code",
      starterCode: "tamanho = 100\njanela = 5\n# Imprima quantas amostras geradas\n",
      hints: [
        { text: "n_amostras = tamanho - janela. Cada janela usa 'janela' pontos como X e o próximo como y.", cost: 25 },
        { text: "Imprima a subtração diretamente.", cost: 30 },
        { text: "print(tamanho - janela)", cost: 35 },
      ],
      xpReward: 950,
      concept: "Janelas Deslizantes (Windowing)",
      conceptExplanation: "Para alimentar LSTM com séries temporais, transforme em problema supervisionado via JANELAS DESLIZANTES: X[i] = serie[i:i+window], y[i] = serie[i+window]. Cada janela tem 'window' pontos como entrada para prever o próximo. Para N pontos de série com janela W, você gera (N - W) amostras. Para forecast de vários passos, varie: y pode ser próximos H pontos em vez de só 1. Shape final para LSTM: (n_amostras, window, n_features). NORMALIZAÇÃO é obrigatória antes do treino (MinMaxScaler ou StandardScaler). DESNORMALIZE as previsões para escala original ao final.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Janelas preparadas.",
      solution: "tamanho = 100\njanela = 5\nprint(tamanho - janela)",
    },
    {
      id: "ds-ts-29",
      worldId: "cronograma-temporal",
      title: "Concept Drift",
      description: "Dado erros=[4,5,7,12], calcule drift=True se o ultimo erro for maior que 1.5 vezes a media dos anteriores. Imprima drift.",
      narrative: "Modelos de séries temporais decaem com o tempo — monitore.",
      difficulty: "avancado",
      setupCode: "erros = [4, 5, 7, 12]",
      expectedOutput: "True",
      testCode: "assert 'erros' in code and 'media' in code and 'drift' in code\nassert output.strip() == 'True'",
      starterCode: "erros = [4, 5, 7, 12]\n# Compare o ultimo erro com 1.5x a media dos anteriores\n",
      hints: [
        { text: "Media dos anteriores: sum(erros[:-1]) / len(erros[:-1]).", cost: 25 },
        { text: "Drift se erros[-1] > media * 1.5.", cost: 30 },
        { text: "media = sum(erros[:-1]) / len(erros[:-1])\ndrift = erros[-1] > media * 1.5\nprint(drift)", cost: 40 },
      ],
      xpReward: 1000,
      concept: "Concept Drift",
      conceptExplanation: "CONCEPT DRIFT é a degradação da performance do modelo ao longo do tempo conforme o mundo muda — padrões que valiam quando o modelo foi treinado deixam de valer. Tipos: (1) Sudden — mudança abrupta (pandemia, mudança regulatória); (2) Gradual — evolução lenta (mudança de comportamento de consumidor); (3) Recurring — sazonalidade não capturada inicialmente; (4) Covariate shift — distribuição de X mudou mas P(y|X) é igual; (5) Real concept drift — relação X→y mudou. DETECÇÃO: monitore métricas em produção continuamente (RMSE, MAPE) — quando degradam, é hora de retreinar. Em produção robusta, retreine periodicamente (semanal/mensal) independente de drift detectado.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Necessidade de retreino reconhecida.",
      solution: "erros = [4, 5, 7, 12]\nmedia = sum(erros[:-1]) / len(erros[:-1])\ndrift = erros[-1] > media * 1.5\nprint(drift)",
    },
    {
      id: "ds-ts-30",
      worldId: "cronograma-temporal",
      title: "Hierarchical Forecasting",
      description: "Dado vendas={'norte':[100,120], 'sul':[80,90]}, calcule forecast_total somando o ultimo valor de cada regiao. Imprima forecast_total.",
      narrative: "Forecast em níveis: por loja, por região, total — todos coerentes.",
      difficulty: "avancado",
      setupCode: "vendas = {'norte': [100, 120], 'sul': [80, 90]}",
      expectedOutput: "210",
      testCode: "assert 'vendas' in code and ('values()' in code or 'for' in code) and 'forecast_total' in code\nassert output.strip() == '210'",
      starterCode: "vendas = {'norte': [100, 120], 'sul': [80, 90]}\n# Some o ultimo forecast de cada regiao\n",
      hints: [
        { text: "Use os valores do dicionario para acessar cada lista regional.", cost: 25 },
        { text: "O ultimo item de uma lista e lista[-1].", cost: 30 },
        { text: "forecast_total = sum(regiao[-1] for regiao in vendas.values())\nprint(forecast_total)", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Hierarchical Forecasting",
      conceptExplanation: "Quando você precisa fazer forecast em MÚLTIPLOS NÍVEIS (vendas por SKU, por loja, por região, total), surgem desafios de COERÊNCIA: as previsões precisam somar corretamente — soma de previsões por loja deve igualar previsão do total. Abordagens: (1) BOTTOM-UP: preveja no nível mais detalhado e agregue (preciso no detalhe, ruidoso no total); (2) TOP-DOWN: preveja o total e distribua por proporções históricas (suave no total, perde precisão no detalhe); (3) MIDDLE-OUT: nível intermediário; (4) RECONCILIATION: prevê em todos os níveis e ajusta otimamente. Bibliotecas: hts (R) e statsforecast/hierarchicalforecast (Python/Nixtla). Crítico em planejamento de demanda em grandes varejistas.",
      successNpc: "Cronomante",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Previsões coerentes em níveis.",
      solution: "vendas = {'norte': [100, 120], 'sul': [80, 90]}\nforecast_total = sum(regiao[-1] for regiao in vendas.values())\nprint(forecast_total)",
    },
  ],
};
