import { World } from "../types";

export const FLORESTA_FUNCOES_WORLD: World = {
  id: "floresta-funcoes",
  title: "Repositório de Funções",
  subtitle: "Modularização do Sistema",
  icon: "package",
  color: "#8B5CF6",
  bgImage: "/assets/images/worlds/function_repo.png",
  lore: "No Repositório Central, os Hackers aprendem a otimizar scripts encapsulando rotinas em blocos reutilizáveis chamados Funções.",
  unlockRequirement: 1500,
  challenges: [
    {
      id: "py-func-01",
      worldId: "floresta-funcoes",
      title: "Sub-rotina de Handshake",
      description: "Defina uma função chamada saudar que recebe um nome e imprime 'Ola, [nome]!'. Chame a sub-rotina passando o nome 'Admin'.",
      narrative: "O servidor principal precisa responder aos pacotes de entrada de forma dinâmica. Encapsule o comando de boas-vindas em uma função reutilizável.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Ola, Admin!",
      testCode: "assert 'saudar' in locals() and callable(saudar) and output.strip() == 'Ola, Admin!'",
      starterCode: "# Defina a sub-rotina saudar e invoque-a\n",
      hints: [
        { text: "Funções começam com def nome(parâmetro):", cost: 10 },
        { text: "Use uma f-string para formatar a string de saída: f'Ola, {nome}!'", cost: 20 },
        { text: "def saudar(nome):\n    print(f'Ola, {nome}!')\n\nsaudar('Admin')", cost: 30 },
      ],
      xpReward: 400,
      concept: "Criação de Funções (def)",
      conceptExplanation: "Uma função (criada com a palavra 'def') é como ensinar um truque novo para o computador. Em vez de escrever o mesmo código várias vezes, você agrupa ele e dá um nome.\n\nPor exemplo:\ndef bom_dia():\n    print('Bom dia, Operador!')\n\nAgora, sempre que você escrever apenas bom_dia() no código, o computador vai executar aquela mensagem!",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Módulo gravado com sucesso. O sistema agora pode escalar chamadas para a sub-rotina automaticamente.",
    },
    {
      id: "py-func-02",
      worldId: "floresta-funcoes",
      title: "Cálculo de Potência de Sinal",
      description: "Crie uma função 'sinal' que recebe 'base' e 'ganho' e printe a multiplicação dos dois. Chame com 10 e 5.",
      narrative: "Para alcançar servidores em outros setores, você deve calcular a potência necessária combinando o sinal base com o multiplicador de ganho.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "50",
      testCode: "assert 'sinal' in locals() and sinal(10, 5) == None and output.strip() == '50'",
      starterCode: "# Crie a função sinal e chame com 10 e 5\n",
      hints: [
        { text: "Funções podem receber vários parâmetros separados por vírgula.", cost: 10 },
        { text: "def sinal(base, ganho):", cost: 20 },
        { text: "sinal(10, 5)", cost: 30 },
      ],
      xpReward: 450,
      concept: "Parâmetros Múltiplos",
      conceptExplanation: "Funções podem receber várias informações de uma vez. Basta listar os nomes dos parâmetros dentro dos parênteses, separados por vírgula. Isso permite criar ferramentas muito mais flexíveis.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Potência calculada. O sinal agora é forte o suficiente para atravessar o firewall do próximo setor.",
    },
    {
      id: "py-func-03",
      worldId: "floresta-funcoes",
      title: "Gerador de Chave Mestra",
      description: "Crie uma função 'gerar_chave' que recebe 'cod' e RETORNA 'cod' multiplicado por 100. Printe o resultado da chamada com 7.",
      narrative: "O sistema exige uma chave gerada por algoritmo. A função deve processar o código semente e devolver o resultado para ser usado no log de acesso.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "700",
      testCode: "assert 'gerar_chave' in locals() and gerar_chave(7) == 700 and output.strip() == '700'",
      starterCode: "# Use 'return' para devolver o valor da função\n",
      hints: [
        { text: "O comando 'return' devolve um valor para quem chamou a função.", cost: 10 },
        { text: "Exemplo: return x * 100", cost: 20 },
        { text: "resultado = gerar_chave(7)\nprint(resultado)", cost: 30 },
      ],
      xpReward: 500,
      concept: "Retorno de Valores (return)",
      conceptExplanation: "Às vezes você quer que a função 'calcule algo e te devolva o resultado' em vez de apenas mostrar na tela. Para isso usamos o `return`. É como pedir para alguém fazer uma conta e te dizer a resposta.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Chave mestre 700 gerada. O acesso ao Repositório Central foi totalmente desbloqueado.",
    },
  ],
};
