import { World } from "../types";

export const FLORESTA_FUNCOES_WORLD: World = {
  id: "floresta-funcoes",
  title: "Repositório de Funções",
  subtitle: "Modularização do Sistema",
  icon: "package",
  color: "#8B5CF6",
  bgImage: "/assets/images/worlds/function_repo.png",
  lore: "No Repositório Central, os Hackers aprendem a otimizar scripts encapsulando rotinas em blocos reutilizáveis chamados Funções.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-func-01",
      worldId: "floresta-funcoes",
      title: "Sub-rotina de Handshake",
      description: "Defina uma função chamada saudar que recebe um nome e imprime 'Ola, [nome]!'. Chame a sub-rotina passando o nome 'Admin'.",
      narrative: "O servidor principal precisa responder aos pacotes de entrada de forma dinâmica. Encapsule o comando de boas-vindas em uma função reutilizável.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Ola, Admin!",
      testCode: "assert 'saudar' in locals() and callable(saudar) and output.strip() == 'Ola, Admin!'",
      starterCode: "# Defina a sub-rotina saudar e invoque-a\n",
      hints: [
        { text: "Funções começam com def nome(parâmetro):", cost: 10 },
        { text: "Use uma f-string para formatar a string de saída: f'Ola, {nome}!'", cost: 20 },
        { text: "def saudar(nome):\n    print(f'Ola, {nome}!')\n\nsaudar('Admin')", cost: 30 },
      ],
      xpReward: 400,
      concept: "Criação de Funções (def)",
      conceptExplanation: "Uma função (criada com a palavra 'def') é como ensinar um truque novo para o computador. Em vez de escrever o mesmo código várias vezes, você agrupa ele e dá um nome.\n\nPor exemplo:\ndef bom_dia():\n    print('Bom dia, Operador!')\n\nAgora, sempre que você escrever apenas bom_dia() no código, o computador vai executar aquela mensagem!",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Módulo gravado com sucesso. O sistema agora pode escalar chamadas para a sub-rotina automaticamente.",
      solution: "def saudar(nome):\n    print(f'Ola, {nome}!')\n\nsaudar('Admin')",
    },
    {
      id: "py-func-02",
      worldId: "floresta-funcoes",
      title: "Cálculo de Potência de Sinal",
      description: "Crie uma função 'sinal' que recebe 'base' e 'ganho' e imprima a multiplicação dos dois. Chame com 10 e 5.",
      narrative: "Para alcançar servidores em outros setores, você deve calcular a potência necessária combinando o sinal base com o multiplicador de ganho.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "50",
      testCode: "assert 'sinal' in locals() and sinal(10, 5) == None and output.strip() == '50'",
      starterCode: "# Crie a função sinal e chame com 10 e 5\n",
      hints: [
        { text: "Funções podem receber vários parâmetros separados por vírgula.", cost: 10 },
        { text: "def sinal(base, ganho):", cost: 20 },
        { text: "sinal(10, 5)", cost: 30 },
      ],
      xpReward: 450,
      concept: "Parâmetros Múltiplos",
      conceptExplanation: "Funções podem receber várias informações de uma vez. Basta listar os nomes dos parâmetros dentro dos parênteses, separados por vírgula. Isso permite criar ferramentas muito mais flexíveis.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Potência calculada. O sinal agora é forte o suficiente para atravessar o firewall do próximo setor.",
      solution: "def sinal(base, ganho):\n    print(base * ganho)\n\nsinal(10, 5)",
    },
    {
      id: "py-func-03",
      worldId: "floresta-funcoes",
      title: "Gerador de Chave Mestra",
      description: "Crie uma função 'gerar_chave' que recebe 'cod' e RETORNA 'cod' multiplicado por 100. Imprima o resultado da chamada com 7.",
      narrative: "O sistema exige uma chave gerada por algoritmo. A função deve processar o código semente e devolver o resultado para ser usado no log de acesso.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "700",
      testCode: "assert 'gerar_chave' in locals() and gerar_chave(7) == 700 and output.strip() == '700'",
      starterCode: "# Use 'return' para devolver o valor da função\n",
      hints: [
        { text: "O comando 'return' devolve um valor para quem chamou a função.", cost: 10 },
        { text: "Exemplo: return x * 100", cost: 20 },
        { text: "resultado = gerar_chave(7)\nprint(resultado)", cost: 30 },
      ],
      xpReward: 500,
      concept: "Retorno de Valores (return)",
      conceptExplanation: "Às vezes você quer que a função 'calcule algo e te devolva o resultado' em vez de apenas mostrar na tela. Para isso usamos o `return`. É como pedir para alguém fazer uma conta e te dizer a resposta.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Chave mestre 700 gerada. O acesso ao Repositório Central foi totalmente desbloqueado.",
      solution: "def gerar_chave(cod):\n    return cod * 100\n\nprint(gerar_chave(7))",
    },
    {
      id: "py-func-04",
      worldId: "floresta-funcoes",
      title: "Configuração de Porta Padrão",
      description: "Crie uma função 'conectar' que recebe 'ip' e 'porta'. A 'porta' deve ter o valor padrão 80. A função deve imprimir 'Conectando em [ip]:[porta]'. Chame apenas com o IP '192.168.1.1'.",
      narrative: "Para agilizar as conexões, a maioria dos servidores usa a porta 80 por padrão. Crie uma função que assuma esse valor, a menos que o operador especifique o contrário.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Conectando em 192.168.1.1:80",
      testCode: "assert 'porta=80' in code.replace(' ', '') and output.strip() == 'Conectando em 192.168.1.1:80'",
      starterCode: "# Use parâmetros padrão na sua função\n",
      hints: [
        { text: "Você pode definir um valor padrão no parâmetro: def func(a, b=10):", cost: 10 },
        { text: "print(f'Conectando em {ip}:{porta}')", cost: 20 },
      ],
      xpReward: 550,
      concept: "Parâmetros Padrão (Default Arguments)",
      conceptExplanation: "Parâmetros padrão permitem que você defina um valor 'reserva'. Se quem chamar a função esquecer de enviar aquele dado, o Python usa o valor que você deixou preparado.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Módulo de conexão otimizado. O sistema agora assume a porta web padrão automaticamente.",
      solution: "def conectar(ip, porta=80):\n    print(f'Conectando em {ip}:{porta}')\n\nconectar('192.168.1.1')",
    },
    {
      id: "py-func-05",
      worldId: "floresta-funcoes",
      title: "Extração Multi-Layer",
      description: "Crie uma função 'analisar' que recebe um número e retorna esse número e o seu dobro (dois valores). Imprima o resultado da chamada com 50.",
      narrative: "Alguns scanners avançados conseguem extrair múltiplos metadados de uma só vez. Sua função deve retornar tanto o valor original quanto o processado.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "(50, 100)",
      testCode: "assert 'return' in code and '50, 100' in output",
      starterCode: "# Retorne múltiplos valores separados por vírgula\n",
      hints: [
        { text: "Para retornar vários valores, use return val1, val2", cost: 10 },
        { text: "Ao imprimir o resultado, o Python mostrará os valores entre parênteses (uma tupla).", cost: 20 },
      ],
      xpReward: 600,
      concept: "Retorno Múltiplo",
      conceptExplanation: "Diferente de muitas linguagens, o Python permite que uma função devolva várias respostas de uma vez só! Basta separá-las por vírgula no `return`.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Dados extraídos em camadas. A análise de redundância confirmou a integridade do dobro da carga.",
      solution: "def analisar(n):\n    return n, n * 2\n\nprint(analisar(50))",
    },
    {
      id: "py-func-06",
      worldId: "floresta-funcoes",
      title: "Documentação de Protocolo",
      description: "Crie uma função qualquer e adicione uma Docstring (comentário de múltiplas linhas logo abaixo do def). A função deve apenas imprimir 'OK'.",
      narrative: "Código profissional precisa ser documentado. As Docstrings permitem que outros hackers (ou você no futuro) entendam o que seu script faz sem precisar ler todo o código.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "OK",
      testCode: "assert '\"\"\"' in code or \"'''\" in code",
      starterCode: "def meu_protocolo():\n    \"\"\"Este script faz tal coisa\"\"\"\n    # Complete aqui\n",
      hints: [
        { text: "Docstrings são strings delimitadas por três aspas: \"\"\" comentário \"\"\"", cost: 10 },
        { text: "Elas devem vir logo na primeira linha dentro da função.", cost: 20 },
      ],
      xpReward: 650,
      concept: "Docstrings (Documentação)",
      conceptExplanation: "Docstrings são como o manual de instruções da sua função, guardado dentro dela. É uma boa prática essencial para quem trabalha em equipe ou em projetos grandes.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Protocolo documentado. Agora seu código segue os padrões internacionais de desenvolvimento Magitech.",
      solution: "def meu_protocolo():\n    \"\"\"Este script faz tal coisa\"\"\"\n    print('OK')\n\nmeu_protocolo()",
    },
    {
      id: "py-func-07",
      worldId: "floresta-funcoes",
      title: "Coleta de Pacotes Variáveis",
      description: "Crie uma função 'somar_pacotes' que aceite uma quantidade indefinida de números usando *args e retorne a soma total. Chame com os valores 10, 20, 30, 40 e imprima o resultado.",
      narrative: "O sniffer captura um número imprevisível de pacotes a cada execução. Sua função precisa aceitar qualquer quantidade de argumentos sem precisar redefinir a assinatura.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "100",
      testCode: "assert '*' in code and 'somar_pacotes' in locals() and somar_pacotes(10, 20, 30, 40) == 100 and output.strip() == '100'",
      starterCode: "# Use *args para aceitar qualquer quantidade de argumentos\n",
      hints: [
        { text: "O *args coleta todos os argumentos posicionais em uma tupla.", cost: 10 },
        { text: "def somar_pacotes(*args): return sum(args)", cost: 20 },
        { text: "print(somar_pacotes(10, 20, 30, 40))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Argumentos Variáveis (*args)",
      conceptExplanation: "Quando você não sabe quantos argumentos a função vai receber, use *args. O Python empacota todos eles em uma tupla automaticamente, permitindo iterar ou somar como se fosse uma lista.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Pacotes consolidados. O sniffer agora processa rajadas de tamanho arbitrário sem reescrever código.",
      solution: "def somar_pacotes(*args):\n    return sum(args)\n\nprint(somar_pacotes(10, 20, 30, 40))",
    },
    {
      id: "py-func-08",
      worldId: "floresta-funcoes",
      title: "Configuração Dinâmica (**kwargs)",
      description: "Crie uma função 'config' que aceite argumentos nomeados (**kwargs) e imprima cada par no formato 'chave=valor', uma linha por par. Chame com host='10.0.0.1', porta=22.",
      narrative: "Cada operação remota usa um conjunto diferente de flags de configuração. Sua função deve aceitar qualquer combinação nomeada sem quebrar.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "host=10.0.0.1\nporta=22",
      testCode: "assert '**' in code and 'host=10.0.0.1' in output and 'porta=22' in output",
      starterCode: "# Use **kwargs para aceitar argumentos nomeados\n",
      hints: [
        { text: "**kwargs coleta argumentos nomeados em um dicionário.", cost: 10 },
        { text: "for chave, valor in kwargs.items(): print(f'{chave}={valor}')", cost: 20 },
      ],
      xpReward: 700,
      concept: "Argumentos Nomeados Variáveis (**kwargs)",
      conceptExplanation: "O **kwargs é o irmão do *args, mas para argumentos com nome. Em vez de tupla, ele entrega um dicionário com as chaves e valores que foram passados. Essencial para criar APIs flexíveis.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Configuração dinâmica aceita. O módulo agora aceita qualquer flag que o operador inventar.",
      solution: "def config(**kwargs):\n    for chave, valor in kwargs.items():\n        print(f'{chave}={valor}')\n\nconfig(host='10.0.0.1', porta=22)",
    },
    {
      id: "py-func-09",
      worldId: "floresta-funcoes",
      title: "Sub-rotina Anônima (Lambda)",
      description: "Crie uma função lambda chamada 'dobrar' que recebe um número e retorna o dobro. Imprima o resultado de dobrar(21).",
      narrative: "Para operações pequenas e descartáveis, criar uma função completa com 'def' é desperdício. Use uma função anônima para encapsular a lógica em uma única linha.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "42",
      testCode: "assert 'lambda' in code and output.strip() == '42'",
      starterCode: "# Crie a função lambda 'dobrar' e imprima dobrar(21)\n",
      hints: [
        { text: "Sintaxe: lambda parametro: expressao", cost: 10 },
        { text: "dobrar = lambda x: x * 2", cost: 20 },
      ],
      xpReward: 750,
      concept: "Funções Lambda (Anônimas)",
      conceptExplanation: "Lambdas são funções de uma linha só, sem nome formal. São perfeitas para operações curtas que você só vai usar uma vez, especialmente quando passadas como argumento para outras funções como map() ou filter().",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Operação inline executada. Código mais enxuto, menos linhas para o adversário rastrear.",
      solution: "dobrar = lambda x: x * 2\nprint(dobrar(21))",
    },
    {
      id: "py-func-10",
      worldId: "floresta-funcoes",
      title: "Escopo Local Isolado",
      description: "Defina uma função 'processar' que cria uma variável local 'segredo = 42' e a imprime. Fora da função, tente imprimir 'segredo' dentro de um bloco try/except — imprima 'fora_de_escopo' se NameError ocorrer. Saída esperada: 42 na primeira linha, 'fora_de_escopo' na segunda.",
      narrative: "Variáveis criadas dentro de uma função vivem em um setor isolado de memória. Elas não vazam para o resto do sistema — o que é uma proteção, não um bug.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "42\nfora_de_escopo",
      testCode: "assert '42' in output and 'fora_de_escopo' in output",
      starterCode: "def processar():\n    segredo = 42\n    print(segredo)\n\nprocessar()\ntry:\n    print(segredo)\nexcept NameError:\n    print('fora_de_escopo')\n",
      hints: [
        { text: "Variáveis dentro da função são locais — não existem fora dela.", cost: 10 },
        { text: "Acessar uma variável local fora da função gera NameError.", cost: 20 },
      ],
      xpReward: 750,
      concept: "Escopo Local",
      conceptExplanation: "Cada função tem seu próprio 'mundo' de variáveis. Nomes criados lá dentro não existem fora — isso é proposital, evita que funções interfiram umas nas outras. É como cada sala de servidor ter seu próprio rack isolado.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Isolamento confirmado. A função selou seus dados, impedindo vazamento para o escopo principal.",
      solution: "def processar():\n    segredo = 42\n    print(segredo)\n\nprocessar()\ntry:\n    print(segredo)\nexcept NameError:\n    print('fora_de_escopo')",
    },
    {
      id: "py-func-11",
      worldId: "floresta-funcoes",
      title: "Variável Global Compartilhada",
      description: "Existe uma variável 'contador = 0' definida globalmente. Crie a função 'incrementar' que usa a palavra-chave 'global' para somar 1 em 'contador'. Chame 3 vezes e imprima o valor final.",
      narrative: "Em situações controladas, você precisa que múltiplas funções compartilhem o mesmo contador de eventos. Use a palavra reservada 'global' com cuidado para liberar essa escrita.",
      difficulty: "avancado",
      setupCode: "contador = 0",
      expectedOutput: "3",
      testCode: "assert 'global' in code and output.strip() == '3'",
      starterCode: "contador = 0\n# Use 'global contador' dentro da função para poder modificá-lo\n",
      hints: [
        { text: "Sem 'global', você apenas cria uma nova variável local com o mesmo nome.", cost: 10 },
        { text: "def incrementar():\n    global contador\n    contador += 1", cost: 20 },
      ],
      xpReward: 800,
      concept: "Palavra-chave global",
      conceptExplanation: "Por padrão, atribuir a uma variável dentro de uma função cria uma cópia local. Para realmente modificar a variável de fora, declare 'global nome' no topo da função. Use com moderação — globais excessivas viram dor de cabeça.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Contador global sincronizado. O sistema rastreia eventos centralizados sem ambiguidade.",
      solution: "contador = 0\n\ndef incrementar():\n    global contador\n    contador += 1\n\nincrementar()\nincrementar()\nincrementar()\nprint(contador)",
    },
    {
      id: "py-func-12",
      worldId: "floresta-funcoes",
      title: "Recursão: Cálculo Fatorial",
      description: "Implemente 'fatorial(n)' usando recursão (a função chama a si mesma). Para n=0 ou n=1, retorne 1. Caso contrário, retorne n * fatorial(n-1). Imprima fatorial(5).",
      narrative: "Algumas operações criptográficas se decompõem em problemas menores idênticos. A recursão é a faca elegante para esses casos — a função invoca a si mesma até atingir o caso base.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "120",
      testCode: "assert 'fatorial' in locals() and fatorial(5) == 120 and fatorial(0) == 1 and output.strip() == '120'",
      starterCode: "# Caso base: n <= 1 retorna 1. Senão, n * fatorial(n-1)\n",
      hints: [
        { text: "Toda recursão precisa de um caso base (condição de parada) — senão entra em loop infinito.", cost: 10 },
        { text: "if n <= 1: return 1\nreturn n * fatorial(n - 1)", cost: 20 },
      ],
      xpReward: 850,
      concept: "Recursão",
      conceptExplanation: "Recursão é uma função que se chama. Tem dois ingredientes: o caso base (quando parar) e o passo recursivo (chamada com problema menor). Sem caso base, o Python estoura a pilha (RecursionError).",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Fatorial 120 computado. A função desceu cinco níveis na pilha e retornou intacta.",
      solution: "def fatorial(n):\n    if n <= 1:\n        return 1\n    return n * fatorial(n - 1)\n\nprint(fatorial(5))",
    },
    {
      id: "py-func-13",
      worldId: "floresta-funcoes",
      title: "Recursão: Contagem Regressiva",
      description: "Crie 'contagem(n)' que imprime n, depois chama contagem(n-1), até chegar em 1. Quando n for 0, imprima 'LANCAMENTO'. Chame com contagem(3).",
      narrative: "Um sistema de detonação remota precisa contar regressivamente em loops recursivos sincronizados. Cada passo da pilha imprime o tique do relógio.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "3\n2\n1\nLANCAMENTO",
      testCode: "assert 'contagem' in locals() and output.strip() == '3\\n2\\n1\\nLANCAMENTO'",
      starterCode: "# Use recursão: imprima n, depois chame contagem(n-1)\n",
      hints: [
        { text: "Caso base: if n == 0: print('LANCAMENTO'); return", cost: 10 },
        { text: "Antes da chamada recursiva, imprima o valor atual de n.", cost: 20 },
      ],
      xpReward: 850,
      concept: "Recursão com Efeito Colateral",
      conceptExplanation: "Recursão não precisa retornar valor — pode apenas executar ações (como printar) a cada nível. O importante é a estrutura: caso base + chamada com argumento reduzido.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Contagem regressiva concluída. O lançamento foi executado sem desincronização entre os frames da pilha.",
      solution: "def contagem(n):\n    if n == 0:\n        print('LANCAMENTO')\n        return\n    print(n)\n    contagem(n - 1)\n\ncontagem(3)",
    },
    {
      id: "py-func-14",
      worldId: "floresta-funcoes",
      title: "Função Aninhada (Inner Function)",
      description: "Crie 'externa()' que define dentro de si uma 'interna()' que imprime 'rotina-secundaria'. A 'externa' deve imprimir 'rotina-principal' e então chamar 'interna()'. Chame externa().",
      narrative: "Algumas rotinas críticas precisam de helpers privados que só fazem sentido em um contexto. Encapsule funções dentro de funções para esconder a complexidade do mundo exterior.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "rotina-principal\nrotina-secundaria",
      testCode: "assert 'def interna' in code.replace(' ', '') or 'definterna' in code.replace(' ', '') and output.strip() == 'rotina-principal\\nrotina-secundaria'",
      starterCode: "# Defina 'interna' DENTRO de 'externa' e chame-a no fim\n",
      hints: [
        { text: "A função interna só existe enquanto a externa está executando.", cost: 10 },
        { text: "def externa():\n    def interna():\n        ...\n    interna()", cost: 20 },
      ],
      xpReward: 800,
      concept: "Funções Aninhadas",
      conceptExplanation: "Você pode declarar funções dentro de outras funções. A interna só existe no escopo da externa — ninguém de fora pode chamá-la diretamente. Ótimo para esconder helpers e organizar código.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Sub-rotina privada executada. O helper interno fez seu trabalho sem expor a API ao mundo exterior.",
      solution: "def externa():\n    def interna():\n        print('rotina-secundaria')\n    print('rotina-principal')\n    interna()\n\nexterna()",
    },
    {
      id: "py-func-15",
      worldId: "floresta-funcoes",
      title: "Closure: Gerador de Contador",
      description: "Crie 'criar_contador()' que define uma variável 'n=0' e retorna uma função interna que incrementa 'n' e o retorna. Crie um contador, chame-o 3 vezes seguidas e imprima cada valor (1, 2, 3).",
      narrative: "Um contador persistente precisa lembrar de seu estado entre chamadas, sem usar variáveis globais. Closures aprisionam o estado dentro da função retornada.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "1\n2\n3",
      testCode: "assert 'nonlocal' in code or 'n=' in code.replace(' ', '') and output.strip() == '1\\n2\\n3'",
      starterCode: "# A função interna precisa modificar 'n' da externa — use 'nonlocal'\n",
      hints: [
        { text: "Use 'nonlocal n' dentro da função interna para modificar a variável da função externa.", cost: 10 },
        { text: "def criar_contador():\n    n = 0\n    def incrementar():\n        nonlocal n\n        n += 1\n        return n\n    return incrementar", cost: 20 },
      ],
      xpReward: 900,
      concept: "Closures",
      conceptExplanation: "Uma closure é uma função que 'lembra' as variáveis do escopo onde foi criada, mesmo depois desse escopo terminar. Use 'nonlocal' para modificar variáveis da função externa (diferente de 'global', que vai ao topo).",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Contador persistente ativo. O estado vive dentro do encapsulamento, intocável por outras partes do sistema.",
      solution: "def criar_contador():\n    n = 0\n    def incrementar():\n        nonlocal n\n        n += 1\n        return n\n    return incrementar\n\ncontador = criar_contador()\nprint(contador())\nprint(contador())\nprint(contador())",
    },
    {
      id: "py-func-16",
      worldId: "floresta-funcoes",
      title: "Callback: Função como Argumento",
      description: "Crie 'executar(funcao, valor)' que apenas retorna o resultado de chamar 'funcao(valor)'. Defina uma função 'quadrado(x)' que retorna x*x. Imprima o resultado de executar(quadrado, 8).",
      narrative: "Sistemas modulares aceitam estratégias plugáveis — você passa qual função executar como se fosse um parâmetro normal. Esse é o poder de tratar funções como dados.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "64",
      testCode: "assert 'executar' in locals() and 'quadrado' in locals() and output.strip() == '64'",
      starterCode: "# 'executar' recebe uma função e um valor, e chama funcao(valor)\n",
      hints: [
        { text: "Em Python, funções são objetos. Você pode passá-las como qualquer outro valor.", cost: 10 },
        { text: "def executar(funcao, valor):\n    return funcao(valor)", cost: 20 },
      ],
      xpReward: 900,
      concept: "Funções de Primeira Classe",
      conceptExplanation: "No Python, funções são 'cidadãs de primeira classe': podem ser passadas como argumento, retornadas de outras funções e guardadas em variáveis. Isso é a base de callbacks, decoradores e programação funcional.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Callback executado com sucesso. O motor agora aceita estratégias customizadas em tempo de execução.",
      solution: "def executar(funcao, valor):\n    return funcao(valor)\n\ndef quadrado(x):\n    return x * x\n\nprint(executar(quadrado, 8))",
    },
    {
      id: "py-func-17",
      worldId: "floresta-funcoes",
      title: "Transformação em Lote (map)",
      description: "Dada a lista 'nums = [1, 2, 3, 4]', use map() com uma lambda para criar uma lista com cada elemento elevado ao quadrado. Imprima a lista resultante.",
      narrative: "Para aplicar a mesma transformação em milhares de registros, evite o loop manual. map() processa o lote inteiro de uma vez, sem rabicho.",
      difficulty: "avancado",
      setupCode: "nums = [1, 2, 3, 4]",
      expectedOutput: "[1, 4, 9, 16]",
      testCode: "assert 'map' in code and output.strip() == '[1, 4, 9, 16]'",
      starterCode: "nums = [1, 2, 3, 4]\n# Use list(map(lambda ..., nums))\n",
      hints: [
        { text: "map(funcao, iteravel) aplica a função em cada item. Envolva com list() para ver o resultado.", cost: 10 },
        { text: "print(list(map(lambda x: x ** 2, nums)))", cost: 20 },
      ],
      xpReward: 950,
      concept: "map()",
      conceptExplanation: "map(funcao, lista) aplica a função em cada item da lista, devolvendo um iterador. Em Python 3, você precisa envolver com list() para materializar o resultado. É a forma funcional do 'for + append'.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Transformação em lote concluída. Os 4 valores foram processados sem laço explícito.",
      solution: "nums = [1, 2, 3, 4]\nprint(list(map(lambda x: x ** 2, nums)))",
    },
    {
      id: "py-func-18",
      worldId: "floresta-funcoes",
      title: "Filtragem de Pacotes (filter)",
      description: "Dada a lista 'portas = [22, 80, 443, 3306, 8080]', use filter() com lambda para manter apenas as portas maiores que 100. Imprima a lista resultante.",
      narrative: "Nem todo pacote é interessante. Use filter() para descartar ruído e ficar apenas com as portas que valem a pena escanear.",
      difficulty: "avancado",
      setupCode: "portas = [22, 80, 443, 3306, 8080]",
      expectedOutput: "[443, 3306, 8080]",
      testCode: "assert 'filter' in code and output.strip() == '[443, 3306, 8080]'",
      starterCode: "portas = [22, 80, 443, 3306, 8080]\n# Use list(filter(lambda ..., portas))\n",
      hints: [
        { text: "filter(funcao, iteravel) mantém apenas os itens em que a função retorna True.", cost: 10 },
        { text: "print(list(filter(lambda p: p > 100, portas)))", cost: 20 },
      ],
      xpReward: 950,
      concept: "filter()",
      conceptExplanation: "filter(funcao, lista) é o irmão do map: em vez de transformar, ele decide quem fica. A função passada deve retornar True/False para cada item. Quem volta True sobrevive ao filtro.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Ruído eliminado. Apenas as portas relevantes seguiram para a próxima fase da varredura.",
      solution: "portas = [22, 80, 443, 3306, 8080]\nprint(list(filter(lambda p: p > 100, portas)))",
    },
    {
      id: "py-func-19",
      worldId: "floresta-funcoes",
      title: "Decorador: Log de Chamadas",
      description: "Crie um decorador 'log' que imprime 'antes' antes de chamar a função e 'depois' depois. Decore uma função 'tarefa()' que imprime 'executando' usando @log. Chame tarefa(). Saída esperada: antes / executando / depois.",
      narrative: "Para auditoria, toda função crítica precisa ser instrumentada — registrar quando iniciou e quando terminou. Decoradores envolvem a função original sem alterar seu corpo.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "antes\nexecutando\ndepois",
      testCode: "assert '@log' in code and output.strip() == 'antes\\nexecutando\\ndepois'",
      starterCode: "# Defina o decorador 'log' (recebe func, retorna wrapper) e use @log na 'tarefa'\n",
      hints: [
        { text: "Um decorador é uma função que recebe outra função e retorna uma nova versão dela.", cost: 10 },
        { text: "def log(func):\n    def wrapper():\n        print('antes')\n        func()\n        print('depois')\n    return wrapper", cost: 20 },
        { text: "@log\ndef tarefa():\n    print('executando')\n\ntarefa()", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Decoradores (@)",
      conceptExplanation: "Um decorador é uma função que recebe outra função e devolve uma versão 'envolvida' dela. A sintaxe @nome_do_decorador acima de uma função é açúcar sintático para: funcao = decorador(funcao). Muito usado para logging, autenticação e cache.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Instrumentação ativa. Toda chamada de função agora deixa rastro nos logs sem poluir o código original.",
      solution: "def log(func):\n    def wrapper():\n        print('antes')\n        func()\n        print('depois')\n    return wrapper\n\n@log\ndef tarefa():\n    print('executando')\n\ntarefa()",
    },
    {
      id: "py-func-20",
      worldId: "floresta-funcoes",
      title: "Anotações de Tipo (Type Hints)",
      description: "Crie uma função 'somar(a: int, b: int) -> int' que retorna a soma de a e b. Imprima somar(7, 3). O código deve usar anotações de tipo nos parâmetros e no retorno.",
      narrative: "Código profissional declara o que espera receber e o que vai devolver. Type hints não mudam o comportamento, mas dão clareza para colegas de equipe e ferramentas de análise estática.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "10",
      testCode: "assert '->' in code and ': int' in code and output.strip() == '10'",
      starterCode: "# Use a: int, b: int e -> int na assinatura\n",
      hints: [
        { text: "Sintaxe: def nome(parametro: tipo) -> tipo_retorno:", cost: 10 },
        { text: "def somar(a: int, b: int) -> int:\n    return a + b", cost: 20 },
      ],
      xpReward: 1000,
      concept: "Type Hints (PEP 484)",
      conceptExplanation: "Type hints anotam quais tipos cada parâmetro e o retorno deveriam ter. O Python não força nada em tempo de execução — mas ferramentas como mypy e o próprio editor usam isso para detectar bugs antes de rodar o código. Padrão em projetos sérios.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Assinatura formalmente declarada. O linter aprovou a função para integração no repositório principal.",
      solution: "def somar(a: int, b: int) -> int:\n    return a + b\n\nprint(somar(7, 3))",
    },
  ],
};
