import { World } from "../types";

export const FLORESTA_FUNCOES_WORLD: World = {
  id: "floresta-funcoes",
  title: "Repositório de Funções",
  subtitle: "Modularização do Sistema",
  icon: "package",
  color: "#8B5CF6",
  bgImage: "/assets/images/worlds/function_repo.png",
  lore: "No Repositório Central, os Hackers aprendem a otimizar scripts encapsulando rotinas em blocos reutilizáveis chamados Funções.",
  unlockRequirement: 8000,
  challenges: [
    {
      id: "py-func-01",
      worldId: "floresta-funcoes",
      title: "Sub-rotina de Handshake",
      description: "Defina uma função chamada saudar que recebe um nome e imprime 'Ola, [nome]!'. Chame a sub-rotina passando o nome 'Admin'.",
      narrative: "O servidor principal precisa responder aos pacotes de entrada de forma dinâmica. Encapsule o comando de boas-vindas em uma função reutilizável.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Ola, Admin!",
      testCode: "assert 'saudar' in locals() and callable(saudar) and output.strip() == 'Ola, Admin!'",
      starterCode: "# Defina a sub-rotina saudar e invoque-a\n",
      hints: [
        { text: "Funções começam com def nome(parâmetro):", cost: 10 },
        { text: "Use uma f-string para formatar a string de saída: f'Ola, {nome}!'", cost: 20 },
        { text: "def saudar(nome):\n    print(f'Ola, {nome}!')\n\nsaudar('Admin')", cost: 30 },
      ],
      xpReward: 400,
      concept: "Criação de Funções (def)",
      conceptExplanation: "Uma função (criada com a palavra 'def') é como ensinar um truque novo para o computador. Em vez de escrever o mesmo código várias vezes, você agrupa ele e dá um nome.\n\nPor exemplo:\ndef bom_dia():\n    print('Bom dia, Operador!')\n\nAgora, sempre que você escrever apenas bom_dia() no código, o computador vai executar aquela mensagem!",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Módulo gravado com sucesso. O sistema agora pode escalar chamadas para a sub-rotina automaticamente.",
    },
    {
      id: "py-func-02",
      worldId: "floresta-funcoes",
      title: "Cálculo de Potência de Sinal",
      description: "Crie uma função 'sinal' que recebe 'base' e 'ganho' e printe a multiplicação dos dois. Chame com 10 e 5.",
      narrative: "Para alcançar servidores em outros setores, você deve calcular a potência necessária combinando o sinal base com o multiplicador de ganho.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "50",
      testCode: "assert 'sinal' in locals() and sinal(10, 5) == None and output.strip() == '50'",
      starterCode: "# Crie a função sinal e chame com 10 e 5\n",
      hints: [
        { text: "Funções podem receber vários parâmetros separados por vírgula.", cost: 10 },
        { text: "def sinal(base, ganho):", cost: 20 },
        { text: "sinal(10, 5)", cost: 30 },
      ],
      xpReward: 450,
      concept: "Parâmetros Múltiplos",
      conceptExplanation: "Funções podem receber várias informações de uma vez. Basta listar os nomes dos parâmetros dentro dos parênteses, separados por vírgula. Isso permite criar ferramentas muito mais flexíveis.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Potência calculada. O sinal agora é forte o suficiente para atravessar o firewall do próximo setor.",
    },
    {
      id: "py-func-03",
      worldId: "floresta-funcoes",
      title: "Gerador de Chave Mestra",
      description: "Crie uma função 'gerar_chave' que recebe 'cod' e RETORNA 'cod' multiplicado por 100. Printe o resultado da chamada com 7.",
      narrative: "O sistema exige uma chave gerada por algoritmo. A função deve processar o código semente e devolver o resultado para ser usado no log de acesso.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "700",
      testCode: "assert 'gerar_chave' in locals() and gerar_chave(7) == 700 and output.strip() == '700'",
      starterCode: "# Use 'return' para devolver o valor da função\n",
      hints: [
        { text: "O comando 'return' devolve um valor para quem chamou a função.", cost: 10 },
        { text: "Exemplo: return x * 100", cost: 20 },
        { text: "resultado = gerar_chave(7)\nprint(resultado)", cost: 30 },
      ],
      xpReward: 500,
      concept: "Retorno de Valores (return)",
      conceptExplanation: "Às vezes você quer que a função 'calcule algo e te devolva o resultado' em vez de apenas mostrar na tela. Para isso usamos o `return`. É como pedir para alguém fazer uma conta e te dizer a resposta.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Chave mestre 700 gerada. O acesso ao Repositório Central foi totalmente desbloqueado.",
    },
    {
      id: "py-func-04",
      worldId: "floresta-funcoes",
      title: "Configuração de Porta Padrão",
      description: "Crie uma função 'conectar' que recebe 'ip' e 'porta'. A 'porta' deve ter o valor padrão 80. A função deve imprimir 'Conectando em [ip]:[porta]'. Chame apenas com o IP '192.168.1.1'.",
      narrative: "Para agilizar as conexões, a maioria dos servidores usa a porta 80 por padrão. Crie uma função que assuma esse valor, a menos que o operador especifique o contrário.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "Conectando em 192.168.1.1:80",
      testCode: "assert 'porta=80' in code.replace(' ', '') and output.strip() == 'Conectando em 192.168.1.1:80'",
      starterCode: "# Use parâmetros padrão na sua função\n",
      hints: [
        { text: "Você pode definir um valor padrão no parâmetro: def func(a, b=10):", cost: 10 },
        { text: "print(f'Conectando em {ip}:{porta}')", cost: 20 },
      ],
      xpReward: 550,
      concept: "Parâmetros Padrão (Default Arguments)",
      conceptExplanation: "Parâmetros padrão permitem que você defina um valor 'reserva'. Se quem chamar a função esquecer de enviar aquele dado, o Python usa o valor que você deixou preparado.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Módulo de conexão otimizado. O sistema agora assume a porta web padrão automaticamente.",
    },
    {
      id: "py-func-05",
      worldId: "floresta-funcoes",
      title: "Extração Multi-Layer",
      description: "Crie uma função 'analisar' que recebe um número e retorna esse número e o seu dobro (dois valores). Printe o resultado da chamada com 50.",
      narrative: "Alguns scanners avançados conseguem extrair múltiplos metadados de uma só vez. Sua função deve retornar tanto o valor original quanto o processado.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "(50, 100)",
      testCode: "assert 'return' in code and '50, 100' in output",
      starterCode: "# Retorne múltiplos valores separados por vírgula\n",
      hints: [
        { text: "Para retornar vários valores, use return val1, val2", cost: 10 },
        { text: "Ao printar o resultado, o Python mostrará os valores entre parênteses (uma tupla).", cost: 20 },
      ],
      xpReward: 600,
      concept: "Retorno Múltiplo",
      conceptExplanation: "Diferente de muitas linguagens, o Python permite que uma função devolva várias respostas de uma vez só! Basta separá-las por vírgula no `return`.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Dados extraídos em camadas. A análise de redundância confirmou a integridade do dobro da carga.",
    },
    {
      id: "py-func-06",
      worldId: "floresta-funcoes",
      title: "Documentação de Protocolo",
      description: "Crie uma função qualquer e adicione uma Docstring (comentário de múltiplas linhas logo abaixo do def). A função deve apenas imprimir 'OK'.",
      narrative: "Código profissional precisa ser documentado. As Docstrings permitem que outros hackers (ou você no futuro) entendam o que seu script faz sem precisar ler todo o código.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "OK",
      testCode: "assert '\"\"\"' in code or \"'''\" in code",
      starterCode: "def meu_protocolo():\n    \"\"\"Este script faz tal coisa\"\"\"\n    # Complete aqui\n",
      hints: [
        { text: "Docstrings são strings delimitadas por três aspas: \"\"\" comentário \"\"\"", cost: 10 },
        { text: "Elas devem vir logo na primeira linha dentro da função.", cost: 20 },
      ],
      xpReward: 650,
      concept: "Docstrings (Documentação)",
      conceptExplanation: "Docstrings são como o manual de instruções da sua função, guardado dentro dela. É uma boa prática essencial para quem trabalha em equipe ou em projetos grandes.",
      successNpc: "SysAdmin, Monitoração de Rede",
      successAvatar: "/avatars/galadriel.webp",
      successStory: "Protocolo documentado. Agora seu código segue os padrões internacionais de desenvolvimento Magitech.",
    },
  ],
};
