import { World } from "../types";

export const FORTALEZA_OOP_WORLD: World = {
  id: "fortaleza-oop",
  title: "Fortaleza dos Objetos",
  subtitle: "Programação Orientada a Objetos",
  icon: "box",
  color: "#F59E0B",
  bgImage: "/assets/images/worlds/oop_fortress.png",
  lore: "A Fortaleza dos Objetos protege a estrutura central. Aqui, códigos isolados não sobrevivem; você deve construir Classes e Objetos — entidades autossuficientes com suas próprias memórias e habilidades para invadir a fortaleza.",
  unlockRequirement: 18000,
  challenges: [
    {
      id: "py-oop-01",
      worldId: "fortaleza-oop",
      title: "O Molde da Classe",
      description: "Crie uma classe vazia chamada 'Bot'. Em seguida, crie uma instância dessa classe chamada 'meu_bot' e imprima o tipo (type) de 'meu_bot'.",
      narrative: "Antes de criar um exército de autômatos, precisamos do molde (blueprint). Defina a estrutura básica do Bot para que possamos instanciá-lo na memória.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "<class '__main__.Bot'>",
      testCode: "assert 'class Bot' in code and 'meu_bot' in locals() and 'Bot' in output",
      starterCode: "# Defina a classe Bot (use 'pass' para classe vazia)\n",
      hints: [
        { text: "Use a palavra 'class Bot:' e coloque 'pass' dentro dela para não dar erro.", cost: 10 },
        { text: "Para instanciar, faça: meu_bot = Bot()", cost: 20 },
      ],
      xpReward: 400,
      concept: "Classes e Instâncias",
      conceptExplanation: "Uma Classe é como a 'planta de uma casa' ou uma forma de bolo. Uma Instância (Objeto) é a 'casa construída' ou o bolo pronto. Você escreve a classe uma vez e cria quantos objetos quiser a partir dela.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Molde definido. A matriz começou a gerar as primeiras instâncias.",
      solution: "class Bot:\n    pass\n\nmeu_bot = Bot()\nprint(type(meu_bot))",
    },
    {
      id: "py-oop-02",
      worldId: "fortaleza-oop",
      title: "A Alma do Objeto (__init__)",
      description: "Na classe Bot, adicione o método __init__ que recebe 'nome' e o armazena em 'self.nome'. Crie o bot 'Alpha' e imprima o atributo '.nome' dele.",
      narrative: "Um Bot vazio é inútil. Dê a ele o método construtor para que, assim que nascer, ele grave o seu próprio nome no banco de memória interno.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Alpha",
      testCode: "assert 'def __init__' in code and 'self.nome' in code and output.strip() == 'Alpha'",
      starterCode: "class Bot:\n    # Crie o construtor __init__(self, nome)\n\n",
      hints: [
        { text: "def __init__(self, nome):\n    self.nome = nome", cost: 15 },
        { text: "meu_bot = Bot('Alpha')\nprint(meu_bot.nome)", cost: 25 },
      ],
      xpReward: 500,
      concept: "Construtor e Propriedades",
      conceptExplanation: "O método especial `__init__` é executado automaticamente assim que você cria o objeto. É a função de 'nascimento'. O `self` representa o próprio objeto; é através do `self` que ele guarda informações (atributos) dentro de si mesmo.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Identidade ativada. O Bot Alpha agora tem consciência de sua própria existência.",
      solution: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n\nmeu_bot = Bot('Alpha')\nprint(meu_bot.nome)",
    },
    {
      id: "py-oop-03",
      worldId: "fortaleza-oop",
      title: "Ação Autônoma (Métodos)",
      description: "Na classe Bot, adicione um método chamado 'atacar' (que recebe self) e imprime '[nome] está atacando!'. Crie o bot 'Zeta' e chame o método atacar().",
      narrative: "Agora que o Bot tem um nome, ensine-o a agir. Adicione uma função (método) para que ele execute o comando de ataque usando sua identidade.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Zeta está atacando!",
      testCode: "assert 'def atacar' in code and 'Zeta' in output",
      starterCode: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n    # Crie o método atacar(self)\n\n",
      hints: [
        { text: "def atacar(self):\n    print(f'{self.nome} está atacando!')", cost: 15 },
        { text: "Instancie: b = Bot('Zeta'). Depois chame: b.atacar()", cost: 25 },
      ],
      xpReward: 600,
      concept: "Métodos de Classe",
      conceptExplanation: "Métodos são simplesmente funções que pertencem a uma classe. O detalhe mágico é que o primeiro parâmetro de qualquer método é SEMPRE `self`. Isso permite que o método acesse os atributos (como `self.nome`) daquele objeto específico.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Protocolo ofensivo ativado. O objeto executou a sub-rotina de combate autonomamente.",
      solution: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n    def atacar(self):\n        print(f'{self.nome} está atacando!')\n\nb = Bot('Zeta')\nb.atacar()",
    },
    {
      id: "py-oop-04",
      worldId: "fortaleza-oop",
      title: "Mutação de Estado",
      description: "Adicione o atributo 'energia = 100' no __init__. No método 'tomar_dano', diminua a energia em 20. Crie um Bot, faça-o tomar dano e imprima a energia final.",
      narrative: "A batalha consome recursos. Os objetos precisam manter e alterar seus próprios estados internos de forma isolada, sem depender de variáveis globais.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "80",
      testCode: "assert 'self.energia -= 20' in code or 'self.energia = self.energia - 20' in code and output.strip() == '80'",
      starterCode: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    # def tomar_dano(self):\n\n",
      hints: [
        { text: "Dentro de tomar_dano, faça: self.energia -= 20", cost: 15 },
      ],
      xpReward: 650,
      concept: "Estado (State)",
      conceptExplanation: "Um objeto guarda seu 'Estado' (variáveis internas). Quando um método muda algo usando `self`, apenas aquele objeto é afetado. Se você tivesse 10 bots, cada um teria sua própria energia independente.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Simulação de combate finalizada. O bot registrou o impacto mantendo seu estado persistente.",
      solution: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\nb = Bot()\nb.tomar_dano()\nprint(b.energia)",
    },
    {
      id: "py-oop-05",
      worldId: "fortaleza-oop",
      title: "Evolução do Código (Herança)",
      description: "Crie uma classe 'BotSniper' que HERDA de 'Bot'. Sem escrever o __init__ ou energia de novo, instancie um BotSniper, faça-o tomar dano e imprima a energia.",
      narrative: "Para não reescrever os códigos básicos, use o mecanismo de Herança. O Sniper herda toda a biologia e resistência do Bot comum, mas será uma unidade especializada.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "80",
      testCode: "assert 'class BotSniper(Bot):' in code and output.strip() == '80'",
      starterCode: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\n# Crie a classe BotSniper herdando de Bot\n",
      hints: [
        { text: "class BotSniper(Bot):\n    pass", cost: 20 },
      ],
      xpReward: 800,
      concept: "Herança (Inheritance)",
      conceptExplanation: "A Herança permite criar uma 'Classe Filha' que ganha automaticamente todos os atributos e métodos da 'Classe Mãe'. É o conceito fundamental para reaproveitamento de código em sistemas gigantescos.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Nova unidade gerada! A classe herdou toda a estrutura base sem redundância de código.",
      solution: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\nclass BotSniper(Bot):\n    pass\n\nsniper = BotSniper()\nsniper.tomar_dano()\nprint(sniper.energia)",
    },
  ],
};
