import { World } from "../types";

export const FORTALEZA_OOP_WORLD: World = {
  id: "fortaleza-oop",
  title: "Fortaleza dos Objetos",
  subtitle: "Programação Orientada a Objetos",
  icon: "box",
  color: "#F59E0B",
  bgImage: "/assets/images/worlds/oop_fortress.png",
  lore: "A Fortaleza dos Objetos protege a estrutura central. Aqui, códigos isolados não sobrevivem; você deve construir Classes e Objetos — entidades autossuficientes com suas próprias memórias e habilidades para invadir a fortaleza.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-oop-01",
      worldId: "fortaleza-oop",
      title: "O Molde da Classe",
      description: "Crie uma classe vazia chamada 'Bot'. Em seguida, crie uma instância dessa classe chamada 'meu_bot' e imprima o tipo (type) de 'meu_bot'.",
      narrative: "Antes de criar um exército de autômatos, precisamos do molde (blueprint). Defina a estrutura básica do Bot para que possamos instanciá-lo na memória.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "<class '__main__.Bot'>",
      testCode: "assert 'class Bot' in code and 'meu_bot' in locals() and 'Bot' in output",
      starterCode: "# Defina a classe Bot (use 'pass' para classe vazia)\n",
      hints: [
        { text: "Use a palavra 'class Bot:' e coloque 'pass' dentro dela para não dar erro.", cost: 10 },
        { text: "Para instanciar, faça: meu_bot = Bot()", cost: 20 },
      ],
      xpReward: 400,
      concept: "Classes e Instâncias",
      conceptExplanation: "Uma Classe é como a 'planta de uma casa' ou uma forma de bolo. Uma Instância (Objeto) é a 'casa construída' ou o bolo pronto. Você escreve a classe uma vez e cria quantos objetos quiser a partir dela.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Molde definido. A matriz começou a gerar as primeiras instâncias.",
      solution: "class Bot:\n    pass\n\nmeu_bot = Bot()\nprint(type(meu_bot))",
    },
    {
      id: "py-oop-02",
      worldId: "fortaleza-oop",
      title: "A Alma do Objeto (__init__)",
      description: "Na classe Bot, adicione o método __init__ que recebe 'nome' e o armazena em 'self.nome'. Crie o bot 'Alpha' e imprima o atributo '.nome' dele.",
      narrative: "Um Bot vazio é inútil. Dê a ele o método construtor para que, assim que nascer, ele grave o seu próprio nome no banco de memória interno.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Alpha",
      testCode: "assert 'def __init__' in code and 'self.nome' in code and output.strip() == 'Alpha'",
      starterCode: "class Bot:\n    # Crie o construtor __init__(self, nome)\n\n",
      hints: [
        { text: "def __init__(self, nome):\n    self.nome = nome", cost: 15 },
        { text: "meu_bot = Bot('Alpha')\nprint(meu_bot.nome)", cost: 25 },
      ],
      xpReward: 500,
      concept: "Construtor e Propriedades",
      conceptExplanation: "O método especial `__init__` é executado automaticamente assim que você cria o objeto. É a função de 'nascimento'. O `self` representa o próprio objeto; é através do `self` que ele guarda informações (atributos) dentro de si mesmo.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Identidade ativada. O Bot Alpha agora tem consciência de sua própria existência.",
      solution: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n\nmeu_bot = Bot('Alpha')\nprint(meu_bot.nome)",
    },
    {
      id: "py-oop-03",
      worldId: "fortaleza-oop",
      title: "Ação Autônoma (Métodos)",
      description: "Na classe Bot, adicione um método chamado 'atacar' (que recebe self) e imprime '[nome] está atacando!'. Crie o bot 'Zeta' e chame o método atacar().",
      narrative: "Agora que o Bot tem um nome, ensine-o a agir. Adicione uma função (método) para que ele execute o comando de ataque usando sua identidade.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Zeta está atacando!",
      testCode: "assert 'def atacar' in code and 'Zeta' in output",
      starterCode: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n    # Crie o método atacar(self)\n\n",
      hints: [
        { text: "def atacar(self):\n    print(f'{self.nome} está atacando!')", cost: 15 },
        { text: "Instancie: b = Bot('Zeta'). Depois chame: b.atacar()", cost: 25 },
      ],
      xpReward: 600,
      concept: "Métodos de Classe",
      conceptExplanation: "Métodos são simplesmente funções que pertencem a uma classe. O detalhe mágico é que o primeiro parâmetro de qualquer método é SEMPRE `self`. Isso permite que o método acesse os atributos (como `self.nome`) daquele objeto específico.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Protocolo ofensivo ativado. O objeto executou a sub-rotina de combate autonomamente.",
      solution: "class Bot:\n    def __init__(self, nome):\n        self.nome = nome\n    def atacar(self):\n        print(f'{self.nome} está atacando!')\n\nb = Bot('Zeta')\nb.atacar()",
    },
    {
      id: "py-oop-04",
      worldId: "fortaleza-oop",
      title: "Mutação de Estado",
      description: "Adicione o atributo 'energia = 100' no __init__. No método 'tomar_dano', diminua a energia em 20. Crie um Bot, faça-o tomar dano e imprima a energia final.",
      narrative: "A batalha consome recursos. Os objetos precisam manter e alterar seus próprios estados internos de forma isolada, sem depender de variáveis globais.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "80",
      testCode: "assert 'self.energia -= 20' in code or 'self.energia = self.energia - 20' in code and output.strip() == '80'",
      starterCode: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    # def tomar_dano(self):\n\n",
      hints: [
        { text: "Dentro de tomar_dano, faça: self.energia -= 20", cost: 15 },
      ],
      xpReward: 650,
      concept: "Estado (State)",
      conceptExplanation: "Um objeto guarda seu 'Estado' (variáveis internas). Quando um método muda algo usando `self`, apenas aquele objeto é afetado. Se você tivesse 10 bots, cada um teria sua própria energia independente.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Simulação de combate finalizada. O bot registrou o impacto mantendo seu estado persistente.",
      solution: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\nb = Bot()\nb.tomar_dano()\nprint(b.energia)",
    },
    {
      id: "py-oop-05",
      worldId: "fortaleza-oop",
      title: "Evolução do Código (Herança)",
      description: "Crie uma classe 'BotSniper' que HERDA de 'Bot'. Sem escrever o __init__ ou energia de novo, instancie um BotSniper, faça-o tomar dano e imprima a energia.",
      narrative: "Para não reescrever os códigos básicos, use o mecanismo de Herança. O Sniper herda toda a biologia e resistência do Bot comum, mas será uma unidade especializada.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "80",
      testCode: "assert 'class BotSniper(Bot):' in code and output.strip() == '80'",
      starterCode: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\n# Crie a classe BotSniper herdando de Bot\n",
      hints: [
        { text: "class BotSniper(Bot):\n    pass", cost: 20 },
      ],
      xpReward: 800,
      concept: "Herança (Inheritance)",
      conceptExplanation: "A Herança permite criar uma 'Classe Filha' que ganha automaticamente todos os atributos e métodos da 'Classe Mãe'. É o conceito fundamental para reaproveitamento de código em sistemas gigantescos.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Nova unidade gerada! A classe herdou toda a estrutura base sem redundância de código.",
      solution: "class Bot:\n    def __init__(self):\n        self.energia = 100\n    def tomar_dano(self):\n        self.energia -= 20\n\nclass BotSniper(Bot):\n    pass\n\nsniper = BotSniper()\nsniper.tomar_dano()\nprint(sniper.energia)",
    },
    {
      id: "py-oop-06",
      worldId: "fortaleza-oop",
      title: "Múltiplas Instâncias Independentes",
      description: "Crie a classe 'Drone' com __init__ recebendo 'id'. Instancie 'd1 = Drone(1)' e 'd2 = Drone(2)'. Imprima d1.id e d2.id (cada um em uma linha).",
      narrative: "Cada drone precisa carregar seu próprio identificador único. Confirme que as instâncias não compartilham memória entre si.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "1\n2",
      testCode: "assert 'class Drone' in code and 'self.id' in code and output.strip() == '1\\n2'",
      starterCode: "# Defina Drone com __init__(self, id), crie d1 e d2\n",
      hints: [
        { text: "Cada chamada a Drone(...) cria um objeto NOVO com sua própria memória.", cost: 10 },
        { text: "class Drone:\n    def __init__(self, id):\n        self.id = id", cost: 20 },
      ],
      xpReward: 700,
      concept: "Identidade de Instâncias",
      conceptExplanation: "Cada vez que você chama a classe (Drone()), o Python cria um objeto totalmente novo na memória. Mudar o atributo de um não afeta o outro — eles têm 'consciência' separada, embora venham do mesmo molde.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Esquadrão registrado. Cada drone opera com seu próprio identificador isolado.",
      solution: "class Drone:\n    def __init__(self, id):\n        self.id = id\n\nd1 = Drone(1)\nd2 = Drone(2)\nprint(d1.id)\nprint(d2.id)",
    },
    {
      id: "py-oop-07",
      worldId: "fortaleza-oop",
      title: "Atributo de Classe (Compartilhado)",
      description: "Crie a classe 'Soldado' com um atributo de CLASSE 'faccao = \"Resistencia\"' (definido fora do __init__). Instancie um soldado e imprima 'Soldado.faccao'.",
      narrative: "Toda unidade dessa divisão pertence à mesma facção. Defina esse valor uma única vez, compartilhado por todas as instâncias.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Resistencia",
      testCode: "assert 'class Soldado' in code and 'faccao' in code and output.strip() == 'Resistencia'",
      starterCode: "# Atributo de classe fica direto no corpo da classe, fora de __init__\n",
      hints: [
        { text: "class Soldado:\n    faccao = 'Resistencia'", cost: 15 },
        { text: "print(Soldado.faccao) — acesso direto pela classe.", cost: 20 },
      ],
      xpReward: 750,
      concept: "Atributos de Classe vs Instância",
      conceptExplanation: "Atributos definidos no corpo da classe (não em __init__) são COMPARTILHADOS por todas as instâncias. Já os atributos em 'self.xxx' são únicos por instância. Útil para constantes ou contadores globais da classe.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Lealdade configurada. Toda a divisão responde à mesma facção sem duplicação de dados.",
      solution: "class Soldado:\n    faccao = 'Resistencia'\n\ns = Soldado()\nprint(Soldado.faccao)",
    },
    {
      id: "py-oop-08",
      worldId: "fortaleza-oop",
      title: "Representação Textual (__str__)",
      description: "Crie a classe 'Agente' com __init__(nome) e o método especial __str__ que retorna f'Agente:{self.nome}'. Instancie 'Smith' e simplesmente faça print(a).",
      narrative: "Quando o sistema loga um objeto, ele precisa saber como descrevê-lo em texto. Implemente o método de auto-descrição para uma identificação clara nos logs.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Agente:Smith",
      testCode: "assert 'def __str__' in code and output.strip() == 'Agente:Smith'",
      starterCode: "# Implemente __str__ retornando a string desejada\n",
      hints: [
        { text: "__str__ deve RETORNAR (return) uma string, não fazer print.", cost: 15 },
        { text: "def __str__(self):\n    return f'Agente:{self.nome}'", cost: 25 },
      ],
      xpReward: 800,
      concept: "Método __str__",
      conceptExplanation: "O __str__ é chamado automaticamente quando você faz print(objeto) ou str(objeto). Sem ele, o Python mostra algo feio como '<__main__.Agente object at 0x7f...>'. Definir __str__ é boa prática em qualquer classe séria.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Auto-descrição habilitada. Os logs agora exibem identidade legível, não endereços de memória.",
      solution: "class Agente:\n    def __init__(self, nome):\n        self.nome = nome\n    def __str__(self):\n        return f'Agente:{self.nome}'\n\na = Agente('Smith')\nprint(a)",
    },
    {
      id: "py-oop-09",
      worldId: "fortaleza-oop",
      title: "Método com Parâmetros",
      description: "Crie 'Conta' com saldo inicial 0. Adicione método 'depositar(valor)' que soma valor ao saldo. Instancie, deposite 250, depois 150, e imprima o saldo final.",
      narrative: "Uma conta bancária precisa receber instruções dinâmicas. Métodos podem aceitar parâmetros como qualquer função, além do obrigatório self.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "400",
      testCode: "assert 'def depositar' in code and 'self.saldo' in code and output.strip() == '400'",
      starterCode: "class Conta:\n    def __init__(self):\n        self.saldo = 0\n    # def depositar(self, valor):\n\n",
      hints: [
        { text: "def depositar(self, valor):\n    self.saldo += valor", cost: 15 },
      ],
      xpReward: 800,
      concept: "Métodos com Argumentos",
      conceptExplanation: "Além do self, métodos podem ter quantos parâmetros você quiser. O self é sempre o primeiro e é preenchido automaticamente. Os demais você passa normalmente: conta.depositar(250).",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Transações registradas. O cofre processou os depósitos sequenciais sem perda de estado.",
      solution: "class Conta:\n    def __init__(self):\n        self.saldo = 0\n    def depositar(self, valor):\n        self.saldo += valor\n\nc = Conta()\nc.depositar(250)\nc.depositar(150)\nprint(c.saldo)",
    },
    {
      id: "py-oop-10",
      worldId: "fortaleza-oop",
      title: "Encapsulamento (Convenção _)",
      description: "Crie 'Cofre' com __init__ que define 'self._senha = \"1234\"' (sublinhado indica privado). Adicione método 'verificar(tentativa)' que retorna True se igual, False caso contrário. Teste com 'verificar(\"1234\")' e imprima.",
      narrative: "Atributos sensíveis devem ser marcados como privados por convenção. O sublinhado é o sinal universal Python: 'NÃO mexa, use o método público'.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "True",
      testCode: "assert 'self._senha' in code and 'def verificar' in code and output.strip() == 'True'",
      starterCode: "# Use self._senha (com sublinhado) e o método verificar\n",
      hints: [
        { text: "Em Python não existe 'private' real — usamos o prefixo _ como convenção.", cost: 15 },
        { text: "def verificar(self, tentativa):\n    return tentativa == self._senha", cost: 25 },
      ],
      xpReward: 850,
      concept: "Encapsulamento",
      conceptExplanation: "Python não tem 'private' como Java/C++, mas a comunidade adotou o sublinhado _ como aviso: 'esse atributo é interno, não mexa direto'. Acesso externo deve passar por métodos públicos — isso protege o estado do objeto.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cofre selado. A senha só é acessível através do canal autorizado.",
      solution: "class Cofre:\n    def __init__(self):\n        self._senha = '1234'\n    def verificar(self, tentativa):\n        return tentativa == self._senha\n\nc = Cofre()\nprint(c.verificar('1234'))",
    },
    {
      id: "py-oop-11",
      worldId: "fortaleza-oop",
      title: "Property (Getter Mágico)",
      description: "Crie 'Reator' com __init__ que recebe 'temp_celsius'. Adicione um @property chamado 'fahrenheit' que retorna 'self.temp_celsius * 9/5 + 32'. Instancie com 100 e imprima 'reator.fahrenheit' (sem parênteses!).",
      narrative: "Acessar um valor derivado como se fosse um atributo, sem expor a lógica de cálculo, é o sinal de uma API bem desenhada.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "212.0",
      testCode: "assert '@property' in code and 'fahrenheit' in code and output.strip() == '212.0'",
      starterCode: "# Use @property acima do método 'fahrenheit'\n",
      hints: [
        { text: "@property transforma um método em um atributo virtual — acessado sem ().", cost: 15 },
        { text: "@property\ndef fahrenheit(self):\n    return self.temp_celsius * 9/5 + 32", cost: 25 },
      ],
      xpReward: 900,
      concept: "@property",
      conceptExplanation: "@property transforma um método em um 'atributo calculado'. O usuário acessa sem parênteses (objeto.atributo) mas por trás roda código. É a forma pythônica de criar getters elegantes e até atributos somente leitura.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Conversão térmica encapsulada. A API ficou limpa, sem expor a fórmula de cálculo.",
      solution: "class Reator:\n    def __init__(self, temp_celsius):\n        self.temp_celsius = temp_celsius\n    @property\n    def fahrenheit(self):\n        return self.temp_celsius * 9/5 + 32\n\nr = Reator(100)\nprint(r.fahrenheit)",
    },
    {
      id: "py-oop-12",
      worldId: "fortaleza-oop",
      title: "Sobrescrita de Método (Override)",
      description: "Dada a classe 'Veiculo' com método 'mover' que imprime 'rodando', crie 'Aviao(Veiculo)' que SOBRESCREVE 'mover' para imprimir 'voando'. Instancie um Aviao e chame .mover().",
      narrative: "Nem toda unidade da fortaleza se move da mesma forma. A classe filha deve poder substituir o comportamento herdado quando necessário.",
      difficulty: "avancado",
      setupCode: "class Veiculo:\n    def mover(self):\n        print('rodando')",
      expectedOutput: "voando",
      testCode: "assert 'class Aviao(Veiculo)' in code and 'def mover' in code and output.strip() == 'voando'",
      starterCode: "class Veiculo:\n    def mover(self):\n        print('rodando')\n\n# Defina Aviao(Veiculo) e sobrescreva 'mover'\n",
      hints: [
        { text: "Basta declarar um método com o mesmo nome na classe filha — o Python usa o mais específico.", cost: 15 },
        { text: "class Aviao(Veiculo):\n    def mover(self):\n        print('voando')", cost: 25 },
      ],
      xpReward: 950,
      concept: "Override (Sobrescrita)",
      conceptExplanation: "Quando uma classe filha define um método com o mesmo nome da classe pai, ela 'sobrescreve' o comportamento original. O Python procura primeiro na classe filha; só sobe na hierarquia se não encontrar.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Subclasse especializada. A unidade aérea agora opera com sua própria mecânica de movimento.",
      solution: "class Veiculo:\n    def mover(self):\n        print('rodando')\n\nclass Aviao(Veiculo):\n    def mover(self):\n        print('voando')\n\na = Aviao()\na.mover()",
    },
    {
      id: "py-oop-13",
      worldId: "fortaleza-oop",
      title: "Chamada à Classe Pai (super)",
      description: "Dada 'Pessoa' com __init__(nome), crie 'Funcionario(Pessoa)' com __init__(nome, salario). Use super().__init__(nome) para reaproveitar o construtor. Instancie 'Funcionario(\"Ana\", 5000)' e imprima nome e salario, um por linha.",
      narrative: "A subclasse não precisa reinventar a roda — chame a inicialização da classe mãe e adicione apenas o que é específico.",
      difficulty: "avancado",
      setupCode: "class Pessoa:\n    def __init__(self, nome):\n        self.nome = nome",
      expectedOutput: "Ana\n5000",
      testCode: "assert 'super().__init__' in code and 'Ana' in output and '5000' in output",
      starterCode: "class Pessoa:\n    def __init__(self, nome):\n        self.nome = nome\n\n# Crie Funcionario(Pessoa) usando super()\n",
      hints: [
        { text: "Dentro do __init__ da filha, faça: super().__init__(nome)", cost: 15 },
        { text: "class Funcionario(Pessoa):\n    def __init__(self, nome, salario):\n        super().__init__(nome)\n        self.salario = salario", cost: 25 },
      ],
      xpReward: 900,
      concept: "super()",
      conceptExplanation: "super() é a referência à classe mãe. Usar super().__init__(...) no construtor da filha permite reaproveitar a inicialização sem copiar código. Essencial para hierarquias profundas e herança múltipla.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cadeia de inicialização integrada. A subclasse honrou os contratos da classe ancestral.",
      solution: "class Pessoa:\n    def __init__(self, nome):\n        self.nome = nome\n\nclass Funcionario(Pessoa):\n    def __init__(self, nome, salario):\n        super().__init__(nome)\n        self.salario = salario\n\nf = Funcionario('Ana', 5000)\nprint(f.nome)\nprint(f.salario)",
    },
    {
      id: "py-oop-14",
      worldId: "fortaleza-oop",
      title: "Polimorfismo Tático",
      description: "Crie 'Gato' e 'Cachorro', cada um com método 'falar' retornando 'miau' e 'au', respectivamente. Em uma lista 'animais = [Gato(), Cachorro()]', itere e imprima a fala de cada um.",
      narrative: "O Operador não precisa saber o tipo exato da unidade — basta chamar o método padrão e cada uma responde à sua maneira. Esse é o coração do polimorfismo.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "miau\nau",
      testCode: "assert 'class Gato' in code and 'class Cachorro' in code and output.strip() == 'miau\\nau'",
      starterCode: "# Defina Gato e Cachorro, cada um com método falar()\n# Itere a lista chamando .falar()\n",
      hints: [
        { text: "Não precisa de herança — basta que ambos tenham o método com o mesmo nome.", cost: 15 },
        { text: "for a in animais:\n    print(a.falar())", cost: 25 },
      ],
      xpReward: 1000,
      concept: "Polimorfismo",
      conceptExplanation: "Polimorfismo (muitas formas) é a capacidade de tratar objetos diferentes pela mesma interface. Se todos tiverem 'falar()', você não precisa saber o tipo — só chamar. Esse princípio dispensa cadeias gigantes de if/elif por tipo.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Resposta unificada. Tipos distintos atenderam à mesma chamada com comportamentos próprios.",
      solution: "class Gato:\n    def falar(self):\n        return 'miau'\n\nclass Cachorro:\n    def falar(self):\n        return 'au'\n\nanimais = [Gato(), Cachorro()]\nfor a in animais:\n    print(a.falar())",
    },
    {
      id: "py-oop-15",
      worldId: "fortaleza-oop",
      title: "Verificação de Tipo (isinstance)",
      description: "Dado 'obj = \"Texto\"', use isinstance(obj, str) e imprima True/False. Em seguida, use isinstance(obj, int) e imprima.",
      narrative: "Antes de executar uma rotina específica, confirme o tipo real do objeto recebido. isinstance é mais flexível que type() — aceita herança.",
      difficulty: "intermediario",
      setupCode: "obj = 'Texto'",
      expectedOutput: "True\nFalse",
      testCode: "assert 'isinstance' in code and output.strip() == 'True\\nFalse'",
      starterCode: "obj = 'Texto'\n# Use isinstance(obj, tipo) duas vezes\n",
      hints: [
        { text: "isinstance(valor, tipo) retorna True se o valor é daquele tipo (ou herda dele).", cost: 10 },
        { text: "print(isinstance(obj, str))\nprint(isinstance(obj, int))", cost: 20 },
      ],
      xpReward: 850,
      concept: "isinstance()",
      conceptExplanation: "isinstance(objeto, classe) checa se um objeto é instância de uma classe (ou de qualquer subclasse dela). É preferível a 'type(x) == X' porque respeita herança — uma das pedras angulares do design POO em Python.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Validação de tipo aprovada. O sistema rejeita inputs incompatíveis antes da execução.",
      solution: "obj = 'Texto'\nprint(isinstance(obj, str))\nprint(isinstance(obj, int))",
    },
    {
      id: "py-oop-16",
      worldId: "fortaleza-oop",
      title: "Método de Classe (@classmethod)",
      description: "Crie 'Contador' com atributo de classe 'total = 0'. Adicione um @classmethod 'incrementar(cls)' que faz 'cls.total += 1'. Chame Contador.incrementar() três vezes e imprima Contador.total.",
      narrative: "Algumas operações afetam a classe como um todo, não uma instância específica. Use classmethod para essas ações administrativas.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "3",
      testCode: "assert '@classmethod' in code and 'cls.total' in code and output.strip() == '3'",
      starterCode: "# Use @classmethod com primeiro parâmetro 'cls' (não 'self')\n",
      hints: [
        { text: "@classmethod\ndef incrementar(cls):\n    cls.total += 1", cost: 15 },
        { text: "Chame direto pela classe: Contador.incrementar()", cost: 20 },
      ],
      xpReward: 1000,
      concept: "@classmethod",
      conceptExplanation: "@classmethod recebe a CLASSE (cls) em vez de uma instância (self). Útil para operações que afetam estado compartilhado, factory methods (criar instâncias de jeitos alternativos) e contadores globais.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Contador centralizado ativo. As operações administrativas operam no nível da classe, não da instância.",
      solution: "class Contador:\n    total = 0\n    @classmethod\n    def incrementar(cls):\n        cls.total += 1\n\nContador.incrementar()\nContador.incrementar()\nContador.incrementar()\nprint(Contador.total)",
    },
    {
      id: "py-oop-17",
      worldId: "fortaleza-oop",
      title: "Método Estático (@staticmethod)",
      description: "Crie 'Calculadora' com um @staticmethod 'somar(a, b)' que retorna a + b (sem self, sem cls). Chame Calculadora.somar(15, 27) e imprima o resultado.",
      narrative: "Algumas utilidades não precisam de objeto nem da classe — só fazem sentido logicamente agrupadas. Use staticmethod para funções utilitárias dentro da classe.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "42",
      testCode: "assert '@staticmethod' in code and output.strip() == '42'",
      starterCode: "# @staticmethod não recebe self nem cls\n",
      hints: [
        { text: "@staticmethod\ndef somar(a, b):\n    return a + b", cost: 15 },
        { text: "Chame: Calculadora.somar(15, 27) — sem instanciar.", cost: 20 },
      ],
      xpReward: 1050,
      concept: "@staticmethod",
      conceptExplanation: "@staticmethod é uma função 'comum' que mora dentro da classe por questão de organização. Não recebe self nem cls. Útil para utilitários relacionados ao domínio da classe mas que não dependem de estado.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Utilitário registrado. A função vive dentro do namespace da classe sem custo de instância.",
      solution: "class Calculadora:\n    @staticmethod\n    def somar(a, b):\n        return a + b\n\nprint(Calculadora.somar(15, 27))",
    },
    {
      id: "py-oop-18",
      worldId: "fortaleza-oop",
      title: "Herança Múltipla",
      description: "Crie 'Voador' com método 'voar' (imprime 'voa'). Crie 'Nadador' com método 'nadar' (imprime 'nada'). Crie 'Pato(Voador, Nadador)' que herda dos dois. Instancie um Pato e chame .voar() e .nadar().",
      narrative: "Algumas unidades precisam combinar habilidades de múltiplas linhagens. O Python permite herdar de várias classes simultaneamente — com critério.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "voa\nnada",
      testCode: "assert 'class Pato(Voador, Nadador)' in code and output.strip() == 'voa\\nnada'",
      starterCode: "# Defina Voador, Nadador e Pato(Voador, Nadador)\n",
      hints: [
        { text: "Sintaxe: class Pato(Voador, Nadador):", cost: 15 },
        { text: "Você pode colocar 'pass' no corpo do Pato — ele herda tudo automaticamente.", cost: 25 },
      ],
      xpReward: 1100,
      concept: "Herança Múltipla",
      conceptExplanation: "Diferente de Java, o Python permite herdar de várias classes ao mesmo tempo. A ordem importa: o Python segue o MRO (Method Resolution Order) — esquerda para a direita. Use com cuidado para evitar conflitos de nome.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Linhagens combinadas. A unidade absorveu capacidades de ambos os ancestrais sem conflito.",
      solution: "class Voador:\n    def voar(self):\n        print('voa')\n\nclass Nadador:\n    def nadar(self):\n        print('nada')\n\nclass Pato(Voador, Nadador):\n    pass\n\np = Pato()\np.voar()\np.nadar()",
    },
    {
      id: "py-oop-19",
      worldId: "fortaleza-oop",
      title: "Composição (Objeto Dentro de Objeto)",
      description: "Crie 'Motor' com __init__(potencia). Crie 'Carro' com __init__(nome) que ARMAZENA um Motor(200) em self.motor. Instancie 'Carro(\"Mustang\")' e imprima 'c.motor.potencia'.",
      narrative: "Em vez de herdar, às vezes você simplesmente CONTÉM outro objeto. Composição costuma ser mais flexível e desacoplada que herança.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "200",
      testCode: "assert 'class Motor' in code and 'self.motor' in code and output.strip() == '200'",
      starterCode: "# Em Carro.__init__, faça self.motor = Motor(200)\n",
      hints: [
        { text: "Composição = HAS-A. Herança = IS-A. Aqui o Carro TEM um motor, não É um motor.", cost: 15 },
        { text: "class Carro:\n    def __init__(self, nome):\n        self.nome = nome\n        self.motor = Motor(200)", cost: 25 },
      ],
      xpReward: 1050,
      concept: "Composição",
      conceptExplanation: "Composição é guardar instâncias de outras classes como atributos. Princípio importante: 'prefira composição à herança'. Composição é mais flexível — você pode trocar o componente sem reescrever a árvore de classes.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Subsistema acoplado. O carro delegou funcionalidades ao motor sem amarrar identidade.",
      solution: "class Motor:\n    def __init__(self, potencia):\n        self.potencia = potencia\n\nclass Carro:\n    def __init__(self, nome):\n        self.nome = nome\n        self.motor = Motor(200)\n\nc = Carro('Mustang')\nprint(c.motor.potencia)",
    },
    {
      id: "py-oop-20",
      worldId: "fortaleza-oop",
      title: "Igualdade Customizada (__eq__)",
      description: "Crie 'Chave' com __init__(codigo). Implemente __eq__(self, outro) retornando True se self.codigo == outro.codigo. Crie c1=Chave('AB') e c2=Chave('AB'), imprima 'c1 == c2'.",
      narrative: "Por padrão, dois objetos só são iguais se forem o MESMO objeto na memória. Para comparar pelo conteúdo, defina como a igualdade deve funcionar.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "True",
      testCode: "assert 'def __eq__' in code and output.strip() == 'True'",
      starterCode: "# Implemente __eq__ comparando self.codigo com outro.codigo\n",
      hints: [
        { text: "def __eq__(self, outro):\n    return self.codigo == outro.codigo", cost: 15 },
        { text: "Sem __eq__, c1 == c2 retorna False mesmo com códigos iguais — porque comparam endereços.", cost: 25 },
      ],
      xpReward: 1150,
      concept: "Método __eq__",
      conceptExplanation: "Métodos especiais (dunder methods) permitem customizar como os operadores funcionam com seus objetos. __eq__ define '==', __lt__ define '<', __add__ define '+', etc. Eles são o que dá ao Python seu polimorfismo de operadores.",
      successNpc: "Arquiteto de Sistemas",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Critério de equivalência ativo. O sistema agora compara conteúdo, não identidade na memória.",
      solution: "class Chave:\n    def __init__(self, codigo):\n        self.codigo = codigo\n    def __eq__(self, outro):\n        return self.codigo == outro.codigo\n\nc1 = Chave('AB')\nc2 = Chave('AB')\nprint(c1 == c2)",
    },
  ],
};
