import { World } from "../types";

export const LABORATORIO_NEURAL_WORLD: World = {
  id: "laboratorio-neural",
  title: "Laboratório Neural",
  subtitle: "Machine Learning",
  icon: "brain",
  color: "#F472B6",
  bgImage: "/assets/images/worlds/neural_lab.png",
  lore: "Treine modelos preditivos. Regressão, classificação e clustering — ensine máquinas a tomar decisões a partir de dados históricos.",
  unlockRequirement: 18000,
  challenges: [
    {
      id: "ds-ml-01",
      worldId: "laboratorio-neural",
      title: "Treinamento Supervisionado",
      description: "Importe LinearRegression. Crie 'modelo' e treine com modelo.fit(X, y).",
      narrative: "Inicialize um modelo de regressão linear para prever a intensidade de ataques.",
      difficulty: "intermediario",
      setupCode: "class LinearRegression:\n    def fit(self, X, y): print('Treinado.')\nX = [[1], [2], [3]]\ny = [10, 20, 30]",
      expectedOutput: "Treinado.",
      testCode: "assert 'LinearRegression' in code and 'fit' in code",
      starterCode: "from sklearn.linear_model import LinearRegression\n# Crie instância e fit\n",
      hints: [
        { text: "Em sklearn, cada algoritmo é uma classe: importe, instancie com (), depois chame .fit().", cost: 20 },
        { text: ".fit(X, y) recebe X (features 2D — lista de listas) e y (respostas 1D).", cost: 25 },
        { text: "modelo = LinearRegression()\\nmodelo.fit(X, y)", cost: 30 },
      ],
      xpReward: 700,
      concept: "Scikit-Learn API",
      conceptExplanation: "Scikit-learn é a biblioteca padrão de ML clássico em Python. A API é UNIFORME para TODOS os modelos: (1) instancia algoritmo = Classe(parametros); (2) treina com .fit(X, y); (3) prediz com .predict(X_novo). LinearRegression encontra a melhor reta entre X (features) e y (alvo contínuo). X SEMPRE 2D — lista de listas — mesmo com uma única feature. É a base de toda intuição sobre ML supervisionado.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo ajustado.",
      solution: "from sklearn.linear_model import LinearRegression\nmodelo = LinearRegression()\nmodelo.fit(X, y)",
    },
    {
      id: "ds-ml-02",
      worldId: "laboratorio-neural",
      title: "Divisão Treino/Teste",
      description: "Use train_test_split(X, y, test_size=0.2) e imprima 'Split realizado.'.",
      narrative: "Reserve 20% para validar o modelo.",
      difficulty: "intermediario",
      setupCode: "def train_test_split(X, y, test_size=0.2): return X[:8], X[8:], y[:8], y[8:]\nX = list(range(10))\ny = list(range(10))",
      expectedOutput: "Split realizado.",
      testCode: "assert 'train_test_split' in code and 'test_size' in code",
      starterCode: "from sklearn.model_selection import train_test_split\n# Faça o split e confirme\n",
      hints: [
        { text: "train_test_split retorna QUATRO valores: X_train, X_test, y_train, y_test. Desempacote com vírgulas.", cost: 20 },
        { text: "test_size=0.2 reserva 20% para teste. Para reprodutibilidade: random_state=42.", cost: 25 },
        { text: "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\\nprint('Split realizado.')", cost: 30 },
      ],
      xpReward: 750,
      concept: "Train/Test Split",
      conceptExplanation: "Regra MAIS IMPORTANTE de ML: separe dados em treino e teste antes do fit. Sem isso, você não tem como saber se o modelo generaliza ou apenas memoriza (overfitting). train_test_split embaralha e divide. Parâmetros úteis: random_state=42 (reprodutibilidade), stratify=y (mantém proporção de classes — importante em classes desbalanceadas). Tipicamente 20-30% para teste. Para validação mais robusta, use cross_val_score (várias divisões).",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Conjunto de validação isolado.",
      solution: "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nprint('Split realizado.')",
    },
    {
      id: "ds-ml-03",
      worldId: "laboratorio-neural",
      title: "Previsão",
      description: "Use modelo.predict([[4]]) e imprima.",
      narrative: "Aplique o modelo treinado a um novo dado.",
      difficulty: "intermediario",
      setupCode: "class Modelo:\n    def predict(self, X): return [v[0] * 10 for v in X]\nmodelo = Modelo()",
      expectedOutput: "[40]",
      testCode: "assert 'modelo.predict' in code",
      starterCode: "# modelo.predict([[4]])\n",
      hints: [
        { text: "Após fit, use .predict(X_novo) — formato igual ao X de treino.", cost: 20 },
        { text: "Mesmo para um único exemplo, envolva em lista de listas: predict([[4]]), nunca predict(4).", cost: 25 },
        { text: "print(modelo.predict([[4]]))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Inferência",
      conceptExplanation: "Inferência (ou predição) é quando você APLICA o modelo a dados novos — após o treino. .predict() recebe X em 2D (mesmo formato do treino, mesmo para um único exemplo — pegadinha clássica). Regressão retorna números contínuos; classificação retorna rótulos. Para classificação, .predict_proba() retorna probabilidades por classe — útil quando você precisa da CONFIANÇA, não só do label. Em produção, predict é chamado milhões de vezes — frequentemente gargalo de performance.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Previsão entregue.",
      solution: "print(modelo.predict([[4]]))",
    },
    {
      id: "ds-ml-04",
      worldId: "laboratorio-neural",
      title: "Score",
      description: "Imprima modelo.score(X_test, y_test). Quanto mais próximo de 1.0, melhor.",
      narrative: "Valide o modelo antes do deploy.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def score(self, X, y): return 0.95\nmodelo = Modelo()\nX_test = [[1], [2]]\ny_test = [10, 20]",
      expectedOutput: "0.95",
      testCode: "assert 'modelo.score' in code",
      starterCode: "# print do score nos dados de TESTE\n",
      hints: [
        { text: "Todo modelo sklearn tem .score(X, y). Use os dados de TESTE — não os de treino.", cost: 20 },
        { text: "Regressão retorna R² (entre -∞ e 1); classificação retorna acurácia (0 a 1).", cost: 25 },
        { text: "print(modelo.score(X_test, y_test))", cost: 30 },
      ],
      xpReward: 850,
      concept: "Métricas Padrão (score)",
      conceptExplanation: ".score() retorna métrica padrão de qualidade — sempre em DADOS DE TESTE (no treino, mede memorização). Regressão: R² (1=perfeito, 0=igual à média, negativo=pior que média). Classificação: acurácia (% de acertos, 0 a 1). Atenção: acurácia ENGANA em classes desbalanceadas — em dataset 95% 'normal', modelo que sempre diz 'normal' tem 95% acurácia mas é inútil. Para análise profunda, use sklearn.metrics: precision, recall, F1, confusion_matrix, roc_auc.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Acurácia validada.",
      solution: "print(modelo.score(X_test, y_test))",
    },
    {
      id: "ds-ml-05",
      worldId: "laboratorio-neural",
      title: "Classificação Logística",
      description: "Importe LogisticRegression, crie 'clf' e treine com clf.fit(X, y).",
      narrative: "Regressão logística é a porta de entrada para classificação binária.",
      difficulty: "intermediario",
      setupCode: "class LogisticRegression:\n    def fit(self, X, y): print('LogReg treinada.')\nX = [[1], [2], [3], [4]]\ny = [0, 0, 1, 1]",
      expectedOutput: "LogReg treinada.",
      testCode: "assert 'LogisticRegression' in code and 'fit' in code",
      starterCode: "from sklearn.linear_model import LogisticRegression\n# Instancie 'clf' e treine\n",
      hints: [
        { text: "Apesar do nome 'regression', LogisticRegression é um CLASSIFICADOR — para problemas binários (0/1) ou multiclasse.", cost: 20 },
        { text: "Mesma API: clf = LogisticRegression(); clf.fit(X, y).", cost: 25 },
        { text: "clf = LogisticRegression()\\nclf.fit(X, y)", cost: 30 },
      ],
      xpReward: 750,
      concept: "Regressão Logística",
      conceptExplanation: "Apesar do nome 'regression', LogisticRegression é o algoritmo de CLASSIFICAÇÃO mais usado como baseline — para problemas binários (spam/não-spam, fraude/legítimo) ou multiclasse. Internamente, calcula uma combinação linear de features + função sigmoid → produz uma probabilidade entre 0 e 1, depois classifica por limiar (0.5). Vantagens: rápida, interpretable (coefficients_ mostra importância de cada feature), pouca configuração. Para classes desbalanceadas, use class_weight='balanced'.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Classificador binário online.",
      solution: "from sklearn.linear_model import LogisticRegression\nclf = LogisticRegression()\nclf.fit(X, y)",
    },
    {
      id: "ds-ml-06",
      worldId: "laboratorio-neural",
      title: "Árvore de Decisão",
      description: "Importe DecisionTreeClassifier, crie 'tree' e treine.",
      narrative: "Árvores são interpretáveis — você pode VER as regras aprendidas.",
      difficulty: "intermediario",
      setupCode: "class DecisionTreeClassifier:\n    def fit(self, X, y): print('Árvore treinada.')\nX = [[1], [2], [3]]\ny = [0, 1, 1]",
      expectedOutput: "Árvore treinada.",
      testCode: "assert 'DecisionTreeClassifier' in code",
      starterCode: "from sklearn.tree import DecisionTreeClassifier\n# Instancie 'tree' e treine\n",
      hints: [
        { text: "DecisionTreeClassifier vem de sklearn.tree. Mesma API.", cost: 20 },
        { text: "Parâmetro útil: max_depth=N limita profundidade — controla overfitting.", cost: 25 },
        { text: "tree = DecisionTreeClassifier()\\ntree.fit(X, y)", cost: 30 },
      ],
      xpReward: 750,
      concept: "Decision Tree",
      conceptExplanation: "Árvore de decisão constrói uma série de perguntas (if feature_X > valor) que dividem os dados em grupos cada vez mais 'puros' até chegar nas classes. Maior vantagem: INTERPRETABILIDADE — você pode visualizar a árvore (plot_tree) e entender exatamente por que cada predição foi feita. Desvantagem: tende a overfitting (decora os dados). Controle com max_depth (profundidade máxima), min_samples_split (mínimo para dividir), min_samples_leaf. Para regressão, use DecisionTreeRegressor.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Árvore de regras construída.",
      solution: "from sklearn.tree import DecisionTreeClassifier\ntree = DecisionTreeClassifier()\ntree.fit(X, y)",
    },
    {
      id: "ds-ml-07",
      worldId: "laboratorio-neural",
      title: "Random Forest",
      description: "Importe RandomForestClassifier, crie 'rf' e treine.",
      narrative: "Várias árvores trabalhando juntas — ensemble robusto.",
      difficulty: "avancado",
      setupCode: "class RandomForestClassifier:\n    def fit(self, X, y): print('Floresta treinada.')\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "Floresta treinada.",
      testCode: "assert 'RandomForestClassifier' in code",
      starterCode: "from sklearn.ensemble import RandomForestClassifier\n# rf = ...\n",
      hints: [
        { text: "RandomForestClassifier está em sklearn.ensemble. Parâmetro n_estimators define quantas árvores (padrão 100).", cost: 25 },
        { text: "É 'random' porque cada árvore vê uma amostra ALEATÓRIA dos dados e features — daí robustez.", cost: 30 },
        { text: "rf = RandomForestClassifier()\\nrf.fit(X, y)", cost: 35 },
      ],
      xpReward: 850,
      concept: "Random Forest",
      conceptExplanation: "Random Forest é um ensemble: treina MUITAS árvores de decisão em subsamples aleatórios dos dados e features, depois agrega as previsões por votação majoritária (classificação) ou média (regressão). Combate o overfitting individual das árvores e geralmente entrega excelente performance OUT-OF-THE-BOX, sem muito tuning — é o 'go-to' para tabelas. Parâmetros principais: n_estimators (mais árvores = melhor mas mais lento), max_depth, max_features. Bonus: rf.feature_importances_ mostra quais features pesaram mais.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ensemble robusto deployado.",
      solution: "from sklearn.ensemble import RandomForestClassifier\nrf = RandomForestClassifier()\nrf.fit(X, y)",
    },
    {
      id: "ds-ml-08",
      worldId: "laboratorio-neural",
      title: "K-Nearest Neighbors",
      description: "Importe KNeighborsClassifier, crie 'knn' com n_neighbors=3 e treine.",
      narrative: "KNN classifica por similaridade — sem modelo abstrato, só vizinhos.",
      difficulty: "intermediario",
      setupCode: "class KNeighborsClassifier:\n    def __init__(self, n_neighbors=5): self.n = n_neighbors\n    def fit(self, X, y): print(f'KNN k={self.n} treinado.')\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "KNN k=3 treinado.",
      testCode: "assert 'KNeighborsClassifier' in code and 'n_neighbors' in code",
      starterCode: "from sklearn.neighbors import KNeighborsClassifier\n# knn com n_neighbors=3\n",
      hints: [
        { text: "Vem de sklearn.neighbors. n_neighbors define K — quantos vizinhos consultar.", cost: 20 },
        { text: "K pequeno (1-3): sensível a ruído. K grande: suaviza fronteiras. K ímpar evita empates.", cost: 25 },
        { text: "knn = KNeighborsClassifier(n_neighbors=3)\\nknn.fit(X, y)", cost: 30 },
      ],
      xpReward: 800,
      concept: "K-Nearest Neighbors",
      conceptExplanation: "KNN é o algoritmo mais simples de classificação: sem modelo abstrato, apenas guarda todos os exemplos de treino. Para classificar um novo ponto, encontra os K vizinhos mais próximos (por distância euclidiana, por padrão) e classifica pela maioria. Vantagens: zero configuração, lida bem com fronteiras complexas. Desvantagens: lento em inferência (compara com TODOS os exemplos de treino), sofre com alta dimensionalidade ('curse of dimensionality'). Sempre normalize features antes (StandardScaler) — sem isso, features com escala maior dominam a distância.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Classificador por similaridade.",
      solution: "from sklearn.neighbors import KNeighborsClassifier\nknn = KNeighborsClassifier(n_neighbors=3)\nknn.fit(X, y)",
    },
    {
      id: "ds-ml-09",
      worldId: "laboratorio-neural",
      title: "SVM",
      description: "Importe SVC, crie 'svm' e treine.",
      narrative: "Support Vector Machine — fronteiras de decisão otimizadas.",
      difficulty: "avancado",
      setupCode: "class SVC:\n    def fit(self, X, y): print('SVM treinado.')\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "SVM treinado.",
      testCode: "assert 'SVC' in code",
      starterCode: "from sklearn.svm import SVC\n# svm = ...\n",
      hints: [
        { text: "SVC (Support Vector Classifier) está em sklearn.svm. SVR para regressão.", cost: 25 },
        { text: "Parâmetro kernel: 'linear', 'rbf' (padrão, não-linear), 'poly'. C controla regularização.", cost: 30 },
        { text: "svm = SVC()\\nsvm.fit(X, y)", cost: 35 },
      ],
      xpReward: 900,
      concept: "Support Vector Machine",
      conceptExplanation: "SVM busca a fronteira de decisão que MAXIMIZA a margem entre classes — a 'rua' mais larga possível entre os pontos. Os pontos mais próximos da fronteira são os 'support vectors' que definem o modelo. Com kernels (linear, RBF, polynomial), consegue fronteiras não-lineares mapeando dados em dimensões superiores. Excelente em datasets pequenos/médios com muitas features. Desvantagens: NÃO escala bem para datasets grandes (>50k linhas) e é sensível à normalização — sempre escale antes.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Margem maximizada.",
      solution: "from sklearn.svm import SVC\nsvm = SVC()\nsvm.fit(X, y)",
    },
    {
      id: "ds-ml-10",
      worldId: "laboratorio-neural",
      title: "Naive Bayes",
      description: "Importe GaussianNB, crie 'nb' e treine.",
      narrative: "Algoritmo probabilístico clássico para classificação de texto.",
      difficulty: "intermediario",
      setupCode: "class GaussianNB:\n    def fit(self, X, y): print('NB treinado.')\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "NB treinado.",
      testCode: "assert 'GaussianNB' in code",
      starterCode: "from sklearn.naive_bayes import GaussianNB\n# nb = ...\n",
      hints: [
        { text: "GaussianNB de sklearn.naive_bayes. Outras variantes: MultinomialNB (texto), BernoulliNB (binário).", cost: 25 },
        { text: "Modelo extremamente rápido. Mesma API: nb = GaussianNB(); nb.fit(X, y).", cost: 30 },
        { text: "nb = GaussianNB()\\nnb.fit(X, y)", cost: 35 },
      ],
      xpReward: 850,
      concept: "Naive Bayes",
      conceptExplanation: "Naive Bayes aplica o Teorema de Bayes assumindo INDEPENDÊNCIA entre features ('naive' = ingênuo, porque essa premissa raramente é verdade). Apesar disso, funciona surpreendentemente bem em texto (filtro de spam, classificação de documentos). Variantes: GaussianNB (features contínuas, assume distribuição normal); MultinomialNB (contagens — clássico para NLP com bag-of-words); BernoulliNB (features binárias). Vantagens: super rápido, lida com dimensionalidade alta, exige pouco dado. Bom baseline para problemas de texto.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Classificador probabilístico online.",
      solution: "from sklearn.naive_bayes import GaussianNB\nnb = GaussianNB()\nnb.fit(X, y)",
    },
    {
      id: "ds-ml-11",
      worldId: "laboratorio-neural",
      title: "Ridge (L2)",
      description: "Importe Ridge, crie 'ridge' com alpha=1.0 e treine.",
      narrative: "Regularização L2 controla overfitting em regressão.",
      difficulty: "avancado",
      setupCode: "class Ridge:\n    def __init__(self, alpha=1.0): self.a = alpha\n    def fit(self, X, y): print(f'Ridge a={self.a}')\nX = [[1], [2]]\ny = [1, 2]",
      expectedOutput: "Ridge a=1.0",
      testCode: "assert 'Ridge' in code and 'alpha' in code",
      starterCode: "from sklearn.linear_model import Ridge\n# ridge com alpha=1.0\n",
      hints: [
        { text: "Ridge = LinearRegression + penalidade L2 (soma dos pesos²). alpha controla a força da penalidade.", cost: 25 },
        { text: "alpha=0 vira regressão linear normal. alpha grande encolhe muito os pesos.", cost: 30 },
        { text: "ridge = Ridge(alpha=1.0)\\nridge.fit(X, y)", cost: 35 },
      ],
      xpReward: 900,
      concept: "Regularização L2 (Ridge)",
      conceptExplanation: "Regressão Ridge adiciona uma PENALIDADE L2 à função de erro: soma dos pesos ao quadrado vezes alpha. Isso 'encolhe' os pesos em direção a zero, prevenindo que features individuais dominem o modelo — combate overfitting. Use Ridge quando você tem MUITAS features correlacionadas. O parâmetro alpha (também chamado lambda) controla a força: alpha=0 = sem penalidade (vira LinearRegression); alpha grande = pesos muito pequenos. Escolha alpha via cross-validation (RidgeCV). Para penalidade L1 (zera alguns pesos), use Lasso.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pesos regularizados.",
      solution: "from sklearn.linear_model import Ridge\nridge = Ridge(alpha=1.0)\nridge.fit(X, y)",
    },
    {
      id: "ds-ml-12",
      worldId: "laboratorio-neural",
      title: "Lasso (L1)",
      description: "Importe Lasso, crie 'lasso' com alpha=0.1 e treine.",
      narrative: "L1 zera pesos de features irrelevantes — seleção automática.",
      difficulty: "avancado",
      setupCode: "class Lasso:\n    def __init__(self, alpha=1.0): self.a = alpha\n    def fit(self, X, y): print(f'Lasso a={self.a}')\nX = [[1], [2]]\ny = [1, 2]",
      expectedOutput: "Lasso a=0.1",
      testCode: "assert 'Lasso' in code and 'alpha' in code",
      starterCode: "from sklearn.linear_model import Lasso\n# lasso com alpha=0.1\n",
      hints: [
        { text: "Lasso usa penalidade L1 (soma dos VALORES ABSOLUTOS dos pesos). Tende a ZERAR pesos de features irrelevantes.", cost: 25 },
        { text: "Mesma API que Ridge — só muda a regularização.", cost: 30 },
        { text: "lasso = Lasso(alpha=0.1)\\nlasso.fit(X, y)", cost: 35 },
      ],
      xpReward: 900,
      concept: "Regularização L1 (Lasso)",
      conceptExplanation: "Lasso (Least Absolute Shrinkage and Selection Operator) usa penalidade L1 — soma dos VALORES ABSOLUTOS dos pesos. Diferença crucial vs Ridge: Lasso ZERA pesos de features irrelevantes, fazendo SELEÇÃO DE FEATURES automaticamente. Útil quando você suspeita que apenas algumas features importam de fato. Use quando interpretabilidade é importante (modelo final com poucas features). Para combinar L1+L2, use ElasticNet — flexibilidade dos dois. Como em Ridge, alpha controla a força da penalidade.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Features irrelevantes eliminadas.",
      solution: "from sklearn.linear_model import Lasso\nlasso = Lasso(alpha=0.1)\nlasso.fit(X, y)",
    },
    {
      id: "ds-ml-13",
      worldId: "laboratorio-neural",
      title: "Gradient Boosting",
      description: "Importe GradientBoostingClassifier, crie 'gb' e treine.",
      narrative: "Boosting: árvores corrigindo erros umas das outras. Estado-da-arte em tabular.",
      difficulty: "avancado",
      setupCode: "class GradientBoostingClassifier:\n    def fit(self, X, y): print('GB treinado.')\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "GB treinado.",
      testCode: "assert 'GradientBoostingClassifier' in code",
      starterCode: "from sklearn.ensemble import GradientBoostingClassifier\n# gb = ...\n",
      hints: [
        { text: "GradientBoostingClassifier está em sklearn.ensemble.", cost: 25 },
        { text: "Parâmetros principais: n_estimators, learning_rate, max_depth. Para versões muito mais rápidas, veja XGBoost e LightGBM.", cost: 30 },
        { text: "gb = GradientBoostingClassifier()\\ngb.fit(X, y)", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Gradient Boosting",
      conceptExplanation: "Boosting treina modelos SEQUENCIALMENTE — cada novo modelo foca em CORRIGIR os erros do anterior. Random Forest treina árvores em paralelo independentes; boosting treina em sequência cada uma melhorando onde as anteriores erraram. Resultado: frequentemente o MELHOR algoritmo para dados tabulares — ganha quase toda competição do Kaggle. Bibliotecas mais rápidas que sklearn: XGBoost, LightGBM, CatBoost — versões otimizadas com paralelismo e GPU. Parâmetros: n_estimators (árvores), learning_rate (passo de correção), max_depth.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ensemble sequencial deployado.",
      solution: "from sklearn.ensemble import GradientBoostingClassifier\ngb = GradientBoostingClassifier()\ngb.fit(X, y)",
    },
    {
      id: "ds-ml-14",
      worldId: "laboratorio-neural",
      title: "StandardScaler",
      description: "Importe StandardScaler, crie 'scaler' e use fit_transform(X). Imprima 'Escalado.'.",
      narrative: "Normalize features para algoritmos sensíveis a escala (SVM, KNN, redes neurais).",
      difficulty: "intermediario",
      setupCode: "class StandardScaler:\n    def fit_transform(self, X): print('Escalado.'); return X\nX = [[1, 100], [2, 200]]",
      expectedOutput: "Escalado.",
      testCode: "assert 'StandardScaler' in code and 'fit_transform' in code",
      starterCode: "from sklearn.preprocessing import StandardScaler\n# Crie scaler e use fit_transform(X)\n",
      hints: [
        { text: "StandardScaler subtrai média e divide pelo desvio padrão (z-score) — média 0, desvio 1.", cost: 20 },
        { text: "fit_transform() faz fit() e transform() de uma vez — calcula média/std e aplica.", cost: 25 },
        { text: "scaler = StandardScaler()\\nscaler.fit_transform(X)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Standardização",
      conceptExplanation: "StandardScaler aplica z-score: (x - média) / desvio_padrão — resultando em features com média 0 e desvio 1. ESSENCIAL para algoritmos sensíveis a escala: SVM, KNN, redes neurais, regressões com regularização. Sem normalização, features com escala maior (ex: salário em milhões vs idade em dezenas) dominam o aprendizado. IMPORTANTE: fit_transform APENAS no treino; no teste use só transform() — caso contrário você está vazando estatísticas. Em Pipeline, isso é automatizado.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Features normalizadas.",
      solution: "from sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\nscaler.fit_transform(X)",
    },
    {
      id: "ds-ml-15",
      worldId: "laboratorio-neural",
      title: "MinMaxScaler",
      description: "Importe MinMaxScaler, escale X para [0, 1] com fit_transform. Imprima 'Min-Max aplicado.'.",
      narrative: "Quando você quer features no intervalo fixo [0, 1].",
      difficulty: "intermediario",
      setupCode: "class MinMaxScaler:\n    def fit_transform(self, X): print('Min-Max aplicado.'); return X\nX = [[1], [10]]",
      expectedOutput: "Min-Max aplicado.",
      testCode: "assert 'MinMaxScaler' in code",
      starterCode: "from sklearn.preprocessing import MinMaxScaler\n# scaler com fit_transform\n",
      hints: [
        { text: "MinMaxScaler mapeia cada feature para [0, 1] linearmente: (x - min) / (max - min).", cost: 20 },
        { text: "Diferente de StandardScaler (média 0, std 1), preserva o formato da distribuição.", cost: 25 },
        { text: "scaler = MinMaxScaler()\\nscaler.fit_transform(X)\\nprint('Min-Max aplicado.') if False else None", cost: 30 },
      ],
      xpReward: 800,
      concept: "Normalização Min-Max",
      conceptExplanation: "MinMaxScaler escala cada feature para um intervalo fixo (padrão [0, 1]): (x - min) / (max - min). Preserva o formato da distribuição (diferente de StandardScaler que recentra). Use quando: (1) você precisa de features em intervalo conhecido (ex: redes neurais com ativações sigmoide); (2) os dados não seguem distribuição normal; (3) você quer interpretabilidade direta dos valores. Desvantagem vs StandardScaler: muito sensível a outliers (um valor extremo comprime todo o resto). Para dados com outliers, use RobustScaler.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Intervalos uniformizados.",
      solution: "from sklearn.preprocessing import MinMaxScaler\nscaler = MinMaxScaler()\nscaler.fit_transform(X)",
    },
    {
      id: "ds-ml-16",
      worldId: "laboratorio-neural",
      title: "LabelEncoder",
      description: "Importe LabelEncoder, codifique labels=['gato','cao','gato'] com fit_transform. Imprima 'Encoded.'.",
      narrative: "Converta strings categóricas em inteiros antes do treino.",
      difficulty: "intermediario",
      setupCode: "class LabelEncoder:\n    def fit_transform(self, y): print('Encoded.'); return [0, 1, 0]",
      expectedOutput: "Encoded.",
      testCode: "assert 'LabelEncoder' in code",
      starterCode: "from sklearn.preprocessing import LabelEncoder\nlabels = ['gato', 'cao', 'gato']\n# Encode\n",
      hints: [
        { text: "LabelEncoder converte rótulos categóricos em inteiros consecutivos: 'gato'→0, 'cao'→1, etc.", cost: 20 },
        { text: "Use APENAS na variável y (alvo) — para features categóricas use OneHotEncoder.", cost: 25 },
        { text: "le = LabelEncoder()\\nle.fit_transform(labels)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Label Encoding",
      conceptExplanation: "LabelEncoder converte rótulos categóricos (strings) em inteiros consecutivos: 'gato'→0, 'cao'→1, 'passaro'→2. Use APENAS na variável y (alvo) em problemas de classificação — sklearn precisa de y numérico. Para features categóricas em X, NÃO use LabelEncoder ingenuamente: ele induz ordem artificial (cao > gato?) que algoritmos lineares interpretam erradamente. Use OneHotEncoder ou get_dummies do pandas. Para reverter: le.inverse_transform([0,1,0]) → ['gato','cao','gato'].",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Rótulos numerizados.",
      solution: "from sklearn.preprocessing import LabelEncoder\nle = LabelEncoder()\nle.fit_transform(['gato', 'cao', 'gato'])",
    },
    {
      id: "ds-ml-17",
      worldId: "laboratorio-neural",
      title: "OneHotEncoder",
      description: "Importe OneHotEncoder, crie 'ohe' e use fit_transform([['A'],['B'],['A']]). Imprima 'OneHot.'.",
      narrative: "Variáveis categóricas em features viram colunas binárias.",
      difficulty: "avancado",
      setupCode: "class OneHotEncoder:\n    def fit_transform(self, X): print('OneHot.'); return X",
      expectedOutput: "OneHot.",
      testCode: "assert 'OneHotEncoder' in code",
      starterCode: "from sklearn.preprocessing import OneHotEncoder\n# ohe com fit_transform\n",
      hints: [
        { text: "OneHotEncoder transforma cada categoria em uma COLUNA binária: 'A'→[1,0], 'B'→[0,1], 'C'→[0,0,1].", cost: 25 },
        { text: "Para features categóricas em X — não para y. Use em vez do LabelEncoder para X.", cost: 30 },
        { text: "ohe = OneHotEncoder()\\nohe.fit_transform([['A'],['B'],['A']])", cost: 35 },
      ],
      xpReward: 900,
      concept: "One-Hot Encoding",
      conceptExplanation: "One-Hot transforma categorias em colunas binárias: 'cor' com valores [vermelho, azul, verde] vira 3 colunas (1 ou 0) indicando presença de cada cor. Evita o problema de ordem artificial do LabelEncoder em features. Use para features categóricas SEM ORDEM intrínseca (cores, países, gêneros). Para categorias com ordem (escolaridade: fund/médio/superior), prefira OrdinalEncoder. Em pandas, a versão fácil é pd.get_dummies(df). Cuidado com 'curse of dimensionality': muitas categorias = muitas colunas.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Categorias expandidas em binário.",
      solution: "from sklearn.preprocessing import OneHotEncoder\nohe = OneHotEncoder()\nohe.fit_transform([['A'],['B'],['A']])",
    },
    {
      id: "ds-ml-18",
      worldId: "laboratorio-neural",
      title: "SimpleImputer",
      description: "Importe SimpleImputer com strategy='mean'. Use fit_transform em X. Imprima 'Imputado.'.",
      narrative: "Preencha valores faltantes com a média antes do modelo.",
      difficulty: "intermediario",
      setupCode: "class SimpleImputer:\n    def __init__(self, strategy='mean'): self.s = strategy\n    def fit_transform(self, X): print(f'Imputado.'); return X\nimport numpy as np\nX = [[1, np.nan], [2, 3]]",
      expectedOutput: "Imputado.",
      testCode: "assert 'SimpleImputer' in code and 'strategy' in code",
      starterCode: "from sklearn.impute import SimpleImputer\n# imp com strategy='mean'\n",
      hints: [
        { text: "SimpleImputer está em sklearn.impute. strategy define a estratégia: 'mean', 'median', 'most_frequent', 'constant'.", cost: 20 },
        { text: "Para constante: SimpleImputer(strategy='constant', fill_value=0). Comum em pipelines.", cost: 25 },
        { text: "imp = SimpleImputer(strategy='mean')\\nimp.fit_transform(X)", cost: 30 },
      ],
      xpReward: 850,
      concept: "Imputação de Nulos",
      conceptExplanation: "SimpleImputer é a forma padrão de preencher NaN no sklearn (pandas tem fillna, mas integra mal com pipelines). Estratégias: 'mean' (média por coluna — só numéricas), 'median' (mediana — robusta a outliers), 'most_frequent' (moda — funciona em qualquer tipo, ideal para categóricas), 'constant' (valor fixo via fill_value). Sempre use em PIPELINE: as estatísticas (média, mediana) devem ser calculadas SÓ no treino e aplicadas no teste — caso contrário há vazamento. Para imputação mais sofisticada: KNNImputer ou IterativeImputer.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Nulos preenchidos.",
      solution: "from sklearn.impute import SimpleImputer\nimp = SimpleImputer(strategy='mean')\nimp.fit_transform(X)",
    },
    {
      id: "ds-ml-19",
      worldId: "laboratorio-neural",
      title: "Acurácia",
      description: "Use accuracy_score(y_real, y_pred) e imprima.",
      narrative: "Métrica clássica para classificação balanceada.",
      difficulty: "intermediario",
      setupCode: "def accuracy_score(a, b): return sum(1 for x,y in zip(a,b) if x==y)/len(a)\ny_real = [0, 1, 1, 0]\ny_pred = [0, 1, 0, 0]",
      expectedOutput: "0.75",
      testCode: "assert 'accuracy_score' in code",
      starterCode: "from sklearn.metrics import accuracy_score\n# Calcule e imprima\n",
      hints: [
        { text: "accuracy_score(y_real, y_pred) calcula proporção de acertos — argumentos: ordem importa pouco aqui (simétrica).", cost: 20 },
        { text: "Retorna float entre 0 e 1. Multiplique por 100 para %.", cost: 25 },
        { text: "print(accuracy_score(y_real, y_pred))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Acurácia",
      conceptExplanation: "accuracy_score calcula a proporção de previsões corretas: acertos / total. Métrica mais intuitiva para classificação, mas ENGANA em classes desbalanceadas. Exemplo: dataset com 95% spam e 5% legítimos — um modelo que sempre prevê 'spam' tem 95% acurácia mas é completamente inútil. Em situações desbalanceadas, use precision, recall, F1 ou ROC-AUC. Para problemas balanceados (50/50), acurácia é o reflexo direto da performance.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Métrica de acerto registrada.",
      solution: "from sklearn.metrics import accuracy_score\nprint(accuracy_score(y_real, y_pred))",
    },
    {
      id: "ds-ml-20",
      worldId: "laboratorio-neural",
      title: "Confusion Matrix",
      description: "Use confusion_matrix(y_real, y_pred) e imprima.",
      narrative: "Veja onde o modelo erra: falsos positivos vs falsos negativos.",
      difficulty: "intermediario",
      setupCode: "def confusion_matrix(a, b): return [[2, 0], [1, 1]]\ny_real = [0, 1, 1, 0]\ny_pred = [0, 1, 0, 0]",
      expectedOutput: "[[2, 0], [1, 1]]",
      testCode: "assert 'confusion_matrix' in code",
      starterCode: "from sklearn.metrics import confusion_matrix\n# Imprima a matriz de confusão\n",
      hints: [
        { text: "confusion_matrix(y_real, y_pred) retorna matriz: linhas=classe real, colunas=classe prevista.", cost: 20 },
        { text: "Em binário: [[VN, FP], [FN, VP]]. VP/VN são acertos; FP/FN são erros.", cost: 25 },
        { text: "print(confusion_matrix(y_real, y_pred))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Matriz de Confusão",
      conceptExplanation: "Matriz NxN (N=classes) mostrando como o modelo confunde classes. Em binário: VN (verdadeiros negativos), FP (falsos positivos — alarme falso), FN (falsos negativos — não detectou), VP (verdadeiros positivos). Revela ASSIMETRIA dos erros: em medicina, FN (não detectou doença) é muito pior que FP. Para visualizar: sns.heatmap(cm, annot=True). Permite calcular todas as outras métricas: precision = VP/(VP+FP), recall = VP/(VP+FN). Sempre olhe a matriz antes de confiar em uma única métrica agregada.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Erros mapeados.",
      solution: "from sklearn.metrics import confusion_matrix\nprint(confusion_matrix(y_real, y_pred))",
    },
    {
      id: "ds-ml-21",
      worldId: "laboratorio-neural",
      title: "Classification Report",
      description: "Use classification_report(y_real, y_pred) e imprima.",
      narrative: "Relatório completo: precision, recall, f1 por classe.",
      difficulty: "intermediario",
      setupCode: "def classification_report(a, b): return 'precision recall f1-score'\ny_real = [0, 1]\ny_pred = [0, 1]",
      expectedOutput: "precision recall f1-score",
      testCode: "assert 'classification_report' in code",
      starterCode: "from sklearn.metrics import classification_report\n# Imprima o relatório\n",
      hints: [
        { text: "classification_report retorna uma string formatada com precision, recall, f1 e suporte para CADA classe.", cost: 20 },
        { text: "É a forma mais rápida de ter visão completa do desempenho. Imprima direto com print.", cost: 25 },
        { text: "print(classification_report(y_real, y_pred))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Classification Report",
      conceptExplanation: "classification_report gera um resumo formatado com precision, recall, F1-score e suporte (n amostras) por classe — visão completa em uma chamada. Adicionalmente fornece médias: 'macro avg' (média simples entre classes — trata todas igual) e 'weighted avg' (média ponderada pelo suporte — privilegia classes maiores). Em classes desbalanceadas, macro avg é mais honesto. Para reporting executivo: classification_report(y, y_pred, target_names=['nao_spam', 'spam']) — substitui números por nomes.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Relatório completo gerado.",
      solution: "from sklearn.metrics import classification_report\nprint(classification_report(y_real, y_pred))",
    },
    {
      id: "ds-ml-22",
      worldId: "laboratorio-neural",
      title: "Precision, Recall, F1",
      description: "Use precision_score(y_real, y_pred) e imprima.",
      narrative: "Em desbalanceado, precision e recall são mais informativos.",
      difficulty: "avancado",
      setupCode: "def precision_score(a, b): return 0.5\ny_real = [0, 1, 1]\ny_pred = [1, 1, 1]",
      expectedOutput: "0.5",
      testCode: "assert 'precision_score' in code",
      starterCode: "from sklearn.metrics import precision_score\n# Calcule e imprima\n",
      hints: [
        { text: "precision_score, recall_score e f1_score estão em sklearn.metrics. Assinatura igual a accuracy_score.", cost: 25 },
        { text: "Para multiclasse, passe average='macro' (média entre classes) ou 'weighted'.", cost: 30 },
        { text: "print(precision_score(y_real, y_pred))", cost: 35 },
      ],
      xpReward: 850,
      concept: "Precision, Recall, F1",
      conceptExplanation: "PRECISION = VP/(VP+FP): das previsões positivas, quantas são realmente positivas. RECALL = VP/(VP+FN): dos positivos reais, quantos foram detectados. F1 = média harmônica entre os dois — balança ambos. Trade-off clássico: melhorar precision frequentemente piora recall e vice-versa. Em detecção de fraude, você prioriza RECALL (não pode deixar fraude passar). Em diagnóstico de câncer, depende — falso negativo é fatal (recall), falso positivo causa stress (precision). F1 quando você quer um único número balanceado.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Trade-off mensurado.",
      solution: "from sklearn.metrics import precision_score\nprint(precision_score(y_real, y_pred))",
    },
    {
      id: "ds-ml-23",
      worldId: "laboratorio-neural",
      title: "MSE (Regressão)",
      description: "Use mean_squared_error(y_real, y_pred) e imprima.",
      narrative: "Erro quadrático médio: a métrica padrão de regressão.",
      difficulty: "intermediario",
      setupCode: "def mean_squared_error(a, b): return sum((x-y)**2 for x,y in zip(a,b))/len(a)\ny_real = [1, 2, 3]\ny_pred = [1.1, 1.9, 3.2]",
      expectedOutput: "0.020000000000000018",
      testCode: "assert 'mean_squared_error' in code",
      starterCode: "from sklearn.metrics import mean_squared_error\n# Imprima MSE\n",
      hints: [
        { text: "mean_squared_error calcula média dos erros AO QUADRADO: amplifica erros grandes.", cost: 20 },
        { text: "Para RMSE (raiz, mesma unidade dos dados): np.sqrt(mse). Para erro absoluto: mean_absolute_error.", cost: 25 },
        { text: "print(mean_squared_error(y_real, y_pred))", cost: 30 },
      ],
      xpReward: 750,
      concept: "Métricas de Regressão",
      conceptExplanation: "MSE (Mean Squared Error) = média de (y_real - y_pred)². Eleva ao quadrado para: (1) eliminar sinal; (2) AMPLIFICAR erros grandes (penaliza mais previsões muito erradas). RMSE = sqrt(MSE) tem a mesma unidade dos dados — mais interpretável. MAE (mean_absolute_error) usa valor absoluto em vez de quadrado: mais robusto a outliers, mas não amplifica erros grandes. R² (r2_score) é uma medida normalizada [0,1] de quão melhor o modelo é vs prever a média sempre. Use múltiplas métricas em conjunto.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Erro quadrático calculado.",
      solution: "from sklearn.metrics import mean_squared_error\nprint(mean_squared_error(y_real, y_pred))",
    },
    {
      id: "ds-ml-24",
      worldId: "laboratorio-neural",
      title: "R² Score",
      description: "Use r2_score(y_real, y_pred) e imprima.",
      narrative: "Coeficiente de determinação: o quão bem o modelo explica a variância.",
      difficulty: "intermediario",
      setupCode: "def r2_score(a, b): return 0.95\ny_real = [1, 2, 3]\ny_pred = [1.1, 1.9, 3.2]",
      expectedOutput: "0.95",
      testCode: "assert 'r2_score' in code",
      starterCode: "from sklearn.metrics import r2_score\n# Imprima R²\n",
      hints: [
        { text: "r2_score retorna entre -infinito e 1. 1 = previsão perfeita; 0 = igual à média; negativo = pior que prever média.", cost: 20 },
        { text: "É a métrica padrão do .score() em modelos de regressão.", cost: 25 },
        { text: "print(r2_score(y_real, y_pred))", cost: 30 },
      ],
      xpReward: 800,
      concept: "R² (Coeficiente de Determinação)",
      conceptExplanation: "R² mede a proporção da variância em y explicada pelo modelo. R² = 1 = previsão perfeita; R² = 0 = modelo igual a prever a média de y para tudo (totalmente inútil); R² negativo = modelo PIOR que prever a média. Valores típicos em problemas reais: 0.5-0.9 dependendo do domínio. NÃO compare R² diretamente entre datasets diferentes — é específico do problema. Para múltiplos features, prefira R² ajustado (penaliza features irrelevantes). É o que .score() retorna em modelos de regressão por padrão.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Variância explicada quantificada.",
      solution: "from sklearn.metrics import r2_score\nprint(r2_score(y_real, y_pred))",
    },
    {
      id: "ds-ml-25",
      worldId: "laboratorio-neural",
      title: "Pipeline",
      description: "Crie Pipeline com steps=[('scaler', StandardScaler()), ('clf', LogisticRegression())] e imprima 'Pipeline criado.'.",
      narrative: "Una preprocessamento e modelo em um só objeto.",
      difficulty: "avancado",
      setupCode: "class StandardScaler: pass\nclass LogisticRegression: pass\nclass Pipeline:\n    def __init__(self, steps): self.s = steps",
      expectedOutput: "Pipeline criado.",
      testCode: "assert 'Pipeline' in code and 'steps' in code",
      starterCode: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\n# Crie o Pipeline\n",
      hints: [
        { text: "Pipeline(steps=[...]) recebe lista de tuplas (nome, transformador). O último deve ser o modelo final.", cost: 30 },
        { text: "Use direto com .fit(X,y) e .predict(X) — chama tudo em sequência automaticamente.", cost: 35 },
        { text: "pipe = Pipeline(steps=[('scaler', StandardScaler()), ('clf', LogisticRegression())])\\nprint('Pipeline criado.')", cost: 40 },
      ],
      xpReward: 1000,
      concept: "Pipelines",
      conceptExplanation: "Pipeline encapsula sequência de transformações + modelo final em um único objeto. Vantagens: (1) elimina vazamento de dados — fit é aplicado SÓ no treino automaticamente; (2) código mais limpo (uma chamada .fit, .predict, .score); (3) deploy mais simples (um objeto); (4) integra com GridSearchCV e cross_val. Estrutura: lista de tuplas (nome, transformador), com o último elemento sendo o modelo. Acesso a steps individuais: pipe.named_steps['scaler']. Padrão de mercado em projetos reais — não há razão para não usar.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Fluxo unificado.",
      solution: "from sklearn.pipeline import Pipeline\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\npipe = Pipeline(steps=[('scaler', StandardScaler()), ('clf', LogisticRegression())])\nprint('Pipeline criado.')",
    },
    {
      id: "ds-ml-26",
      worldId: "laboratorio-neural",
      title: "Cross-Validation",
      description: "Use cross_val_score(modelo, X, y, cv=5) e imprima 'Validado.'.",
      narrative: "Avaliação robusta: 5 partições rotativas.",
      difficulty: "avancado",
      setupCode: "def cross_val_score(m, X, y, cv): print('Validado.'); return [0.9]*cv\nclass Modelo: pass\nmodelo = Modelo()\nX = [[1], [2]]\ny = [0, 1]",
      expectedOutput: "Validado.",
      testCode: "assert 'cross_val_score' in code and 'cv' in code",
      starterCode: "from sklearn.model_selection import cross_val_score\n# Use cv=5\n",
      hints: [
        { text: "cross_val_score(modelo, X, y, cv=5) divide os dados em 5 partes, treina em 4 e testa em 1, rotacionando.", cost: 30 },
        { text: "Retorna ARRAY com 5 scores — uma execução por fold. Tire média (.mean()) e desvio (.std()).", cost: 35 },
        { text: "cross_val_score(modelo, X, y, cv=5)\\nprint('Validado.')", cost: 40 },
      ],
      xpReward: 1050,
      concept: "Cross-Validation (K-Fold)",
      conceptExplanation: "Cross-validation é avaliação mais robusta que train_test_split único: divide os dados em K partes ('folds'), treina K vezes (cada vez deixando uma parte fora para teste), e retorna K scores. Vantagens: (1) usa todos os dados para teste em algum momento; (2) reduz variância da estimativa de performance; (3) detecta instabilidade do modelo. Tipicamente cv=5 ou cv=10. Para problemas de classificação desbalanceada, use StratifiedKFold. Sempre reporte média ± desvio padrão: 'F1 = 0.85 ± 0.03'.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Performance validada em K folds.",
      solution: "from sklearn.model_selection import cross_val_score\ncross_val_score(modelo, X, y, cv=5)\nprint('Validado.')",
    },
    {
      id: "ds-ml-27",
      worldId: "laboratorio-neural",
      title: "GridSearchCV",
      description: "Crie GridSearchCV(modelo, param_grid={'C': [0.1, 1, 10]}, cv=3) e imprima 'Grid configurado.'.",
      narrative: "Busca automatizada pelos melhores hiperparâmetros.",
      difficulty: "avancado",
      setupCode: "class GridSearchCV:\n    def __init__(self, m, param_grid, cv): pass\nclass Modelo: pass\nmodelo = Modelo()",
      expectedOutput: "Grid configurado.",
      testCode: "assert 'GridSearchCV' in code and 'param_grid' in code",
      starterCode: "from sklearn.model_selection import GridSearchCV\n# Crie o grid search\n",
      hints: [
        { text: "GridSearchCV(modelo, param_grid={'param': [valores]}, cv=K) testa todas as combinações com cross-validation.", cost: 30 },
        { text: "Após .fit(), acesse .best_params_ (melhores hiperparâmetros) e .best_score_ (melhor score).", cost: 35 },
        { text: "grid = GridSearchCV(modelo, param_grid={'C': [0.1, 1, 10]}, cv=3)\\nprint('Grid configurado.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Tuning de Hiperparâmetros",
      conceptExplanation: "GridSearchCV automatiza busca de hiperparâmetros: você passa um modelo e um dicionário com valores a testar, e ele testa TODAS as combinações com cross-validation, retornando os melhores. Após .fit(): grid.best_params_ (combinação vencedora), grid.best_score_ (melhor score CV), grid.best_estimator_ (modelo já treinado com os melhores params). Para muitas combinações, use RandomizedSearchCV (amostragem aleatória — muito mais rápido). Para busca bayesiana avançada: Optuna, Hyperopt. CRUCIAL: nunca tune hiperparâmetros usando o set de teste final.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Hiperparâmetros otimizados.",
      solution: "from sklearn.model_selection import GridSearchCV\ngrid = GridSearchCV(modelo, param_grid={'C': [0.1, 1, 10]}, cv=3)\nprint('Grid configurado.')",
    },
    {
      id: "ds-ml-28",
      worldId: "laboratorio-neural",
      title: "KMeans (Clustering)",
      description: "Crie KMeans(n_clusters=3), treine com .fit(X) e imprima 'Clusters formados.'.",
      narrative: "Aprendizado NÃO-supervisionado: agrupar sem rótulos.",
      difficulty: "avancado",
      setupCode: "class KMeans:\n    def __init__(self, n_clusters): self.n = n_clusters\n    def fit(self, X): print('Clusters formados.')\nX = [[1, 2], [1, 4], [10, 8]]",
      expectedOutput: "Clusters formados.",
      testCode: "assert 'KMeans' in code and 'n_clusters' in code",
      starterCode: "from sklearn.cluster import KMeans\n# n_clusters=3, fit, confirmação\n",
      hints: [
        { text: "Em clustering NÃO há y — passe só X para .fit(). O algoritmo descobre os grupos.", cost: 25 },
        { text: "n_clusters define quantos grupos formar — decisão SUA, baseada no problema.", cost: 30 },
        { text: "kmeans = KMeans(n_clusters=3)\\nkmeans.fit(X)\\nprint('Clusters formados.')", cost: 35 },
      ],
      xpReward: 900,
      concept: "Aprendizado Não-Supervisionado",
      conceptExplanation: "Clustering é aprendizado NÃO-supervisionado: você só tem X (sem rótulos), e o algoritmo descobre estrutura sozinho. KMeans: dado K, encontra K centros e atribui cada ponto ao centro mais próximo, iterativamente ajustando. Após fit: .labels_ (cluster de cada ponto), .cluster_centers_ (coordenadas dos centros). Aplicações: segmentação de clientes, agrupamento de documentos, compressão de imagens, detecção de anomalias. Escolha K pelo 'método do cotovelo' (plote inércia vs K) ou silhouette score.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Três grupos descobertos.",
      solution: "from sklearn.cluster import KMeans\nkmeans = KMeans(n_clusters=3)\nkmeans.fit(X)\nprint('Clusters formados.')",
    },
    {
      id: "ds-ml-29",
      worldId: "laboratorio-neural",
      title: "DBSCAN",
      description: "Importe DBSCAN, crie 'dbs' e use fit(X). Imprima 'DBSCAN ok.'.",
      narrative: "Clustering baseado em densidade — descobre clusters de formato arbitrário.",
      difficulty: "avancado",
      setupCode: "class DBSCAN:\n    def fit(self, X): print('DBSCAN ok.')\nX = [[1,2],[1,3]]",
      expectedOutput: "DBSCAN ok.",
      testCode: "assert 'DBSCAN' in code",
      starterCode: "from sklearn.cluster import DBSCAN\n# fit e print\n",
      hints: [
        { text: "DBSCAN está em sklearn.cluster. Não precisa pré-definir número de clusters.", cost: 30 },
        { text: "Parâmetros: eps (distância máxima entre vizinhos), min_samples (mínimo para core point).", cost: 35 },
        { text: "dbs = DBSCAN()\\ndbs.fit(X)\\nprint('DBSCAN ok.')", cost: 40 },
      ],
      xpReward: 1000,
      concept: "DBSCAN",
      conceptExplanation: "DBSCAN (Density-Based Spatial Clustering of Applications with Noise) descobre clusters baseado em DENSIDADE de pontos, não em distância a centros. Vantagens sobre KMeans: (1) NÃO precisa definir N de clusters; (2) descobre clusters de formato ARBITRÁRIO (não só esféricos); (3) identifica OUTLIERS como ruído (label -1). Parâmetros: eps (raio de vizinhança) e min_samples (mínimo de pontos para formar cluster denso). Ideal para detecção de anomalias e clusters irregulares. Desvantagem: difícil em dados de alta dimensionalidade (a noção de densidade se degrada).",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Clusters densos descobertos.",
      solution: "from sklearn.cluster import DBSCAN\ndbs = DBSCAN()\ndbs.fit(X)\nprint('DBSCAN ok.')",
    },
    {
      id: "ds-ml-30",
      worldId: "laboratorio-neural",
      title: "PCA",
      description: "Importe PCA, crie 'pca' com n_components=2 e use fit_transform(X). Imprima 'PCA aplicado.'.",
      narrative: "Reduza dimensionalidade preservando o máximo de variância.",
      difficulty: "avancado",
      setupCode: "class PCA:\n    def __init__(self, n_components): self.n = n_components\n    def fit_transform(self, X): print('PCA aplicado.'); return X\nX = [[1,2,3],[4,5,6]]",
      expectedOutput: "PCA aplicado.",
      testCode: "assert 'PCA' in code and 'n_components' in code",
      starterCode: "from sklearn.decomposition import PCA\n# pca com n_components=2\n",
      hints: [
        { text: "PCA está em sklearn.decomposition. n_components define dimensões resultantes.", cost: 30 },
        { text: "fit_transform reduz dimensionalidade ENCONTRANDO direções de maior variância.", cost: 35 },
        { text: "pca = PCA(n_components=2)\\npca.fit_transform(X)\\nprint('PCA aplicado.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "PCA (Análise de Componentes Principais)",
      conceptExplanation: "PCA reduz dimensionalidade encontrando direções (componentes principais) que capturam MAIS VARIÂNCIA dos dados. Use para: (1) visualização — reduzir de 100 features para 2-3 e plotar; (2) acelerar treinos — menos features = mais rápido; (3) combater 'curse of dimensionality'; (4) remover ruído (componentes menos relevantes geralmente são ruído). pca.explained_variance_ratio_ mostra quanto da variância cada componente preserva — escolha N até atingir 80-95% acumulado. ATENÇÃO: sempre StandardScaler antes — PCA é sensível a escala. Para redução não-linear: t-SNE, UMAP.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Dimensionalidade reduzida com variância preservada.",
      solution: "from sklearn.decomposition import PCA\npca = PCA(n_components=2)\npca.fit_transform(X)\nprint('PCA aplicado.')",
    },
  ],
};
