import { World } from "../types";

export const LABORATORIO_NEURAL_WORLD: World = {
  id: "laboratorio-neural",
  title: "Laboratório Neural",
  subtitle: "Machine Learning",
  icon: "brain",
  color: "#F472B6",
  bgImage: "/assets/images/worlds/neural_lab.png",
  lore: "Treine modelos preditivos. Regressão, classificação e clustering — ensine máquinas a tomar decisões a partir de dados históricos.",
  unlockRequirement: 18000,
  challenges: [
    {
      id: "ds-ml-01",
      worldId: "laboratorio-neural",
      title: "Treinamento Supervisionado",
      description: "Importe LinearRegression. Crie a instância 'modelo' e treine com modelo.fit(X, y).",
      narrative: "Precisamos prever o próximo ataque da CorpHQ. Inicialize um modelo de regressão linear para encontrar a correlação entre dias e intensidade dos ataques.",
      difficulty: "intermediario",
      setupCode: "class LinearRegression:\n    def fit(self, X, y):\n        print('Modelo treinado com sucesso.')\nX = [[1], [2], [3]]\ny = [10, 20, 30]",
      expectedOutput: "Modelo treinado com sucesso.",
      testCode: "assert 'LinearRegression' in code and 'fit' in code",
      starterCode: "from sklearn.linear_model import LinearRegression\n# Crie a instância 'modelo' e chame modelo.fit(X, y)\n",
      hints: [
        { text: "Em scikit-learn, cada algoritmo é uma classe. Você importa a classe, cria uma instância (com parênteses) e depois treina com .fit().", cost: 20 },
        { text: ".fit(X, y) recebe DOIS argumentos: X são as features (entradas, sempre 2D — lista de listas) e y são as respostas esperadas (1D).", cost: 25 },
        { text: "modelo = LinearRegression()\\nmodelo.fit(X, y)", cost: 30 },
      ],
      xpReward: 700,
      concept: "Scikit-Learn e a API de Modelos",
      conceptExplanation: "Scikit-learn é a biblioteca padrão de Machine Learning clássico em Python — quase todos os algoritmos não-Deep-Learning estão lá: regressões, árvores, florestas, SVMs, KNN, clustering, PCA. A genialidade dela é a API UNIFORME: todo modelo, qualquer que seja, segue o mesmo padrão: (1) você cria uma instância com algoritmo = Classe(parâmetros); (2) treina com algoritmo.fit(X, y); (3) faz previsões com algoritmo.predict(X_novo). LinearRegression é o algoritmo mais simples — encontra a melhor reta (ou hiperplano em mais dimensões) que descreve a relação entre X (features) e y (alvo numérico contínuo). É a base de toda intuição sobre ML supervisionado: o modelo 'aprende' os parâmetros que minimizam o erro entre previsões e respostas reais durante o fit. X deve ser SEMPRE 2D (lista de listas) — sklearn espera múltiplas features mesmo quando você tem só uma.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo ajustado à curva de probabilidade. Previsões online.",
      solution: "from sklearn.linear_model import LinearRegression\nmodelo = LinearRegression()\nmodelo.fit(X, y)",
    },
    {
      id: "ds-ml-02",
      worldId: "laboratorio-neural",
      title: "Divisão Treino/Teste",
      description: "Use train_test_split para separar X e y em treino e teste (20% para teste). Depois imprima 'Split realizado.'.",
      narrative: "Antes de treinar, você deve reservar 20% dos dados para validar o modelo. Caso contrário, ele apenas memoriza.",
      difficulty: "intermediario",
      setupCode: "def train_test_split(X, y, test_size=0.2):\n    return X[:8], X[8:], y[:8], y[8:]\nX = list(range(10))\ny = list(range(10))",
      expectedOutput: "Split realizado.",
      testCode: "assert 'train_test_split' in code and 'test_size' in code",
      starterCode: "from sklearn.model_selection import train_test_split\n# Divida em treino/teste e imprima 'Split realizado.'\n",
      hints: [
        { text: "train_test_split retorna QUATRO valores na ordem: X_train, X_test, y_train, y_test. Desempacote todos na atribuição com vírgulas.", cost: 20 },
        { text: "Passe test_size=0.2 (ou outra fração) para definir quantos por cento ficam no teste. 0.2 = 20% teste, 80% treino.", cost: 25 },
        { text: "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\\nprint('Split realizado.')", cost: 30 },
      ],
      xpReward: 750,
      concept: "Train/Test Split e Generalização",
      conceptExplanation: "Separar dados em treino e teste é a regra MAIS IMPORTANTE de Machine Learning — sem isso, você não tem como saber se o modelo está realmente aprendendo padrões generalizáveis ou apenas memorizando exemplos (esse problema se chama OVERFITTING). A função train_test_split embaralha os dados e os separa em duas partes: o conjunto de treino é usado no .fit() para o modelo aprender; o conjunto de teste é usado DEPOIS para avaliar o desempenho em dados que o modelo NUNCA viu — só assim a métrica é honesta. Tipicamente reserva-se 20-30% para teste. Parâmetros úteis: random_state=42 (ou qualquer número) torna a divisão reproduzível entre execuções; stratify=y mantém a proporção de classes em ambos os conjuntos (importante em classificação com classes desbalanceadas). Para validações mais robustas, existe o cross-validation (cross_val_score), que faz múltiplas divisões.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Conjunto de validação isolado. Treinamento sem vazamento de dados.",
      solution: "from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)\nprint('Split realizado.')",
    },
    {
      id: "ds-ml-03",
      worldId: "laboratorio-neural",
      title: "Previsões com .predict()",
      description: "Use modelo.predict([[4]]) para gerar uma previsão e imprima o resultado.",
      narrative: "O modelo está treinado. Agora faça uma previsão: dado o dia 4, quantos ataques são esperados?",
      difficulty: "intermediario",
      setupCode: "class Modelo:\n    def predict(self, X):\n        return [v[0] * 10 for v in X]\nmodelo = Modelo()",
      expectedOutput: "[40]",
      testCode: "assert 'modelo.predict' in code",
      starterCode: "# Chame modelo.predict([[4]]) e imprima o retorno\n",
      hints: [
        { text: "Após o fit, o modelo já consegue prever. Use modelo.predict(X_novo) — o formato de X_novo precisa ser o MESMO usado no treino.", cost: 20 },
        { text: "Mesmo para um único exemplo, envolva em lista de listas (2D): predict([[4]]), não predict(4) nem predict([4]). O retorno é um array com as previsões.", cost: 25 },
        { text: "print(modelo.predict([[4]]))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Inferência (Predição)",
      conceptExplanation: "Após o treino, a fase de 'inferência' (também chamada de 'predição' ou 'scoring') é quando você efetivamente USA o modelo — aplica ele a dados novos para tomar decisões. O método .predict() recebe dados no MESMO formato que o X de treino, sempre 2D, mesmo para um único exemplo (essa é a pegadinha mais comum para iniciantes). Para problemas de regressão, predict retorna números contínuos (valores previstos). Para classificação, retorna rótulos de classe (0, 1, 2 ou 'spam', 'ham'). Modelos de classificação também têm o método .predict_proba(), que retorna a probabilidade estimada de cada classe — útil quando você quer não apenas a resposta mas a CONFIANÇA do modelo, ou quando precisa ajustar o limiar de decisão. Em produção, .predict() é a função chamada milhões de vezes — frequentemente é o gargalo de performance que motiva otimizações.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Previsão entregue. 40 ataques esperados no dia 4 — equipe de defesa em alerta.",
      solution: "print(modelo.predict([[4]]))",
    },
    {
      id: "ds-ml-04",
      worldId: "laboratorio-neural",
      title: "Avaliação com .score()",
      description: "Chame modelo.score(X_test, y_test) e imprima. Quanto mais próximo de 1.0, melhor o modelo.",
      narrative: "Para validar o modelo antes do deploy em produção, calcule sua acurácia no conjunto de teste.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def score(self, X, y):\n        return 0.95\nmodelo = Modelo()\nX_test = [[1], [2]]\ny_test = [10, 20]",
      expectedOutput: "0.95",
      testCode: "assert 'modelo.score' in code",
      starterCode: "# Imprima o score do modelo nos dados de teste\n",
      hints: [
        { text: "Todo modelo sklearn tem o método .score(X, y) que retorna uma métrica padrão de qualidade. Sempre passe os dados de TESTE — não os de treino.", cost: 20 },
        { text: "O retorno é um único número. Para regressão é R² (entre -∞ e 1, quanto maior melhor); para classificação é acurácia (entre 0 e 1).", cost: 25 },
        { text: "print(modelo.score(X_test, y_test))", cost: 30 },
      ],
      xpReward: 850,
      concept: "Métricas de Avaliação de Modelos",
      conceptExplanation: "Após treinar um modelo, você precisa medir sua qualidade — e essa medida DEVE ser feita no conjunto de TESTE, não no de treino (caso contrário você está medindo memorização, não capacidade de generalizar). O método .score() retorna uma métrica padrão dependendo do tipo de modelo: para regressão, R² (coeficiente de determinação, varia de -infinito a 1, sendo 1 = previsão perfeita, 0 = igual à média, negativo = pior que prever a média); para classificação, acurácia (proporção de previsões corretas, entre 0 e 1). Para análises mais profundas, o módulo sklearn.metrics oferece dezenas de outras: precision e recall (essenciais quando classes são desbalanceadas), F1-score (harmônica entre precision e recall), MSE/MAE/RMSE (erros em regressão), confusion_matrix (matriz de acertos/erros por classe), roc_auc_score. ATENÇÃO: acurácia sozinha engana em datasets desbalanceados — em um problema onde 95% dos casos são da classe 'normal', um modelo que sempre prevê 'normal' tem 95% de acurácia mas é completamente inútil.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Acurácia de 95% confirmada. Deploy aprovado pela equipe de QA.",
      solution: "print(modelo.score(X_test, y_test))",
    },
    {
      id: "ds-ml-05",
      worldId: "laboratorio-neural",
      title: "Clustering com KMeans",
      description: "Crie kmeans = KMeans(n_clusters=3), treine com .fit(X) e imprima 'Clusters formados.'.",
      narrative: "Sem rótulos? Use aprendizado não-supervisionado. Agrupe os IPs em 3 clusters por comportamento.",
      difficulty: "avancado",
      setupCode: "class KMeans:\n    def __init__(self, n_clusters):\n        self.n = n_clusters\n    def fit(self, X):\n        print('Clusters formados.')\nX = [[1, 2], [1, 4], [10, 8]]",
      expectedOutput: "Clusters formados.",
      testCode: "assert 'KMeans' in code and 'n_clusters' in code and 'fit' in code",
      starterCode: "from sklearn.cluster import KMeans\n# Crie KMeans com 3 clusters, treine e confirme\n",
      hints: [
        { text: "Em clustering, você NÃO tem y (rótulos). Passe apenas X para o fit. O algoritmo descobre os grupos sozinho.", cost: 20 },
        { text: "O parâmetro n_clusters define quantos grupos você quer encontrar — é uma decisão SUA, baseada no problema. KMeans(n_clusters=3).", cost: 25 },
        { text: "kmeans = KMeans(n_clusters=3)\\nkmeans.fit(X)\\nprint('Clusters formados.')", cost: 30 },
      ],
      xpReward: 900,
      concept: "Aprendizado Não-Supervisionado e Clustering",
      conceptExplanation: "Até agora você viu aprendizado SUPERVISIONADO — você tem X (features) e y (respostas corretas), e o modelo aprende a mapear X em y. Clustering é APRENDIZADO NÃO-SUPERVISIONADO: você tem apenas X, sem rótulos nenhum, e o algoritmo descobre estrutura sozinho — identifica quais pontos são parecidos e os agrupa. KMeans é o algoritmo mais clássico de clustering: dado K (número de clusters, escolhido por você), ele encontra K 'centros' no espaço de features e atribui cada ponto ao centro mais próximo, depois ajusta os centros para a média dos pontos atribuídos, e itera até convergir. Aplicações reais: segmentação de clientes em marketing, agrupamento de documentos por tópico, compressão de imagens, descoberta exploratória de padrões em dados não rotulados, detecção de anomalias (pontos longe de qualquer cluster). Após o fit, kmeans.labels_ tem o rótulo de cluster de cada ponto e kmeans.cluster_centers_ tem as coordenadas dos centros. Para escolher K, use o 'método do cotovelo' (plotando inércia vs K) ou silhouette score.",
      successNpc: "Mente Sintética",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Três perfis de atacante identificados. Estratégias defensivas customizadas em deploy.",
      solution: "from sklearn.cluster import KMeans\nkmeans = KMeans(n_clusters=3)\nkmeans.fit(X)\nprint('Clusters formados.')",
    },
  ],
};
