import { World } from "../types";

export const MONTANHA_LOOPS_WORLD: World = {
  id: "montanha-loops",
  title: "Setor de Iteração",
  subtitle: "Ciclos de Processamento Infinito",
  icon: "refresh-cw",
  color: "#F97316",
  bgImage: "/assets/images/worlds/loops.png",
  lore: "No Setor de Iteração, o tempo é medido em ciclos de CPU. Aqui, você deve aprender a dominar os Loops de Processamento para executar tarefas repetitivas em escala massiva com um único script.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-loop-01",
      worldId: "montanha-loops",
      title: "Varredura de Sequência",
      description: "Use o comando for e a função range() para imprimir os números de 0 a 4.",
      narrative: "O scanner de rede precisa realizar uma varredura em cinco portas consecutivas. Automatize a verificação usando um loop 'for' para não precisar digitar cada comando manualmente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "0\n1\n2\n3\n4",
      testCode: "assert output.strip() == '0\\n1\\n2\\n3\\n4'",
      starterCode: "# Inicie o loop com for e range(5)\n",
      hints: [
        { text: "A função range(5) cria uma sequência que vai de 0 até 4.", cost: 10 },
        { text: "O comando print(i) deve estar indentado dentro do loop for.", cost: 20 },
        { text: "for i in range(5):\n    print(i)", cost: 30 },
      ],
      xpReward: 300,
      concept: "Loop de Repetição 'for'",
      conceptExplanation: "O loop 'for' permite que você execute o mesmo bloco de código várias vezes. É como dar uma ordem repetitiva para o computador: 'Para cada item nesta lista, faça isso'.\n\nExemplo:\nfor i in range(3):\n    print('Repetindo...')\n\nIsso mostrará a frase 3 vezes.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Varredura concluída. O loop de processamento estabilizou as portas de entrada do setor.",
      solution: "for i in range(5):\n    print(i)",
    },
    {
      id: "py-loop-02",
      worldId: "montanha-loops",
      title: "Contagem Regressiva de Segurança",
      description: "Use um loop for e range() para imprimir uma contagem regressiva de 5 até 1.",
      narrative: "O sistema de autodestruição foi ativado por engano. Você deve sincronizar o cronômetro de cancelamento emitindo os sinais de 5 a 1 em ordem decrescente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "5\n4\n3\n2\n1",
      testCode: "assert output.strip() == '5\\n4\\n3\\n2\\n1'",
      starterCode: "# Use range(inicio, fim, passo) para a contagem\n",
      hints: [
        { text: "A função range(5, 0, -1) começa em 5, vai até o 0 (não incluso) e subtrai 1 a cada passo.", cost: 10 },
        { text: "for i in range(5, 0, -1):", cost: 20 },
      ],
      xpReward: 350,
      concept: "Range com Passo Negativo",
      conceptExplanation: "A função `range()` é muito flexível. Se você passar três números, o último é o 'passo'. Se usar -1, o Python contará de trás para frente!",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cronômetro sincronizado. O protocolo de autodestruição foi abortado com sucesso.",
      solution: "for i in range(5, 0, -1):\n    print(i)",
    },
    {
      id: "py-loop-03",
      worldId: "montanha-loops",
      title: "Acumulador de Dados",
      description: "Dada a lista 'cargas', use um loop for para calcular a soma total dos valores e imprima o resultado.",
      narrative: "Diversos pacotes de dados chegaram fragmentados. Você deve percorrer todos eles, somando suas cargas úteis para reconstruir o arquivo original.",
      difficulty: "intermediario",
      setupCode: "cargas = [10, 20, 30, 40]",
      expectedOutput: "100",
      testCode: "assert 'for ' in code and output.strip() == '100'",
      starterCode: "cargas = [10, 20, 30, 40]\ntotal = 0\n# Some as cargas usando um loop\n",
      hints: [
        { text: "Crie uma variável total iniciando em 0 e vá somando cada carga nela dentro do loop.", cost: 10 },
        { text: "for c in cargas:\n    total = total + c", cost: 20 },
      ],
      xpReward: 380,
      concept: "Acumuladores",
      conceptExplanation: "Um padrão muito comum na programação é o 'acumulador'. Você cria uma variável fora do loop e, a cada volta do loop, adiciona algo novo nela.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Soma concluída. O arquivo de 100 bytes foi reconstruído e está pronto para análise.",
      solution: "total = 0\nfor c in cargas:\n    total += c\nprint(total)",
    },
    {
      id: "py-loop-04",
      worldId: "montanha-loops",
      title: "Loop de Manutenção 'while'",
      description: "Use um loop while para imprimir o valor de 'tentativas' enquanto ele for maior que 0. Diminua 1 a cada volta.",
      narrative: "O sistema de força bruta está tentando quebrar uma criptografia. Execute o loop de tentativas até que os recursos se esgotem.",
      difficulty: "intermediario",
      setupCode: "tentativas = 3",
      expectedOutput: "3\n2\n1",
      testCode: "assert 'while' in code and output.strip() == '3\\n2\\n1'",
      starterCode: "tentativas = 3\n# Use while para repetir enquanto tentativas > 0\n",
      hints: [
        { text: "O while continua repetindo enquanto a condição for verdadeira.", cost: 10 },
        { text: "Não esqueça de diminuir o valor: tentativas = tentativas - 1", cost: 20 },
        { text: "while tentativas > 0:\n    print(tentativas)\n    tentativas -= 1", cost: 30 },
      ],
      xpReward: 400,
      concept: "Loop Condicional 'while'",
      conceptExplanation: "O `while` (enquanto) é usado quando você não sabe exatamente quantas vezes algo vai repetir, mas sabe a condição que deve ser mantida para ele continuar rodando.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Criptografia quebrada no último ciclo. O acesso ao setor foi mantido.",
      solution: "while tentativas > 0:\n    print(tentativas)\n    tentativas -= 1",
    },
    {
      id: "py-loop-05",
      worldId: "montanha-loops",
      title: "Scanner de Intrusos",
      description: "Percorra a lista 'ips' e imprima cada um. Se encontrar '192.168.1.100', imprima 'ALERTA' e pare o loop com break.",
      narrative: "Um endereço IP suspeito foi detectado na rede. Varra a lista de conexões ativas e interrompa o processo assim que o intruso for localizado.",
      difficulty: "intermediario",
      setupCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']",
      expectedOutput: "192.168.1.1\n10.0.0.5\n192.168.1.100\nALERTA",
      testCode: "assert 'break' in code and 'ALERTA' in output",
      starterCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']\n# Percorra e use break ao achar o intruso\n",
      hints: [
        { text: "Use if dentro do for para verificar o IP.", cost: 10 },
        { text: "O comando break encerra o loop imediatamente.", cost: 20 },
      ],
      xpReward: 450,
      concept: "Interrupção de Loops (break)",
      conceptExplanation: "O `break` é um botão de emergência. Ele serve para parar um loop instantaneamente, mesmo que ele ainda tivesse mais voltas para dar.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Intruso localizado e isolado. O scanner foi interrompido para economizar recursos de defesa.",
      solution: "for ip in ips:\n    print(ip)\n    if ip == '192.168.1.100':\n        print('ALERTA')\n        break",
    },
    {
      id: "py-loop-06",
      worldId: "montanha-loops",
      title: "Filtro de Pacotes Vazios",
      description: "Percorra a lista 'dados'. Se o valor for 0, use continue para pular. Caso contrário, imprima o valor.",
      narrative: "A rede está cheia de pacotes vazios (ruído). Otimize seu processamento ignorando todos os valores zero e processando apenas os dados reais.",
      difficulty: "intermediario",
      setupCode: "dados = [10, 0, 50, 0, 30]",
      expectedOutput: "10\n50\n30",
      testCode: "assert 'continue' in code and '0' not in output",
      starterCode: "dados = [10, 0, 50, 0, 30]\n# Pule os zeros usando continue\n",
      hints: [
        { text: "O comando continue pula para a próxima volta do loop sem executar o que vem abaixo dele.", cost: 10 },
        { text: "if valor == 0:\n    continue", cost: 20 },
      ],
      xpReward: 480,
      concept: "Pular Iterações (continue)",
      conceptExplanation: "O `continue` serve para dizer ao loop: 'Pule essa volta e vá direto para a próxima'. É ótimo para ignorar dados inválidos ou desnecessários.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Ruído filtrado. Apenas dados úteis foram processados, economizando 40% de banda de rede.",
      solution: "for d in dados:\n    if d == 0:\n        continue\n    print(d)",
    },
    {
      id: "py-loop-07",
      worldId: "montanha-loops",
      title: "Iteração Direta de Coleção",
      description: "Dada a lista 'usuarios', use um loop for para imprimir cada nome (um por linha), sem usar range().",
      narrative: "O sistema de auditoria precisa logar cada usuário ativo. Itere diretamente sobre a coleção, sem se preocupar com índices numéricos.",
      difficulty: "intermediario",
      setupCode: "usuarios = ['Neo', 'Trinity', 'Morpheus']",
      expectedOutput: "Neo\nTrinity\nMorpheus",
      testCode: "assert 'for' in code and 'range' not in code and output.strip() == 'Neo\\nTrinity\\nMorpheus'",
      starterCode: "usuarios = ['Neo', 'Trinity', 'Morpheus']\n# Itere diretamente, sem range()\n",
      hints: [
        { text: "Você pode escrever 'for nome in usuarios:' diretamente.", cost: 10 },
        { text: "for u in usuarios:\n    print(u)", cost: 20 },
      ],
      xpReward: 500,
      concept: "Iteração Direta",
      conceptExplanation: "O for em Python aceita qualquer 'coisa iterável': listas, strings, ranges, dicionários... Você não precisa de índices na maior parte dos casos.\n\nIsso deixa o código mais limpo e expressivo. Use range() apenas quando o índice for realmente necessário.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Auditoria registrada. Cada operador foi catalogado no log mestre.",
      solution: "for u in usuarios:\n    print(u)",
    },
    {
      id: "py-loop-08",
      worldId: "montanha-loops",
      title: "Indexador Sincronizado",
      description: "Use enumerate() para imprimir 'indice: valor' para cada item da lista 'modulos'. Exemplo: '0: AUTH'.",
      narrative: "O carregador de módulos precisa de um relatório com a posição e o nome de cada componente. Sincronize índice e valor em uma única passagem do loop.",
      difficulty: "intermediario",
      setupCode: "modulos = ['AUTH', 'NET', 'DB']",
      expectedOutput: "0: AUTH\n1: NET\n2: DB",
      testCode: "assert 'enumerate' in code and output.strip() == '0: AUTH\\n1: NET\\n2: DB'",
      starterCode: "modulos = ['AUTH', 'NET', 'DB']\n# Use enumerate() no for\n",
      hints: [
        { text: "for i, valor in enumerate(lista): te entrega índice e valor ao mesmo tempo.", cost: 15 },
        { text: "Use f-string para formatar: f'{i}: {valor}'", cost: 25 },
      ],
      xpReward: 550,
      concept: "Função enumerate()",
      conceptExplanation: "Quando você precisa do índice E do valor durante a iteração, use enumerate(). Ela 'embrulha' a lista e devolve pares (índice, item) a cada volta.\n\nÉ a forma idiomática em Python de fazer iteração com índice — evite o anti-padrão 'for i in range(len(lista))'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Relatório emitido. O carregador conhece a posição exata de cada componente do sistema.",
      solution: "for i, m in enumerate(modulos):\n    print(f'{i}: {m}')",
    },
    {
      id: "py-loop-09",
      worldId: "montanha-loops",
      title: "Varredura de Matriz",
      description: "Dada a matriz 'grid' (lista de listas), use loops aninhados para imprimir cada número (um por linha).",
      narrative: "O scanner precisa percorrer cada célula da grade de segurança 2x2. Use um loop dentro do outro para cobrir cada linha e cada coluna sem deixar nenhum ponto cego.",
      difficulty: "avancado",
      setupCode: "grid = [[1, 2], [3, 4]]",
      expectedOutput: "1\n2\n3\n4",
      testCode: "assert code.count('for ') >= 2 and output.strip() == '1\\n2\\n3\\n4'",
      starterCode: "grid = [[1, 2], [3, 4]]\n# Use dois fors aninhados\n",
      hints: [
        { text: "O for externo percorre as linhas (sublistas). O for interno percorre os valores de cada linha.", cost: 15 },
        { text: "for linha in grid:\n    for valor in linha:\n        print(valor)", cost: 30 },
      ],
      xpReward: 600,
      concept: "Loops Aninhados",
      conceptExplanation: "Você pode colocar um for dentro de outro for. O loop interno é executado por completo a cada volta do externo.\n\nÉ a forma natural de varrer estruturas 2D (matrizes, grids, tabuleiros). Cuidado: cada nível adicional multiplica o tempo de execução do programa.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Grade varrida em sua totalidade. Nenhuma célula da matriz escapou ao scanner.",
      solution: "for linha in grid:\n    for valor in linha:\n        print(valor)",
    },
    {
      id: "py-loop-10",
      worldId: "montanha-loops",
      title: "Sistema de Vigilância",
      description: "Use 'while True' com break. A cada ciclo, imprima 'energia' e diminua 25. Quando 'energia' for menor que 25, encerre o loop com break.",
      narrative: "O sistema de vigilância roda em loop contínuo até que a bateria entre em modo crítico. Implemente o ciclo infinito com saída controlada por uma condição interna.",
      difficulty: "avancado",
      setupCode: "energia = 100",
      expectedOutput: "100\n75\n50\n25",
      testCode: "assert 'while True' in code and 'break' in code and output.strip() == '100\\n75\\n50\\n25'",
      starterCode: "energia = 100\n# while True com break quando energia < 25\n",
      hints: [
        { text: "while True: cria um loop infinito. O break é a única saída.", cost: 15 },
        { text: "Imprima primeiro, depois decremente, depois teste a condição de break.", cost: 25 },
        { text: "while True:\n    print(energia)\n    energia -= 25\n    if energia < 25:\n        break", cost: 35 },
      ],
      xpReward: 650,
      concept: "Loop Infinito Controlado",
      conceptExplanation: "Às vezes você não sabe a condição de parada antecipadamente — talvez ela dependa de um evento, de uma entrada externa ou de um cálculo interno.\n\n'while True' cria um ciclo eterno que só termina quando um break é executado. É um padrão comum em sistemas de monitoramento, servidores e jogos.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Bateria em estado crítico. O sistema entrou em hibernação preservando os dados coletados.",
      solution: "while True:\n    print(energia)\n    energia -= 25\n    if energia < 25:\n        break",
    },
    {
      id: "py-loop-11",
      worldId: "montanha-loops",
      title: "Decifrador de Caracteres",
      description: "Itere sobre cada caractere da string 'token' e imprima-o (um por linha).",
      narrative: "Um token criptografado chegou ao buffer. Disseque cada caractere para análise individual antes de tentar o ataque de dicionário.",
      difficulty: "avancado",
      setupCode: "token = 'X1Y2'",
      expectedOutput: "X\n1\nY\n2",
      testCode: "assert 'for' in code and output.strip() == 'X\\n1\\nY\\n2'",
      starterCode: "token = 'X1Y2'\n# Itere sobre a string\n",
      hints: [
        { text: "Strings também são iteráveis em Python. Você pode usar 'for letra in string:'.", cost: 10 },
        { text: "for c in token:\n    print(c)", cost: 20 },
      ],
      xpReward: 700,
      concept: "Iteração sobre Strings",
      conceptExplanation: "Em Python, strings se comportam como sequências de caracteres. Isso significa que você pode iterar sobre elas com for, fazer slicing, usar len() e o operador 'in' — tudo igual a uma lista.\n\nIsso unifica a forma como você trabalha com texto e coleções.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Token desmontado caractere a caractere. A análise de dicionário pode começar.",
      solution: "for c in token:\n    print(c)",
    },
    {
      id: "py-loop-12",
      worldId: "montanha-loops",
      title: "Catalogador Seletivo",
      description: "Dada a lista 'valores', use um loop for combinado com if para contar quantos números são pares. Imprima a contagem final.",
      narrative: "O coletor precisa rastrear apenas os pacotes com identificador par. Conte quantos passam pelo filtro durante a varredura completa.",
      difficulty: "avancado",
      setupCode: "valores = [3, 8, 12, 7, 22, 5, 4]",
      expectedOutput: "4",
      testCode: "assert 'for' in code and '%' in code and output.strip() == '4'",
      starterCode: "valores = [3, 8, 12, 7, 22, 5, 4]\ncontador = 0\n# Conte os pares e imprima 'contador'\n",
      hints: [
        { text: "Use 'if v % 2 == 0:' dentro do loop para identificar pares.", cost: 15 },
        { text: "Some 1 ao contador a cada par encontrado.", cost: 25 },
      ],
      xpReward: 750,
      concept: "Contagem Condicional",
      conceptExplanation: "Combinar loop + condicional + acumulador é um dos padrões mais usados em programação. Você itera sobre os dados, testa cada item e atualiza um contador (ou outra estrutura) com base no resultado.\n\nÉ a base de filtros, busca, validação e geração de relatórios.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Quatro pacotes pares confirmados. O catálogo do coletor foi atualizado.",
      solution: "contador = 0\nfor v in valores:\n    if v % 2 == 0:\n        contador += 1\nprint(contador)",
    },
    {
      id: "py-loop-13",
      worldId: "montanha-loops",
      title: "Sincronizador de Streams",
      description: "Use zip() para iterar sobre as listas 'ips' e 'portas' em paralelo, imprimindo 'ip:porta' em cada linha.",
      narrative: "Dois streams de dados chegaram em paralelo: a lista de IPs e a lista de portas correspondentes. Sincronize-os par a par para montar os endpoints completos.",
      difficulty: "epico",
      setupCode: "ips = ['10.0.0.1', '10.0.0.2', '10.0.0.3']\nportas = [80, 443, 22]",
      expectedOutput: "10.0.0.1:80\n10.0.0.2:443\n10.0.0.3:22",
      testCode: "assert 'zip' in code and output.strip() == '10.0.0.1:80\\n10.0.0.2:443\\n10.0.0.3:22'",
      starterCode: "ips = ['10.0.0.1', '10.0.0.2', '10.0.0.3']\nportas = [80, 443, 22]\n# Use zip() para iterar nas duas em paralelo\n",
      hints: [
        { text: "for ip, p in zip(ips, portas): te entrega um par a cada volta.", cost: 20 },
        { text: "Use f-string: f'{ip}:{p}'", cost: 30 },
      ],
      xpReward: 850,
      concept: "Função zip()",
      conceptExplanation: "zip() recebe duas (ou mais) sequências e devolve pares (tuplas) sincronizados — o primeiro item de cada, depois o segundo, e assim por diante.\n\nSe as listas tiverem tamanhos diferentes, zip() para no menor. É a ferramenta padrão para iterar em paralelo sem precisar gerenciar índices manualmente.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Streams alinhados. Os endpoints completos foram montados sem perda de pacotes.",
      solution: "for ip, p in zip(ips, portas):\n    print(f'{ip}:{p}')",
    },
    {
      id: "py-loop-14",
      worldId: "montanha-loops",
      title: "Compilador em Uma Linha",
      description: "Use list comprehension para criar 'quadrados' contendo o quadrado (n*n) de cada número da lista 'numeros'. Imprima a lista resultante.",
      narrative: "O processamento em massa exige que cada valor seja elevado ao quadrado. Compacte toda a operação em uma única linha de código de alta performance.",
      difficulty: "epico",
      setupCode: "numeros = [1, 2, 3, 4, 5]",
      expectedOutput: "[1, 4, 9, 16, 25]",
      testCode: "assert 'for' in code and quadrados == [1, 4, 9, 16, 25] and output.strip() == str(quadrados)",
      starterCode: "numeros = [1, 2, 3, 4, 5]\n# Use list comprehension para criar 'quadrados'\n",
      hints: [
        { text: "Sintaxe: [expressao for item in iteravel]", cost: 20 },
        { text: "quadrados = [n ** 2 for n in numeros]", cost: 30 },
      ],
      xpReward: 950,
      concept: "List Comprehension Avançada",
      conceptExplanation: "List comprehension é a forma mais idiomática de Python para criar listas a partir de iteráveis. Internamente é um loop, mas escrito em uma única expressão.\n\nSintaxe completa: [expressao for item in iteravel if condicao]\n\nÉ mais rápido que um for + append() tradicional e considerado mais 'pythônico'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Compilação massiva concluída em um único ciclo. O Setor de Iteração reconhece sua maestria sobre os ciclos de CPU.",
      solution: "quadrados = [n ** 2 for n in numeros]\nprint(quadrados)",
    },
    {
      id: "py-loop-15",
      worldId: "montanha-loops",
      title: "Range com Início e Fim",
      description: "Use range(2, 7) em um loop for para imprimir os números de 2 até 6 (cada um em uma linha).",
      narrative: "A varredura precisa começar na porta 2 e parar antes da 7. Configure o range com os limites corretos.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "2\n3\n4\n5\n6",
      testCode: "assert 'range(2' in code and output.strip() == '2\\n3\\n4\\n5\\n6'",
      starterCode: "# Use range(2, 7)\n",
      hints: [
        { text: "range(inicio, fim) inclui o início mas EXCLUI o fim.", cost: 10 },
        { text: "for i in range(2, 7):\n    print(i)", cost: 20 },
      ],
      xpReward: 800,
      concept: "range(inicio, fim)",
      conceptExplanation: "range() aceita 1, 2 ou 3 argumentos. Com 2: range(inicio, fim) — gera valores de 'inicio' até 'fim-1'. O fim sempre é exclusivo (similar a slicing). Use isso para faixas customizadas sem precisar ajustar manualmente os índices.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Faixa de portas escaneada. As 5 entradas intermediárias foram registradas.",
      solution: "for i in range(2, 7):\n    print(i)",
    },
    {
      id: "py-loop-16",
      worldId: "montanha-loops",
      title: "Salto Customizado",
      description: "Use range(0, 21, 5) para imprimir múltiplos de 5 entre 0 e 20 (inclusive).",
      narrative: "O sistema só processa endereços alinhados em blocos de 5. Configure o passo do iterador para saltar diretamente para o próximo bloco válido.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "0\n5\n10\n15\n20",
      testCode: "assert 'range(0, 21, 5)' in code.replace(' ', '') or 'range(0,21,5)' in code.replace(' ', '') and output.strip() == '0\\n5\\n10\\n15\\n20'",
      starterCode: "# Use range(0, 21, 5)\n",
      hints: [
        { text: "Sintaxe: range(inicio, fim, passo)", cost: 10 },
        { text: "for i in range(0, 21, 5):\n    print(i)", cost: 20 },
      ],
      xpReward: 820,
      concept: "range com Passo",
      conceptExplanation: "O terceiro argumento de range() é o 'step' — o quanto pular a cada iteração. Default = 1. Use passos maiores para varrer faixas espalhadas; passos negativos para contagem regressiva.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Blocos alinhados varridos. Cada endereço-base foi auditado sem perda de ciclos.",
      solution: "for i in range(0, 21, 5):\n    print(i)",
    },
    {
      id: "py-loop-17",
      worldId: "montanha-loops",
      title: "Reversão de Stream",
      description: "Dada a lista 'pilha', use reversed() em um loop for para imprimir cada item na ordem inversa (cada um em uma linha).",
      narrative: "A pilha de eventos chegou em ordem cronológica; processe-a do mais recente ao mais antigo para responder ao incidente mais novo primeiro.",
      difficulty: "intermediario",
      setupCode: "pilha = ['evt1', 'evt2', 'evt3']",
      expectedOutput: "evt3\nevt2\nevt1",
      testCode: "assert 'reversed' in code and output.strip() == 'evt3\\nevt2\\nevt1'",
      starterCode: "pilha = ['evt1', 'evt2', 'evt3']\n# for x in reversed(pilha):\n",
      hints: [
        { text: "reversed(iteravel) devolve um iterador na ordem reversa, sem criar nova lista.", cost: 10 },
        { text: "for ev in reversed(pilha):\n    print(ev)", cost: 20 },
      ],
      xpReward: 840,
      concept: "Função reversed()",
      conceptExplanation: "reversed() devolve um iterador percorrendo a coleção de trás para frente. Mais eficiente em memória que lista[::-1] (que copia tudo). Use diretamente em for ou converta com list(reversed(...)) se precisar de uma lista materializada.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Eventos processados em ordem inversa. A resposta priorizou o incidente mais recente.",
      solution: "pilha = ['evt1', 'evt2', 'evt3']\nfor ev in reversed(pilha):\n    print(ev)",
    },
    {
      id: "py-loop-18",
      worldId: "montanha-loops",
      title: "Cláusula else do for",
      description: "Itere sobre 'tentativas'. Se algum item for 'SUCESSO', imprima 'achei' e BREAK. Caso o loop termine SEM break, o bloco else deve imprimir 'fracasso'. Saída esperada: fracasso.",
      narrative: "Após varrer todas as tentativas sem encontrar sucesso, o sistema precisa registrar a falha total. Use o else do for para essa lógica final.",
      difficulty: "avancado",
      setupCode: "tentativas = ['x', 'y', 'z']",
      expectedOutput: "fracasso",
      testCode: "assert 'else:' in code and 'for' in code and 'break' in code and output.strip() == 'fracasso'",
      starterCode: "tentativas = ['x', 'y', 'z']\n# for ... if ... break / else: print('fracasso')\n",
      hints: [
        { text: "O else do for só roda se o loop terminou NATURALMENTE (sem break).", cost: 20 },
        { text: "for t in tentativas:\n    if t == 'SUCESSO':\n        print('achei')\n        break\nelse:\n    print('fracasso')", cost: 30 },
      ],
      xpReward: 900,
      concept: "for/else",
      conceptExplanation: "Pouco conhecido: o for em Python aceita uma cláusula 'else' que executa SE o loop terminou normalmente (sem break). Ideal para padrões de busca: 'achei algo? sim → break. Loop acabou sem break? → não achei, executa else'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Varredura completa sem hits. O sistema documentou a falha total para escalonamento.",
      solution: "tentativas = ['x', 'y', 'z']\nfor t in tentativas:\n    if t == 'SUCESSO':\n        print('achei')\n        break\nelse:\n    print('fracasso')",
    },
    {
      id: "py-loop-19",
      worldId: "montanha-loops",
      title: "While com else",
      description: "Inicie n=0. Use 'while n < 3: print(n) e n+=1'. Adicione else: print('feito'). Saída esperada: 0 / 1 / 2 / feito.",
      narrative: "Após o loop de retransmissão completar sem interrupção, marque o protocolo como bem-sucedido usando a cláusula else.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "0\n1\n2\nfeito",
      testCode: "assert 'while' in code and 'else:' in code and output.strip() == '0\\n1\\n2\\nfeito'",
      starterCode: "n = 0\n# while n < 3 ... else: print('feito')\n",
      hints: [
        { text: "Igual ao for/else: o else do while só roda se o loop terminou pela condição (não por break).", cost: 20 },
        { text: "n = 0\nwhile n < 3:\n    print(n)\n    n += 1\nelse:\n    print('feito')", cost: 30 },
      ],
      xpReward: 920,
      concept: "while/else",
      conceptExplanation: "O while também aceita else. Roda quando a condição vira False naturalmente (sem break). Usado em padrões de 'tentativas com retry': se esgotou todas sem sucesso, execute o else para registrar timeout/desistência.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Protocolo concluído sem interrupção. O sistema registrou o ciclo completo no log de auditoria.",
      solution: "n = 0\nwhile n < 3:\n    print(n)\n    n += 1\nelse:\n    print('feito')",
    },
    {
      id: "py-loop-20",
      worldId: "montanha-loops",
      title: "Varredura de Dicionário",
      description: "Dado 'sistema', use 'for chave in sistema:' para imprimir cada chave (uma por linha).",
      narrative: "O sistema de configuração armazena dados em pares. Liste apenas os nomes dos campos disponíveis para um catálogo rápido.",
      difficulty: "intermediario",
      setupCode: "sistema = {'os': 'linux', 'cpu': '8c', 'ram': '16g'}",
      expectedOutput: "os\ncpu\nram",
      testCode: "assert 'for' in code and 'in sistema' in code and output.strip() == 'os\\ncpu\\nram'",
      starterCode: "sistema = {'os': 'linux', 'cpu': '8c', 'ram': '16g'}\n# for chave in sistema: print(chave)\n",
      hints: [
        { text: "Iterar diretamente sobre um dict percorre suas chaves.", cost: 10 },
        { text: "for chave in sistema:\n    print(chave)", cost: 20 },
      ],
      xpReward: 850,
      concept: "Iteração em Dicionário",
      conceptExplanation: "Por padrão, iterar um dict com 'for x in d' percorre as CHAVES. Equivalente a 'for x in d.keys()'. Para iterar valores: 'for v in d.values()'. Para ambos: 'for k, v in d.items()'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Catálogo de campos emitido. A estrutura do sistema foi mapeada.",
      solution: "sistema = {'os': 'linux', 'cpu': '8c', 'ram': '16g'}\nfor chave in sistema:\n    print(chave)",
    },
    {
      id: "py-loop-21",
      worldId: "montanha-loops",
      title: "Iteração Sincronizada com .items()",
      description: "Dado 'config', use .items() para iterar e imprimir 'chave=valor' (formato exato) para cada par.",
      narrative: "Cada configuração precisa ser exportada no formato 'chave=valor' para o arquivo .env do servidor.",
      difficulty: "avancado",
      setupCode: "config = {'host': 'local', 'port': 8080, 'ssl': True}",
      expectedOutput: "host=local\nport=8080\nssl=True",
      testCode: "assert '.items()' in code and 'host=local' in output and 'port=8080' in output and 'ssl=True' in output",
      starterCode: "config = {'host': 'local', 'port': 8080, 'ssl': True}\n# for k, v in config.items(): print(f'{k}={v}')\n",
      hints: [
        { text: ".items() devolve pares (chave, valor) — desempacote em duas variáveis no for.", cost: 15 },
        { text: "for k, v in config.items():\n    print(f'{k}={v}')", cost: 25 },
      ],
      xpReward: 900,
      concept: "Iteração com items()",
      conceptExplanation: "dict.items() devolve uma view de tuplas (chave, valor) — a forma idiomática de iterar com os dois ao mesmo tempo. Internamente é mais eficiente que buscar o valor com d[k] dentro do loop.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Arquivo .env gerado. As configurações estão prontas para deploy.",
      solution: "config = {'host': 'local', 'port': 8080, 'ssl': True}\nfor k, v in config.items():\n    print(f'{k}={v}')",
    },
    {
      id: "py-loop-22",
      worldId: "montanha-loops",
      title: "List Comprehension com Filtro",
      description: "Dada 'valores', use list comprehension com if para criar 'pares' contendo apenas múltiplos de 2. Imprima a lista.",
      narrative: "Compacte um filtro de pares em uma única expressão. O pipeline de processamento exige máxima densidade.",
      difficulty: "avancado",
      setupCode: "valores = [1, 2, 3, 4, 5, 6, 7]",
      expectedOutput: "[2, 4, 6]",
      testCode: "assert 'for' in code and 'if' in code and pares == [2, 4, 6] and output.strip() == str(pares)",
      starterCode: "valores = [1, 2, 3, 4, 5, 6, 7]\n# pares = [v for v in valores if v % 2 == 0]\n",
      hints: [
        { text: "Sintaxe: [expr for item in iter if condicao]", cost: 15 },
        { text: "pares = [v for v in valores if v % 2 == 0]", cost: 25 },
      ],
      xpReward: 950,
      concept: "Comprehension com if",
      conceptExplanation: "O 'if' no final filtra quais itens entram. Combina filtragem e transformação em uma só expressão. É mais rápido que loop + append manual, e padrão da comunidade Python para datasets pequenos/médios.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Filtro denso aplicado. Apenas pares cruzaram o pipeline.",
      solution: "valores = [1, 2, 3, 4, 5, 6, 7]\npares = [v for v in valores if v % 2 == 0]\nprint(pares)",
    },
    {
      id: "py-loop-23",
      worldId: "montanha-loops",
      title: "Generator Expression em sum()",
      description: "Dada 'numeros', use uma generator expression DENTRO de sum() para somar APENAS os números maiores que 10. Imprima o resultado.",
      narrative: "Calcule o tráfego total ignorando os pacotes pequenos (que são apenas keep-alive). Use uma expressão geradora para evitar criar lista intermediária.",
      difficulty: "epico",
      setupCode: "numeros = [5, 15, 8, 20, 3, 25]",
      expectedOutput: "60",
      testCode: "assert 'sum(' in code and 'for' in code and 'if' in code and output.strip() == '60'",
      starterCode: "numeros = [5, 15, 8, 20, 3, 25]\n# total = sum(n for n in numeros if n > 10)\n",
      hints: [
        { text: "Generator expressions usam parênteses (em vez de colchetes) — mais leves em memória.", cost: 20 },
        { text: "print(sum(n for n in numeros if n > 10))", cost: 30 },
      ],
      xpReward: 1050,
      concept: "Generator Expression",
      conceptExplanation: "Uma generator expression é como list comprehension mas com parênteses: '(expr for x in it)'. Não cria lista — gera valores um a um, sob demanda. Dentro de funções como sum(), max(), any(), all(), é mais eficiente que criar uma lista intermediária.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cálculo otimizado em streaming. Nenhuma memória foi desperdiçada com lista temporária.",
      solution: "numeros = [5, 15, 8, 20, 3, 25]\nprint(sum(n for n in numeros if n > 10))",
    },
    {
      id: "py-loop-24",
      worldId: "montanha-loops",
      title: "Multiplicação Acumulada (Fatorial)",
      description: "Calcule o fatorial de 6 (6 * 5 * 4 * 3 * 2 * 1) usando um for. Acumule em 'resultado' iniciado em 1. Imprima o resultado final.",
      narrative: "O algoritmo de criptografia exige uma chave fatorial. Use multiplicação acumulada para gerar a constante.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "720",
      testCode: "assert 'for' in code and ('*=' in code or 'resultado * ' in code) and output.strip() == '720'",
      starterCode: "resultado = 1\n# Use for i in range(1, 7): resultado *= i\n",
      hints: [
        { text: "Inicie resultado=1 (não 0, senão multiplicação anula tudo).", cost: 15 },
        { text: "for i in range(1, 7):\n    resultado *= i", cost: 25 },
      ],
      xpReward: 1000,
      concept: "Acumulador Multiplicativo",
      conceptExplanation: "Acumuladores não precisam ser sempre de soma. Para multiplicação: inicie em 1 (elemento neutro da multiplicação) e use *=. Para concatenação de strings: inicie com ''. O padrão é o mesmo — adapte o operador e o valor inicial.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Chave fatorial 720 gerada. O motor de criptografia está pronto para o handshake.",
      solution: "resultado = 1\nfor i in range(1, 7):\n    resultado *= i\nprint(resultado)",
    },
    {
      id: "py-loop-25",
      worldId: "montanha-loops",
      title: "Sequência de Fibonacci",
      description: "Use while para gerar os primeiros 7 termos da sequência de Fibonacci (0, 1, 1, 2, 3, 5, 8). Imprima cada um em uma linha.",
      narrative: "Os números de Fibonacci aparecem em padrões de tráfego naturais. Gere a sequência para alimentar o gerador de honeytokens.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "0\n1\n1\n2\n3\n5\n8",
      testCode: "assert 'while' in code and output.strip() == '0\\n1\\n1\\n2\\n3\\n5\\n8'",
      starterCode: "a, b = 0, 1\ncontador = 0\n# while contador < 7: print(a); a, b = b, a + b; contador += 1\n",
      hints: [
        { text: "Use a atribuição múltipla 'a, b = b, a + b' para atualizar ambos sem variável temporária.", cost: 20 },
        { text: "a, b = 0, 1\nfor _ in range(7):\n    print(a)\n    a, b = b, a + b", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Algoritmo Iterativo Clássico",
      conceptExplanation: "Fibonacci é o exemplo canônico de iteração com estado: cada termo depende dos dois anteriores. A atribuição múltipla 'a, b = b, a + b' atualiza os dois em paralelo, sem variável auxiliar — uma elegância única do Python.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Sequência fractal alimentada ao gerador. Os honeytokens seguirão padrões orgânicos.",
      solution: "a, b = 0, 1\nfor _ in range(7):\n    print(a)\n    a, b = b, a + b",
    },
    {
      id: "py-loop-26",
      worldId: "montanha-loops",
      title: "Busca com Flag",
      description: "Dada 'alvos' e 'procurado=\"BACKDOOR\"', use um for com uma flag 'encontrado=False'. Quando achar, mude flag para True. Após o loop, imprima 'achei' se flag for True, senão 'nao_achei'. Saída esperada: achei.",
      narrative: "Use a abordagem de flag para registrar se o alvo foi encontrado durante a varredura — útil quando você precisa continuar processando após o match.",
      difficulty: "avancado",
      setupCode: "alvos = ['firewall', 'BACKDOOR', 'router']\nprocurado = 'BACKDOOR'",
      expectedOutput: "achei",
      testCode: "assert 'encontrado' in code and 'True' in code and output.strip() == 'achei'",
      starterCode: "alvos = ['firewall', 'BACKDOOR', 'router']\nprocurado = 'BACKDOOR'\nencontrado = False\n# Itere, marque a flag, e depois imprima resultado\n",
      hints: [
        { text: "Crie 'encontrado = False'. Dentro do for, se achar, 'encontrado = True'.", cost: 15 },
        { text: "Depois do for, use if encontrado: print('achei') else: print('nao_achei').", cost: 25 },
      ],
      xpReward: 1000,
      concept: "Padrão Flag",
      conceptExplanation: "O 'padrão flag' usa uma variável booleana para registrar se algo aconteceu durante o loop. Alternativa ao for/else. Útil quando você precisa fazer mais coisas após detectar o item, não apenas sair.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Backdoor detectado e registrado. O scanner continuou a varredura mesmo após o match.",
      solution: "alvos = ['firewall', 'BACKDOOR', 'router']\nprocurado = 'BACKDOOR'\nencontrado = False\nfor a in alvos:\n    if a == procurado:\n        encontrado = True\nif encontrado:\n    print('achei')\nelse:\n    print('nao_achei')",
    },
    {
      id: "py-loop-27",
      worldId: "montanha-loops",
      title: "Dict Comprehension",
      description: "Use dict comprehension para criar 'tabela' com cada número de range(1, 4) como chave e o seu cubo como valor. Imprima a tabela.",
      narrative: "Construa uma tabela de lookup pré-calculada para o motor de criptografia em uma única expressão.",
      difficulty: "epico",
      setupCode: "",
      expectedOutput: "{1: 1, 2: 8, 3: 27}",
      testCode: "assert 'for' in code and ':' in code and tabela == {1: 1, 2: 8, 3: 27} and output.strip() == str(tabela)",
      starterCode: "# tabela = {n: n**3 for n in range(1, 4)}\n",
      hints: [
        { text: "Sintaxe: {chave: valor for item in iter}", cost: 20 },
        { text: "tabela = {n: n**3 for n in range(1, 4)}\nprint(tabela)", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Dict Comprehension",
      conceptExplanation: "Mesma ideia da list comprehension, mas constrói dicionários. Sintaxe '{chave: valor for ...}'. Ideal para criar mapas/lookup tables direto de iteráveis, com filtragem opcional via 'if'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Tabela de lookup precomputada. As consultas serão instantâneas em runtime.",
      solution: "tabela = {n: n**3 for n in range(1, 4)}\nprint(tabela)",
    },
    {
      id: "py-loop-28",
      worldId: "montanha-loops",
      title: "Set Comprehension",
      description: "Dada a lista 'logs', use set comprehension para criar 'unicos' contendo apenas valores distintos. Imprima o tamanho do set (len).",
      narrative: "Conte quantos IPs distintos atacaram a infraestrutura. Use set comprehension para deduplicar em uma só passada.",
      difficulty: "avancado",
      setupCode: "logs = ['ip1', 'ip2', 'ip1', 'ip3', 'ip2', 'ip4']",
      expectedOutput: "4",
      testCode: "assert 'for' in code and '{' in code and len(unicos) == 4 and output.strip() == '4'",
      starterCode: "logs = ['ip1', 'ip2', 'ip1', 'ip3', 'ip2', 'ip4']\n# unicos = {x for x in logs}\n",
      hints: [
        { text: "Set comprehension usa chaves {} sem ':' — apenas a expressão.", cost: 15 },
        { text: "unicos = {x for x in logs}\nprint(len(unicos))", cost: 25 },
      ],
      xpReward: 1000,
      concept: "Set Comprehension",
      conceptExplanation: "Sintaxe: '{expr for item in iter}' (sem ':', diferente de dict). Cria sets — automaticamente sem duplicatas. Mesma idea da list/dict comprehension, mas com semântica de conjunto.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Atacantes únicos contados: 4. Equipe de resposta priorizará os IPs distintos.",
      solution: "logs = ['ip1', 'ip2', 'ip1', 'ip3', 'ip2', 'ip4']\nunicos = {x for x in logs}\nprint(len(unicos))",
    },
    {
      id: "py-loop-29",
      worldId: "montanha-loops",
      title: "Iteração com Range Reverso",
      description: "Use range para iterar de 10 até 1 (inclusive), descendo de 2 em 2. Imprima cada valor. Saída esperada: 10, 8, 6, 4, 2.",
      narrative: "O contador de desligamento decresce em saltos de 2 para sincronizar com o relógio interno do sistema.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "10\n8\n6\n4\n2",
      testCode: "assert 'range' in code and '-2' in code and output.strip() == '10\\n8\\n6\\n4\\n2'",
      starterCode: "# range(10, 0, -2)\n",
      hints: [
        { text: "Para parar em 2 inclusive: vá até 0 (exclusivo) com passo -2.", cost: 15 },
        { text: "for i in range(10, 0, -2):\n    print(i)", cost: 25 },
      ],
      xpReward: 950,
      concept: "Range Reverso com Passo",
      conceptExplanation: "Combinando os três parâmetros de range() com passo negativo, você cria sequências decrescentes customizadas. Lembre que o 'fim' continua exclusivo — ajuste para incluir o valor final desejado.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Contagem regressiva sincronizada. O desligamento ocorreu no tique correto do relógio.",
      solution: "for i in range(10, 0, -2):\n    print(i)",
    },
    {
      id: "py-loop-30",
      worldId: "montanha-loops",
      title: "Mestre dos Ciclos: Matriz Transposta",
      description: "Dada 'matriz = [[1,2,3],[4,5,6]]' (2 linhas, 3 colunas), use list comprehension aninhada para criar 'transposta' (3 linhas, 2 colunas). Imprima 'transposta'.",
      narrative: "O algoritmo de visão computacional exige a matriz girada 90°. Construa a transposta em uma única expressão de alta densidade.",
      difficulty: "epico",
      setupCode: "matriz = [[1, 2, 3], [4, 5, 6]]",
      expectedOutput: "[[1, 4], [2, 5], [3, 6]]",
      testCode: "assert 'for' in code and code.count('for') >= 2 and transposta == [[1, 4], [2, 5], [3, 6]] and output.strip() == str(transposta)",
      starterCode: "matriz = [[1, 2, 3], [4, 5, 6]]\n# transposta = [[linha[i] for linha in matriz] for i in range(len(matriz[0]))]\n",
      hints: [
        { text: "Você precisa de dois 'for' — externo: cada coluna (índice); interno: cada linha.", cost: 25 },
        { text: "transposta = [[linha[i] for linha in matriz] for i in range(len(matriz[0]))]", cost: 40 },
      ],
      xpReward: 1500,
      concept: "Comprehension Aninhada",
      conceptExplanation: "List comprehensions podem ser aninhadas dentro de outras, construindo matrizes em uma expressão. A leitura segue de fora para dentro: o 'for' mais externo define a estrutura externa, o interno preenche cada linha. Use com moderação — pode ficar difícil de ler.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Matriz transposta gerada em uma expressão. O Setor de Iteração registra você como Mestre dos Ciclos.",
      solution: "matriz = [[1, 2, 3], [4, 5, 6]]\ntransposta = [[linha[i] for linha in matriz] for i in range(len(matriz[0]))]\nprint(transposta)",
    },
  ],
};
