import { World } from "../types";

export const MONTANHA_LOOPS_WORLD: World = {
  id: "montanha-loops",
  title: "Setor de Iteração",
  subtitle: "Ciclos de Processamento Infinito",
  icon: "refresh-cw",
  color: "#F97316",
  bgImage: "/assets/images/worlds/iteration_sector.png",
  lore: "No Setor de Iteração, o tempo é medido em ciclos de CPU. Aqui, você deve aprender a dominar os Loops de Processamento para executar tarefas repetitivas em escala massiva com um único script.",
  unlockRequirement: 5500,
  challenges: [
    {
      id: "py-loop-01",
      worldId: "montanha-loops",
      title: "Varredura de Sequência",
      description: "Use o comando for e a função range() para imprimir os números de 0 a 4.",
      narrative: "O scanner de rede precisa realizar uma varredura em cinco portas consecutivas. Automatize a verificação usando um loop 'for' para não precisar digitar cada comando manualmente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "0\n1\n2\n3\n4",
      testCode: "assert output.strip() == '0\\n1\\n2\\n3\\n4'",
      starterCode: "# Inicie o loop com for e range(5)\n",
      hints: [
        { text: "A função range(5) cria uma sequência que vai de 0 até 4.", cost: 10 },
        { text: "O comando print(i) deve estar indentado dentro do loop for.", cost: 20 },
        { text: "for i in range(5):\n    print(i)", cost: 30 },
      ],
      xpReward: 300,
      concept: "Loop de Repetição 'for'",
      conceptExplanation: "O loop 'for' permite que você execute o mesmo bloco de código várias vezes. É como dar uma ordem repetitiva para o computador: 'Para cada item nesta lista, faça isso'.\n\nExemplo:\nfor i in range(3):\n    print('Repetindo...')\n\nIsso mostrará a frase 3 vezes.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Varredura concluída. O loop de processamento estabilizou as portas de entrada do setor.",
      solution: "for i in range(5):\n    print(i)",
    },
    {
      id: "py-loop-02",
      worldId: "montanha-loops",
      title: "Contagem Regressiva de Segurança",
      description: "Use um loop for e range() para imprimir uma contagem regressiva de 5 até 1.",
      narrative: "O sistema de autodestruição foi ativado por engano. Você deve sincronizar o cronômetro de cancelamento emitindo os sinais de 5 a 1 em ordem decrescente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "5\n4\n3\n2\n1",
      testCode: "assert output.strip() == '5\\n4\\n3\\n2\\n1'",
      starterCode: "# Use range(inicio, fim, passo) para a contagem\n",
      hints: [
        { text: "A função range(5, 0, -1) começa em 5, vai até o 0 (não incluso) e subtrai 1 a cada passo.", cost: 10 },
        { text: "for i in range(5, 0, -1):", cost: 20 },
      ],
      xpReward: 350,
      concept: "Range com Passo Negativo",
      conceptExplanation: "A função `range()` é muito flexível. Se você passar três números, o último é o 'passo'. Se usar -1, o Python contará de trás para frente!",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cronômetro sincronizado. O protocolo de autodestruição foi abortado com sucesso.",
      solution: "for i in range(5, 0, -1):\n    print(i)",
    },
    {
      id: "py-loop-03",
      worldId: "montanha-loops",
      title: "Acumulador de Dados",
      description: "Dada a lista 'cargas', use um loop for para calcular a soma total dos valores e imprima o resultado.",
      narrative: "Diversos pacotes de dados chegaram fragmentados. Você deve percorrer todos eles, somando suas cargas úteis para reconstruir o arquivo original.",
      difficulty: "intermediario",
      setupCode: "cargas = [10, 20, 30, 40]",
      expectedOutput: "100",
      testCode: "assert 'for ' in code and output.strip() == '100'",
      starterCode: "cargas = [10, 20, 30, 40]\ntotal = 0\n# Some as cargas usando um loop\n",
      hints: [
        { text: "Crie uma variável total iniciando em 0 e vá somando cada carga nela dentro do loop.", cost: 10 },
        { text: "for c in cargas:\n    total = total + c", cost: 20 },
      ],
      xpReward: 380,
      concept: "Acumuladores",
      conceptExplanation: "Um padrão muito comum na programação é o 'acumulador'. Você cria uma variável fora do loop e, a cada volta do loop, adiciona algo novo nela.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Soma concluída. O arquivo de 100 bytes foi reconstruído e está pronto para análise.",
      solution: "total = 0\nfor c in cargas:\n    total += c\nprint(total)",
    },
    {
      id: "py-loop-04",
      worldId: "montanha-loops",
      title: "Loop de Manutenção 'while'",
      description: "Use um loop while para imprimir o valor de 'tentativas' enquanto ele for maior que 0. Diminua 1 a cada volta.",
      narrative: "O sistema de força bruta está tentando quebrar uma criptografia. Execute o loop de tentativas até que os recursos se esgotem.",
      difficulty: "intermediario",
      setupCode: "tentativas = 3",
      expectedOutput: "3\n2\n1",
      testCode: "assert 'while' in code and output.strip() == '3\\n2\\n1'",
      starterCode: "tentativas = 3\n# Use while para repetir enquanto tentativas > 0\n",
      hints: [
        { text: "O while continua repetindo enquanto a condição for verdadeira.", cost: 10 },
        { text: "Não esqueça de diminuir o valor: tentativas = tentativas - 1", cost: 20 },
        { text: "while tentativas > 0:\n    print(tentativas)\n    tentativas -= 1", cost: 30 },
      ],
      xpReward: 400,
      concept: "Loop Condicional 'while'",
      conceptExplanation: "O `while` (enquanto) é usado quando você não sabe exatamente quantas vezes algo vai repetir, mas sabe a condição que deve ser mantida para ele continuar rodando.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Criptografia quebrada no último ciclo. O acesso ao setor foi mantido.",
      solution: "while tentativas > 0:\n    print(tentativas)\n    tentativas -= 1",
    },
    {
      id: "py-loop-05",
      worldId: "montanha-loops",
      title: "Scanner de Intrusos",
      description: "Percorra a lista 'ips' e imprima cada um. Se encontrar '192.168.1.100', imprima 'ALERTA' e pare o loop com break.",
      narrative: "Um endereço IP suspeito foi detectado na rede. Varra a lista de conexões ativas e interrompa o processo assim que o intruso for localizado.",
      difficulty: "intermediario",
      setupCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']",
      expectedOutput: "192.168.1.1\n10.0.0.5\n192.168.1.100\nALERTA",
      testCode: "assert 'break' in code and 'ALERTA' in output",
      starterCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']\n# Percorra e use break ao achar o intruso\n",
      hints: [
        { text: "Use if dentro do for para verificar o IP.", cost: 10 },
        { text: "O comando break encerra o loop imediatamente.", cost: 20 },
      ],
      xpReward: 450,
      concept: "Interrupção de Loops (break)",
      conceptExplanation: "O `break` é um botão de emergência. Ele serve para parar um loop instantaneamente, mesmo que ele ainda tivesse mais voltas para dar.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Intruso localizado e isolado. O scanner foi interrompido para economizar recursos de defesa.",
      solution: "for ip in ips:\n    print(ip)\n    if ip == '192.168.1.100':\n        print('ALERTA')\n        break",
    },
    {
      id: "py-loop-06",
      worldId: "montanha-loops",
      title: "Filtro de Pacotes Vazios",
      description: "Percorra a lista 'dados'. Se o valor for 0, use continue para pular. Caso contrário, imprima o valor.",
      narrative: "A rede está cheia de pacotes vazios (ruído). Otimize seu processamento ignorando todos os valores zero e processando apenas os dados reais.",
      difficulty: "intermediario",
      setupCode: "dados = [10, 0, 50, 0, 30]",
      expectedOutput: "10\n50\n30",
      testCode: "assert 'continue' in code and '0' not in output",
      starterCode: "dados = [10, 0, 50, 0, 30]\n# Pule os zeros usando continue\n",
      hints: [
        { text: "O comando continue pula para a próxima volta do loop sem executar o que vem abaixo dele.", cost: 10 },
        { text: "if valor == 0:\n    continue", cost: 20 },
      ],
      xpReward: 480,
      concept: "Pular Iterações (continue)",
      conceptExplanation: "O `continue` serve para dizer ao loop: 'Pule essa volta e vá direto para a próxima'. É ótimo para ignorar dados inválidos ou desnecessários.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Ruído filtrado. Apenas dados úteis foram processados, economizando 40% de banda de rede.",
      solution: "for d in dados:\n    if d == 0:\n        continue\n    print(d)",
    },
    {
      id: "py-loop-07",
      worldId: "montanha-loops",
      title: "Iteração Direta de Coleção",
      description: "Dada a lista 'usuarios', use um loop for para imprimir cada nome (um por linha), sem usar range().",
      narrative: "O sistema de auditoria precisa logar cada usuário ativo. Itere diretamente sobre a coleção, sem se preocupar com índices numéricos.",
      difficulty: "intermediario",
      setupCode: "usuarios = ['Neo', 'Trinity', 'Morpheus']",
      expectedOutput: "Neo\nTrinity\nMorpheus",
      testCode: "assert 'for' in code and 'range' not in code and output.strip() == 'Neo\\nTrinity\\nMorpheus'",
      starterCode: "usuarios = ['Neo', 'Trinity', 'Morpheus']\n# Itere diretamente, sem range()\n",
      hints: [
        { text: "Você pode escrever 'for nome in usuarios:' diretamente.", cost: 10 },
        { text: "for u in usuarios:\n    print(u)", cost: 20 },
      ],
      xpReward: 500,
      concept: "Iteração Direta",
      conceptExplanation: "O for em Python aceita qualquer 'coisa iterável': listas, strings, ranges, dicionários... Você não precisa de índices na maior parte dos casos.\n\nIsso deixa o código mais limpo e expressivo. Use range() apenas quando o índice for realmente necessário.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Auditoria registrada. Cada operador foi catalogado no log mestre.",
      solution: "for u in usuarios:\n    print(u)",
    },
    {
      id: "py-loop-08",
      worldId: "montanha-loops",
      title: "Indexador Sincronizado",
      description: "Use enumerate() para imprimir 'indice: valor' para cada item da lista 'modulos'. Exemplo: '0: AUTH'.",
      narrative: "O carregador de módulos precisa de um relatório com a posição e o nome de cada componente. Sincronize índice e valor em uma única passagem do loop.",
      difficulty: "intermediario",
      setupCode: "modulos = ['AUTH', 'NET', 'DB']",
      expectedOutput: "0: AUTH\n1: NET\n2: DB",
      testCode: "assert 'enumerate' in code and output.strip() == '0: AUTH\\n1: NET\\n2: DB'",
      starterCode: "modulos = ['AUTH', 'NET', 'DB']\n# Use enumerate() no for\n",
      hints: [
        { text: "for i, valor in enumerate(lista): te entrega índice e valor ao mesmo tempo.", cost: 15 },
        { text: "Use f-string para formatar: f'{i}: {valor}'", cost: 25 },
      ],
      xpReward: 550,
      concept: "Função enumerate()",
      conceptExplanation: "Quando você precisa do índice E do valor durante a iteração, use enumerate(). Ela 'embrulha' a lista e devolve pares (índice, item) a cada volta.\n\nÉ a forma idiomática em Python de fazer iteração com índice — evite o anti-padrão 'for i in range(len(lista))'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Relatório emitido. O carregador conhece a posição exata de cada componente do sistema.",
      solution: "for i, m in enumerate(modulos):\n    print(f'{i}: {m}')",
    },
    {
      id: "py-loop-09",
      worldId: "montanha-loops",
      title: "Varredura de Matriz",
      description: "Dada a matriz 'grid' (lista de listas), use loops aninhados para imprimir cada número (um por linha).",
      narrative: "O scanner precisa percorrer cada célula da grade de segurança 2x2. Use um loop dentro do outro para cobrir cada linha e cada coluna sem deixar nenhum ponto cego.",
      difficulty: "avancado",
      setupCode: "grid = [[1, 2], [3, 4]]",
      expectedOutput: "1\n2\n3\n4",
      testCode: "assert code.count('for ') >= 2 and output.strip() == '1\\n2\\n3\\n4'",
      starterCode: "grid = [[1, 2], [3, 4]]\n# Use dois fors aninhados\n",
      hints: [
        { text: "O for externo percorre as linhas (sublistas). O for interno percorre os valores de cada linha.", cost: 15 },
        { text: "for linha in grid:\n    for valor in linha:\n        print(valor)", cost: 30 },
      ],
      xpReward: 600,
      concept: "Loops Aninhados",
      conceptExplanation: "Você pode colocar um for dentro de outro for. O loop interno é executado por completo a cada volta do externo.\n\nÉ a forma natural de varrer estruturas 2D (matrizes, grids, tabuleiros). Cuidado: cada nível adicional multiplica o tempo de execução do programa.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Grade varrida em sua totalidade. Nenhuma célula da matriz escapou ao scanner.",
      solution: "for linha in grid:\n    for valor in linha:\n        print(valor)",
    },
    {
      id: "py-loop-10",
      worldId: "montanha-loops",
      title: "Sistema de Vigilância",
      description: "Use 'while True' com break. A cada ciclo, imprima 'energia' e diminua 25. Quando 'energia' for menor que 25, encerre o loop com break.",
      narrative: "O sistema de vigilância roda em loop contínuo até que a bateria entre em modo crítico. Implemente o ciclo infinito com saída controlada por uma condição interna.",
      difficulty: "avancado",
      setupCode: "energia = 100",
      expectedOutput: "100\n75\n50\n25",
      testCode: "assert 'while True' in code and 'break' in code and output.strip() == '100\\n75\\n50\\n25'",
      starterCode: "energia = 100\n# while True com break quando energia < 25\n",
      hints: [
        { text: "while True: cria um loop infinito. O break é a única saída.", cost: 15 },
        { text: "Imprima primeiro, depois decremente, depois teste a condição de break.", cost: 25 },
        { text: "while True:\n    print(energia)\n    energia -= 25\n    if energia < 25:\n        break", cost: 35 },
      ],
      xpReward: 650,
      concept: "Loop Infinito Controlado",
      conceptExplanation: "Às vezes você não sabe a condição de parada antecipadamente — talvez ela dependa de um evento, de uma entrada externa ou de um cálculo interno.\n\n'while True' cria um ciclo eterno que só termina quando um break é executado. É um padrão comum em sistemas de monitoramento, servidores e jogos.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Bateria em estado crítico. O sistema entrou em hibernação preservando os dados coletados.",
      solution: "while True:\n    print(energia)\n    energia -= 25\n    if energia < 25:\n        break",
    },
    {
      id: "py-loop-11",
      worldId: "montanha-loops",
      title: "Decifrador de Caracteres",
      description: "Itere sobre cada caractere da string 'token' e imprima-o (um por linha).",
      narrative: "Um token criptografado chegou ao buffer. Disseque cada caractere para análise individual antes de tentar o ataque de dicionário.",
      difficulty: "avancado",
      setupCode: "token = 'X1Y2'",
      expectedOutput: "X\n1\nY\n2",
      testCode: "assert 'for' in code and output.strip() == 'X\\n1\\nY\\n2'",
      starterCode: "token = 'X1Y2'\n# Itere sobre a string\n",
      hints: [
        { text: "Strings também são iteráveis em Python. Você pode usar 'for letra in string:'.", cost: 10 },
        { text: "for c in token:\n    print(c)", cost: 20 },
      ],
      xpReward: 700,
      concept: "Iteração sobre Strings",
      conceptExplanation: "Em Python, strings se comportam como sequências de caracteres. Isso significa que você pode iterar sobre elas com for, fazer slicing, usar len() e o operador 'in' — tudo igual a uma lista.\n\nIsso unifica a forma como você trabalha com texto e coleções.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Token desmontado caractere a caractere. A análise de dicionário pode começar.",
      solution: "for c in token:\n    print(c)",
    },
    {
      id: "py-loop-12",
      worldId: "montanha-loops",
      title: "Catalogador Seletivo",
      description: "Dada a lista 'valores', use um loop for combinado com if para contar quantos números são pares. Imprima a contagem final.",
      narrative: "O coletor precisa rastrear apenas os pacotes com identificador par. Conte quantos passam pelo filtro durante a varredura completa.",
      difficulty: "avancado",
      setupCode: "valores = [3, 8, 12, 7, 22, 5, 4]",
      expectedOutput: "4",
      testCode: "assert 'for' in code and '%' in code and output.strip() == '4'",
      starterCode: "valores = [3, 8, 12, 7, 22, 5, 4]\ncontador = 0\n# Conte os pares e imprima 'contador'\n",
      hints: [
        { text: "Use 'if v % 2 == 0:' dentro do loop para identificar pares.", cost: 15 },
        { text: "Some 1 ao contador a cada par encontrado.", cost: 25 },
      ],
      xpReward: 750,
      concept: "Contagem Condicional",
      conceptExplanation: "Combinar loop + condicional + acumulador é um dos padrões mais usados em programação. Você itera sobre os dados, testa cada item e atualiza um contador (ou outra estrutura) com base no resultado.\n\nÉ a base de filtros, busca, validação e geração de relatórios.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Quatro pacotes pares confirmados. O catálogo do coletor foi atualizado.",
      solution: "contador = 0\nfor v in valores:\n    if v % 2 == 0:\n        contador += 1\nprint(contador)",
    },
    {
      id: "py-loop-13",
      worldId: "montanha-loops",
      title: "Sincronizador de Streams",
      description: "Use zip() para iterar sobre as listas 'ips' e 'portas' em paralelo, imprimindo 'ip:porta' em cada linha.",
      narrative: "Dois streams de dados chegaram em paralelo: a lista de IPs e a lista de portas correspondentes. Sincronize-os par a par para montar os endpoints completos.",
      difficulty: "epico",
      setupCode: "ips = ['10.0.0.1', '10.0.0.2', '10.0.0.3']\nportas = [80, 443, 22]",
      expectedOutput: "10.0.0.1:80\n10.0.0.2:443\n10.0.0.3:22",
      testCode: "assert 'zip' in code and output.strip() == '10.0.0.1:80\\n10.0.0.2:443\\n10.0.0.3:22'",
      starterCode: "ips = ['10.0.0.1', '10.0.0.2', '10.0.0.3']\nportas = [80, 443, 22]\n# Use zip() para iterar nas duas em paralelo\n",
      hints: [
        { text: "for ip, p in zip(ips, portas): te entrega um par a cada volta.", cost: 20 },
        { text: "Use f-string: f'{ip}:{p}'", cost: 30 },
      ],
      xpReward: 850,
      concept: "Função zip()",
      conceptExplanation: "zip() recebe duas (ou mais) sequências e devolve pares (tuplas) sincronizados — o primeiro item de cada, depois o segundo, e assim por diante.\n\nSe as listas tiverem tamanhos diferentes, zip() para no menor. É a ferramenta padrão para iterar em paralelo sem precisar gerenciar índices manualmente.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Streams alinhados. Os endpoints completos foram montados sem perda de pacotes.",
      solution: "for ip, p in zip(ips, portas):\n    print(f'{ip}:{p}')",
    },
    {
      id: "py-loop-14",
      worldId: "montanha-loops",
      title: "Compilador em Uma Linha",
      description: "Use list comprehension para criar 'quadrados' contendo o quadrado (n*n) de cada número da lista 'numeros'. Imprima a lista resultante.",
      narrative: "O processamento em massa exige que cada valor seja elevado ao quadrado. Compacte toda a operação em uma única linha de código de alta performance.",
      difficulty: "epico",
      setupCode: "numeros = [1, 2, 3, 4, 5]",
      expectedOutput: "[1, 4, 9, 16, 25]",
      testCode: "assert 'for' in code and quadrados == [1, 4, 9, 16, 25] and output.strip() == str(quadrados)",
      starterCode: "numeros = [1, 2, 3, 4, 5]\n# Use list comprehension para criar 'quadrados'\n",
      hints: [
        { text: "Sintaxe: [expressao for item in iteravel]", cost: 20 },
        { text: "quadrados = [n ** 2 for n in numeros]", cost: 30 },
      ],
      xpReward: 950,
      concept: "List Comprehension Avançada",
      conceptExplanation: "List comprehension é a forma mais idiomática de Python para criar listas a partir de iteráveis. Internamente é um loop, mas escrito em uma única expressão.\n\nSintaxe completa: [expressao for item in iteravel if condicao]\n\nÉ mais rápido que um for + append() tradicional e considerado mais 'pythônico'.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Compilação massiva concluída em um único ciclo. O Setor de Iteração reconhece sua maestria sobre os ciclos de CPU.",
      solution: "quadrados = [n ** 2 for n in numeros]\nprint(quadrados)",
    },
  ],
};
