import { World } from "../types";

export const MONTANHA_LOOPS_WORLD: World = {
  id: "montanha-loops",
  title: "Setor de Iteração",
  subtitle: "Ciclos de Processamento Infinito",
  icon: "refresh-cw",
  color: "#F97316",
  bgImage: "/assets/images/worlds/iteration_sector.png",
  lore: "No Setor de Iteração, o tempo é medido em ciclos de CPU. Aqui, você deve aprender a dominar os Loops de Processamento para executar tarefas repetitivas em escala massiva com um único script.",
  unlockRequirement: 800,
  challenges: [
    {
      id: "py-loop-01",
      worldId: "montanha-loops",
      title: "Varredura de Sequência",
      description: "Use o comando for e a função range() para imprimir os números de 0 a 4.",
      narrative: "O scanner de rede precisa realizar uma varredura em cinco portas consecutivas. Automatize a verificação usando um loop 'for' para não precisar digitar cada comando manualmente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "0\n1\n2\n3\n4",
      testCode: "assert output.strip() == '0\\n1\\n2\\n3\\n4'",
      starterCode: "# Inicie o loop com for e range(5)\n",
      hints: [
        { text: "A função range(5) cria uma sequência que vai de 0 até 4.", cost: 10 },
        { text: "O comando print(i) deve estar indentado dentro do loop for.", cost: 20 },
        { text: "for i in range(5):\n    print(i)", cost: 30 },
      ],
      xpReward: 300,
      concept: "Loop de Repetição 'for'",
      conceptExplanation: "O loop 'for' permite que você execute o mesmo bloco de código várias vezes. É como dar uma ordem repetitiva para o computador: 'Para cada item nesta lista, faça isso'.\n\nExemplo:\nfor i in range(3):\n    print('Repetindo...')\n\nIsso mostrará a frase 3 vezes.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Varredura concluída. O loop de processamento estabilizou as portas de entrada do setor.",
    },
    {
      id: "py-loop-02",
      worldId: "montanha-loops",
      title: "Contagem Regressiva de Segurança",
      description: "Use um loop for e range() para imprimir uma contagem regressiva de 5 até 1.",
      narrative: "O sistema de autodestruição foi ativado por engano. Você deve sincronizar o cronômetro de cancelamento emitindo os sinais de 5 a 1 em ordem decrescente.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "5\n4\n3\n2\n1",
      testCode: "assert output.strip() == '5\\n4\\n3\\n2\\n1'",
      starterCode: "# Use range(inicio, fim, passo) para a contagem\n",
      hints: [
        { text: "A função range(5, 0, -1) começa em 5, vai até o 0 (não incluso) e subtrai 1 a cada passo.", cost: 10 },
        { text: "for i in range(5, 0, -1):", cost: 20 },
      ],
      xpReward: 350,
      concept: "Range com Passo Negativo",
      conceptExplanation: "A função `range()` é muito flexível. Se você passar três números, o último é o 'passo'. Se usar -1, o Python contará de trás para frente!",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Cronômetro sincronizado. O protocolo de autodestruição foi abortado com sucesso.",
    },
    {
      id: "py-loop-03",
      worldId: "montanha-loops",
      title: "Acumulador de Dados",
      description: "Dada a lista 'cargas', use um loop for para calcular a soma total dos valores e imprima o resultado.",
      narrative: "Diversos pacotes de dados chegaram fragmentados. Você deve percorrer todos eles, somando suas cargas úteis para reconstruir o arquivo original.",
      difficulty: "intermediario",
      setupCode: "cargas = [10, 20, 30, 40]",
      expectedOutput: "100",
      testCode: "assert 'for ' in code and output.strip() == '100'",
      starterCode: "cargas = [10, 20, 30, 40]\ntotal = 0\n# Some as cargas usando um loop\n",
      hints: [
        { text: "Crie uma variável total iniciando em 0 e vá somando cada carga nela dentro do loop.", cost: 10 },
        { text: "for c in cargas:\n    total = total + c", cost: 20 },
      ],
      xpReward: 380,
      concept: "Acumuladores",
      conceptExplanation: "Um padrão muito comum na programação é o 'acumulador'. Você cria uma variável fora do loop e, a cada volta do loop, adiciona algo novo nela.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Soma concluída. O arquivo de 100 bytes foi reconstruído e está pronto para análise.",
    },
    {
      id: "py-loop-04",
      worldId: "montanha-loops",
      title: "Loop de Manutenção 'while'",
      description: "Use um loop while para imprimir o valor de 'tentativas' enquanto ele for maior que 0. Diminua 1 a cada volta.",
      narrative: "O sistema de força bruta está tentando quebrar uma criptografia. Execute o loop de tentativas até que os recursos se esgotem.",
      difficulty: "intermediario",
      setupCode: "tentativas = 3",
      expectedOutput: "3\n2\n1",
      testCode: "assert 'while' in code and output.strip() == '3\\n2\\n1'",
      starterCode: "tentativas = 3\n# Use while para repetir enquanto tentativas > 0\n",
      hints: [
        { text: "O while continua repetindo enquanto a condição for verdadeira.", cost: 10 },
        { text: "Não esqueça de diminuir o valor: tentativas = tentativas - 1", cost: 20 },
        { text: "while tentativas > 0:\n    print(tentativas)\n    tentativas -= 1", cost: 30 },
      ],
      xpReward: 400,
      concept: "Loop Condicional 'while'",
      conceptExplanation: "O `while` (enquanto) é usado quando você não sabe exatamente quantas vezes algo vai repetir, mas sabe a condição que deve ser mantida para ele continuar rodando.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Criptografia quebrada no último ciclo. O acesso ao setor foi mantido.",
    },
    {
      id: "py-loop-05",
      worldId: "montanha-loops",
      title: "Scanner de Intrusos",
      description: "Percorra a lista 'ips' e imprima cada um. Se encontrar '192.168.1.100', imprima 'ALERTA' e pare o loop com break.",
      narrative: "Um endereço IP suspeito foi detectado na rede. Varra a lista de conexões ativas e interrompa o processo assim que o intruso for localizado.",
      difficulty: "intermediario",
      setupCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']",
      expectedOutput: "192.168.1.1\n10.0.0.5\n192.168.1.100\nALERTA",
      testCode: "assert 'break' in code and 'ALERTA' in output",
      starterCode: "ips = ['192.168.1.1', '10.0.0.5', '192.168.1.100', '8.8.8.8']\n# Percorra e use break ao achar o intruso\n",
      hints: [
        { text: "Use if dentro do for para verificar o IP.", cost: 10 },
        { text: "O comando break encerra o loop imediatamente.", cost: 20 },
      ],
      xpReward: 450,
      concept: "Interrupção de Loops (break)",
      conceptExplanation: "O `break` é um botão de emergência. Ele serve para parar um loop instantaneamente, mesmo que ele ainda tivesse mais voltas para dar.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Intruso localizado e isolado. O scanner foi interrompido para economizar recursos de defesa.",
    },
    {
      id: "py-loop-06",
      worldId: "montanha-loops",
      title: "Filtro de Pacotes Vazios",
      description: "Percorra a lista 'dados'. Se o valor for 0, use continue para pular. Caso contrário, imprima o valor.",
      narrative: "A rede está cheia de pacotes vazios (ruído). Otimize seu processamento ignorando todos os valores zero e processando apenas os dados reais.",
      difficulty: "intermediario",
      setupCode: "dados = [10, 0, 50, 0, 30]",
      expectedOutput: "10\n50\n30",
      testCode: "assert 'continue' in code and '0' not in output",
      starterCode: "dados = [10, 0, 50, 0, 30]\n# Pule os zeros usando continue\n",
      hints: [
        { text: "O comando continue pula para a próxima volta do loop sem executar o que vem abaixo dele.", cost: 10 },
        { text: "if valor == 0:\n    continue", cost: 20 },
      ],
      xpReward: 480,
      concept: "Pular Iterações (continue)",
      conceptExplanation: "O `continue` serve para dizer ao loop: 'Pule essa volta e vá direto para a próxima'. É ótimo para ignorar dados inválidos ou desnecessários.",
      successNpc: "Iter-8, Autômato de Ciclos",
      successAvatar: "/avatars/wizard.webp",
      successStory: "Ruído filtrado. Apenas dados úteis foram processados, economizando 40% de banda de rede.",
    },
  ],
};
