import { World } from "../types";

export const NINHO_LISTAS_WORLD: World = {
  id: "ninho-listas",
  title: "Ninho das Listas",
  subtitle: "Processamento em Lote",
  icon: "layers",
  color: "#A855F7",
  bgImage: "/assets/images/worlds/list_nest.png",
  lore: "O tráfego de dados no Core não viaja sozinho; ele flui em fluxos massivos e estruturados. No Ninho das Listas, você aprenderá a agrupar pacotes, fatiar buffers de memória e gerenciar coleções de informações para ataques em larga escala.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "li-01",
      worldId: "ninho-listas",
      title: "Buffer de Reconhecimento",
      description: "Crie uma lista chamada 'servidores' com as strings 'Nginx', 'Apache' e 'IIS', e imprima a lista.",
      narrative: "Sua sonda interceptou os nomes dos servidores ativos. Armazene-os em uma lista para processamento posterior.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "['Nginx', 'Apache', 'IIS']",
      testCode: "assert servidores == ['Nginx', 'Apache', 'IIS'] and output.strip() == str(servidores)",
      starterCode: "# Crie a lista de servidores\n",
      hints: [
        { text: "Listas em Python são definidas usando colchetes [ ].", cost: 10 },
        { text: "Separe os itens por vírgula.", cost: 20 },
        { text: "servidores = ['Nginx', 'Apache', 'IIS']\nprint(servidores)", cost: 30 },
      ],
      xpReward: 150,
      concept: "Criação de Listas",
      conceptExplanation: "Uma lista é como uma gaveta com várias divisórias. Você pode guardar muitas informações em uma única variável, mantendo a ordem em que foram colocadas.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Inventário de servidores registrado. O buffer está pronto para indexação.",
      solution: "servidores = ['Nginx', 'Apache', 'IIS']\nprint(servidores)",
    },
    {
      id: "li-02",
      worldId: "ninho-listas",
      title: "Alvo Prioritário",
      description: "Dada a lista 'ips', imprima o primeiro e o último elemento (um em cada linha).",
      narrative: "Em uma lista de alvos, o primeiro e o último costumam ser o gateway e o backup. Identifique-os rapidamente.",
      difficulty: "iniciante",
      setupCode: "ips = ['192.168.1.1', '10.0.0.5', '172.16.0.254']",
      expectedOutput: "192.168.1.1\n172.16.0.254",
      testCode: "assert output.strip().split('\\n') == ['192.168.1.1', '172.16.0.254']",
      starterCode: "ips = ['192.168.1.1', '10.0.0.5', '172.16.0.254']\n# Imprima o primeiro e o último elemento\n",
      hints: [
        { text: "O índice do primeiro elemento é 0: lista[0].", cost: 10 },
        { text: "O índice do último elemento pode ser -1: lista[-1].", cost: 20 },
        { text: "print(ips[0])\nprint(ips[-1])", cost: 30 },
      ],
      xpReward: 160,
      concept: "Indexação de Listas",
      conceptExplanation: "Cada item na lista tem uma posição (índice). O Python começa a contar do zero. Você também pode contar de trás para frente usando números negativos!",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Extremidades da rede identificadas. O perímetro está mapeado.",
      solution: "print(ips[0])\nprint(ips[-1])",
    },
    {
      id: "li-03",
      worldId: "ninho-listas",
      title: "Fatiamento de Buffer",
      description: "Dada a lista 'dados', imprima os primeiros 3 elementos usando o recurso de fatiamento (slicing).",
      narrative: "O dump de memória é grande demais. Extraia apenas o cabeçalho (os primeiros 3 bytes) para análise rápida.",
      difficulty: "iniciante",
      setupCode: "dados = [0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46]",
      expectedOutput: "[255, 216, 255]",
      testCode: "assert output.strip() == str(dados[:3])",
      starterCode: "dados = [255, 216, 255, 224, 0, 16, 74, 70]\n# Use slicing para pegar os 3 primeiros\n",
      hints: [
        { text: "Slicing usa a sintaxe: lista[inicio:fim].", cost: 10 },
        { text: "O item no índice 'fim' não é incluído. Use :3 para pegar 0, 1 e 2.", cost: 20 },
        { text: "print(dados[:3])", cost: 30 },
      ],
      xpReward: 180,
      concept: "Fatiamento (Slicing)",
      conceptExplanation: "Slicing permite 'cortar' pedaços da lista. Se você quer do início até o índice 3 (sem incluir o 3), use [:3].",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Cabeçalho extraído. O tipo de arquivo foi identificado como JPEG criptografado.",
      solution: "print(dados[:3])",
    },
    {
      id: "li-04",
      worldId: "ninho-listas",
      title: "Contagem de Hosts",
      description: "Dada a lista 'conexoes', use a função len() para imprimir a quantidade de conexões ativas.",
      narrative: "Quantos dispositivos estão pendurados na nossa rede agora? O sistema precisa de um número exato para alocar largura de banda.",
      difficulty: "iniciante",
      setupCode: "conexoes = ['user1', 'user2', 'bot3', 'admin', 'guest']",
      expectedOutput: "5",
      testCode: "assert output.strip() == '5'",
      starterCode: "conexoes = ['user1', 'user2', 'bot3', 'admin', 'guest']\n# Imprima o tamanho da lista\n",
      hints: [
        { text: "A função len(lista) retorna o número de itens.", cost: 10 },
        { text: "print(len(conexoes))", cost: 30 },
      ],
      xpReward: 150,
      concept: "Função len()",
      conceptExplanation: "len() é abreviação de 'length' (comprimento). Use para saber quantos itens existem em qualquer coleção.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Carga de rede calculada. 5 sessões ativas detectadas.",
      solution: "print(len(conexoes))",
    },
    {
      id: "li-05",
      worldId: "ninho-listas",
      title: "Injeção de Pacote",
      description: "Dada a lista 'blacklist', adicione a string '10.0.0.1' ao final da lista usando append() e imprima a lista completa.",
      narrative: "Um novo IP suspeito foi detectado tentando força bruta. Insira-o na nossa lista negra imediatamente.",
      difficulty: "iniciante",
      setupCode: "blacklist = ['1.1.1.1', '2.2.2.2']",
      expectedOutput: "['1.1.1.1', '2.2.2.2', '10.0.0.1']",
      testCode: "assert '10.0.0.1' in blacklist and output.strip() == str(blacklist)",
      starterCode: "blacklist = ['1.1.1.1', '2.2.2.2']\n# Adicione '10.0.0.1' e imprima\n",
      hints: [
        { text: "Use lista.append(item) para adicionar algo ao final.", cost: 10 },
        { text: "Note que append() altera a lista original, não precisa de '='.", cost: 20 },
        { text: "blacklist.append('10.0.0.1')\nprint(blacklist)", cost: 30 },
      ],
      xpReward: 170,
      concept: "Método append()",
      conceptExplanation: "O append() coloca um novo item 'no rabo' da lista. É o método mais comum para crescer uma lista dinamicamente.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "IP bloqueado. O sistema de defesa foi atualizado.",
      solution: "blacklist.append('10.0.0.1')\nprint(blacklist)",
    },
    {
      id: "li-06",
      worldId: "ninho-listas",
      title: "Limpeza de Logs",
      description: "Dada a lista 'logs', remova o último elemento usando pop() e imprima a lista atualizada.",
      narrative: "O último registro do log contém sua pegada digital. Remova-o antes que o sistema de auditoria o detecte.",
      difficulty: "iniciante",
      setupCode: "logs = ['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS', 'YOUR_IP']",
      expectedOutput: "['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS']",
      testCode: "assert 'YOUR_IP' not in logs and output.strip() == str(logs)",
      starterCode: "logs = ['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS', 'YOUR_IP']\n# Remova o último log e imprima a lista\n",
      hints: [
        { text: "O método lista.pop() remove e retorna o último item.", cost: 10 },
        { text: "logs.pop()\nprint(logs)", cost: 30 },
      ],
      xpReward: 180,
      concept: "Método pop()",
      conceptExplanation: "pop() 'estoura' o último item da lista para fora. Se você não passar nenhum índice, ele tira o último por padrão.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Evidência removida. Sua presença nesta thread agora é fantasmagórica.",
      solution: "logs.pop()\nprint(logs)",
    },
    {
      id: "li-07",
      worldId: "ninho-listas",
      title: "Ordenação de Portas",
      description: "Dada a lista de portas, ordene-a em ordem crescente usando sort() e imprima o resultado.",
      narrative: "As portas escaneadas estão uma bagunça. Organize-as numericamente para que possamos planejar o ataque sequencial.",
      difficulty: "intermediario",
      setupCode: "portas = [80, 22, 443, 21, 8080]",
      expectedOutput: "[21, 22, 80, 443, 8080]",
      testCode: "assert portas == [21, 22, 80, 443, 8080] and output.strip() == str(portas)",
      starterCode: "portas = [80, 22, 443, 21, 8080]\n# Ordene a lista e imprima\n",
      hints: [
        { text: "O método lista.sort() organiza a lista 'in-place' (na própria variável).", cost: 10 },
        { text: "portas.sort()\nprint(portas)", cost: 30 },
      ],
      xpReward: 200,
      concept: "Método sort()",
      conceptExplanation: "O sort() coloca a lista em ordem. Se forem números, do menor para o maior. Se forem strings, em ordem alfabética.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Vetor de ataque organizado. Começaremos pela porta FTP (21).",
      solution: "portas.sort()\nprint(portas)",
    },
    {
      id: "li-08",
      worldId: "ninho-listas",
      title: "Análise de Latência",
      description: "Dada a lista 'pings', imprima o menor e o maior valor usando as funções min() e max().",
      narrative: "Encontre o servidor mais rápido e o mais lento na rede local para decidir onde hospedar nosso backdoor.",
      difficulty: "intermediario",
      setupCode: "pings = [45, 12, 89, 5, 120, 31]",
      expectedOutput: "5\n120",
      testCode: "assert 'min' in code and 'max' in code and '5' in output and '120' in output",
      starterCode: "pings = [45, 12, 89, 5, 120, 31]\n# Imprima o mínimo e o máximo\n",
      hints: [
        { text: "Use min(lista) para o menor valor e max(lista) para o maior.", cost: 10 },
      ],
      xpReward: 210,
      concept: "Funções min() e max()",
      conceptExplanation: "Essas funções utilitárias analisam toda a lista e retornam o extremo desejado em um piscar de olhos.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Servidor de 5ms selecionado como host primário.",
      solution: "print(min(pings))\nprint(max(pings))",
    },
    {
      id: "li-09",
      worldId: "ninho-listas",
      title: "Carga Total de Dados",
      description: "Dada a lista 'pacotes' (tamanhos em KB), imprima a soma total de todos os elementos usando sum().",
      narrative: "Calcule o peso total da carga útil que estamos prestes a exfiltrar dos servidores da CorpHQ.",
      difficulty: "intermediario",
      setupCode: "pacotes = [120, 500, 250, 10, 80]",
      expectedOutput: "960",
      testCode: "assert 'sum' in code and output.strip() == '960'",
      starterCode: "pacotes = [120, 500, 250, 10, 80]\n# Calcule a soma e imprima\n",
      hints: [
        { text: "A função sum(lista) soma todos os números da lista automaticamente.", cost: 10 },
      ],
      xpReward: 220,
      concept: "Função sum()",
      conceptExplanation: "Ao invés de somar um por um, a função sum() faz o trabalho pesado de iteração para você.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "960KB prontos para transferência. Iniciando upload criptografado.",
      solution: "print(sum(pacotes))",
    },
    {
      id: "li-10",
      worldId: "ninho-listas",
      title: "Filtro de Invasor",
      description: "Verifique se '192.168.1.50' está na lista 'permitidos' usando o operador 'in' e imprima o resultado (True ou False).",
      narrative: "Uma requisição externa chegou. Verifique se o IP de origem consta na nossa lista branca de acesso permitido.",
      difficulty: "intermediario",
      setupCode: "permitidos = ['192.168.1.10', '192.168.1.20', '192.168.1.30']",
      expectedOutput: "False",
      testCode: "assert 'in' in code and output.strip() == 'False'",
      starterCode: "permitidos = ['192.168.1.10', '192.168.1.20', '192.168.1.30']\n# Verifique se '192.168.1.50' está na lista\n",
      hints: [
        { text: "Use a sintaxe: item in lista.", cost: 10 },
        { text: "Isso retorna um valor Booleano (True ou False).", cost: 20 },
      ],
      xpReward: 230,
      concept: "Operador in",
      conceptExplanation: "O operador 'in' (dentro) é a forma mais rápida de perguntar se um valor existe dentro de uma coleção.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Acesso negado. O invasor foi redirecionado para um honeypot.",
      solution: "print('192.168.1.50' in permitidos)",
    },
    {
      id: "li-11",
      worldId: "ninho-listas",
      title: "Matriz de Dados",
      description: "Dada a matriz 3x3 'grid', acesse e imprima o elemento central (o número 5).",
      narrative: "O Core usa proteção em camadas (matrizes). Para acessar o núcleo, você deve indexar a coordenada central da grade de segurança.",
      difficulty: "avancado",
      setupCode: "grid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      expectedOutput: "5",
      testCode: "assert 'grid[1][1]' in code and output.strip() == '5'",
      starterCode: "grid = [\n  [1, 2, 3],\n  [4, 5, 6],\n  [7, 8, 9]\n]\n# Acesse o valor 5 e imprima\n",
      hints: [
        { text: "Para acessar listas dentro de listas, use dois pares de colchetes: grid[linha][coluna].", cost: 10 },
        { text: "Lembre-se: índices começam em 0. O elemento central está na linha 1, coluna 1.", cost: 20 },
        { text: "print(grid[1][1])", cost: 30 },
      ],
      xpReward: 300,
      concept: "Listas Aninhadas (Matrizes)",
      conceptExplanation: "Uma lista pode conter outras listas! Isso cria estruturas de dados em 2D, como planilhas ou mapas. Você acessa primeiro a 'lista externa' e depois a 'lista interna'.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Núcleo acessado! A grade de segurança foi perfurada exatamente no centro.",
      solution: "print(grid[1][1])",
    },
    {
      id: "li-12",
      worldId: "ninho-listas",
      title: "Desafio Final: Swap de Chaves",
      description: "Dada a lista 'chaves' com dois elementos, inverta a ordem deles (troque o primeiro pelo segundo e vice-versa) e imprima a lista.",
      narrative: "Para enganar o firewall, devemos inverter a ordem das chaves de criptografia no buffer de saída. Rápido, o tempo está acabando!",
      difficulty: "avancado",
      setupCode: "chaves = ['PUB_KEY', 'PRIV_KEY']",
      expectedOutput: "['PRIV_KEY', 'PUB_KEY']",
      testCode: "assert chaves == ['PRIV_KEY', 'PUB_KEY'] and output.strip() == str(chaves)",
      starterCode: "chaves = ['PUB_KEY', 'PRIV_KEY']\n# Inverta a ordem dos elementos e imprima\n",
      hints: [
        { text: "Você pode usar uma variável temporária ou a atribuição múltipla do Python.", cost: 10 },
        { text: "Atribuição múltipla: a, b = b, a", cost: 20 },
        { text: "chaves[0], chaves[1] = chaves[1], chaves[0]\nprint(chaves)", cost: 30 },
      ],
      xpReward: 400,
      concept: "Troca de Valores (Swap)",
      conceptExplanation: "O Python permite trocar valores de variáveis ou itens de lista de forma elegante: x, y = y, x. Isso evita a necessidade de criar variáveis extras apenas para a troca.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Handshake invertido! O firewall foi enganado e você agora tem acesso ao setor de armazenamento em lote. Excelente trabalho, Operador.",
      solution: "chaves[0], chaves[1] = chaves[1], chaves[0]\nprint(chaves)",
    },
    {
      id: "li-13",
      worldId: "ninho-listas",
      title: "Inserção Estratégica",
      description: "Use insert() para inserir o IP '0.0.0.0' na posição 0 (início) da lista 'blacklist' e imprima a lista.",
      narrative: "Um novo IP de altíssima prioridade foi detectado. Ele precisa ir para o topo da blacklist, garantindo que seja verificado primeiro pelo firewall.",
      difficulty: "intermediario",
      setupCode: "blacklist = ['1.1.1.1', '2.2.2.2']",
      expectedOutput: "['0.0.0.0', '1.1.1.1', '2.2.2.2']",
      testCode: "assert 'insert' in code and blacklist[0] == '0.0.0.0' and output.strip() == str(blacklist)",
      starterCode: "blacklist = ['1.1.1.1', '2.2.2.2']\n# Use insert(indice, item)\n",
      hints: [
        { text: "lista.insert(indice, item) coloca o item na posição indicada.", cost: 10 },
        { text: "Os elementos a partir desse índice são empurrados uma posição para frente.", cost: 20 },
        { text: "blacklist.insert(0, '0.0.0.0')\nprint(blacklist)", cost: 30 },
      ],
      xpReward: 250,
      concept: "Método insert()",
      conceptExplanation: "Enquanto append() sempre coloca o item no final, insert() permite escolher exatamente em qual posição o novo elemento entra. Os itens existentes a partir desse índice são deslocados uma posição para frente, sem perder nenhum dado.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "IP prioritário posicionado. O firewall agora checa esse alvo antes de qualquer outro.",
      solution: "blacklist.insert(0, '0.0.0.0')\nprint(blacklist)",
    },
    {
      id: "li-14",
      worldId: "ninho-listas",
      title: "Quarentena Selecionada",
      description: "Use remove() para tirar o nó 'COMPROMETIDO' da lista 'cluster' e imprima a lista atualizada.",
      narrative: "Um nó do cluster foi infiltrado por malware. Isole-o do pool ativo antes que a infecção se espalhe para os demais.",
      difficulty: "intermediario",
      setupCode: "cluster = ['Node-A', 'COMPROMETIDO', 'Node-C']",
      expectedOutput: "['Node-A', 'Node-C']",
      testCode: "assert 'remove' in code and 'COMPROMETIDO' not in cluster and output.strip() == str(cluster)",
      starterCode: "cluster = ['Node-A', 'COMPROMETIDO', 'Node-C']\n# Use remove() para tirar o nó pelo valor\n",
      hints: [
        { text: "lista.remove(valor) retira a primeira ocorrência do valor informado.", cost: 10 },
        { text: "cluster.remove('COMPROMETIDO')", cost: 20 },
      ],
      xpReward: 260,
      concept: "Método remove()",
      conceptExplanation: "Diferente do pop() — que remove pela posição —, o remove() recebe o VALOR que você quer tirar. É útil quando você sabe o que precisa remover, mas não onde ele está.\n\nObs: se houver mais de uma ocorrência, apenas a primeira é removida.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Nó comprometido isolado. O cluster volta a operar em condições limpas.",
      solution: "cluster.remove('COMPROMETIDO')\nprint(cluster)",
    },
    {
      id: "li-15",
      worldId: "ninho-listas",
      title: "Triangulação de Alvo",
      description: "Use index() para descobrir a posição do IP '172.16.0.5' na lista 'rastreio' e imprima esse índice.",
      narrative: "Você precisa localizar exatamente onde o invasor aparece na sequência de logs interceptada para correlacionar com o timestamp do ataque.",
      difficulty: "intermediario",
      setupCode: "rastreio = ['10.0.0.1', '192.168.1.1', '172.16.0.5', '8.8.8.8']",
      expectedOutput: "2",
      testCode: "assert 'index' in code and output.strip() == '2'",
      starterCode: "rastreio = ['10.0.0.1', '192.168.1.1', '172.16.0.5', '8.8.8.8']\n# Use index() para achar a posição\n",
      hints: [
        { text: "lista.index(valor) retorna o índice da primeira ocorrência do valor.", cost: 10 },
        { text: "print(rastreio.index('172.16.0.5'))", cost: 20 },
      ],
      xpReward: 270,
      concept: "Método index()",
      conceptExplanation: "Enquanto o operador 'in' apenas diz se algo existe (True/False), o index() vai além e te entrega a posição exata onde o valor aparece pela primeira vez.\n\nSe o valor não estiver na lista, o método lança um erro — então use 'in' antes para garantir.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Posição triangulada. O timestamp do invasor já foi correlacionado com a câmera de segurança.",
      solution: "print(rastreio.index('172.16.0.5'))",
    },
    {
      id: "li-16",
      worldId: "ninho-listas",
      title: "Análise de Frequência",
      description: "Use count() para contar quantas vezes o IP '5.5.5.5' aparece na lista 'tentativas' e imprima o resultado.",
      narrative: "O sistema de defesa detectou múltiplas requisições do mesmo IP. Quantifique a frequência para classificar como ataque de força bruta ou tentativa isolada.",
      difficulty: "intermediario",
      setupCode: "tentativas = ['1.1.1.1', '5.5.5.5', '2.2.2.2', '5.5.5.5', '5.5.5.5']",
      expectedOutput: "3",
      testCode: "assert 'count' in code and output.strip() == '3'",
      starterCode: "tentativas = ['1.1.1.1', '5.5.5.5', '2.2.2.2', '5.5.5.5', '5.5.5.5']\n# Use count() para contar ocorrências\n",
      hints: [
        { text: "lista.count(valor) retorna quantas vezes o valor aparece na lista.", cost: 10 },
        { text: "print(tentativas.count('5.5.5.5'))", cost: 20 },
      ],
      xpReward: 280,
      concept: "Método count()",
      conceptExplanation: "O count() faz uma varredura completa da lista e te diz quantas vezes um valor específico aparece. É a ferramenta ideal para análise de frequência sem precisar escrever um loop manualmente.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Frequência confirmada: 3 tentativas em poucos segundos. Alerta de força bruta acionado.",
      solution: "print(tentativas.count('5.5.5.5'))",
    },
    {
      id: "li-17",
      worldId: "ninho-listas",
      title: "Fusão de Buffers",
      description: "Use extend() para anexar todos os elementos de 'novos_alvos' ao final de 'alvos' e imprima 'alvos'.",
      narrative: "Dois reconhecimentos paralelos retornaram listas distintas de alvos. Funda-as em um único buffer mestre antes do ataque coordenado.",
      difficulty: "intermediario",
      setupCode: "alvos = ['A1', 'A2']\nnovos_alvos = ['B1', 'B2', 'B3']",
      expectedOutput: "['A1', 'A2', 'B1', 'B2', 'B3']",
      testCode: "assert 'extend' in code and alvos == ['A1', 'A2', 'B1', 'B2', 'B3'] and output.strip() == str(alvos)",
      starterCode: "alvos = ['A1', 'A2']\nnovos_alvos = ['B1', 'B2', 'B3']\n# Use extend() para mesclar as duas\n",
      hints: [
        { text: "lista_a.extend(lista_b) adiciona TODOS os elementos de lista_b ao final de lista_a.", cost: 10 },
        { text: "Cuidado: append(lista_b) adicionaria a lista inteira como UM item. Use extend() para 'desempacotar'.", cost: 20 },
      ],
      xpReward: 300,
      concept: "Método extend()",
      conceptExplanation: "extend() é o método correto para concatenar duas listas em uma só, mantendo a estrutura plana. Se você usasse append() com uma lista, ela viraria um item aninhado.\n\nAlternativa: você também pode usar o operador '+' para criar uma nova lista combinada (sem alterar as originais).",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Buffers unificados. Cinco alvos prontos para ataque coordenado em paralelo.",
      solution: "alvos.extend(novos_alvos)\nprint(alvos)",
    },
    {
      id: "li-18",
      worldId: "ninho-listas",
      title: "Decifrador Reverso",
      description: "Dada a lista 'codigo', inverta a ordem dos elementos usando slicing [::-1] e imprima a lista resultante.",
      narrative: "A mensagem foi interceptada de trás para frente. Inverta o buffer para reconstruir a sequência original do payload.",
      difficulty: "avancado",
      setupCode: "codigo = ['F', 'I', 'M', '_', 'O', 'L', 'A', 'H']",
      expectedOutput: "['H', 'A', 'L', 'O', '_', 'M', 'I', 'F']",
      testCode: "assert '[::-1]' in code and output.strip() == \"['H', 'A', 'L', 'O', '_', 'M', 'I', 'F']\"",
      starterCode: "codigo = ['F', 'I', 'M', '_', 'O', 'L', 'A', 'H']\n# Use slicing reverso [::-1]\n",
      hints: [
        { text: "Em slicing, o terceiro número é o passo. Usar -1 inverte a sequência.", cost: 15 },
        { text: "lista[::-1] cria uma nova lista invertida sem alterar a original.", cost: 25 },
      ],
      xpReward: 350,
      concept: "Slicing Reverso",
      conceptExplanation: "O slicing aceita três parâmetros: [inicio:fim:passo]. Quando o passo é -1, o Python percorre a lista de trás para frente, criando uma cópia invertida.\n\nÉ uma das formas mais elegantes e idiomáticas de inverter uma sequência em Python.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Mensagem decifrada. O payload original foi reconstituído byte a byte.",
      solution: "print(codigo[::-1])",
    },
    {
      id: "li-19",
      worldId: "ninho-listas",
      title: "Compilador em Massa",
      description: "Use list comprehension para gerar uma nova lista 'dobrados' com cada valor de 'numeros' multiplicado por 2 e imprima-a.",
      narrative: "Os pacotes precisam ter seu valor de header dobrado para passar pela nova rotina de validação. Compacte toda a transformação em uma única instrução.",
      difficulty: "avancado",
      setupCode: "numeros = [1, 2, 3, 4, 5]",
      expectedOutput: "[2, 4, 6, 8, 10]",
      testCode: "assert 'for' in code and dobrados == [2, 4, 6, 8, 10] and output.strip() == str(dobrados)",
      starterCode: "numeros = [1, 2, 3, 4, 5]\n# Crie 'dobrados' com list comprehension\n",
      hints: [
        { text: "Sintaxe: [expressao for item in lista]", cost: 15 },
        { text: "dobrados = [n * 2 for n in numeros]", cost: 25 },
      ],
      xpReward: 450,
      concept: "List Comprehension",
      conceptExplanation: "List comprehension é uma forma compacta e poderosa de criar listas a partir de outras listas, em uma única linha.\n\nSintaxe: [expressao for item in lista if condicao]\n\nIsso substitui um loop for inteiro com append() — mais rápido, mais legível e idiomático em Python.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Transformação em massa concluída. Todos os pacotes passaram pela validação simultaneamente.",
      solution: "dobrados = [n * 2 for n in numeros]\nprint(dobrados)",
    },
    {
      id: "li-20",
      worldId: "ninho-listas",
      title: "Ranking de Ameaças",
      description: "Use sorted() com reverse=True para criar 'ranking' com os valores de 'ameacas' em ordem decrescente, e imprima-o.",
      narrative: "O sistema de inteligência avaliou cada IP atacante com um score de risco. Ordene-os do mais perigoso para o menos perigoso para priorizar a resposta.",
      difficulty: "avancado",
      setupCode: "ameacas = [45, 92, 17, 78, 30]",
      expectedOutput: "[92, 78, 45, 30, 17]",
      testCode: "assert 'sorted' in code and 'reverse' in code and ranking == [92, 78, 45, 30, 17] and output.strip() == str(ranking)",
      starterCode: "ameacas = [45, 92, 17, 78, 30]\n# Use sorted() com reverse=True\n",
      hints: [
        { text: "sorted() retorna uma NOVA lista ordenada (não altera a original como sort()).", cost: 15 },
        { text: "ranking = sorted(ameacas, reverse=True)", cost: 25 },
      ],
      xpReward: 500,
      concept: "Função sorted() com reverse",
      conceptExplanation: "Diferente do método sort() — que modifica a lista no lugar —, a função sorted() retorna uma nova lista ordenada e preserva a original.\n\nO parâmetro reverse=True faz a ordenação ser decrescente. Você também pode passar key=funcao para ordenar por critérios customizados.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ranking de ameaças finalizado. A defesa neutralizará o IP de score 92 primeiro.",
      solution: "ranking = sorted(ameacas, reverse=True)\nprint(ranking)",
    },
    {
      id: "li-21",
      worldId: "ninho-listas",
      title: "Compilação de Path",
      description: "Dada a lista 'partes' com fragmentos de um caminho, use .join() com o separador '/' para montar uma string única. Imprima o resultado.",
      narrative: "Os fragmentos do path estão isolados. Concatene-os com separadores para reconstruir o endereço completo do arquivo alvo.",
      difficulty: "intermediario",
      setupCode: "partes = ['etc', 'opt', 'corphq', 'config']",
      expectedOutput: "etc/opt/corphq/config",
      testCode: "assert 'join' in code and output.strip() == 'etc/opt/corphq/config'",
      starterCode: "partes = ['etc', 'opt', 'corphq', 'config']\n# Use '/'.join(partes)\n",
      hints: [
        { text: "Sintaxe: separador.join(lista) — o método é da string, não da lista.", cost: 10 },
        { text: "print('/'.join(partes))", cost: 20 },
      ],
      xpReward: 520,
      concept: "Método join()",
      conceptExplanation: "str.join(iteravel) é a forma idiomática de concatenar uma lista de strings em uma única string com separador. Note que o método pertence à string separadora, não à lista. Funciona apenas com listas de strings — converta números com map(str, lista) antes se precisar.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Path reconstruído. O endereço completo está pronto para acesso direto.",
      solution: "partes = ['etc', 'opt', 'corphq', 'config']\nprint('/'.join(partes))",
    },
    {
      id: "li-22",
      worldId: "ninho-listas",
      title: "Fragmentação de Header",
      description: "Dada a string 'csv' com valores separados por vírgula, use .split(',') para quebrá-la em uma lista de tokens. Atribua a 'tokens' e imprima.",
      narrative: "Um header CSV chegou ao buffer como uma única linha. Fragmente-o em tokens individuais para processamento campo a campo.",
      difficulty: "intermediario",
      setupCode: "csv = 'id,nome,nivel,acesso'",
      expectedOutput: "['id', 'nome', 'nivel', 'acesso']",
      testCode: "assert 'split' in code and tokens == ['id', 'nome', 'nivel', 'acesso'] and output.strip() == str(tokens)",
      starterCode: "csv = 'id,nome,nivel,acesso'\n# Use csv.split(',') e atribua a 'tokens'\n",
      hints: [
        { text: "string.split(separador) devolve uma lista com os pedaços.", cost: 10 },
        { text: "tokens = csv.split(',')", cost: 20 },
      ],
      xpReward: 540,
      concept: "Método split()",
      conceptExplanation: "str.split(separador) é o inverso de join(): quebra a string em uma lista de pedaços. Sem argumentos, separa por espaços em branco. Aceita parâmetro 'maxsplit' para limitar o número de divisões. Ferramenta fundamental para parsing de texto.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Header fragmentado em 4 campos. O parser pode processar cada coluna individualmente.",
      solution: "csv = 'id,nome,nivel,acesso'\ntokens = csv.split(',')\nprint(tokens)",
    },
    {
      id: "li-23",
      worldId: "ninho-listas",
      title: "Filtro Compacto (Comprehension com if)",
      description: "Dada a lista 'numeros', use list comprehension com 'if' para criar 'pares' contendo APENAS os números pares. Imprima a lista.",
      narrative: "O sistema só processa pacotes com identificador par. Filtre o lote em uma única expressão, descartando ímpares imediatamente.",
      difficulty: "avancado",
      setupCode: "numeros = [1, 2, 3, 4, 5, 6, 7, 8]",
      expectedOutput: "[2, 4, 6, 8]",
      testCode: "assert 'for' in code and 'if' in code and pares == [2, 4, 6, 8] and output.strip() == str(pares)",
      starterCode: "numeros = [1, 2, 3, 4, 5, 6, 7, 8]\n# pares = [n for n in numeros if n % 2 == 0]\n",
      hints: [
        { text: "Sintaxe: [expressao for item in lista if condicao]", cost: 15 },
        { text: "pares = [n for n in numeros if n % 2 == 0]", cost: 25 },
      ],
      xpReward: 600,
      concept: "List Comprehension com Filtro",
      conceptExplanation: "Adicionando 'if condicao' ao final de uma list comprehension, você filtra quais itens entram na lista resultante. Substitui um loop for + if + append em uma só linha. Para filtragem mais complexa, considere usar filter() ou funções dedicadas.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Filtro aplicado. Apenas os pacotes pares seguiram para a próxima etapa do pipeline.",
      solution: "numeros = [1, 2, 3, 4, 5, 6, 7, 8]\npares = [n for n in numeros if n % 2 == 0]\nprint(pares)",
    },
    {
      id: "li-24",
      worldId: "ninho-listas",
      title: "Purga Total (clear)",
      description: "Use o método .clear() para esvaziar completamente a lista 'cache' e depois imprima a lista (deve aparecer []).",
      narrative: "O cache contém dados sensíveis. Esvazie-o imediatamente antes que o sistema de auditoria sincronize com o backup.",
      difficulty: "intermediario",
      setupCode: "cache = ['tmp1', 'tmp2', 'tmp3']",
      expectedOutput: "[]",
      testCode: "assert 'clear' in code and cache == [] and output.strip() == '[]'",
      starterCode: "cache = ['tmp1', 'tmp2', 'tmp3']\n# Use cache.clear()\n",
      hints: [
        { text: "lista.clear() remove TODOS os itens sem destruir a variável.", cost: 10 },
        { text: "cache.clear()\nprint(cache)", cost: 20 },
      ],
      xpReward: 560,
      concept: "Método clear()",
      conceptExplanation: "clear() esvazia a lista mantendo o objeto original (mesmo id na memória). Diferente de 'cache = []', que criaria uma NOVA lista — útil quando outras variáveis ou estruturas estão apontando para a mesma referência.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Cache totalmente expurgado. A auditoria encontrará apenas um buffer limpo.",
      solution: "cache = ['tmp1', 'tmp2', 'tmp3']\ncache.clear()\nprint(cache)",
    },
    {
      id: "li-25",
      worldId: "ninho-listas",
      title: "Backup Independente (copy)",
      description: "Use .copy() para criar 'backup' como uma cópia rasa de 'original'. Depois faça backup.append('NOVO'). Imprima 'original' (deve continuar inalterada).",
      narrative: "Você precisa testar mutações sem corromper o dataset principal. Crie um backup independente antes de aplicar modificações destrutivas.",
      difficulty: "avancado",
      setupCode: "original = ['A', 'B', 'C']",
      expectedOutput: "['A', 'B', 'C']",
      testCode: "assert 'copy' in code and original == ['A', 'B', 'C'] and 'NOVO' not in original and output.strip() == str(original)",
      starterCode: "original = ['A', 'B', 'C']\n# backup = original.copy() ; backup.append('NOVO') ; print(original)\n",
      hints: [
        { text: "Sem copy(), 'backup = original' criaria apenas um apelido — alterações afetariam ambos!", cost: 15 },
        { text: "backup = original.copy()\nbackup.append('NOVO')\nprint(original)", cost: 25 },
      ],
      xpReward: 620,
      concept: "Cópia vs Referência",
      conceptExplanation: "Em Python, 'b = a' faz b apontar para a MESMA lista que a — alterações em uma refletem na outra. Use .copy() (ou list(a), ou a[:]) para criar uma cópia independente. Note: é cópia 'rasa' — listas aninhadas dentro continuam compartilhadas. Para cópia profunda use copy.deepcopy().",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Backup isolado. As mutações experimentais não contaminaram o dataset principal.",
      solution: "original = ['A', 'B', 'C']\nbackup = original.copy()\nbackup.append('NOVO')\nprint(original)",
    },
    {
      id: "li-26",
      worldId: "ninho-listas",
      title: "Concatenação de Buffers (+)",
      description: "Dadas 'header' e 'payload', use o operador '+' para criar uma NOVA lista 'pacote' combinando as duas. Imprima 'pacote' (originais NÃO devem ser modificadas).",
      narrative: "Combine o cabeçalho do protocolo com o payload de dados sem alterar nenhum dos buffers originais — eles ainda serão usados em retransmissões.",
      difficulty: "intermediario",
      setupCode: "header = ['SOF', 'LEN']\npayload = ['D1', 'D2', 'D3']",
      expectedOutput: "['SOF', 'LEN', 'D1', 'D2', 'D3']",
      testCode: "assert ' + ' in code and pacote == ['SOF', 'LEN', 'D1', 'D2', 'D3'] and header == ['SOF', 'LEN']",
      starterCode: "header = ['SOF', 'LEN']\npayload = ['D1', 'D2', 'D3']\n# pacote = header + payload\n",
      hints: [
        { text: "O operador '+' em listas cria uma NOVA lista concatenada (não modifica originais).", cost: 10 },
        { text: "pacote = header + payload\nprint(pacote)", cost: 20 },
      ],
      xpReward: 580,
      concept: "Concatenação com +",
      conceptExplanation: "Diferente de extend() (que modifica a lista original), o operador '+' devolve uma NOVA lista combinada. Use '+' quando quiser preservar os originais; extend() quando quiser crescer in-place. Há também o operador '+=' (que se comporta como extend()).",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pacote montado preservando os buffers originais. Pronto para transmissão.",
      solution: "header = ['SOF', 'LEN']\npayload = ['D1', 'D2', 'D3']\npacote = header + payload\nprint(pacote)",
    },
    {
      id: "li-27",
      worldId: "ninho-listas",
      title: "Replicação de Padrão (*)",
      description: "Crie uma lista 'padrao' contendo o número 0 repetido 5 vezes usando o operador '*'. Imprima.",
      narrative: "Inicialize um buffer de 5 slots zerados para receber a próxima leitura do sensor. Use a multiplicação de listas para evitar repetição manual.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "[0, 0, 0, 0, 0]",
      testCode: "assert '* 5' in code or '*5' in code and padrao == [0, 0, 0, 0, 0] and output.strip() == str(padrao)",
      starterCode: "# padrao = [0] * 5\n",
      hints: [
        { text: "[item] * n cria uma lista com o item repetido n vezes.", cost: 10 },
        { text: "padrao = [0] * 5\nprint(padrao)", cost: 20 },
      ],
      xpReward: 580,
      concept: "Operador * em Listas",
      conceptExplanation: "[item] * n cria uma lista nova com o item repetido n vezes. Útil para inicializar buffers, vetores de zeros e padrões repetidos. Cuidado com objetos mutáveis aninhados: [[]] * 3 cria 3 referências para a MESMA lista interna.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Buffer de 5 slots inicializado em zero. Pronto para ingestão de telemetria.",
      solution: "padrao = [0] * 5\nprint(padrao)",
    },
    {
      id: "li-28",
      worldId: "ninho-listas",
      title: "Desempacotamento de Coordenadas",
      description: "Dada a lista 'coord' com 3 elementos, desempacote-os em três variáveis 'x', 'y', 'z' em uma única atribuição. Imprima x, y, z (cada um em uma linha).",
      narrative: "As coordenadas vêm em formato de lista. Atribua cada eixo a uma variável independente em uma única operação.",
      difficulty: "avancado",
      setupCode: "coord = [10, 20, 30]",
      expectedOutput: "10\n20\n30",
      testCode: "assert 'x, y, z' in code or 'x,y,z' in code.replace(' ', '') and output.strip() == '10\\n20\\n30'",
      starterCode: "coord = [10, 20, 30]\n# x, y, z = coord\n",
      hints: [
        { text: "Atribuição múltipla: a, b, c = lista — funciona se o nº de variáveis bater com o tamanho.", cost: 15 },
        { text: "x, y, z = coord\nprint(x)\nprint(y)\nprint(z)", cost: 25 },
      ],
      xpReward: 700,
      concept: "Unpacking (Desempacotamento)",
      conceptExplanation: "Python permite desempacotar coleções em variáveis de uma única vez. A quantidade de variáveis no lado esquerdo deve ser exatamente igual ao tamanho da coleção — senão dispara ValueError. Funciona com listas, tuplas e qualquer iterável.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Coordenadas extraídas em paralelo. As três dimensões estão prontas para cálculo vetorial.",
      solution: "coord = [10, 20, 30]\nx, y, z = coord\nprint(x)\nprint(y)\nprint(z)",
    },
    {
      id: "li-29",
      worldId: "ninho-listas",
      title: "Cabeça e Cauda (Starred Unpacking)",
      description: "Dada 'pacote', use desempacotamento com '*' para separar o primeiro elemento em 'header' e o RESTO em 'corpo' (lista). Imprima header (linha 1) e corpo (linha 2).",
      narrative: "O primeiro byte é o cabeçalho do protocolo; o resto é payload. Separe ambos em uma única expressão usando o operador estrela.",
      difficulty: "epico",
      setupCode: "pacote = ['SOF', 'D1', 'D2', 'D3', 'D4']",
      expectedOutput: "SOF\n['D1', 'D2', 'D3', 'D4']",
      testCode: "assert '*' in code and header == 'SOF' and corpo == ['D1', 'D2', 'D3', 'D4'] and output.strip() == \"SOF\\n['D1', 'D2', 'D3', 'D4']\"",
      starterCode: "pacote = ['SOF', 'D1', 'D2', 'D3', 'D4']\n# header, *corpo = pacote\n",
      hints: [
        { text: "Sintaxe: a, *resto = lista (a vira o primeiro, resto vira lista com os demais).", cost: 20 },
        { text: "header, *corpo = pacote\nprint(header)\nprint(corpo)", cost: 30 },
      ],
      xpReward: 800,
      concept: "Starred Unpacking",
      conceptExplanation: "O operador * no desempacotamento captura uma quantidade variável de elementos em uma lista. Pode ficar em qualquer posição: 'a, *meio, b = lista' captura primeiro, último e o meio numa lista. Padrão poderoso para parsing.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Header isolado em uma operação. O payload está pronto para descriptografia em bloco.",
      solution: "pacote = ['SOF', 'D1', 'D2', 'D3', 'D4']\nheader, *corpo = pacote\nprint(header)\nprint(corpo)",
    },
    {
      id: "li-30",
      worldId: "ninho-listas",
      title: "Ordenação por Comprimento (key)",
      description: "Dada 'nomes' com strings de tamanhos variados, use sorted() com key=len para ordenar do MAIS CURTO ao mais longo. Imprima a lista.",
      narrative: "O sistema renderiza identificadores em ordem de comprimento para otimizar a fila de exibição. Implemente a ordenação por critério customizado.",
      difficulty: "epico",
      setupCode: "nomes = ['Morpheus', 'Neo', 'Trinity', 'Oracle']",
      expectedOutput: "['Neo', 'Oracle', 'Trinity', 'Morpheus']",
      testCode: "assert 'sorted' in code and 'key' in code and 'len' in code and output.strip() == \"['Neo', 'Oracle', 'Trinity', 'Morpheus']\"",
      starterCode: "nomes = ['Morpheus', 'Neo', 'Trinity', 'Oracle']\n# Use sorted(nomes, key=len)\n",
      hints: [
        { text: "O parâmetro key= recebe uma função que extrai o critério de cada item.", cost: 20 },
        { text: "print(sorted(nomes, key=len))", cost: 30 },
      ],
      xpReward: 900,
      concept: "sorted() com key",
      conceptExplanation: "O parâmetro key= recebe qualquer função que receba um item e devolva o valor de comparação. Pode ser len (tamanho), str.lower (case-insensitive), uma lambda (key=lambda x: x[1]) ou um método. Permite ordenar por QUALQUER critério, não só pelo valor bruto.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Fila otimizada por comprimento. A renderização agora segue a ordem ideal de exibição.",
      solution: "nomes = ['Morpheus', 'Neo', 'Trinity', 'Oracle']\nprint(sorted(nomes, key=len))",
    },
  ],
};
