import { World } from "../types";

export const NINHO_LISTAS_WORLD: World = {
  id: "ninho-listas",
  title: "Ninho das Listas",
  subtitle: "Processamento em Lote",
  icon: "layers",
  color: "#A855F7",
  bgImage: "/assets/images/worlds/list_nest.png",
  lore: "O tráfego de dados no Core não viaja sozinho; ele flui em fluxos massivos e estruturados. No Ninho das Listas, você aprenderá a agrupar pacotes, fatiar buffers de memória e gerenciar coleções de informações para ataques em larga escala.",
  unlockRequirement: 3500,
  challenges: [
    {
      id: "li-01",
      worldId: "ninho-listas",
      title: "Buffer de Reconhecimento",
      description: "Crie uma lista chamada 'servidores' com as strings 'Nginx', 'Apache' e 'IIS', e imprima a lista.",
      narrative: "Sua sonda interceptou os nomes dos servidores ativos. Armazene-os em uma lista para processamento posterior.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "['Nginx', 'Apache', 'IIS']",
      testCode: "assert servidores == ['Nginx', 'Apache', 'IIS'] and output.strip() == str(servidores)",
      starterCode: "# Crie a lista de servidores\n",
      hints: [
        { text: "Listas em Python são definidas usando colchetes [ ].", cost: 10 },
        { text: "Separe os itens por vírgula.", cost: 20 },
        { text: "servidores = ['Nginx', 'Apache', 'IIS']\nprint(servidores)", cost: 30 },
      ],
      xpReward: 150,
      concept: "Criação de Listas",
      conceptExplanation: "Uma lista é como uma gaveta com várias divisórias. Você pode guardar muitas informações em uma única variável, mantendo a ordem em que foram colocadas.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Inventário de servidores registrado. O buffer está pronto para indexação.",
    },
    {
      id: "li-02",
      worldId: "ninho-listas",
      title: "Alvo Prioritário",
      description: "Dada a lista 'ips', imprima o primeiro e o último elemento (um em cada linha).",
      narrative: "Em uma lista de alvos, o primeiro e o último costumam ser o gateway e o backup. Identifique-os rapidamente.",
      difficulty: "iniciante",
      setupCode: "ips = ['192.168.1.1', '10.0.0.5', '172.16.0.254']",
      expectedOutput: "192.168.1.1\n172.16.0.254",
      testCode: "assert output.strip().split('\\n') == ['192.168.1.1', '172.16.0.254']",
      starterCode: "ips = ['192.168.1.1', '10.0.0.5', '172.16.0.254']\n# Imprima o primeiro e o último elemento\n",
      hints: [
        { text: "O índice do primeiro elemento é 0: lista[0].", cost: 10 },
        { text: "O índice do último elemento pode ser -1: lista[-1].", cost: 20 },
        { text: "print(ips[0])\nprint(ips[-1])", cost: 30 },
      ],
      xpReward: 160,
      concept: "Indexação de Listas",
      conceptExplanation: "Cada item na lista tem uma posição (índice). O Python começa a contar do zero. Você também pode contar de trás para frente usando números negativos!",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Extremidades da rede identificadas. O perímetro está mapeado.",
    },
    {
      id: "li-03",
      worldId: "ninho-listas",
      title: "Fatiamento de Buffer",
      description: "Dada a lista 'dados', imprima os primeiros 3 elementos usando o recurso de fatiamento (slicing).",
      narrative: "O dump de memória é grande demais. Extraia apenas o cabeçalho (os primeiros 3 bytes) para análise rápida.",
      difficulty: "iniciante",
      setupCode: "dados = [0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46]",
      expectedOutput: "[255, 216, 255]",
      testCode: "assert output.strip() == str(dados[:3])",
      starterCode: "dados = [255, 216, 255, 224, 0, 16, 74, 70]\n# Use slicing para pegar os 3 primeiros\n",
      hints: [
        { text: "Slicing usa a sintaxe: lista[inicio:fim].", cost: 10 },
        { text: "O item no índice 'fim' não é incluído. Use :3 para pegar 0, 1 e 2.", cost: 20 },
        { text: "print(dados[:3])", cost: 30 },
      ],
      xpReward: 180,
      concept: "Fatiamento (Slicing)",
      conceptExplanation: "Slicing permite 'cortar' pedaços da lista. Se você quer do início até o índice 3 (sem incluir o 3), use [:3].",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Cabeçalho extraído. O tipo de arquivo foi identificado como JPEG criptografado.",
    },
    {
      id: "li-04",
      worldId: "ninho-listas",
      title: "Contagem de Hosts",
      description: "Dada a lista 'conexoes', use a função len() para imprimir a quantidade de conexões ativas.",
      narrative: "Quantos dispositivos estão pendurados na nossa rede agora? O sistema precisa de um número exato para alocar largura de banda.",
      difficulty: "iniciante",
      setupCode: "conexoes = ['user1', 'user2', 'bot3', 'admin', 'guest']",
      expectedOutput: "5",
      testCode: "assert output.strip() == '5'",
      starterCode: "conexoes = ['user1', 'user2', 'bot3', 'admin', 'guest']\n# Imprima o tamanho da lista\n",
      hints: [
        { text: "A função len(lista) retorna o número de itens.", cost: 10 },
        { text: "print(len(conexoes))", cost: 30 },
      ],
      xpReward: 150,
      concept: "Função len()",
      conceptExplanation: "len() é abreviação de 'length' (comprimento). Use para saber quantos itens existem em qualquer coleção.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Carga de rede calculada. 5 sessões ativas detectadas.",
    },
    {
      id: "li-05",
      worldId: "ninho-listas",
      title: "Injeção de Pacote",
      description: "Dada a lista 'blacklist', adicione a string '10.0.0.1' ao final da lista usando append() e imprima a lista completa.",
      narrative: "Um novo IP suspeito foi detectado tentando força bruta. Insira-o na nossa lista negra imediatamente.",
      difficulty: "iniciante",
      setupCode: "blacklist = ['1.1.1.1', '2.2.2.2']",
      expectedOutput: "['1.1.1.1', '2.2.2.2', '10.0.0.1']",
      testCode: "assert '10.0.0.1' in blacklist and output.strip() == str(blacklist)",
      starterCode: "blacklist = ['1.1.1.1', '2.2.2.2']\n# Adicione '10.0.0.1' e imprima\n",
      hints: [
        { text: "Use lista.append(item) para adicionar algo ao final.", cost: 10 },
        { text: "Note que append() altera a lista original, não precisa de '='.", cost: 20 },
        { text: "blacklist.append('10.0.0.1')\nprint(blacklist)", cost: 30 },
      ],
      xpReward: 170,
      concept: "Método append()",
      conceptExplanation: "O append() coloca um novo item 'no rabo' da lista. É o método mais comum para crescer uma lista dinamicamente.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "IP bloqueado. O sistema de defesa foi atualizado.",
    },
    {
      id: "li-06",
      worldId: "ninho-listas",
      title: "Limpeza de Logs",
      description: "Dada a lista 'logs', remova o último elemento usando pop() e imprima a lista atualizada.",
      narrative: "O último registro do log contém sua pegada digital. Remova-o antes que o sistema de auditoria o detecte.",
      difficulty: "iniciante",
      setupCode: "logs = ['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS', 'YOUR_IP']",
      expectedOutput: "['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS']",
      testCode: "assert 'YOUR_IP' not in logs and output.strip() == str(logs)",
      starterCode: "logs = ['LOGIN', 'ACCESS_CORE', 'UPLOAD_VIRUS', 'YOUR_IP']\n# Remova o último log e imprima a lista\n",
      hints: [
        { text: "O método lista.pop() remove e retorna o último item.", cost: 10 },
        { text: "logs.pop()\nprint(logs)", cost: 30 },
      ],
      xpReward: 180,
      concept: "Método pop()",
      conceptExplanation: "pop() 'estoura' o último item da lista para fora. Se você não passar nenhum índice, ele tira o último por padrão.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Evidência removida. Sua presença nesta thread agora é fantasmagórica.",
    },
    {
      id: "li-07",
      worldId: "ninho-listas",
      title: "Ordenação de Portas",
      description: "Dada a lista de portas, ordene-a em ordem crescente usando sort() e imprima o resultado.",
      narrative: "As portas escaneadas estão uma bagunça. Organize-as numericamente para que possamos planejar o ataque sequencial.",
      difficulty: "intermediario",
      setupCode: "portas = [80, 22, 443, 21, 8080]",
      expectedOutput: "[21, 22, 80, 443, 8080]",
      testCode: "assert portas == [21, 22, 80, 443, 8080] and output.strip() == str(portas)",
      starterCode: "portas = [80, 22, 443, 21, 8080]\n# Ordene a lista e imprima\n",
      hints: [
        { text: "O método lista.sort() organiza a lista 'in-place' (na própria variável).", cost: 10 },
        { text: "portas.sort()\nprint(portas)", cost: 30 },
      ],
      xpReward: 200,
      concept: "Método sort()",
      conceptExplanation: "O sort() coloca a lista em ordem. Se forem números, do menor para o maior. Se forem strings, em ordem alfabética.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Vetor de ataque organizado. Começaremos pela porta FTP (21).",
    },
    {
      id: "li-08",
      worldId: "ninho-listas",
      title: "Análise de Latência",
      description: "Dada a lista 'pings', imprima o menor e o maior valor usando as funções min() e max().",
      narrative: "Encontre o servidor mais rápido e o mais lento na rede local para decidir onde hospedar nosso backdoor.",
      difficulty: "intermediario",
      setupCode: "pings = [45, 12, 89, 5, 120, 31]",
      expectedOutput: "5\n120",
      testCode: "assert 'min' in code and 'max' in code and '5' in output and '120' in output",
      starterCode: "pings = [45, 12, 89, 5, 120, 31]\n# Imprima o mínimo e o máximo\n",
      hints: [
        { text: "Use min(lista) para o menor valor e max(lista) para o maior.", cost: 10 },
      ],
      xpReward: 210,
      concept: "Funções min() e max()",
      conceptExplanation: "Essas funções utilitárias analisam toda a lista e retornam o extremo desejado em um piscar de olhos.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Servidor de 5ms selecionado como host primário.",
    },
    {
      id: "li-09",
      worldId: "ninho-listas",
      title: "Carga Total de Dados",
      description: "Dada a lista 'pacotes' (tamanhos em KB), imprima a soma total de todos os elementos usando sum().",
      narrative: "Calcule o peso total da carga útil que estamos prestes a exfiltrar dos servidores da CorpHQ.",
      difficulty: "intermediario",
      setupCode: "pacotes = [120, 500, 250, 10, 80]",
      expectedOutput: "960",
      testCode: "assert 'sum' in code and output.strip() == '960'",
      starterCode: "pacotes = [120, 500, 250, 10, 80]\n# Calcule a soma e imprima\n",
      hints: [
        { text: "A função sum(lista) soma todos os números da lista automaticamente.", cost: 10 },
      ],
      xpReward: 220,
      concept: "Função sum()",
      conceptExplanation: "Ao invés de somar um por um, a função sum() faz o trabalho pesado de iteração para você.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "960KB prontos para transferência. Iniciando upload criptografado.",
    },
    {
      id: "li-10",
      worldId: "ninho-listas",
      title: "Filtro de Invasor",
      description: "Verifique se '192.168.1.50' está na lista 'permitidos' usando o operador 'in' e imprima o resultado (True ou False).",
      narrative: "Uma requisição externa chegou. Verifique se o IP de origem consta na nossa lista branca de acesso permitido.",
      difficulty: "intermediario",
      setupCode: "permitidos = ['192.168.1.10', '192.168.1.20', '192.168.1.30']",
      expectedOutput: "False",
      testCode: "assert 'in' in code and output.strip() == 'False'",
      starterCode: "permitidos = ['192.168.1.10', '192.168.1.20', '192.168.1.30']\n# Verifique se '192.168.1.50' está na lista\n",
      hints: [
        { text: "Use a sintaxe: item in lista.", cost: 10 },
        { text: "Isso retorna um valor Booleano (True ou False).", cost: 20 },
      ],
      xpReward: 230,
      concept: "Operador in",
      conceptExplanation: "O operador 'in' (dentro) é a forma mais rápida de perguntar se um valor existe dentro de uma coleção.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Acesso negado. O invasor foi redirecionado para um honeypot.",
    },
    {
      id: "li-11",
      worldId: "ninho-listas",
      title: "Matriz de Dados",
      description: "Dada a matriz 3x3 'grid', acesse e imprima o elemento central (o número 5).",
      narrative: "O Core usa proteção em camadas (matrizes). Para acessar o núcleo, você deve indexar a coordenada central da grade de segurança.",
      difficulty: "avancado",
      setupCode: "grid = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]",
      expectedOutput: "5",
      testCode: "assert 'grid[1][1]' in code and output.strip() == '5'",
      starterCode: "grid = [\n  [1, 2, 3],\n  [4, 5, 6],\n  [7, 8, 9]\n]\n# Acesse o valor 5 e imprima\n",
      hints: [
        { text: "Para acessar listas dentro de listas, use dois pares de colchetes: grid[linha][coluna].", cost: 10 },
        { text: "Lembre-se: índices começam em 0. O elemento central está na linha 1, coluna 1.", cost: 20 },
        { text: "print(grid[1][1])", cost: 30 },
      ],
      xpReward: 300,
      concept: "Listas Aninhadas (Matrizes)",
      conceptExplanation: "Uma lista pode conter outras listas! Isso cria estruturas de dados em 2D, como planilhas ou mapas. Você acessa primeiro a 'lista externa' e depois a 'lista interna'.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Núcleo acessado! A grade de segurança foi perfurada exatamente no centro.",
    },
    {
      id: "li-12",
      worldId: "ninho-listas",
      title: "Desafio Final: Swap de Chaves",
      description: "Dada a lista 'chaves' com dois elementos, inverta a ordem deles (troque o primeiro pelo segundo e vice-versa) e imprima a lista.",
      narrative: "Para enganar o firewall, devemos inverter a ordem das chaves de criptografia no buffer de saída. Rápido, o tempo está acabando!",
      difficulty: "avancado",
      setupCode: "chaves = ['PUB_KEY', 'PRIV_KEY']",
      expectedOutput: "['PRIV_KEY', 'PUB_KEY']",
      testCode: "assert chaves == ['PRIV_KEY', 'PUB_KEY'] and output.strip() == str(chaves)",
      starterCode: "chaves = ['PUB_KEY', 'PRIV_KEY']\n# Inverta a ordem dos elementos e imprima\n",
      hints: [
        { text: "Você pode usar uma variável temporária ou a atribuição múltipla do Python.", cost: 10 },
        { text: "Atribuição múltipla: a, b = b, a", cost: 20 },
        { text: "chaves[0], chaves[1] = chaves[1], chaves[0]\nprint(chaves)", cost: 30 },
      ],
      xpReward: 400,
      concept: "Troca de Valores (Swap)",
      conceptExplanation: "O Python permite trocar valores de variáveis ou itens de lista de forma elegante: x, y = y, x. Isso evita a necessidade de criar variáveis extras apenas para a troca.",
      successNpc: "AI-7",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Handshake invertido! O firewall foi enganado e você agora tem acesso ao setor de armazenamento em lote. Excelente trabalho, Operador.",
    },
  ],
};
