import { World } from "../types";

export const NUCLEO_SINTETICO_WORLD: World = {
  id: "nucleo-sintetico",
  title: "Núcleo Sintético",
  subtitle: "Deep Learning",
  icon: "sparkles",
  color: "#FBBF24",
  bgImage: "/assets/images/worlds/synthetic_core.png",
  lore: "O auge da IA. Redes neurais profundas, visão computacional e processamento de linguagem natural — a fronteira do conhecimento cibernético.",
  unlockRequirement: 20000,
  challenges: [
    {
      id: "ds-dl-01",
      worldId: "nucleo-sintetico",
      title: "Despertar da Rede",
      description: "Monte um dicionario config com camadas_ocultas=3 e tensores=128. Imprima config['tensores'].",
      narrative: "Inicialize a rede neural profunda.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "128",
      testCode: "assert 'config' in code and 'camadas_ocultas' in code and 'tensores' in code and \"['tensores']\" in code",
      starterCode: "# Crie config com camadas_ocultas e tensores\n",
      hints: [
        { text: "Use um dicionario Python para representar a configuracao da rede.", cost: 10 },
        { text: "Acesse um valor do dicionario com config['tensores'].", cost: 20 },
        { text: "config = {'camadas_ocultas': 3, 'tensores': 128}\nprint(config['tensores'])", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Frameworks de Deep Learning",
      conceptExplanation: "TensorFlow (Google) e PyTorch (Meta) são os dois frameworks dominantes de Deep Learning — toda IA moderna usa um dos dois. Ambos manipulam TENSORES (generalizações de matrizes para N dimensões: escalar 0D, vetor 1D, matriz 2D, imagem RGB 3D, vídeo 4D). Ambos fazem DIFERENCIAÇÃO AUTOMÁTICA: rastreiam operações e calculam gradientes sozinhos — motor matemático de backpropagation. TensorFlow + Keras é dominante em produção; PyTorch em pesquisa. Ambos rodam em GPU/TPU acelerando 50-100x.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Sinapses acesas.",
      solution: "config = {'camadas_ocultas': 3, 'tensores': 128}\nprint(config['tensores'])",
    },
    {
      id: "ds-dl-02",
      worldId: "nucleo-sintetico",
      title: "Sequential e Dense",
      description: "Crie modelo = Sequential([Dense(64), Dense(10)]) e imprima quantas camadas ele possui.",
      narrative: "Empilhe camadas para construir a rede.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n): self.n = n\nclass Sequential:\n    def __init__(self, layers): self.l = layers",
      expectedOutput: "2",
      testCode: "assert 'Sequential' in code and 'Dense' in code and 'len' in code and 'modelo.l' in code",
      starterCode: "from tensorflow.keras import Sequential\nfrom tensorflow.keras.layers import Dense\n# Modelo com 2 Dense e print do total de camadas\n",
      hints: [
        { text: "Sequential recebe uma lista de camadas.", cost: 20 },
        { text: "Neste simulador, as camadas ficam em modelo.l.", cost: 25 },
        { text: "modelo = Sequential([Dense(64), Dense(10)])\nprint(len(modelo.l))", cost: 30 },
      ],
      xpReward: 1050,
      concept: "API Sequential e Dense",
      conceptExplanation: "Sequential é a API simples do Keras: passe lista de camadas, conexões automáticas em sequência. Dense (totalmente conectada) é o tijolo básico — cada neurônio recebe entrada de TODOS os neurônios da camada anterior. Camadas ocultas: 32, 64, 128, 256 são valores típicos (decisão sua). Última camada determinada pelo problema: 1 neurônio (regressão), N (N classes). Para arquiteturas complexas (Transformers, ResNets), use API Funcional. Outras camadas: Conv2D (imagem), LSTM (sequência), Dropout (regularização).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Arquitetura registrada.",
      solution: "modelo = Sequential([Dense(64), Dense(10)])\nprint(len(modelo.l))",
    },
    {
      id: "ds-dl-03",
      worldId: "nucleo-sintetico",
      title: "Compilação",
      description: "Chame modelo.compile(optimizer='adam', loss='mse') e imprima a loss gravada no modelo.",
      narrative: "Configure motor de aprendizado.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def compile(self, optimizer, loss):\n        self.optimizer = optimizer\n        self.loss = loss\nmodelo = Modelo()",
      expectedOutput: "mse",
      testCode: "assert 'compile' in code and 'adam' in code and 'mse' in code and 'modelo.loss' in code",
      starterCode: "# compile com adam e mse, depois imprima modelo.loss\n",
      hints: [
        { text: "compile configura optimizer e loss antes do treino.", cost: 20 },
        { text: "Depois de compilar, acesse o atributo modelo.loss.", cost: 25 },
        { text: "modelo.compile(optimizer='adam', loss='mse')\nprint(modelo.loss)", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Compilação (Optimizer e Loss)",
      conceptExplanation: "compile() configura como aprender. (1) OPTIMIZER: 'adam' (padrão moderno, robusto), 'sgd' (clássico), 'rmsprop' (RNNs). (2) LOSS (função de perda — mede QUÃO ERRADO): 'mse' (regressão), 'binary_crossentropy' (binária), 'categorical_crossentropy' (multi-classe one-hot), 'sparse_categorical_crossentropy' (multi-classe inteiros). (3) METRICS opcionais: ['accuracy']. Sem compile, fit() falha — rede precisa saber medir erro e atualizar pesos.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Motor pronto.",
      solution: "modelo.compile(optimizer='adam', loss='mse')\nprint(modelo.loss)",
    },
    {
      id: "ds-dl-04",
      worldId: "nucleo-sintetico",
      title: "Treinamento (fit)",
      description: "Chame modelo.fit(X, y, epochs=5) e imprima 'Treinamento concluído.'.",
      narrative: "Treine por 5 epochs.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def fit(self, X, y, epochs): print(f'Treinando por {epochs} epochs...')\nmodelo = Modelo()\nX = [[1, 2], [3, 4]]\ny = [0, 1]",
      expectedOutput: "Treinando por 5 epochs...\nTreinamento concluído.",
      testCode: "assert 'fit' in code and 'epochs' in code",
      starterCode: "# fit por 5 epochs\n",
      hints: [
        { text: "fit é onde acontece o treino real. Passe X, y e epochs.", cost: 20 },
        { text: "Cada epoch é uma passagem COMPLETA pelos dados, ajustando pesos por batch.", cost: 25 },
        { text: "modelo.fit(X, y, epochs=5)\\nprint('Treinamento concluído.')", cost: 30 },
      ],
      xpReward: 1150,
      concept: "Epochs e Batches",
      conceptExplanation: "EPOCH = passagem completa pelos dados de treino. Dentro de cada epoch, dados são divididos em BATCHES (lotes — 32, 64 exemplos): gradiente é calculado por batch, não por exemplo individual nem pelo total ('mini-batch gradient descent'). Mais epochs reduzem erro de treino, mas em EXCESSO causam overfitting (memorização). Monitore erro no conjunto de validação (validation_split=0.2 no fit): quando erro de validação para de cair e começa a subir, você passou do ponto. Combata overfitting: dropout, regularização, early stopping, mais dados.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pesos convergiram.",
      solution: "modelo.fit(X, y, epochs=5)\nprint('Treinamento concluído.')",
    },
    {
      id: "ds-dl-05",
      worldId: "nucleo-sintetico",
      title: "Activation: ReLU",
      description: "Crie Dense(64, activation='relu') e imprima 'ReLU ativada.'.",
      narrative: "ReLU é a função de ativação padrão das redes modernas.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n, activation=None): self.a = activation",
      expectedOutput: "ReLU ativada.",
      testCode: "assert \"activation='relu'\" in code or 'activation=\"relu\"' in code",
      starterCode: "from tensorflow.keras.layers import Dense\n# Dense com 64 neurônios e ReLU\n",
      hints: [
        { text: "Passe activation='relu' ao criar a camada. Sem ativação, a rede é só uma sequência de operações lineares.", cost: 20 },
        { text: "ReLU = max(0, x): zera valores negativos, mantém positivos. Simples e eficaz.", cost: 25 },
        { text: "camada = Dense(64, activation='relu')\\nprint('ReLU ativada.')", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Funções de Ativação",
      conceptExplanation: "Funções de ativação introduzem NÃO-LINEARIDADE na rede — sem elas, qualquer rede (não importa quantas camadas) é equivalente a uma única transformação linear. ReLU = max(0, x) é a padrão moderna: simples, rápida, evita 'vanishing gradients' (problema das ativações antigas tanh/sigmoid). Variantes: LeakyReLU (permite gradiente pequeno para negativos), ELU, GELU (usado em Transformers). Para camadas DE SAÍDA, escolha conforme problema: sigmoid (binário), softmax (multi-classe), linear/sem ativação (regressão).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Não-linearidade injetada.",
      solution: "camada = Dense(64, activation='relu')\nprint('ReLU ativada.')",
    },
    {
      id: "ds-dl-06",
      worldId: "nucleo-sintetico",
      title: "Activation: Sigmoid",
      description: "Crie Dense(1, activation='sigmoid') para saída binária. Imprima 'Sigmoid pronta.'.",
      narrative: "Para problemas binários, a saída precisa ser uma probabilidade entre 0 e 1.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n, activation=None): self.a = activation",
      expectedOutput: "Sigmoid pronta.",
      testCode: "assert 'sigmoid' in code",
      starterCode: "from tensorflow.keras.layers import Dense\n# Saída binária com sigmoid\n",
      hints: [
        { text: "Para problema binário, use 1 neurônio com sigmoid — saída entre 0 e 1 (probabilidade).", cost: 25 },
        { text: "Combine com loss='binary_crossentropy' no compile().", cost: 30 },
        { text: "saida = Dense(1, activation='sigmoid')\\nprint('Sigmoid pronta.')", cost: 35 },
      ],
      xpReward: 1050,
      concept: "Sigmoid (Saída Binária)",
      conceptExplanation: "Sigmoid: σ(x) = 1/(1+e^-x), mapeia qualquer número real para (0, 1) — ideal para saída de classificação BINÁRIA, interpretada como probabilidade. Use Dense(1, activation='sigmoid') na última camada + binary_crossentropy como loss. NÃO use sigmoid em camadas internas de redes modernas — ela causa 'vanishing gradients' (gradiente quase zero para entradas grandes/pequenas), ReLU é melhor. Para saída de probabilidades em MULTI-classe, use softmax (não sigmoid em cada).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Saída probabilística binária.",
      solution: "saida = Dense(1, activation='sigmoid')\nprint('Sigmoid pronta.')",
    },
    {
      id: "ds-dl-07",
      worldId: "nucleo-sintetico",
      title: "Activation: Softmax",
      description: "Crie Dense(10, activation='softmax') para 10 classes. Imprima 'Softmax configurada.'.",
      narrative: "Para classificar dígitos 0-9, você precisa de 10 probabilidades que somem 1.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n, activation=None): self.a = activation",
      expectedOutput: "Softmax configurada.",
      testCode: "assert 'softmax' in code",
      starterCode: "from tensorflow.keras.layers import Dense\n# Saída para 10 classes com softmax\n",
      hints: [
        { text: "Softmax: N saídas que somam 1 — vetor de probabilidades por classe.", cost: 25 },
        { text: "Use Dense(N_CLASSES, activation='softmax') + categorical_crossentropy.", cost: 30 },
        { text: "saida = Dense(10, activation='softmax')\\nprint('Softmax configurada.')", cost: 35 },
      ],
      xpReward: 1050,
      concept: "Softmax (Multi-classe)",
      conceptExplanation: "Softmax: para classificação MULTI-classe, mapeia N saídas para N probabilidades que SOMAM 1. softmax(z_i) = e^(z_i) / Σ e^(z_j). Use Dense(N_classes, activation='softmax') na última camada + categorical_crossentropy (se y é one-hot) ou sparse_categorical_crossentropy (se y é inteiros 0..N). A previsão final é a classe com maior probabilidade (np.argmax). NUNCA use sigmoid em cada classe separadamente em multi-classe — softmax garante que as N probabilidades somem 1 (mutuamente exclusivas).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição de classes configurada.",
      solution: "saida = Dense(10, activation='softmax')\nprint('Softmax configurada.')",
    },
    {
      id: "ds-dl-08",
      worldId: "nucleo-sintetico",
      title: "Input Shape",
      description: "Crie Dense(64, input_shape=(784,)) e imprima 'Input definido.'.",
      narrative: "A primeira camada precisa saber a forma da entrada.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n, input_shape=None): self.s = input_shape",
      expectedOutput: "Input definido.",
      testCode: "assert 'input_shape' in code",
      starterCode: "from tensorflow.keras.layers import Dense\n# Dense(64) com input_shape (784,)\n",
      hints: [
        { text: "input_shape é uma TUPLA — defina apenas na PRIMEIRA camada (as seguintes inferem do anterior).", cost: 25 },
        { text: "Para imagens 28x28 flatten: (784,). Para batch implícito, NÃO inclua a dim de batch.", cost: 30 },
        { text: "entrada = Dense(64, input_shape=(784,))\\nprint('Input definido.')", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Input Shape",
      conceptExplanation: "A PRIMEIRA camada precisa do input_shape: tupla com as dimensões de UM exemplo (sem batch). Imagem 28x28 flatten: (784,); imagem RGB 32x32: (32, 32, 3); sequência de 100 tokens com embedding 50: (100, 50). Camadas seguintes inferem automaticamente. Em Sequential, defina assim ou via .build(input_shape=...) ou tf.keras.Input(shape=...). Erro de shape é o bug mais comum em DL — verifique sempre com modelo.summary() após criar.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Entrada dimensionada.",
      solution: "entrada = Dense(64, input_shape=(784,))\nprint('Input definido.')",
    },
    {
      id: "ds-dl-09",
      worldId: "nucleo-sintetico",
      title: "Dropout",
      description: "Crie Dropout(0.5) e imprima 'Dropout ativo.'.",
      narrative: "Regularização: 'desliga' neurônios aleatoriamente para evitar overfitting.",
      difficulty: "avancado",
      setupCode: "class Dropout:\n    def __init__(self, rate): self.r = rate",
      expectedOutput: "Dropout ativo.",
      testCode: "assert 'Dropout' in code",
      starterCode: "from tensorflow.keras.layers import Dropout\n# Dropout 0.5\n",
      hints: [
        { text: "Dropout(taxa) recebe a probabilidade de desligar cada neurônio (entre 0 e 1).", cost: 25 },
        { text: "0.5 é comum: 50% dos neurônios são desligados a cada batch DURANTE TREINO (no teste todos ficam ativos).", cost: 30 },
        { text: "drop = Dropout(0.5)\\nprint('Dropout ativo.')", cost: 35 },
      ],
      xpReward: 1100,
      concept: "Dropout",
      conceptExplanation: "Dropout é regularização: durante o TREINO, desliga aleatoriamente uma fração de neurônios em cada batch — força a rede a não depender de neurônios específicos, prevenindo overfitting. Durante a INFERÊNCIA, todos ficam ativos. Taxa típica: 0.2-0.5 em camadas Dense; menor em Conv (0.1-0.25). Coloque após camadas ocultas, NÃO na saída. É talvez a técnica de regularização mais popular em DL — simples e eficaz. Alternativas: L2, BatchNormalization, EarlyStopping.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Overfitting combatido.",
      solution: "drop = Dropout(0.5)\nprint('Dropout ativo.')",
    },
    {
      id: "ds-dl-10",
      worldId: "nucleo-sintetico",
      title: "Batch Normalization",
      description: "Crie BatchNormalization() e imprima 'BatchNorm.'.",
      narrative: "Normaliza ativações por batch — acelera e estabiliza o treino.",
      difficulty: "avancado",
      setupCode: "class BatchNormalization: pass",
      expectedOutput: "BatchNorm.",
      testCode: "assert 'BatchNormalization' in code",
      starterCode: "from tensorflow.keras.layers import BatchNormalization\n# Instancie e imprima\n",
      hints: [
        { text: "BatchNormalization() não recebe parâmetros obrigatórios. Adicione após camadas Dense/Conv.", cost: 30 },
        { text: "Normaliza as ativações (média 0, variância 1) por batch — estabiliza distribuição interna.", cost: 35 },
        { text: "bn = BatchNormalization()\\nprint('BatchNorm.')", cost: 40 },
      ],
      xpReward: 1150,
      concept: "Batch Normalization",
      conceptExplanation: "Batch Normalization normaliza as ativações de uma camada por batch (média 0, variância 1), reduzindo 'internal covariate shift'. Benefícios: (1) treino MUITO mais rápido (você pode usar learning rates maiores); (2) regularização parcial (substitui ou complementa dropout); (3) menos sensibilidade à inicialização. Coloque entre camadas Dense/Conv e a ativação — Conv → BN → ReLU. Durante inferência, usa estatísticas acumuladas no treino. Para sequências, prefira LayerNormalization.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ativações estabilizadas.",
      solution: "bn = BatchNormalization()\nprint('BatchNorm.')",
    },
    {
      id: "ds-dl-11",
      worldId: "nucleo-sintetico",
      title: "Flatten",
      description: "Crie Flatten() para achatar tensor 2D em 1D. Imprima 'Flatten ok.'.",
      narrative: "Conecte saída de Conv2D com Dense — precisa achatar primeiro.",
      difficulty: "avancado",
      setupCode: "class Flatten: pass",
      expectedOutput: "Flatten ok.",
      testCode: "assert 'Flatten' in code",
      starterCode: "from tensorflow.keras.layers import Flatten\n# Instancie\n",
      hints: [
        { text: "Flatten() converte tensor (h, w, c) em vetor 1D — usado entre Conv2D e Dense.", cost: 25 },
        { text: "Não tem parâmetros — só converte shape.", cost: 30 },
        { text: "f = Flatten()\\nprint('Flatten ok.')", cost: 35 },
      ],
      xpReward: 950,
      concept: "Flatten",
      conceptExplanation: "Flatten reformata um tensor multidimensional em VETOR 1D. Cenário típico em CNN: após várias camadas Conv2D + Pooling, você tem tensores 3D (h, w, canais). Antes da camada Dense final (que espera vetor 1D), use Flatten para achatar. Ex: tensor (4, 4, 64) → vetor de 1024 elementos. Alternativa em problemas modernos: GlobalAveragePooling2D, que faz médias por canal (reduz parâmetros significativamente — preferido em redes maiores como ResNet).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tensor achatado.",
      solution: "f = Flatten()\nprint('Flatten ok.')",
    },
    {
      id: "ds-dl-12",
      worldId: "nucleo-sintetico",
      title: "Convolutional 2D",
      description: "Crie Conv2D(32, kernel_size=(3,3), activation='relu') e imprima 'Conv2D pronta.'.",
      narrative: "Camadas convolucionais são a base de visão computacional.",
      difficulty: "avancado",
      setupCode: "class Conv2D:\n    def __init__(self, n, kernel_size=None, activation=None): pass",
      expectedOutput: "Conv2D pronta.",
      testCode: "assert 'Conv2D' in code and 'kernel_size' in code",
      starterCode: "from tensorflow.keras.layers import Conv2D\n# 32 filtros 3x3 com ReLU\n",
      hints: [
        { text: "Conv2D(filtros, kernel_size, activation). Filtros = quantos mapas de features extrair.", cost: 30 },
        { text: "kernel_size=(3,3) é o padrão clássico para imagens.", cost: 35 },
        { text: "conv = Conv2D(32, kernel_size=(3,3), activation='relu')\\nprint('Conv2D pronta.')", cost: 40 },
      ],
      xpReward: 1200,
      concept: "Convolutional Neural Networks",
      conceptExplanation: "Conv2D é o tijolo de CNNs (Convolutional Neural Networks) — dominantes em visão computacional. Aplica FILTROS (kernels) pequenos (3x3, 5x5) deslizando sobre a imagem, extraindo padrões locais: bordas, texturas, formas. Diferente de Dense (que olha pixels independentes), Conv preserva relações espaciais. Parâmetros: filtros (quantos kernels = quantos mapas de features), kernel_size (tamanho do filtro), strides (passo do deslizamento), padding ('same' preserva tamanho, 'valid' reduz). Arquiteturas famosas: ResNet, VGG, Inception, EfficientNet.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Filtros visuais ativos.",
      solution: "conv = Conv2D(32, kernel_size=(3,3), activation='relu')\nprint('Conv2D pronta.')",
    },
    {
      id: "ds-dl-13",
      worldId: "nucleo-sintetico",
      title: "MaxPooling 2D",
      description: "Crie MaxPooling2D(pool_size=(2,2)) e imprima 'Pool ok.'.",
      narrative: "Reduz dimensionalidade espacial preservando o máximo.",
      difficulty: "avancado",
      setupCode: "class MaxPooling2D:\n    def __init__(self, pool_size=None): pass",
      expectedOutput: "Pool ok.",
      testCode: "assert 'MaxPooling2D' in code",
      starterCode: "from tensorflow.keras.layers import MaxPooling2D\n# Pool 2x2\n",
      hints: [
        { text: "MaxPooling2D(pool_size=(2,2)) reduz a imagem pela metade pegando o MÁXIMO em cada janela 2x2.", cost: 30 },
        { text: "Vai SEMPRE após Conv2D — pattern: Conv → ReLU → Pool.", cost: 35 },
        { text: "pool = MaxPooling2D(pool_size=(2,2))\\nprint('Pool ok.')", cost: 40 },
      ],
      xpReward: 1150,
      concept: "Pooling",
      conceptExplanation: "Pooling REDUZ dimensionalidade espacial entre camadas Conv — diminui processamento e introduz invariância a pequenas translações. MaxPooling pega o MÁXIMO em cada janela (preserva ativações mais fortes); AveragePooling tira a média (mais suave). Tamanho típico: (2,2) com strides=(2,2) — reduz imagem pela metade. Pattern clássico em CNN: Conv2D → ReLU → MaxPooling, repetido várias vezes, depois Flatten + Dense. Em arquiteturas modernas (ResNet, EfficientNet), pooling é substituído por strided convolutions ou GlobalAveragePooling.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Dimensão espacial reduzida.",
      solution: "pool = MaxPooling2D(pool_size=(2,2))\nprint('Pool ok.')",
    },
    {
      id: "ds-dl-14",
      worldId: "nucleo-sintetico",
      title: "LSTM",
      description: "Crie LSTM(64) para processar sequências. Imprima 'LSTM ativa.'.",
      narrative: "Para texto e séries temporais, redes recorrentes lembram do passado.",
      difficulty: "avancado",
      setupCode: "class LSTM:\n    def __init__(self, n): pass",
      expectedOutput: "LSTM ativa.",
      testCode: "assert 'LSTM' in code",
      starterCode: "from tensorflow.keras.layers import LSTM\n# LSTM com 64 unidades\n",
      hints: [
        { text: "LSTM(unidades) cria uma camada recorrente. Útil para sequências (texto, séries temporais).", cost: 30 },
        { text: "Mantém um 'estado' interno entre passos da sequência — memória de curto e longo prazo.", cost: 35 },
        { text: "lstm = LSTM(64)\\nprint('LSTM ativa.')", cost: 40 },
      ],
      xpReward: 1200,
      concept: "Recurrent Neural Networks (LSTM)",
      conceptExplanation: "LSTM (Long Short-Term Memory) é o tipo mais popular de RNN para processar SEQUÊNCIAS (texto, áudio, séries temporais). Diferente de Dense/Conv, mantém ESTADO interno entre passos da sequência — 'lembra' do que veio antes. Resolve o problema de vanishing gradients de RNNs simples através de 'gates' (esquecimento, entrada, saída). Variantes: GRU (mais simples e rápida), Bidirectional (processa em ambas direções). NOTA: para texto moderno, TRANSFORMERS (BERT, GPT) substituíram LSTMs na maioria dos casos — atenção paralelizável e melhor performance em sequências longas.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Memória sequencial ativada.",
      solution: "lstm = LSTM(64)\nprint('LSTM ativa.')",
    },
    {
      id: "ds-dl-15",
      worldId: "nucleo-sintetico",
      title: "Embedding (NLP)",
      description: "Crie Embedding(input_dim=10000, output_dim=128) e imprima 'Embedding criado.'.",
      narrative: "Texto vira vetores densos antes de qualquer rede.",
      difficulty: "avancado",
      setupCode: "class Embedding:\n    def __init__(self, input_dim, output_dim): pass",
      expectedOutput: "Embedding criado.",
      testCode: "assert 'Embedding' in code and 'output_dim' in code",
      starterCode: "from tensorflow.keras.layers import Embedding\n# vocab 10000, dimensão 128\n",
      hints: [
        { text: "Embedding(vocab_size, dim) mapeia inteiros (índices de palavras) para vetores densos.", cost: 30 },
        { text: "Primeira camada em modelos de NLP — input são índices, saída são vetores.", cost: 35 },
        { text: "emb = Embedding(input_dim=10000, output_dim=128)\\nprint('Embedding criado.')", cost: 40 },
      ],
      xpReward: 1200,
      concept: "Embeddings",
      conceptExplanation: "Embedding é a primeira camada em quase qualquer modelo de NLP. Recebe inteiros (índices de palavras de um vocabulário) e retorna VETORES DENSOS aprendíveis. Vantagens vs one-hot: (1) muito menos parâmetros (vocab de 50k → vetor 128 vs 50k); (2) palavras similares ficam PRÓXIMAS no espaço (rei-rainha ≈ homem-mulher); (3) acelera redes drasticamente. Os pesos são aprendidos junto com a tarefa, ou inicializados de modelos pré-treinados (Word2Vec, GloVe, BERT). Para texto moderno: começa com Embedding, segue para LSTM/GRU ou Transformer.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Vocabulário vetorizado.",
      solution: "emb = Embedding(input_dim=10000, output_dim=128)\nprint('Embedding criado.')",
    },
    {
      id: "ds-dl-16",
      worldId: "nucleo-sintetico",
      title: "Predict",
      description: "Use modelo.predict(X), salve em pred e imprima o primeiro valor previsto.",
      narrative: "Aplique o modelo treinado a dados novos.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def predict(self, X): return [[0.8]]\nmodelo = Modelo()\nX = [[1, 2]]",
      expectedOutput: "0.8",
      testCode: "assert 'predict' in code and 'pred' in code and '[0][0]' in code",
      starterCode: "# pred = modelo.predict(X)\n# imprima o primeiro valor\n",
      hints: [
        { text: "predict retorna uma estrutura 2D neste simulador.", cost: 25 },
        { text: "Acesse linha zero e coluna zero com pred[0][0].", cost: 30 },
        { text: "pred = modelo.predict(X)\nprint(pred[0][0])", cost: 35 },
      ],
      xpReward: 900,
      concept: "Inferência em Keras",
      conceptExplanation: "modelo.predict(X) aplica a rede treinada a dados novos — retorna array NumPy com previsões. X deve ter SHAPE COMPLETO (batch, features...). Em classificação binária com sigmoid, retorna probabilidades; em multi-classe com softmax, retorna vetor por exemplo. Para decisão final: np.argmax(predictions, axis=1). Para um único exemplo: model.predict(X[0:1]) — mantém batch. Em produção, considere model.predict_on_batch (sem overhead de iteração) ou converter para TFLite/ONNX para deploy.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Inferência entregue.",
      solution: "pred = modelo.predict(X)\nprint(pred[0][0])",
    },
    {
      id: "ds-dl-17",
      worldId: "nucleo-sintetico",
      title: "Evaluate",
      description: "Use modelo.evaluate(X_test, y_test), salve em metricas e imprima a acuracia.",
      narrative: "Calcule loss e métricas no conjunto de teste.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def evaluate(self, X, y): return [0.1, 0.95]\nmodelo = Modelo()\nX_test = [[1], [2]]\ny_test = [0, 1]",
      expectedOutput: "0.95",
      testCode: "assert 'evaluate' in code and 'metricas' in code and '[1]' in code",
      starterCode: "# metricas = modelo.evaluate(X_test, y_test)\n# imprima a acuracia\n",
      hints: [
        { text: "evaluate costuma retornar [loss, metricas...].", cost: 25 },
        { text: "Aqui a acuracia esta na posicao 1.", cost: 30 },
        { text: "metricas = modelo.evaluate(X_test, y_test)\nprint(metricas[1])", cost: 35 },
      ],
      xpReward: 950,
      concept: "Evaluate",
      conceptExplanation: "modelo.evaluate(X, y) computa loss e todas as métricas definidas no compile no conjunto fornecido — análogo a .score() do sklearn. Retorna lista: [loss, metric1, metric2, ...]. Para nomear: use model.metrics_names. Use em CONJUNTO DE TESTE separado, nunca de treino. Diferente de predict (que retorna saídas), evaluate retorna métricas agregadas. Útil para comparar versões do modelo: salve resultados para A/B testing.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Performance final mensurada.",
      solution: "metricas = modelo.evaluate(X_test, y_test)\nprint(metricas[1])",
    },
    {
      id: "ds-dl-18",
      worldId: "nucleo-sintetico",
      title: "Summary",
      description: "Chame modelo.summary() e imprima 'Sumário gerado.'.",
      narrative: "Revise a arquitetura e contagem de parâmetros antes do treino.",
      difficulty: "intermediario",
      setupCode: "class Modelo:\n    def summary(self): print('Sumário gerado.')\nmodelo = Modelo()",
      expectedOutput: "Sumário gerado.",
      testCode: "assert 'summary' in code",
      starterCode: "# Imprima o summary\n",
      hints: [
        { text: "modelo.summary() imprime tabela com camadas, shapes e parâmetros.", cost: 15 },
        { text: "Use logo após criar o modelo — confirma que arquitetura está correta.", cost: 20 },
        { text: "modelo.summary()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Model Summary",
      conceptExplanation: "modelo.summary() imprime tabela detalhada: nome da camada, shape de saída e número de parâmetros (pesos + bias) por camada, mais total geral. Use SEMPRE após criar o modelo — confirma que arquitetura está correta antes de gastar horas treinando errado. Total de parâmetros é importante: muito alto = lento e propenso a overfitting; muito baixo = capacidade insuficiente. Para modelos com milhões de parâmetros, considere arquiteturas mais eficientes (MobileNet, EfficientNet, transfer learning).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Arquitetura inspecionada.",
      solution: "modelo.summary()",
    },
    {
      id: "ds-dl-19",
      worldId: "nucleo-sintetico",
      title: "Early Stopping",
      description: "Crie EarlyStopping(patience=5) e imprima 'Callback configurado.'.",
      narrative: "Pare o treino automaticamente quando o modelo parar de melhorar.",
      difficulty: "avancado",
      setupCode: "class EarlyStopping:\n    def __init__(self, patience=5): pass",
      expectedOutput: "Callback configurado.",
      testCode: "assert 'EarlyStopping' in code",
      starterCode: "from tensorflow.keras.callbacks import EarlyStopping\n# patience=5\n",
      hints: [
        { text: "EarlyStopping monitora uma métrica de validação (val_loss por padrão).", cost: 30 },
        { text: "patience=5 espera 5 epochs sem melhora antes de parar.", cost: 35 },
        { text: "es = EarlyStopping(patience=5)\\nprint('Callback configurado.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Callbacks (Early Stopping)",
      conceptExplanation: "EarlyStopping monitora uma métrica de validação durante o treino — se ela não melhora por N epochs (patience), interrompe o treino automaticamente, evitando overfitting e economizando tempo. Parâmetros: monitor='val_loss' (qual métrica vigiar), patience=N (epochs sem melhora antes de parar), restore_best_weights=True (volta pros pesos do melhor epoch). Use no fit: model.fit(..., callbacks=[es]). É uma das melhores práticas absolutas em DL — quase sempre ativada. Outros callbacks: ModelCheckpoint, ReduceLROnPlateau, TensorBoard.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Parada automática armada.",
      solution: "from tensorflow.keras.callbacks import EarlyStopping\nes = EarlyStopping(patience=5)\nprint('Callback configurado.')",
    },
    {
      id: "ds-dl-20",
      worldId: "nucleo-sintetico",
      title: "Model Checkpoint",
      description: "Crie ModelCheckpoint('best.h5', save_best_only=True) e imprima 'Checkpoint armado.'.",
      narrative: "Salve automaticamente o melhor modelo durante o treino.",
      difficulty: "avancado",
      setupCode: "class ModelCheckpoint:\n    def __init__(self, path, save_best_only=False): pass",
      expectedOutput: "Checkpoint armado.",
      testCode: "assert 'ModelCheckpoint' in code",
      starterCode: "from tensorflow.keras.callbacks import ModelCheckpoint\n# best.h5, save_best_only=True\n",
      hints: [
        { text: "ModelCheckpoint(caminho, save_best_only=True) salva durante o treino, mantendo só o melhor.", cost: 30 },
        { text: "Por padrão monitora val_loss — passe monitor='val_accuracy' se quiser.", cost: 35 },
        { text: "mc = ModelCheckpoint('best.h5', save_best_only=True)\\nprint('Checkpoint armado.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Model Checkpoint",
      conceptExplanation: "ModelCheckpoint salva o modelo durante o treino. save_best_only=True só salva quando uma métrica monitorada melhora — garante que você fique com a MELHOR versão, mesmo se o treino degradar depois. Sem isso, você fica com a versão do último epoch (que pode ter overfitado). Parâmetros: filepath ('model_{epoch:02d}_{val_loss:.4f}.h5' nomeia com valores), monitor (qual métrica), mode ('min' para loss, 'max' para accuracy). Combine com EarlyStopping — checkpoint salva o melhor, early stopping para de gastar tempo.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Melhor versão preservada.",
      solution: "from tensorflow.keras.callbacks import ModelCheckpoint\nmc = ModelCheckpoint('best.h5', save_best_only=True)\nprint('Checkpoint armado.')",
    },
    {
      id: "ds-dl-21",
      worldId: "nucleo-sintetico",
      title: "Learning Rate",
      description: "Configure Adam(learning_rate=0.001) e imprima 'LR configurado.'.",
      narrative: "Learning rate é o hiperparâmetro mais importante de uma rede neural.",
      difficulty: "avancado",
      setupCode: "class Adam:\n    def __init__(self, learning_rate=0.001): pass",
      expectedOutput: "LR configurado.",
      testCode: "assert 'learning_rate' in code",
      starterCode: "from tensorflow.keras.optimizers import Adam\n# Adam com lr=0.001\n",
      hints: [
        { text: "Em vez de passar string 'adam' no compile, instancie Adam(learning_rate=X) para controlar o LR.", cost: 30 },
        { text: "Valores típicos: 0.001 (padrão Adam), 0.01, 0.0001. Muito alto = não converge; muito baixo = lento.", cost: 35 },
        { text: "opt = Adam(learning_rate=0.001)\\nprint('LR configurado.')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Learning Rate",
      conceptExplanation: "Learning rate (LR) controla o TAMANHO DO PASSO de atualização dos pesos a cada batch. É O hiperparâmetro mais crítico em DL: muito alto = oscila sem convergir; muito baixo = treino lento ou estaca em mínimos locais. Valores típicos: Adam=0.001 (padrão), SGD=0.01. Estratégias avançadas: Learning Rate Scheduler (reduz LR durante treino), Warmup (começa baixo, aumenta), Cyclical LR. Para encontrar o LR ideal: técnica do 'LR finder' (aumenta LR exponencialmente, plota loss — pegue o valor antes do mínimo).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Taxa de aprendizado ajustada.",
      solution: "from tensorflow.keras.optimizers import Adam\nopt = Adam(learning_rate=0.001)\nprint('LR configurado.')",
    },
    {
      id: "ds-dl-22",
      worldId: "nucleo-sintetico",
      title: "Salvar Modelo",
      description: "Chame modelo.save('rede.h5') e imprima 'Modelo salvo.'.",
      narrative: "Persista o modelo treinado em disco para uso posterior.",
      difficulty: "intermediario",
      setupCode: "class Modelo:\n    def save(self, path): print('Modelo salvo.')\nmodelo = Modelo()",
      expectedOutput: "Modelo salvo.",
      testCode: "assert '.save' in code",
      starterCode: "# modelo.save('rede.h5')\n",
      hints: [
        { text: "modelo.save('arquivo.h5') salva arquitetura + pesos + otimizador em arquivo único.", cost: 20 },
        { text: "Formato recomendado moderno: 'rede.keras' (SavedModel) em vez de .h5.", cost: 25 },
        { text: "modelo.save('rede.h5')", cost: 30 },
      ],
      xpReward: 800,
      concept: "Persistência de Modelo",
      conceptExplanation: "modelo.save('arquivo') salva o modelo completo: arquitetura + pesos aprendidos + estado do otimizador. Formatos: .h5 (HDF5, legado), 'pasta/' (SavedModel TF — recomendado para produção), .keras (formato moderno unificado). Para salvar SÓ pesos: model.save_weights('arq.h5'). Sempre salve após treino para deploy ou continuação posterior. Carregar: tf.keras.models.load_model('arquivo') — modelo volta exatamente como estava, pronto para predict ou continuar fit.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo persistido.",
      solution: "modelo.save('rede.h5')",
    },
    {
      id: "ds-dl-23",
      worldId: "nucleo-sintetico",
      title: "Carregar Modelo",
      description: "Use load_model('rede.h5') e imprima 'Modelo carregado.'.",
      narrative: "Recupere modelo treinado para inferência em produção.",
      difficulty: "intermediario",
      setupCode: "def load_model(path): print('Modelo carregado.')",
      expectedOutput: "Modelo carregado.",
      testCode: "assert 'load_model' in code",
      starterCode: "from tensorflow.keras.models import load_model\n# carregue 'rede.h5'\n",
      hints: [
        { text: "load_model(caminho) restaura modelo completo do arquivo salvo.", cost: 20 },
        { text: "Após carregar, está pronto para .predict() — sem reconstruir arquitetura.", cost: 25 },
        { text: "modelo = load_model('rede.h5')", cost: 30 },
      ],
      xpReward: 800,
      concept: "Load Model",
      conceptExplanation: "load_model('arquivo') restaura modelo salvo: arquitetura + pesos + otimizador. Aceita .h5, SavedModel ou .keras. Para custom layers/funções, passe custom_objects={'minha_func': minha_func}. Em produção, geralmente: (1) treine offline, salve; (2) load_model no serviço; (3) predict on demand. Para inferência mais rápida, considere converter: tflite (mobile), ONNX (multi-plataforma), TensorRT (NVIDIA GPU). Em workflows de cloud (AWS SageMaker, Google AI Platform), o load é automático ao deployar.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo restaurado.",
      solution: "from tensorflow.keras.models import load_model\nmodelo = load_model('rede.h5')",
    },
    {
      id: "ds-dl-24",
      worldId: "nucleo-sintetico",
      title: "Tensor PyTorch",
      description: "Importe torch. Crie t = torch.tensor([1, 2, 3]) e imprima.",
      narrative: "PyTorch é a alternativa preferida em pesquisa.",
      difficulty: "avancado",
      setupCode: "class torch_mock:\n    @staticmethod\n    def tensor(d): return f'tensor({d})'\ntorch = torch_mock()",
      expectedOutput: "tensor([1, 2, 3])",
      testCode: "assert 'torch.tensor' in code",
      starterCode: "import torch\n# t = torch.tensor([1,2,3])\n",
      hints: [
        { text: "Sem alias — escreva 'import torch'.", cost: 20 },
        { text: "torch.tensor(lista) é equivalente ao np.array() do NumPy, mas com superpoderes.", cost: 25 },
        { text: "t = torch.tensor([1, 2, 3])\\nprint(t)", cost: 30 },
      ],
      xpReward: 1100,
      concept: "PyTorch Tensors",
      conceptExplanation: "Em PyTorch, Tensor é o objeto central — array NumPy com superpoderes: (1) movível para GPU via .to('cuda') ou .cuda() (50-100x mais rápido); (2) AUTOGRAD — rastreia operações e calcula gradientes automaticamente quando você chama .backward(). PyTorch usa grafos DINÂMICOS (operações executadas imediatamente, como Python normal), facilitando debug e experimentação — daí preferência em pesquisa. Sintaxe propositalmente próxima de NumPy: torch.tensor, torch.zeros, torch.ones, slicing, broadcasting iguais. requires_grad=True ativa o rastreamento de gradiente.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tensor instanciado.",
      solution: "import torch\nt = torch.tensor([1, 2, 3])\nprint(t)",
    },
    {
      id: "ds-dl-25",
      worldId: "nucleo-sintetico",
      title: "nn.Linear",
      description: "Crie linear = nn.Linear(in_features=10, out_features=5) e imprima 'Linear pronta.'.",
      narrative: "Equivalente PyTorch da Dense do Keras.",
      difficulty: "avancado",
      setupCode: "class nn_mock:\n    class Linear:\n        def __init__(self, in_features, out_features): pass\nnn = nn_mock()",
      expectedOutput: "Linear pronta.",
      testCode: "assert 'nn.Linear' in code",
      starterCode: "import torch.nn as nn\n# Linear 10 -> 5\n",
      hints: [
        { text: "nn.Linear(in, out) é a equivalente PyTorch da Dense.", cost: 25 },
        { text: "Diferente de Keras (que infere automaticamente), PyTorch exige in_features e out_features.", cost: 30 },
        { text: "linear = nn.Linear(in_features=10, out_features=5)\\nprint('Linear pronta.')", cost: 35 },
      ],
      xpReward: 1100,
      concept: "Camadas PyTorch (nn.Linear)",
      conceptExplanation: "nn.Linear(in_features, out_features) é a camada totalmente conectada do PyTorch — equivalente à Dense do Keras. Diferença crucial: PyTorch exige in_features explícito (não infere do anterior como Keras). Pesos são inicializados automaticamente. Para aplicar: y = linear(x). Outras camadas em torch.nn: Conv2d, MaxPool2d, BatchNorm2d, Dropout, LSTM, Embedding — mesma família, sintaxe parecida. Para arquiteturas, herde de nn.Module e defina forward() — abordagem mais flexível que Sequential mas mais código.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Camada linear pronta.",
      solution: "import torch.nn as nn\nlinear = nn.Linear(in_features=10, out_features=5)\nprint('Linear pronta.')",
    },
    {
      id: "ds-dl-26",
      worldId: "nucleo-sintetico",
      title: "nn.Module",
      description: "Crie uma classe MinhaRede(nn.Module). Imprima 'Módulo criado.'.",
      narrative: "A forma idiomática de construir redes em PyTorch.",
      difficulty: "avancado",
      setupCode: "class nn_mock:\n    class Module: pass\nnn = nn_mock()",
      expectedOutput: "Módulo criado.",
      testCode: "assert 'nn.Module' in code and 'class' in code",
      starterCode: "import torch.nn as nn\n# Defina a classe e imprima\n",
      hints: [
        { text: "Em PyTorch, modelos são classes que HERDAM de nn.Module.", cost: 30 },
        { text: "Defina camadas em __init__ e o fluxo em forward(self, x). Aqui só criamos a classe.", cost: 35 },
        { text: "class MinhaRede(nn.Module): pass\\nprint('Módulo criado.')", cost: 40 },
      ],
      xpReward: 1200,
      concept: "nn.Module",
      conceptExplanation: "nn.Module é a classe base de toda rede em PyTorch — você HERDA dela. Estrutura padrão: em __init__ você instancia as camadas (self.linear1 = nn.Linear(...), self.conv = nn.Conv2d(...)); em forward(self, x) você define o fluxo dos dados — qualquer Python válido (loops, condicionais, multiplas saídas). Chamando model(x) automaticamente chama forward(). Vantagens: máxima flexibilidade — qualquer arquitetura imaginável (não-sequencial, ramificada, com lógica condicional, multi-input/output). É por isso que pesquisadores preferem PyTorch.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Módulo base estabelecido.",
      solution: "import torch.nn as nn\nclass MinhaRede(nn.Module): pass\nprint('Módulo criado.')",
    },
    {
      id: "ds-dl-27",
      worldId: "nucleo-sintetico",
      title: "Autograd",
      description: "Crie t = torch.tensor(2.0, requires_grad=True) e imprima 'Gradiente ativado.'.",
      narrative: "Requirements_grad ativa o motor de diferenciação automática.",
      difficulty: "avancado",
      setupCode: "class torch_mock:\n    @staticmethod\n    def tensor(d, requires_grad=False): return None\ntorch = torch_mock()",
      expectedOutput: "Gradiente ativado.",
      testCode: "assert 'requires_grad' in code",
      starterCode: "import torch\n# Crie tensor com requires_grad=True\n",
      hints: [
        { text: "Passe requires_grad=True ao criar o tensor — PyTorch passará a rastrear operações.", cost: 30 },
        { text: "Depois você chama .backward() para calcular gradientes em relação a esse tensor.", cost: 35 },
        { text: "t = torch.tensor(2.0, requires_grad=True)\\nprint('Gradiente ativado.')", cost: 40 },
      ],
      xpReward: 1250,
      concept: "Autograd (Diferenciação Automática)",
      conceptExplanation: "Autograd é o motor matemático que permite redes neurais aprenderem: rastreia automaticamente todas as operações em tensores com requires_grad=True, construindo um GRAFO COMPUTACIONAL. Ao chamar loss.backward(), PyTorch percorre esse grafo de trás para frente (backpropagation) e calcula derivadas parciais (gradientes) para cada parâmetro com requires_grad=True. Esses gradientes ficam em tensor.grad. O otimizador usa eles para atualizar os pesos. Em geral, parâmetros de nn.Module têm requires_grad=True automaticamente — você raramente liga manualmente.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Diferenciação automática armada.",
      solution: "import torch\nt = torch.tensor(2.0, requires_grad=True)\nprint('Gradiente ativado.')",
    },
    {
      id: "ds-dl-28",
      worldId: "nucleo-sintetico",
      title: "Optim Adam",
      description: "Crie optim.Adam(parametros, lr=0.001) e imprima 'Optim Adam criado.'.",
      narrative: "Otimizador é quem efetivamente atualiza os pesos a cada passo.",
      difficulty: "avancado",
      setupCode: "class optim_mock:\n    class Adam:\n        def __init__(self, params, lr=0.001): pass\noptim = optim_mock()\nparametros = []",
      expectedOutput: "Optim Adam criado.",
      testCode: "assert 'optim.Adam' in code and 'lr' in code",
      starterCode: "import torch.optim as optim\n# Adam com lr=0.001\n",
      hints: [
        { text: "optim.Adam recebe parâmetros do modelo (model.parameters()) e learning rate.", cost: 30 },
        { text: "No loop de treino: optimizer.zero_grad(), depois loss.backward(), depois optimizer.step().", cost: 35 },
        { text: "opt = optim.Adam(parametros, lr=0.001)\\nprint('Optim Adam criado.')", cost: 40 },
      ],
      xpReward: 1250,
      concept: "Otimizadores PyTorch",
      conceptExplanation: "torch.optim contém os otimizadores: Adam (mais usado), SGD (clássico), RMSprop, AdamW. Sempre recebe os PARÂMETROS do modelo (model.parameters() retorna lista de tensores treináveis) e o learning rate. Loop de treino típico em PyTorch (muito mais explícito que Keras): (1) optimizer.zero_grad() — zera gradientes acumulados; (2) forward: outputs = model(X); (3) loss = criterion(outputs, y); (4) loss.backward() — calcula gradientes via autograd; (5) optimizer.step() — atualiza pesos usando os gradientes.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Otimizador pronto.",
      solution: "import torch.optim as optim\nopt = optim.Adam(parametros, lr=0.001)\nprint('Optim Adam criado.')",
    },
    {
      id: "ds-dl-29",
      worldId: "nucleo-sintetico",
      title: "GPU com .cuda()",
      description: "Crie t = Tensor(), mova para GPU com t.cuda() e imprima o device do tensor retornado.",
      narrative: "Para treinar redes modernas em tempo razoável, GPU é obrigatório.",
      difficulty: "avancado",
      setupCode: "class Tensor:\n    def __init__(self): self.device = 'cpu'\n    def cuda(self):\n        self.device = 'cuda'\n        return self",
      expectedOutput: "cuda",
      testCode: "assert 'Tensor' in code and '.cuda()' in code and '.device' in code",
      starterCode: "# Crie Tensor, chame cuda e imprima device\n",
      hints: [
        { text: "cuda() move o tensor para GPU e aqui retorna o proprio tensor.", cost: 25 },
        { text: "Guarde o retorno de t.cuda() antes de imprimir o device.", cost: 30 },
        { text: "t = Tensor()\nt_gpu = t.cuda()\nprint(t_gpu.device)", cost: 35 },
      ],
      xpReward: 1100,
      concept: "GPU em PyTorch",
      conceptExplanation: "GPU é essencial para DL moderno — uma rede que treina em DIAS na CPU treina em HORAS na GPU. PyTorch: device = 'cuda' if torch.cuda.is_available() else 'cpu'. Mova tensores e modelo: tensor.to(device) ou .cuda(). REGRA: TUDO precisa estar no MESMO device — modelo, entrada, alvo, parâmetros — caso contrário erro. Boas práticas: criar tensores direto no device (torch.tensor([1,2], device='cuda')); usar DataLoader com num_workers e pin_memory=True para acelerar transferências. Para multi-GPU: nn.DataParallel ou DistributedDataParallel.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Computação acelerada.",
      solution: "t = Tensor()\nt_gpu = t.cuda()\nprint(t_gpu.device)",
    },
    {
      id: "ds-dl-30",
      worldId: "nucleo-sintetico",
      title: "Transfer Learning",
      description: "Carregue base = ResNet50(weights='imagenet') e imprima os pesos usados.",
      narrative: "Não treine do zero — comece de modelos pré-treinados em milhões de imagens.",
      difficulty: "avancado",
      setupCode: "class ResNet50:\n    def __init__(self, weights): self.weights = weights",
      expectedOutput: "imagenet",
      testCode: "assert 'ResNet50' in code and 'weights' in code and 'imagenet' in code and '.weights' in code",
      starterCode: "# Use ResNet50 com weights='imagenet'\n",
      hints: [
        { text: "Transfer learning comeca carregando pesos pre-treinados.", cost: 25 },
        { text: "Passe weights='imagenet' ao criar a ResNet50.", cost: 30 },
        { text: "base = ResNet50(weights='imagenet')\nprint(base.weights)", cost: 35 },
      ],
      xpReward: 1300,
      concept: "Transfer Learning",
      conceptExplanation: "Transfer Learning é a técnica DEFINITIVA para projetos práticos de DL: em vez de treinar do zero (precisa de MILHÕES de exemplos rotulados + dias de GPU), você carrega pesos de um modelo PRÉ-TREINADO em dataset gigante (ImageNet para visão; BERT/GPT para texto) e ADAPTA para sua tarefa com poucos dados. Estratégias: (1) Feature Extraction — congela todas camadas exceto a final, retreina só a saída; (2) Fine-tuning — descongela algumas das últimas e treina com LR baixíssimo. Em Keras: tf.keras.applications.ResNet50(weights='imagenet'). Em PyTorch: torchvision.models. Praticamente todo projeto comercial usa transfer learning.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Conhecimento de bilhões de imagens herdado.",
      solution: "base = ResNet50(weights='imagenet')\nprint(base.weights)",
    },
  ],
};
