import { World } from "../types";

export const NUCLEO_SINTETICO_WORLD: World = {
  id: "nucleo-sintetico",
  title: "Núcleo Sintético",
  subtitle: "Deep Learning",
  icon: "sparkles",
  color: "#FBBF24",
  bgImage: "/assets/images/worlds/synthetic_core.png",
  lore: "O auge da IA. Redes neurais profundas, visão computacional e processamento de linguagem natural — a fronteira do conhecimento cibernético.",
  unlockRequirement: 20000,
  challenges: [
    {
      id: "ds-dl-01",
      worldId: "nucleo-sintetico",
      title: "Despertar da Rede",
      description: "Importe TensorFlow como tf. Imprima a mensagem: 'Rede Neural Inicializada: 3 camadas ocultas, 128 tensores.'.",
      narrative: "Para vencer a inteligência central da CorpHQ, precisamos combater fogo com fogo. Inicialize a rede neural profunda.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Rede Neural Inicializada: 3 camadas ocultas, 128 tensores.",
      testCode: "assert '128 tensores' in output",
      starterCode: "import tensorflow as tf\n# Imprima a mensagem exata pedida no enunciado\n",
      hints: [
        { text: "O alias 'tf' é convenção universal para TensorFlow — toda documentação e tutorial usam.", cost: 10 },
        { text: "Use print() com a string EXATA pedida no enunciado, incluindo pontuação e acentos. O teste valida a presença de '128 tensores' na saída.", cost: 20 },
        { text: "import tensorflow as tf\\nprint('Rede Neural Inicializada: 3 camadas ocultas, 128 tensores.')", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Frameworks de Deep Learning",
      conceptExplanation: "TensorFlow (criado pelo Google) e PyTorch (criado pela Meta) são os dois frameworks dominantes de Deep Learning no mundo — toda IA moderna (ChatGPT, sistemas de visão computacional, recomendação, tradução automática) usa um dos dois. Ambos manipulam 'tensores', generalizações de matrizes para N dimensões (um número escalar é tensor 0D, vetor é 1D, matriz é 2D, imagem RGB é 3D, vídeo é 4D). O ponto-chave dos dois é a DIFERENCIAÇÃO AUTOMÁTICA: o framework rastreia cada operação que você faz nos tensores e consegue calcular gradientes automaticamente — esse é o motor matemático do treinamento via backpropagation. TensorFlow tem o Keras como API de alto nível (Sequential, Dense, etc.) — é dominante em produção e deploy industrial. PyTorch tem sintaxe mais 'pythônica' e grafos dinâmicos, sendo dominante em pesquisa acadêmica. Ambos rodam em GPU/TPU para acelerar cálculos 50-100x.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "As sinapses acenderam. A IA agora respira na rede.",
      solution: "import tensorflow as tf\nprint('Rede Neural Inicializada: 3 camadas ocultas, 128 tensores.')",
    },
    {
      id: "ds-dl-02",
      worldId: "nucleo-sintetico",
      title: "Construção Sequential",
      description: "Crie modelo = Sequential([Dense(64), Dense(10)]) e imprima 'Arquitetura definida.'.",
      narrative: "Toda rede neural começa empilhando camadas. Construa um modelo Sequential com uma camada oculta de 64 neurônios e uma de saída de 10.",
      difficulty: "avancado",
      setupCode: "class Dense:\n    def __init__(self, n):\n        self.n = n\nclass Sequential:\n    def __init__(self, layers):\n        self.layers = layers",
      expectedOutput: "Arquitetura definida.",
      testCode: "assert 'Sequential' in code and 'Dense' in code",
      starterCode: "from tensorflow.keras import Sequential\nfrom tensorflow.keras.layers import Dense\n# Monte um modelo Sequential com duas camadas Dense\n",
      hints: [
        { text: "Sequential recebe UMA lista de camadas — passe-as entre colchetes. As camadas se conectam em sequência automaticamente.", cost: 20 },
        { text: "Dense(n) cria uma camada totalmente conectada com n neurônios. A primeira camada tem 64 neurônios (oculta); a segunda tem 10 (saída).", cost: 25 },
        { text: "modelo = Sequential([Dense(64), Dense(10)])\\nprint('Arquitetura definida.')", cost: 30 },
      ],
      xpReward: 1050,
      concept: "Arquitetura de Redes Neurais e API Sequential",
      conceptExplanation: "Sequential é a API mais simples do Keras para montar redes neurais — você passa uma lista de camadas e o framework conecta a saída de uma na entrada da próxima automaticamente, em sequência linear (daí o nome). Camadas Dense (também chamadas de 'totalmente conectadas' ou 'fully connected') são o tijolo básico de toda rede: cada neurônio de uma camada Dense recebe entrada de TODOS os neurônios da camada anterior, com um peso aprendível para cada conexão. Quantos neurônios usar em cada camada? Camadas ocultas (do meio) são decisão sua e variam por problema — 32, 64, 128, 256 são valores típicos. A última camada é determinada pelo problema: 1 neurônio para regressão simples; N neurônios para classificação em N classes (10 para dígitos 0-9, 1000 para ImageNet). Para arquiteturas mais complexas (com ramificações, conexões residuais, múltiplas entradas/saídas como Transformers), usa-se a API Funcional ou subclassing de tf.keras.Model. Outras camadas comuns: Conv2D (visão computacional), LSTM/GRU (sequências e texto), Dropout (regularização).",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Arquitetura registrada. 64 → 10 neurônios, prontos para fluir tensores.",
      solution: "modelo = Sequential([Dense(64), Dense(10)])\nprint('Arquitetura definida.')",
    },
    {
      id: "ds-dl-03",
      worldId: "nucleo-sintetico",
      title: "Compilação do Modelo",
      description: "Chame modelo.compile(optimizer='adam', loss='mse') e imprima 'Modelo compilado.'.",
      narrative: "Antes de treinar, você deve definir o otimizador (motor de gradiente) e a função de perda (bússola do aprendizado).",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def compile(self, optimizer, loss):\n        pass\nmodelo = Modelo()",
      expectedOutput: "Modelo compilado.",
      testCode: "assert 'compile' in code and 'adam' in code and 'mse' in code",
      starterCode: "# Compile o modelo com otimizador 'adam' e loss 'mse', depois confirme\n",
      hints: [
        { text: "compile() não treina nada — apenas configura COMO treinar. É como ajustar as engrenagens do motor antes de ligar.", cost: 20 },
        { text: "Passe os parâmetros nomeados: optimizer='adam' (algoritmo que atualiza os pesos) e loss='mse' (medida do erro).", cost: 25 },
        { text: "modelo.compile(optimizer='adam', loss='mse')\\nprint('Modelo compilado.')", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Compilação: Otimizador e Função de Perda",
      conceptExplanation: "compile() configura COMO a rede vai aprender, sem ainda treinar nada. Três parâmetros principais: (1) OPTIMIZER — é o algoritmo que ajusta os pesos a cada passo, usando os gradientes calculados. 'adam' é o padrão moderno (combina momento e taxas adaptativas, funciona bem na maioria dos casos); 'sgd' é o gradiente descendente clássico (mais lento, mas com bom comportamento); 'rmsprop' funciona bem em redes recorrentes. (2) LOSS (função de perda) — mede QUÃO ERRADO o modelo está em cada previsão. A escolha depende do problema: 'mse' (mean squared error) para regressão; 'binary_crossentropy' para classificação binária (2 classes); 'categorical_crossentropy' para classificação em N classes; 'sparse_categorical_crossentropy' quando y vem como inteiros e não one-hot. (3) METRICS — lista opcional de métricas adicionais para acompanhar durante o treino (['accuracy'], ['mae']). Sem chamar compile(), o método .fit() falha imediatamente — toda rede precisa saber como medir erro e como atualizar pesos antes de aprender.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Gradiente descendente ativado. Adam pronto para minimizar o erro.",
      solution: "modelo.compile(optimizer='adam', loss='mse')\nprint('Modelo compilado.')",
    },
    {
      id: "ds-dl-04",
      worldId: "nucleo-sintetico",
      title: "Treinamento com Epochs",
      description: "Chame modelo.fit(X, y, epochs=5) e imprima 'Treinamento concluído.'.",
      narrative: "Hora de propagar gradientes. Treine por 5 epochs para que a rede aprenda os padrões dos dados.",
      difficulty: "avancado",
      setupCode: "class Modelo:\n    def fit(self, X, y, epochs):\n        print(f'Treinando por {epochs} epochs...')\nmodelo = Modelo()\nX = [[1, 2], [3, 4]]\ny = [0, 1]",
      expectedOutput: "Treinando por 5 epochs...\nTreinamento concluído.",
      testCode: "assert 'fit' in code and 'epochs' in code",
      starterCode: "# Treine o modelo por 5 epochs e confirme com print\n",
      hints: [
        { text: "É no .fit() que o treinamento realmente acontece — o modelo ajusta seus pesos a cada batch dos dados.", cost: 20 },
        { text: "Passe X (entradas), y (respostas esperadas) e epochs=5 (5 passagens completas pelos dados). A ordem dos primeiros 2 importa; o epochs vai nomeado.", cost: 25 },
        { text: "modelo.fit(X, y, epochs=5)\\nprint('Treinamento concluído.')", cost: 30 },
      ],
      xpReward: 1150,
      concept: "Epochs, Batches e Treinamento Iterativo",
      conceptExplanation: "Treinar uma rede neural é um processo iterativo: o algoritmo percorre os dados de treino várias vezes, ajustando os pesos para reduzir o erro a cada passagem. Um EPOCH é uma passagem completa por todos os dados de treino. Dentro de cada epoch, os dados são divididos em BATCHES (lotes pequenos, tipicamente 32 ou 64 exemplos): o gradiente do erro é calculado por batch (não por exemplo individual nem pelos dados inteiros), e os pesos são atualizados após cada batch — esse é o 'mini-batch gradient descent'. Mais epochs geralmente reduzem o erro de treino, mas em EXCESSO causam overfitting: a rede memoriza os dados de treino específicos e perde a capacidade de generalizar. O ponto ideal é encontrado monitorando o erro no conjunto de VALIDAÇÃO (parâmetros validation_split=0.2 ou validation_data=(X_val, y_val) no fit) — quando o erro de treino continua caindo mas o de validação para de cair e começa a subir, você passou do ponto. Técnicas para combater overfitting: dropout, regularização L2, early stopping, mais dados.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pesos convergiram. A rede agora reconhece padrões da CorpHQ com precisão letal.",
      solution: "modelo.fit(X, y, epochs=5)\nprint('Treinamento concluído.')",
    },
    {
      id: "ds-dl-05",
      worldId: "nucleo-sintetico",
      title: "Tensor com PyTorch",
      description: "Importe torch. Crie t = torch.tensor([1, 2, 3]) e imprima t.",
      narrative: "PyTorch é a alternativa preferida nos laboratórios de pesquisa. Crie seu primeiro tensor.",
      difficulty: "avancado",
      setupCode: "class torch_mock:\n    @staticmethod\n    def tensor(data): return f'tensor({data})'\ntorch = torch_mock()",
      expectedOutput: "tensor([1, 2, 3])",
      testCode: "assert 'torch.tensor' in code",
      starterCode: "import torch\n# Crie um tensor a partir da lista [1, 2, 3] e imprima\n",
      hints: [
        { text: "Importe como 'import torch' — PyTorch NÃO tem alias convencional como pandas (pd) ou numpy (np); é simplesmente 'torch'.", cost: 20 },
        { text: "torch.tensor(lista) converte uma lista Python em tensor — equivalente direto ao np.array() do NumPy, mas com superpoderes de GPU e gradientes.", cost: 25 },
        { text: "import torch\\nt = torch.tensor([1, 2, 3])\\nprint(t)", cost: 30 },
      ],
      xpReward: 1200,
      concept: "PyTorch: Tensores, GPU e Autograd",
      conceptExplanation: "Em PyTorch, o objeto central é o Tensor — uma generalização de array NumPy com DUAS superpotências: (1) pode ser movido para GPU com .to('cuda') ou .cuda(), acelerando cálculos 50-100x para redes grandes (sem GPU, treinar uma rede moderna seria impraticável); (2) mantém histórico de operações para AUTOGRAD (diferenciação automática) — o framework rastreia cada operação que você faz e calcula gradientes automaticamente quando você chama .backward(). Diferente do TensorFlow clássico (que historicamente usava grafos estáticos definidos antes da execução), PyTorch usa 'grafos dinâmicos': as operações são executadas IMEDIATAMENTE, como em código Python normal — isso facilita debug (você pode usar print, pdb, ver shapes em tempo real) e é por isso que pesquisadores preferem PyTorch. A sintaxe é deliberadamente próxima do NumPy: torch.tensor (≈ np.array), torch.zeros, torch.ones, slicing igual, broadcasting igual, .shape, .reshape. Para começar a usar gradientes (essencial em treino de redes), basta passar requires_grad=True ao criar o tensor — daí toda operação subsequente é rastreada.",
      successNpc: "Oráculo IA",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tensor instanciado no dispositivo. Gradientes prontos para fluir.",
      solution: "import torch\nt = torch.tensor([1, 2, 3])\nprint(t)",
    },
  ],
};
