import { World } from "../types";

export const REFINARIA_DADOS_WORLD: World = {
  id: "refinaria-dados",
  title: "Refinaria de Dados",
  subtitle: "Manipulação de Dados",
  icon: "bar-chart-3",
  color: "#A78BFA",
  bgImage: "/assets/images/worlds/data_refinery.png",
  lore: "Aprenda a domar fluxos massivos de dados brutos. Pandas e NumPy são as ferramentas de elite para limpar, transformar e analisar tabelas de bilhões de linhas.",
  unlockRequirement: 14000,
  challenges: [
    {
      id: "ds-pandas-01",
      worldId: "refinaria-dados",
      title: "O Primeiro DataFrame",
      description: "Importe o pandas como pd. Crie um DataFrame a partir do dicionário 'dados' e imprima-o.",
      narrative: "Bem-vindo à Refinaria. Aqui, dados soltos são inúteis. Você precisa estruturá-los em um DataFrame — o bloco fundamental da ciência de dados.",
      difficulty: "iniciante",
      setupCode: "dados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}",
      expectedOutput: "       Nome  Nivel\n0       Neo      5\n1   Trinity      7\n2  Morpheus      9",
      testCode: "assert 'pd.DataFrame' in code and 'pandas' in code",
      starterCode: "import pandas as pd\ndados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}\n# Crie o DataFrame 'df' e imprima com print(df)\n",
      hints: [
        { text: "Importe a biblioteca com o alias padrão: 'import pandas as pd'. Esse 'pd' é uma convenção universal — toda documentação de pandas usa.", cost: 10 },
        { text: "Passe o dicionário direto para pd.DataFrame(...). Cada chave do dicionário vira o nome de uma coluna; os valores (listas) viram a coluna em si.", cost: 20 },
        { text: "import pandas as pd\\ndf = pd.DataFrame(dados)\\nprint(df)", cost: 30 },
      ],
      xpReward: 500,
      concept: "DataFrames",
      conceptExplanation: "O DataFrame é a estrutura central da biblioteca pandas — pense em uma tabela do Excel ou do SQL: linhas (registros) e colunas (atributos), com um índice numérico atribuído automaticamente para cada linha. Cada coluna pode ter um tipo de dado diferente (números, texto, datas). Quando você constrói a partir de um dicionário Python, cada chave do dicionário vira o nome de uma coluna e a lista de valores vira o conteúdo dessa coluna. DataFrames são onde 90% do trabalho de análise de dados em Python acontece, e eles são a entrada padrão para visualização (matplotlib, seaborn) e Machine Learning (scikit-learn).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "DataFrame inicializado. O fluxo de dados brutos agora tem uma estrutura rígida.",
      solution: "import pandas as pd\ndados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}\ndf = pd.DataFrame(dados)\nprint(df)",
    },
    {
      id: "ds-pandas-02",
      worldId: "refinaria-dados",
      title: "Filtragem de Anomalias",
      description: "O DataFrame 'df' já existe. Imprima apenas as linhas onde a coluna 'Risco' for maior que 8.",
      narrative: "O firewall interceptou pacotes suspeitos. Filtre a tabela para isolar apenas as ameaças de alto risco.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '192.168.1.5', '172.16.0.2'], 'Risco': [2, 9, 5]})\n",
      expectedOutput: "            IP  Risco\n1  192.168.1.5      9",
      testCode: "assert \"df['Risco'] > 8\" in code or 'df[df.Risco > 8]' in code or 'df[df[\"Risco\"] > 8]' in code",
      starterCode: "# Imprima apenas as linhas onde 'Risco' é maior que 8\n",
      hints: [
        { text: "Para filtrar, você passa uma condição entre colchetes do DataFrame: df[condição]. A condição retorna True/False para cada linha; o pandas mantém apenas as True.", cost: 20 },
        { text: "A condição é uma comparação aplicada a uma coluna: df['Risco'] > 8. Isso gera uma Series booleana — uma lista de True/False com o mesmo tamanho do DataFrame.", cost: 25 },
        { text: "print(df[df['Risco'] > 8])", cost: 30 },
      ],
      xpReward: 600,
      concept: "Filtros Booleanos (Boolean Indexing)",
      conceptExplanation: "Qualquer comparação aplicada a uma coluna do pandas (>, <, ==, !=) gera uma Series booleana — uma sequência de True/False, uma para cada linha. Quando você passa essa Series booleana entre colchetes do DataFrame, ele retorna apenas as linhas onde o valor é True. Esse padrão se chama 'boolean indexing' e é uma das ferramentas mais poderosas do pandas: você usa para filtrar outliers, separar grupos, isolar erros e limpar dados. Para combinar várias condições, use & (e) e | (ou) com cada condição entre parênteses: df[(df['a'] > 5) & (df['b'] < 10)]. NÃO use 'and' ou 'or' do Python puro aqui — pandas exige os operadores bitwise.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Anomalias isoladas com sucesso. A equipe de CyberSec já foi alertada.",
      solution: "print(df[df['Risco'] > 8])",
    },
    {
      id: "ds-pandas-03",
      worldId: "refinaria-dados",
      title: "Coluna Derivada",
      description: "O DataFrame 'df' tem 'Ataques' e 'Defesas'. Crie uma nova coluna 'Saldo' = Ataques - Defesas e imprima o DataFrame.",
      narrative: "Os analistas precisam saber o saldo de combate de cada operador. Derive uma nova métrica diretamente das colunas existentes.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Operador': ['Neo', 'Trinity'], 'Ataques': [42, 30], 'Defesas': [12, 15]})\n",
      expectedOutput: "  Operador  Ataques  Defesas  Saldo\n0      Neo       42       12     30\n1  Trinity       30       15     15",
      testCode: "assert \"df['Saldo']\" in code or 'df[\"Saldo\"]' in code",
      starterCode: "# Crie a coluna 'Saldo' como a diferença entre 'Ataques' e 'Defesas'\n",
      hints: [
        { text: "Para criar uma nova coluna, simplesmente atribua a uma chave que ainda não existe no DataFrame: df['nova_coluna'] = ... — o pandas cria automaticamente.", cost: 20 },
        { text: "Operações entre colunas são vetorizadas: df['A'] - df['B'] retorna uma nova Series com a subtração linha a linha. Sem loop manual.", cost: 25 },
        { text: "df['Saldo'] = df['Ataques'] - df['Defesas']\\nprint(df)", cost: 30 },
      ],
      xpReward: 650,
      concept: "Engenharia de Features (Feature Engineering)",
      conceptExplanation: "'Engenharia de features' é o processo de criar novas variáveis a partir das existentes para revelar informação útil — frequentemente o passo que mais melhora a performance de modelos de Machine Learning. Em pandas, toda operação aritmética entre colunas é vetorizada: o cálculo acontece elemento a elemento sem loop manual, em C, sendo muito mais rápido e legível que iterar com for. Atribuir a uma chave nova (df['nova']) cria a coluna; atribuir a uma chave existente sobrescreve. Você pode encadear operações complexas (df['A'] * df['B'] + 10), aplicar funções (df['A'].apply(lambda x: x**2)) ou condicionais (np.where(df['A'] > 0, 'positivo', 'negativo')). Esse padrão é a base de toda preparação de dados antes do treino.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Métrica criada. Os relatórios de combate agora têm o saldo em tempo real.",
      solution: "df['Saldo'] = df['Ataques'] - df['Defesas']\nprint(df)",
    },
    {
      id: "ds-pandas-04",
      worldId: "refinaria-dados",
      title: "Agregação por Grupo",
      description: "Agrupe 'df' pela coluna 'Setor' e imprima a soma de 'Acessos' por setor.",
      narrative: "Os logs de acesso estão sendo agregados. Descubra qual setor da CorpHQ recebe mais tráfego suspeito.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Setor': ['Core', 'Edge', 'Core', 'Edge'], 'Acessos': [10, 5, 7, 3]})\n",
      expectedOutput: "Setor\nCore    17\nEdge     8\nName: Acessos, dtype: int64",
      testCode: "assert 'groupby' in code and 'Setor' in code",
      starterCode: "# Agrupe por 'Setor' e some 'Acessos'\n",
      hints: [
        { text: "Comece chamando df.groupby('coluna_categoria') — isso ainda não calcula nada, apenas prepara o agrupamento (é como o GROUP BY do SQL).", cost: 20 },
        { text: "Depois do groupby, selecione a coluna a agregar e a função: groupby('Setor')['Acessos'].sum(). Você pode trocar sum() por mean(), count(), max(), min().", cost: 25 },
        { text: "print(df.groupby('Setor')['Acessos'].sum())", cost: 30 },
      ],
      xpReward: 750,
      concept: "GroupBy (Split-Apply-Combine)",
      conceptExplanation: "groupby() implementa o padrão 'split-apply-combine': ele divide o DataFrame em grupos com base em uma chave (split), aplica uma função em cada grupo (apply) e combina os resultados em uma nova estrutura (combine). É o equivalente direto do GROUP BY do SQL e o coração de qualquer análise exploratória — qualquer pergunta do tipo 'qual é o total/média/máximo por categoria?' se resolve com groupby. As agregações mais comuns são .sum(), .mean(), .count(), .min(), .max(), .std(). Para aplicar várias de uma vez, use .agg(['sum', 'mean']). Você pode agrupar por múltiplas colunas passando uma lista: groupby(['Pais', 'Cidade']). O retorno de groupby + agregação tipicamente é uma Series indexada pelo grupo — converta para DataFrame com .reset_index() quando precisar.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Setor Core identificado como ponto crítico. Recursos sendo realocados.",
      solution: "print(df.groupby('Setor')['Acessos'].sum())",
    },
    {
      id: "ds-numpy-01",
      worldId: "refinaria-dados",
      title: "Matriz Numérica (NumPy)",
      description: "Importe numpy como np. Crie um array a partir de [1, 2, 3, 4, 5], multiplique por 10 e imprima.",
      narrative: "Para processamento de alto desempenho, listas Python são lentas demais. Inicialize um Array NumPy para ativar a aceleração vetorial.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "[10 20 30 40 50]",
      testCode: "assert 'numpy' in code and 'np.array' in code",
      starterCode: "import numpy as np\nlista = [1, 2, 3, 4, 5]\n# Converta para array NumPy, multiplique por 10 e imprima\n",
      hints: [
        { text: "Importe NumPy com o alias padrão: 'import numpy as np'. Esse 'np' é convenção universal — toda a comunidade científica do Python o usa.", cost: 20 },
        { text: "Use np.array(lista) para converter. Diferente de listas Python (onde [1,2,3] * 10 repete a lista 10 vezes), arrays NumPy aplicam a operação a CADA elemento.", cost: 25 },
        { text: "import numpy as np\\narr = np.array(lista)\\nprint(arr * 10)", cost: 30 },
      ],
      xpReward: 650,
      concept: "Arrays NumPy e Vetorização",
      conceptExplanation: "NumPy é a biblioteca base de todo o ecossistema científico do Python — pandas, scikit-learn e tensorflow são construídos sobre ela. Sua estrutura central é o ndarray (N-dimensional array): números armazenados em blocos contínuos de memória, permitindo operações vetorizadas implementadas em C que são 10 a 100 vezes mais rápidas que loops Python equivalentes. Quando você escreve arr * 10, o NumPy aplica a multiplicação a cada elemento sem nenhum loop visível — isso se chama 'broadcasting'. O mesmo vale para soma, subtração, comparações e funções como np.sqrt, np.log, np.sin: todas operam vetorialmente. Listas Python não têm essa capacidade — lista * 10 repete a lista 10 vezes em vez de multiplicar cada elemento. Por isso, todo código científico/numérico em Python passa por NumPy.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Aceleração ativada. O processamento vetorial reduziu o tempo de execução em 98%.",
      solution: "import numpy as np\nlista = [1, 2, 3, 4, 5]\narr = np.array(lista)\nprint(arr * 10)",
    },
    {
      id: "ds-numpy-02",
      worldId: "refinaria-dados",
      title: "Estatística Vetorial",
      description: "Dado 'temperaturas' = np.array([22, 28, 35, 19, 41]), imprima a média e o desvio padrão (uma por linha).",
      narrative: "Os sensores térmicos reportaram leituras flutuantes. Calcule a média e o desvio padrão para detectar superaquecimento.",
      difficulty: "avancado",
      setupCode: "import numpy as np\ntemperaturas = np.array([22, 28, 35, 19, 41])",
      expectedOutput: "29.0\n8.0",
      testCode: "assert 'np.mean' in code and 'np.std' in code",
      starterCode: "# Imprima np.mean(...) e np.std(...) do array, um em cada linha\n",
      hints: [
        { text: "NumPy traz funções estatísticas embutidas e otimizadas: np.mean(arr) calcula a média; np.std(arr) calcula o desvio padrão.", cost: 20 },
        { text: "Cada função recebe o array inteiro de uma vez e retorna um único número. Use dois print() separados — um para cada métrica.", cost: 25 },
        { text: "print(np.mean(temperaturas))\\nprint(np.std(temperaturas))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Estatística Descritiva com NumPy",
      conceptExplanation: "Para análise quantitativa, NumPy oferece um conjunto completo de funções estatísticas otimizadas que operam em arrays inteiros sem loops: np.mean (média aritmética), np.median (mediana — valor do meio quando ordenado), np.std (desvio padrão), np.var (variância), np.min/max, np.percentile (quantis). A média te dá o valor central; o desvio padrão te diz quão espalhados os dados estão em torno dessa média (desvio baixo = dados próximos da média; desvio alto = dispersão grande). Juntas, essas duas métricas são o 'primeiro olhar' obrigatório em qualquer dataset numérico — antes de qualquer análise mais sofisticada ou modelo de ML. Para análise por linha ou coluna em arrays 2D, use o parâmetro axis: np.mean(matriz, axis=0) calcula a média de cada coluna.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Variância dentro do limite seguro. Sistema térmico estável.",
      solution: "import numpy as np\ntemperaturas = np.array([22, 28, 35, 19, 41])\nprint(np.mean(temperaturas))\nprint(np.std(temperaturas))",
    },
  ],
};
