import { World } from "../types";

export const REFINARIA_DADOS_WORLD: World = {
  id: "refinaria-dados",
  title: "Refinaria de Dados",
  subtitle: "Manipulação de Dados",
  icon: "bar-chart-3",
  color: "#A78BFA",
  bgImage: "/assets/images/worlds/data_refinery.png",
  lore: "Aprenda a domar fluxos massivos de dados brutos. Pandas e NumPy são as ferramentas de elite para limpar, transformar e analisar tabelas de bilhões de linhas.",
  unlockRequirement: 14000,
  challenges: [
    {
      id: "ds-pandas-01",
      worldId: "refinaria-dados",
      title: "O Primeiro DataFrame",
      description: "Importe pandas como pd. Crie um DataFrame a partir do dicionário 'dados' e imprima-o.",
      narrative: "Bem-vindo à Refinaria. Aqui, dados soltos são inúteis — você precisa estruturá-los em um DataFrame, o bloco fundamental da ciência de dados.",
      difficulty: "iniciante",
      setupCode: "dados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}",
      expectedOutput: "       Nome  Nivel\n0       Neo      5\n1   Trinity      7\n2  Morpheus      9",
      testCode: "assert 'pd.DataFrame' in code and 'pandas' in code",
      starterCode: "import pandas as pd\ndados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}\n# Crie o DataFrame 'df' e imprima com print(df)\n",
      hints: [
        { text: "Importe a biblioteca com o alias padrão: 'import pandas as pd'. Esse 'pd' é convenção universal — toda documentação de pandas usa.", cost: 10 },
        { text: "Passe o dicionário direto para pd.DataFrame(...). Cada chave do dicionário vira nome de coluna; os valores (listas) viram a coluna.", cost: 20 },
        { text: "import pandas as pd\\ndf = pd.DataFrame(dados)\\nprint(df)", cost: 30 },
      ],
      xpReward: 500,
      concept: "DataFrames",
      conceptExplanation: "O DataFrame é a estrutura central do pandas — pense em uma tabela do Excel ou SQL: linhas (registros) e colunas (atributos), com índice numérico automático. Quando você constrói a partir de um dicionário, cada chave vira coluna e a lista vira o conteúdo. DataFrames são onde 90% do trabalho de análise acontece em Python — entrada padrão para visualização (matplotlib, seaborn) e ML (sklearn).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "DataFrame inicializado. O fluxo de dados brutos agora tem estrutura rígida.",
      solution: "import pandas as pd\ndados = {'Nome': ['Neo', 'Trinity', 'Morpheus'], 'Nivel': [5, 7, 9]}\ndf = pd.DataFrame(dados)\nprint(df)",
    },
    {
      id: "ds-pandas-02",
      worldId: "refinaria-dados",
      title: "Selecionar Coluna",
      description: "O DataFrame 'df' tem as colunas 'IP' e 'Risco'. Imprima apenas a coluna 'IP'.",
      narrative: "O setor de segurança precisa apenas dos IPs — descarte o resto do payload.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '192.168.1.5'], 'Risco': [2, 9]})",
      expectedOutput: "0       10.0.0.1\n1    192.168.1.5\nName: IP, dtype: object",
      testCode: "assert \"df['IP']\" in code or 'df.IP' in code",
      starterCode: "# Selecione e imprima a coluna 'IP'\n",
      hints: [
        { text: "Para acessar uma coluna, use colchetes com o nome dela entre aspas: df['nome_coluna']. O retorno é uma Series (coluna isolada).", cost: 10 },
        { text: "Alternativamente, pode usar notação de atributo: df.IP — mas isso só funciona se o nome não tiver espaços nem caracteres especiais.", cost: 20 },
        { text: "print(df['IP'])", cost: 30 },
      ],
      xpReward: 450,
      concept: "Seleção de Coluna (Series)",
      conceptExplanation: "Selecionar uma coluna do DataFrame retorna uma Series — estrutura 1D do pandas com índice, similar a um array NumPy mas com rótulos. A notação df['col'] funciona sempre; df.col é açúcar sintático que só funciona se o nome for um identificador Python válido. Series tem todos os métodos da coluna: .mean(), .max(), .unique(), .value_counts(). É a base de todas as operações por coluna.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "IPs extraídos. O resto dos campos foi descartado.",
      solution: "print(df['IP'])",
    },
    {
      id: "ds-pandas-03",
      worldId: "refinaria-dados",
      title: "Múltiplas Colunas",
      description: "Selecione e imprima as colunas 'IP' e 'Risco' simultaneamente.",
      narrative: "Os analistas pediram um subset com IPs e risco. Outras colunas são ruído neste relatório.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '192.168.1.5'], 'Porta': [80, 443], 'Risco': [2, 9]})",
      expectedOutput: "            IP  Risco\n0     10.0.0.1      2\n1  192.168.1.5      9",
      testCode: "assert \"['IP', 'Risco']\" in code or '[\"IP\", \"Risco\"]' in code",
      starterCode: "# Selecione 'IP' e 'Risco' juntos\n",
      hints: [
        { text: "Para múltiplas colunas, passe uma LISTA de nomes dentro dos colchetes — note o duplo par de colchetes: df[[...]].", cost: 10 },
        { text: "Diferente de uma coluna só (que retorna Series), múltiplas colunas retornam um DataFrame.", cost: 20 },
        { text: "print(df[['IP', 'Risco']])", cost: 30 },
      ],
      xpReward: 500,
      concept: "Seleção Múltipla",
      conceptExplanation: "Quando você quer mais de uma coluna, passe uma lista de nomes — daí os duplos colchetes: df[['a', 'b']]. O par externo é a sintaxe de indexação; o interno é a lista. O retorno é um novo DataFrame (não uma Series), mantendo a tabela 2D. Essa é a forma padrão de criar 'visões' do DataFrame com apenas as colunas relevantes antes de análises ou plots.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Subset criado. Relatório enxuto.",
      solution: "print(df[['IP', 'Risco']])",
    },
    {
      id: "ds-pandas-04",
      worldId: "refinaria-dados",
      title: "Filtragem de Anomalias",
      description: "Imprima apenas as linhas onde 'Risco' for maior que 8.",
      narrative: "O firewall interceptou pacotes suspeitos. Isole apenas as ameaças de alto risco.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '192.168.1.5', '172.16.0.2'], 'Risco': [2, 9, 5]})",
      expectedOutput: "            IP  Risco\n1  192.168.1.5      9",
      testCode: "assert \"df['Risco'] > 8\" in code or 'df[df.Risco > 8]' in code",
      starterCode: "# Filtre linhas onde Risco > 8\n",
      hints: [
        { text: "Filtros usam colchetes com uma CONDIÇÃO: df[df['col'] > valor]. A condição retorna True/False por linha; o pandas mantém só as True.", cost: 20 },
        { text: "Para combinar condições, use & (e) e | (ou) com parênteses: df[(df['a']>5) & (df['b']<10)]. NÃO use 'and'/'or' do Python aqui.", cost: 25 },
        { text: "print(df[df['Risco'] > 8])", cost: 30 },
      ],
      xpReward: 600,
      concept: "Boolean Indexing",
      conceptExplanation: "Qualquer comparação aplicada a uma coluna (>, <, ==, !=) gera uma Series booleana — sequência de True/False, uma para cada linha. Passada entre colchetes, o DataFrame retorna apenas as linhas onde o valor é True. Esse padrão é o coração da manipulação em pandas — usado para filtrar outliers, separar grupos, isolar erros. Combine condições com & e | (cada uma entre parênteses). 'and'/'or' do Python puro NÃO funcionam aqui.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Anomalias isoladas. CyberSec alertada.",
      solution: "print(df[df['Risco'] > 8])",
    },
    {
      id: "ds-pandas-05",
      worldId: "refinaria-dados",
      title: "Coluna Derivada",
      description: "Crie a coluna 'Saldo' = Ataques - Defesas e imprima o DataFrame.",
      narrative: "Os analistas precisam saber o saldo de combate de cada operador.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Operador': ['Neo', 'Trinity'], 'Ataques': [42, 30], 'Defesas': [12, 15]})",
      expectedOutput: "  Operador  Ataques  Defesas  Saldo\n0      Neo       42       12     30\n1  Trinity       30       15     15",
      testCode: "assert \"df['Saldo']\" in code",
      starterCode: "# Crie a coluna 'Saldo' como diferença das outras duas\n",
      hints: [
        { text: "Atribua a uma chave nova: df['nova_coluna'] = ...  O pandas cria a coluna automaticamente.", cost: 20 },
        { text: "Operações entre colunas são vetorizadas: df['A'] - df['B'] retorna uma Series com a subtração linha a linha, sem loop manual.", cost: 25 },
        { text: "df['Saldo'] = df['Ataques'] - df['Defesas']\\nprint(df)", cost: 30 },
      ],
      xpReward: 650,
      concept: "Feature Engineering",
      conceptExplanation: "Engenharia de features é criar novas variáveis a partir das existentes — frequentemente o passo que mais melhora modelos de ML. Em pandas, toda operação aritmética entre colunas é vetorizada: o cálculo acontece em C, elemento a elemento, sem loop manual. Atribuir a chave nova cria coluna; a chave existente sobrescreve. Você pode encadear operações (df['A']*df['B']+10), aplicar funções (df['A'].apply(lambda x: x**2)) e usar condicionais (np.where).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Métrica criada. Saldo em tempo real.",
      solution: "df['Saldo'] = df['Ataques'] - df['Defesas']\nprint(df)",
    },
    {
      id: "ds-pandas-06",
      worldId: "refinaria-dados",
      title: "GroupBy",
      description: "Agrupe por Setor, calcule soma e media de Acessos com agg, e imprima a soma do setor Core.",
      narrative: "Descubra qual setor da CorpHQ recebe mais tráfego suspeito.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Setor': ['Core', 'Edge', 'Core', 'Edge'], 'Acessos': [10, 5, 7, 3]})",
      expectedOutput: "17",
      testCode: "assert 'groupby' in code and 'agg' in code and 'Core' in code\nassert output.strip() == '17'",
      starterCode: "# Agrupe por Setor e gere soma/media de Acessos\n",
      hints: [
        { text: "Use df.groupby('Setor')['Acessos'].agg(['sum', 'mean']).", cost: 25 },
        { text: "Depois acesse a linha Core e a coluna sum com .loc.", cost: 30 },
        { text: "resumo = df.groupby('Setor')['Acessos'].agg(['sum', 'mean'])\nprint(resumo.loc['Core', 'sum'])", cost: 40 },
      ],
      xpReward: 750,
      concept: "GroupBy (Split-Apply-Combine)",
      conceptExplanation: "groupby() implementa 'split-apply-combine': divide o DataFrame em grupos por uma chave, aplica uma função em cada grupo, combina os resultados. Equivalente ao GROUP BY do SQL e coração de análise exploratória — qualquer pergunta 'total/média por categoria?' usa groupby. Funções: sum(), mean(), count(), min(), max(), std(). Para várias de uma vez use .agg(['sum','mean']). Para agrupar por múltiplas colunas passe uma lista: groupby(['Pais','Cidade']).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Setor Core identificado como ponto crítico.",
      solution: "resumo = df.groupby('Setor')['Acessos'].agg(['sum', 'mean'])\nprint(resumo.loc['Core', 'sum'])",
    },
    {
      id: "ds-pandas-07",
      worldId: "refinaria-dados",
      title: "Inspeção com .head()",
      description: "O DataFrame 'df' tem 100 linhas. Imprima apenas as 5 primeiras com .head().",
      narrative: "Antes de processar um dataset gigante, sempre dê uma olhada nas primeiras linhas para entender a estrutura.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'ID': range(100), 'Valor': range(100, 200)})",
      expectedOutput: "   ID  Valor\n0   0    100\n1   1    101\n2   2    102\n3   3    103\n4   4    104",
      testCode: "assert '.head' in code",
      starterCode: "# Imprima as 5 primeiras linhas\n",
      hints: [
        { text: "df.head() retorna as primeiras N linhas. Sem argumento, retorna 5. Equivalente para o final: df.tail().", cost: 10 },
        { text: "Para um número específico: df.head(10) retorna 10 linhas.", cost: 20 },
        { text: "print(df.head())", cost: 30 },
      ],
      xpReward: 400,
      concept: "Inspeção Inicial",
      conceptExplanation: "Análise de dados sempre começa com inspeção: head() (primeiras linhas) e tail() (últimas) te mostram a estrutura sem carregar a tela. Em datasets grandes (milhões de linhas), nunca imprima o DataFrame inteiro — head() é seu primeiro reflexo. Combine com df.shape (tamanho), df.columns (nomes), df.dtypes (tipos) e df.info() (resumo geral) para entender o que você tem em mãos.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Primeira inspeção feita. Estrutura compreendida.",
      solution: "print(df.head())",
    },
    {
      id: "ds-pandas-08",
      worldId: "refinaria-dados",
      title: "Resumo Estatístico",
      description: "Use .describe() para imprimir estatísticas resumidas do DataFrame.",
      narrative: "Antes de qualquer análise, é regra examinar média, desvio e quartis das colunas numéricas.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Latencia': [10, 20, 30, 40, 50]})\nprint(df.describe()) if False else None",
      expectedOutput: "        Latencia\ncount   5.000000\nmean   30.000000\nstd    15.811388\nmin    10.000000\n25%    20.000000\n50%    30.000000\n75%    40.000000\nmax    50.000000",
      testCode: "assert '.describe' in code",
      starterCode: "# Imprima describe() do df\n",
      hints: [
        { text: "df.describe() é um método sem argumentos. Retorna média, desvio, mínimo, máximo e quartis das colunas numéricas.", cost: 10 },
        { text: "Para incluir colunas de texto também, use df.describe(include='all').", cost: 20 },
        { text: "print(df.describe())", cost: 30 },
      ],
      xpReward: 450,
      concept: "Estatística Descritiva (describe)",
      conceptExplanation: "describe() é a forma mais rápida de obter um panorama numérico do DataFrame: retorna count (não-nulos), mean (média), std (desvio padrão), min, max e quartis (25%, 50% mediana, 75%) para cada coluna numérica. Em dados desconhecidos, é um dos primeiros comandos a executar — revela escala, dispersão e suspeitas de outliers. Para colunas categóricas, use describe(include=['object']) — mostra contagem, únicos, top e frequência.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Panorama estatístico mapeado.",
      solution: "print(df.describe())",
    },
    {
      id: "ds-pandas-09",
      worldId: "refinaria-dados",
      title: "Formato do DataFrame",
      description: "Imprima o shape (linhas, colunas) do DataFrame 'df'.",
      narrative: "Saber o tamanho do dataset é o primeiro passo antes de carregar tudo na memória.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6], 'C': [7,8,9]})",
      expectedOutput: "(3, 3)",
      testCode: "assert '.shape' in code",
      starterCode: "# Imprima df.shape\n",
      hints: [
        { text: "df.shape é um ATRIBUTO (sem parênteses) que retorna uma tupla (linhas, colunas).", cost: 10 },
        { text: "Outros atributos úteis: df.columns (nomes), df.dtypes (tipos), df.size (total de células).", cost: 20 },
        { text: "print(df.shape)", cost: 30 },
      ],
      xpReward: 400,
      concept: "Atributos do DataFrame",
      conceptExplanation: "Atributos do DataFrame (sem parênteses) revelam metadados sem custo computacional: .shape (tupla linhas, colunas), .columns (Index com nomes), .index (Index com rótulos das linhas), .dtypes (tipo de cada coluna), .size (total de células). Diferente de métodos (com parênteses, que executam alguma operação), atributos são valores já calculados e instantâneos. df.shape[0] dá só o número de linhas.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Dimensões do dataset confirmadas.",
      solution: "print(df.shape)",
    },
    {
      id: "ds-pandas-10",
      worldId: "refinaria-dados",
      title: "Renomear Colunas",
      description: "Renomeie a coluna 'IP' para 'Endereco' e imprima o DataFrame resultante.",
      narrative: "O sistema de logs antigo usava nomes diferentes. Padronize os nomes das colunas.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '10.0.0.2'], 'Porta': [80, 443]})",
      expectedOutput: "    Endereco  Porta\n0  10.0.0.1     80\n1  10.0.0.2    443",
      testCode: "assert 'rename' in code and 'Endereco' in code",
      starterCode: "# Use df.rename com columns={'antigo': 'novo'}\n",
      hints: [
        { text: "df.rename(columns={...}) recebe um dicionário com mapeamento antigo->novo. Por padrão, retorna um NOVO DataFrame sem modificar o original.", cost: 20 },
        { text: "df = df.rename(columns={'IP': 'Endereco'}) — reatribua para persistir. Ou passe inplace=True para modificar o original.", cost: 25 },
        { text: "df = df.rename(columns={'IP': 'Endereco'})\\nprint(df)", cost: 30 },
      ],
      xpReward: 550,
      concept: "Renomeação de Colunas",
      conceptExplanation: "rename() permite renomear colunas (parâmetro columns) ou linhas (index) passando um dicionário com mapeamento. Por padrão retorna um novo DataFrame — você precisa reatribuir (df = df.rename(...)) ou usar inplace=True. Para renomear TODAS as colunas de uma vez, atribua diretamente uma lista a df.columns: df.columns = ['a','b','c']. Padronização de nomes é etapa obrigatória ao consolidar dados de fontes diferentes.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Esquema padronizado.",
      solution: "df = df.rename(columns={'IP': 'Endereco'})\nprint(df)",
    },
    {
      id: "ds-pandas-11",
      worldId: "refinaria-dados",
      title: "Ordenação",
      description: "Ordene por Risco em ordem decrescente, salve em ranking e imprima o IP mais arriscado.",
      narrative: "O dashboard precisa mostrar os IPs mais perigosos primeiro.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '192.168.1.5', '172.16.0.2'], 'Risco': [2, 9, 5]})",
      expectedOutput: "192.168.1.5",
      testCode: "assert 'sort_values' in code and 'ascending=False' in code and 'ranking' in code\nassert output.strip() == '192.168.1.5'",
      starterCode: "# Ordene em ranking e extraia o IP da primeira linha\n",
      hints: [
        { text: "sort_values('Risco', ascending=False) coloca maior risco primeiro.", cost: 25 },
        { text: "Use .iloc[0] para pegar a primeira linha depois da ordenacao.", cost: 30 },
        { text: "ranking = df.sort_values('Risco', ascending=False)\nprint(ranking.iloc[0]['IP'])", cost: 40 },
      ],
      xpReward: 550,
      concept: "Ordenação (sort_values)",
      conceptExplanation: "sort_values() ordena o DataFrame pelos valores de uma ou mais colunas. Por padrão é ascendente; passe ascending=False para descendente. Para múltiplas colunas (e diferentes direções por coluna), passe listas: sort_values(['a','b'], ascending=[True, False]). Para ordenar pelo ÍNDICE em vez de valores, use sort_index(). Combinar com .head() é o padrão para 'top N': df.sort_values('vendas', ascending=False).head(10).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Top ameaças listadas.",
      solution: "ranking = df.sort_values('Risco', ascending=False)\nprint(ranking.iloc[0]['IP'])",
    },
    {
      id: "ds-pandas-12",
      worldId: "refinaria-dados",
      title: "Detectar Valores Nulos",
      description: "Use df.isna().sum() para contar nulos em cada coluna e imprima.",
      narrative: "Dados sujos com campos faltantes são o pesadelo de qualquer analista. Detecte onde estão.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'A': [1, np.nan, 3], 'B': [np.nan, np.nan, 6]})",
      expectedOutput: "A    1\nB    2\ndtype: int64",
      testCode: "assert 'isna' in code or 'isnull' in code",
      starterCode: "# Conte nulos por coluna\n",
      hints: [
        { text: "df.isna() retorna um DataFrame de booleanos (True onde há NaN/None). Aliás 'isnull' funciona igual.", cost: 20 },
        { text: "Some os booleanos por coluna com .sum() — True conta como 1, False como 0. Resultado: número de nulos por coluna.", cost: 25 },
        { text: "print(df.isna().sum())", cost: 30 },
      ],
      xpReward: 600,
      concept: "Detecção de Nulos",
      conceptExplanation: "Valores nulos (NaN, None, NaT) são endêmicos em dados reais. df.isna() retorna um DataFrame booleano marcando onde estão. Combinado com .sum() te dá contagem por coluna; com .sum().sum() dá total geral. Para taxa percentual: df.isna().mean() * 100. Ignorar nulos antes de modelos de ML quase sempre gera erros — sempre detecte primeiro, depois decida: preencher (fillna), remover (dropna) ou tratar como categoria especial.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Buracos no dataset mapeados.",
      solution: "print(df.isna().sum())",
    },
    {
      id: "ds-pandas-13",
      worldId: "refinaria-dados",
      title: "Preencher Nulos",
      description: "Use fillna(0) para substituir todos os NaN por zero e imprima o DataFrame.",
      narrative: "Antes de alimentar o modelo de ML, preencha os buracos com valores neutros.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'A': [1.0, np.nan, 3.0], 'B': [np.nan, 5.0, 6.0]})",
      expectedOutput: "     A    B\n0  1.0  0.0\n1  0.0  5.0\n2  3.0  6.0",
      testCode: "assert 'fillna' in code",
      starterCode: "# Substitua NaN por 0\n",
      hints: [
        { text: "df.fillna(valor) substitui todos os NaN por 'valor'. Retorna um novo DataFrame; reatribua ou use inplace=True.", cost: 20 },
        { text: "Você pode preencher diferente por coluna: df.fillna({'A': 0, 'B': df['B'].mean()}).", cost: 25 },
        { text: "print(df.fillna(0))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Preenchimento de Nulos (fillna)",
      conceptExplanation: "fillna(valor) substitui NaN por valor especificado. Estratégias comuns: preencher com 0 (quando NaN representa ausência); com a média/mediana da coluna (df['col'].fillna(df['col'].mean())) — adequado para numéricos sem viés; com a moda (mais comum) para categóricos; ou com 'unknown' como categoria explícita. Você também pode usar method='ffill' (propaga último valor válido para frente) ou 'bfill' (próximo válido para trás) — útil em séries temporais.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Lacunas preenchidas. Dataset pronto para modelo.",
      solution: "print(df.fillna(0))",
    },
    {
      id: "ds-pandas-14",
      worldId: "refinaria-dados",
      title: "Remover Nulos",
      description: "Use dropna() para remover linhas com qualquer NaN e imprima o resultado.",
      narrative: "Em casos críticos, é melhor descartar linhas incompletas a inferir valores.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\nimport numpy as np\ndf = pd.DataFrame({'A': [1.0, np.nan, 3.0], 'B': [4.0, 5.0, 6.0]})",
      expectedOutput: "     A    B\n0  1.0  4.0\n2  3.0  6.0",
      testCode: "assert 'dropna' in code",
      starterCode: "# Remova linhas com NaN\n",
      hints: [
        { text: "df.dropna() remove TODAS as linhas que tenham pelo menos um NaN. Retorna novo DataFrame (reatribua ou use inplace=True).", cost: 20 },
        { text: "Para remover só se TODA a linha for NaN, use how='all'. Para remover por coluna em vez de linha, axis=1.", cost: 25 },
        { text: "print(df.dropna())", cost: 30 },
      ],
      xpReward: 600,
      concept: "Remoção de Nulos (dropna)",
      conceptExplanation: "dropna() remove linhas/colunas com nulos. Por padrão, remove qualquer linha com pelo menos um NaN (how='any'). Use how='all' para remover só linhas 100% nulas. Para colunas, axis=1. Para exigir um mínimo de não-nulos, thresh=N. Para considerar só algumas colunas, subset=['a','b']. Cuidado: dropna pode destruir grande parte do dataset se você tem muitos nulos esparsos — sempre verifique df.shape antes e depois.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Linhas corrompidas eliminadas.",
      solution: "print(df.dropna())",
    },
    {
      id: "ds-pandas-15",
      worldId: "refinaria-dados",
      title: "Remover Duplicatas",
      description: "Use drop_duplicates() para eliminar linhas repetidas e imprima.",
      narrative: "Logs duplicados inflam métricas. Limpe antes de calcular qualquer agregação.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '10.0.0.2', '10.0.0.1']})",
      expectedOutput: "         IP\n0  10.0.0.1\n1  10.0.0.2",
      testCode: "assert 'drop_duplicates' in code",
      starterCode: "# Remova duplicatas\n",
      hints: [
        { text: "df.drop_duplicates() mantém a primeira ocorrência de cada linha duplicada. Retorna novo DataFrame.", cost: 20 },
        { text: "Para considerar duplicata baseada em apenas algumas colunas: drop_duplicates(subset=['col']). Para manter a última em vez da primeira: keep='last'.", cost: 25 },
        { text: "print(df.drop_duplicates())", cost: 30 },
      ],
      xpReward: 600,
      concept: "Deduplicação",
      conceptExplanation: "drop_duplicates() remove linhas duplicadas, mantendo por padrão a primeira ocorrência. Parâmetros úteis: subset=['col1','col2'] considera duplicata baseado só nessas colunas; keep='last' mantém a última em vez da primeira; keep=False remove TODAS as ocorrências de duplicatas (incluindo a primeira). Para apenas identificar duplicatas sem remover, use df.duplicated() (retorna Series booleana). Deduplicação é essencial em pipelines de ETL — logs, JOINs ruins e exports podem gerar duplicidade.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Repetições eliminadas. Métricas confiáveis.",
      solution: "print(df.drop_duplicates())",
    },
    {
      id: "ds-pandas-16",
      worldId: "refinaria-dados",
      title: "Converter Tipos",
      description: "A coluna 'Valor' está como string. Converta para int usando astype e imprima o dtype resultante.",
      narrative: "Tipos errados quebram operações numéricas. Force a conversão.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Valor': ['1', '2', '3']})",
      expectedOutput: "int64",
      testCode: "assert 'astype' in code",
      starterCode: "# Converta df['Valor'] para int e imprima o dtype resultante\n",
      hints: [
        { text: "Series.astype(tipo) converte o tipo: int, float, str, 'category'. Reatribua: df['Valor'] = df['Valor'].astype(int).", cost: 20 },
        { text: "Para imprimir o tipo resultante: print(df['Valor'].dtype) — note: dtype (atributo), não dtypes.", cost: 25 },
        { text: "df['Valor'] = df['Valor'].astype(int)\\nprint(df['Valor'].dtype)", cost: 30 },
      ],
      xpReward: 650,
      concept: "Conversão de Tipos (astype)",
      conceptExplanation: "astype() converte o tipo de uma Series. Tipos comuns: 'int', 'float', 'str', 'bool', 'category', 'datetime64[ns]'. Pandas infere tipos ao carregar dados (CSV, JSON), mas erra frequentemente — colunas numéricas viram strings se houver qualquer caractere inesperado. Para conversão segura de string para número (lidando com erros), use pd.to_numeric(col, errors='coerce') — valores inválidos viram NaN em vez de quebrar. Para datas: pd.to_datetime(col).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tipos corrigidos. Pipeline numérico desbloqueado.",
      solution: "df['Valor'] = df['Valor'].astype(int)\nprint(df['Valor'].dtype)",
    },
    {
      id: "ds-pandas-17",
      worldId: "refinaria-dados",
      title: "Apply em Coluna",
      description: "Use apply com lambda para criar a coluna Dobro = Valor*2 e imprima a soma da coluna Dobro.",
      narrative: "Precisamos transformar cada item por uma lógica custom — apply é a faca suíça.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Valor': [1, 2, 3]})",
      expectedOutput: "12",
      testCode: "assert 'apply' in code and 'lambda' in code and 'Dobro' in code\nassert output.strip() == '12'",
      starterCode: "# Crie df['Dobro'] com apply e imprima a soma\n",
      hints: [
        { text: "Crie uma coluna nova em vez de apenas imprimir a Series transformada.", cost: 25 },
        { text: "Depois use df['Dobro'].sum().", cost: 30 },
        { text: "df['Dobro'] = df['Valor'].apply(lambda x: x * 2)\nprint(df['Dobro'].sum())", cost: 40 },
      ],
      xpReward: 700,
      concept: "Apply",
      conceptExplanation: "apply() aplica uma função arbitrária a cada elemento de uma Series (ou linha/coluna de DataFrame). É a ferramenta de transformação custom quando operações vetorizadas embutidas não dão conta — lógica condicional complexa, transformações de texto, regex. Sintaxe: series.apply(func). Pode ser função nomeada ou lambda (anônima). Em DataFrame, df.apply(func, axis=0) aplica por coluna; axis=1 aplica por linha (recebe cada linha como Series). É flexível mas mais lento que ufuncs NumPy — sempre prefira vetorização quando possível.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Transformação custom aplicada com sucesso.",
      solution: "df['Dobro'] = df['Valor'].apply(lambda x: x * 2)\nprint(df['Dobro'].sum())",
    },
    {
      id: "ds-pandas-18",
      worldId: "refinaria-dados",
      title: "Contagem de Valores",
      description: "Use value_counts(normalize=True) na coluna Status, salve em proporcoes e imprima round(proporcoes['OK'], 2).",
      narrative: "Quantos pacotes foram bloqueados versus permitidos? value_counts é o caminho mais rápido.",
      difficulty: "iniciante",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Status': ['OK', 'FAIL', 'OK', 'OK', 'FAIL']})",
      expectedOutput: "0.6",
      testCode: "assert 'value_counts' in code and 'normalize=True' in code and 'proporcoes' in code\nassert output.strip() == '0.6'",
      starterCode: "# Calcule proporcoes por status\n",
      hints: [
        { text: "value_counts(normalize=True) retorna frequencias relativas.", cost: 20 },
        { text: "A proporcao de OK fica em proporcoes['OK'].", cost: 30 },
        { text: "proporcoes = df['Status'].value_counts(normalize=True)\nprint(round(proporcoes['OK'], 2))", cost: 40 },
      ],
      xpReward: 500,
      concept: "value_counts",
      conceptExplanation: "value_counts() é o método mais usado em análise exploratória — em uma linha, te dá a distribuição de uma coluna categórica: cada valor único e sua frequência, ordenado do mais frequente ao menos. Equivalente a groupby + count, mas direto. Parâmetros úteis: normalize=True (proporções em vez de contagens); dropna=False (inclui NaN); ascending=True (do menos para o mais comum). Para mais de uma coluna, use crosstab ou groupby.size().",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Distribuição de status mapeada.",
      solution: "proporcoes = df['Status'].value_counts(normalize=True)\nprint(round(proporcoes['OK'], 2))",
    },
    {
      id: "ds-pandas-19",
      worldId: "refinaria-dados",
      title: "Acesso .loc",
      description: "Use df.loc[0] para imprimir a primeira linha (rótulo 0).",
      narrative: "Para acessar uma linha por seu RÓTULO de índice, .loc é a ferramenta correta.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '10.0.0.2'], 'Risco': [2, 9]})",
      expectedOutput: "IP       10.0.0.1\nRisco           2\nName: 0, dtype: object",
      testCode: "assert '.loc' in code",
      starterCode: "# Use df.loc[0]\n",
      hints: [
        { text: ".loc usa RÓTULOS — passe o nome do índice ou da coluna. Para a primeira linha (rótulo 0): df.loc[0].", cost: 20 },
        { text: "Sintaxe avançada: df.loc[linha, coluna]. Ex: df.loc[0, 'IP'] pega a célula. df.loc[:, 'IP'] pega a coluna inteira.", cost: 25 },
        { text: "print(df.loc[0])", cost: 30 },
      ],
      xpReward: 700,
      concept: "Indexação .loc (label-based)",
      conceptExplanation: ".loc é o seletor 'label-based' do pandas: você usa os RÓTULOS do índice e dos nomes de coluna, não posições inteiras. Sintaxe: df.loc[linhas, colunas]. Aceita rótulo único (df.loc[0]), lista (df.loc[[0,2]]), slice (df.loc[0:5] — INCLUSIVE em ambos os lados, diferente de slicing Python normal!) ou condição booleana (df.loc[df['a']>5]). Combinar slice com colunas: df.loc[0:5, ['a','b']]. É o método preferido para indexação clara e explícita.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso preciso por rótulo confirmado.",
      solution: "print(df.loc[0])",
    },
    {
      id: "ds-pandas-20",
      worldId: "refinaria-dados",
      title: "Acesso .iloc",
      description: "Use df.iloc[1] para imprimir a SEGUNDA linha (posição 1).",
      narrative: "Quando o índice não é numérico ou você quer pegar por posição absoluta, use iloc.",
      difficulty: "intermediario",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'IP': ['10.0.0.1', '10.0.0.2'], 'Risco': [2, 9]})",
      expectedOutput: "IP       10.0.0.2\nRisco           9\nName: 1, dtype: object",
      testCode: "assert '.iloc' in code",
      starterCode: "# Use df.iloc[1]\n",
      hints: [
        { text: ".iloc usa POSIÇÕES inteiras, sempre começando de 0 — independente dos rótulos do índice.", cost: 20 },
        { text: "Sintaxe: df.iloc[linha, coluna]. Slicing iloc é EXCLUSIVE do fim (igual Python): df.iloc[0:5] retorna posições 0 a 4.", cost: 25 },
        { text: "print(df.iloc[1])", cost: 30 },
      ],
      xpReward: 700,
      concept: "Indexação .iloc (position-based)",
      conceptExplanation: ".iloc é o seletor 'integer-position-based': você usa POSIÇÕES inteiras (0-based), independente dos rótulos. Útil quando o índice não é numérico (datas, strings) ou quando você quer 'primeiro/último elemento' literal. Sintaxe igual ao .loc mas com inteiros: df.iloc[0] (primeira linha), df.iloc[-1] (última), df.iloc[0:5] (primeiras 5, EXCLUSIVE — diferente do .loc!), df.iloc[:, 0] (primeira coluna). Use .iloc quando posição importa; .loc quando rótulo importa.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Linha 2 (posição 1) capturada.",
      solution: "print(df.iloc[1])",
    },
    {
      id: "ds-pandas-21",
      worldId: "refinaria-dados",
      title: "Concatenar DataFrames",
      description: "Concatene df1 e df2 com ignore_index=True, salve em logs e imprima logs.shape[0].",
      narrative: "Logs vieram de dois servidores. Empilhe os dois arquivos em um único dataset.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\ndf1 = pd.DataFrame({'IP': ['10.0.0.1']})\ndf2 = pd.DataFrame({'IP': ['10.0.0.2']})",
      expectedOutput: "2",
      testCode: "assert 'pd.concat' in code and 'ignore_index=True' in code and 'logs' in code\nassert output.strip() == '2'",
      starterCode: "# Concatene resetando o indice e imprima numero de linhas\n",
      hints: [
        { text: "ignore_index=True recria o indice 0..N depois de empilhar.", cost: 25 },
        { text: "shape[0] retorna quantidade de linhas.", cost: 30 },
        { text: "logs = pd.concat([df1, df2], ignore_index=True)\nprint(logs.shape[0])", cost: 40 },
      ],
      xpReward: 800,
      concept: "Concatenação",
      conceptExplanation: "pd.concat([df1, df2, ...]) empilha DataFrames. Por padrão axis=0 (vertical, adicionando linhas) — exige que as colunas coincidam (colunas faltantes viram NaN com sort=False). axis=1 concatena horizontalmente (lado a lado), alinhando pelo índice. ignore_index=True regenera o índice de 0..N (importante quando os índices originais conflitam). Para diversidade de schemas, use join='inner' (mantém só colunas em comum). Não confunda com merge() — concat é colagem; merge é JOIN relacional.",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Logs unificados em dataset único.",
      solution: "logs = pd.concat([df1, df2], ignore_index=True)\nprint(logs.shape[0])",
    },
    {
      id: "ds-pandas-22",
      worldId: "refinaria-dados",
      title: "Merge (JOIN)",
      description: "Fa?a merge de usuarios e compras por id, salve em relatorio e imprima a soma da coluna valor.",
      narrative: "Junte a tabela de usuários com a de transações — é um JOIN clássico.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\nusuarios = pd.DataFrame({'id': [1, 2], 'nome': ['Neo', 'Trinity']})\ncompras = pd.DataFrame({'id': [1, 2], 'valor': [100, 200]})",
      expectedOutput: "300",
      testCode: "assert ('pd.merge' in code or '.merge' in code) and 'relatorio' in code and 'sum' in code\nassert output.strip() == '300'",
      starterCode: "# Una as tabelas e some o valor total\n",
      hints: [
        { text: "pd.merge(usuarios, compras, on='id') cruza cadastro e compras.", cost: 25 },
        { text: "Depois some relatorio['valor'].", cost: 30 },
        { text: "relatorio = pd.merge(usuarios, compras, on='id')\nprint(relatorio['valor'].sum())", cost: 40 },
      ],
      xpReward: 850,
      concept: "Merge (JOIN Relacional)",
      conceptExplanation: "pd.merge() implementa JOIN no estilo SQL: combina linhas de dois DataFrames baseado em uma chave comum. Parâmetro how define o tipo: 'inner' (padrão, só chaves em ambos), 'left' (todas as chaves do esquerdo), 'right' (todas do direito), 'outer' (união completa, NaN onde não há match). 'on' especifica a chave; left_on/right_on quando os nomes diferem. Diferença vs concat: concat empilha; merge cruza relacionalmente. É a base de qualquer pipeline que consolida dados de múltiplas fontes (banco transacional, cadastro, eventos).",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tabelas cruzadas. Análise unificada.",
      solution: "relatorio = pd.merge(usuarios, compras, on='id')\nprint(relatorio['valor'].sum())",
    },
    {
      id: "ds-pandas-23",
      worldId: "refinaria-dados",
      title: "Pivot Table",
      description: "Crie a pivot_table por Cidade/Categoria, salve em matriz e imprima matriz.loc['RJ', 'B'].",
      narrative: "Transforme dados longos em uma matriz analítica para o dashboard executivo.",
      difficulty: "avancado",
      setupCode: "import pandas as pd\ndf = pd.DataFrame({'Cidade': ['SP','SP','RJ','RJ'], 'Categoria': ['A','B','A','B'], 'Vendas': [10,20,30,40]})",
      expectedOutput: "40",
      testCode: "assert 'pivot_table' in code and 'matriz' in code and '.loc' in code\nassert output.strip() == '40'",
      starterCode: "# Gere a pivot e extraia vendas de RJ na categoria B\n",
      hints: [
        { text: "Use index='Cidade', columns='Categoria', values='Vendas', aggfunc='sum'.", cost: 25 },
        { text: "Depois acesse a celula com matriz.loc['RJ', 'B'].", cost: 35 },
        { text: "matriz = df.pivot_table(index='Cidade', columns='Categoria', values='Vendas', aggfunc='sum')\nprint(matriz.loc['RJ', 'B'])", cost: 45 },
      ],
      xpReward: 950,
      concept: "Pivot Tables",
      conceptExplanation: "pivot_table() é o equivalente das tabelas dinâmicas do Excel: transforma dados de formato longo (uma linha por observação) em formato largo (matriz com agregações). Parâmetros: index (eixo das linhas), columns (eixo das colunas), values (o que agregar), aggfunc ('sum', 'mean', 'count', 'max', função custom). fill_value preenche células vazias. Ideal para análise multidimensional e dashboards. Versão simplificada sem agregação: df.pivot(); para reverter (largo → longo): df.melt().",
      successNpc: "Engenheiro de Dados",
      successAvatar: "/avatars/golem.webp",
      successStory: "Matriz analítica gerada. Dashboard atualizado.",
      solution: "matriz = df.pivot_table(index='Cidade', columns='Categoria', values='Vendas', aggfunc='sum')\nprint(matriz.loc['RJ', 'B'])",
    },
    {
      id: "ds-numpy-01",
      worldId: "refinaria-dados",
      title: "Array NumPy",
      description: "Importe numpy como np. Crie um array a partir de [1,2,3,4,5], multiplique por 10 e imprima.",
      narrative: "Para alta performance, listas Python são lentas. Ative o vetor NumPy.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "[10 20 30 40 50]",
      testCode: "assert 'np.array' in code",
      starterCode: "import numpy as np\nlista = [1, 2, 3, 4, 5]\n# Crie array, multiplique por 10, imprima\n",
      hints: [
        { text: "Importe com alias padrão: 'import numpy as np'. Convenção universal — toda a comunidade científica usa.", cost: 20 },
        { text: "np.array(lista) converte. Diferente de listas Python (onde lista*10 repete), arrays NumPy aplicam a CADA elemento.", cost: 25 },
        { text: "arr = np.array(lista)\\nprint(arr * 10)", cost: 30 },
      ],
      xpReward: 650,
      concept: "Arrays NumPy",
      conceptExplanation: "NumPy é a base de todo ecossistema científico Python — pandas, sklearn e tensorflow rodam sobre ele. A estrutura central é o ndarray: números em blocos contínuos de memória, permitindo operações VETORIZADAS em C, 10-100x mais rápidas que loops Python. arr * 10 aplica a multiplicação a cada elemento sem loop visível — isso é 'broadcasting'. Mesmo para soma, comparações, np.sqrt, np.log: todas vetorizadas. Listas Python normais não têm isso — lista * 10 só repete a lista.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Aceleração vetorial ativada.",
      solution: "import numpy as np\narr = np.array([1, 2, 3, 4, 5])\nprint(arr * 10)",
    },
    {
      id: "ds-numpy-02",
      worldId: "refinaria-dados",
      title: "Estatística NumPy",
      description: "Dado o array 'temp' = np.array([22,28,35,19,41]), imprima média e desvio padrão (uma por linha).",
      narrative: "Sensores térmicos reportaram leituras. Calcule média e desvio para detectar anomalias.",
      difficulty: "avancado",
      setupCode: "import numpy as np\ntemp = np.array([22, 28, 35, 19, 41])",
      expectedOutput: "29.0\n8.0",
      testCode: "assert 'np.mean' in code and 'np.std' in code",
      starterCode: "# Imprima np.mean e np.std\n",
      hints: [
        { text: "np.mean(arr) calcula a média; np.std(arr) calcula o desvio padrão. Ambos retornam um único número.", cost: 20 },
        { text: "Imprima em linhas separadas — dois print() distintos.", cost: 25 },
        { text: "print(np.mean(temp))\\nprint(np.std(temp))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Estatística com NumPy",
      conceptExplanation: "NumPy oferece estatística otimizada em arrays inteiros sem loops: np.mean (média), np.median (mediana — meio quando ordenado), np.std (desvio padrão — dispersão em torno da média), np.var (variância), np.min/max, np.percentile (quantis). Desvio baixo = dados próximos da média; alto = dispersão. Para análise por linha/coluna em arrays 2D, use axis: np.mean(M, axis=0) por coluna; axis=1 por linha. Essas são as primeiras métricas obrigatórias em qualquer análise.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Variância dentro do limite seguro.",
      solution: "import numpy as np\ntemp = np.array([22, 28, 35, 19, 41])\nprint(np.mean(temp))\nprint(np.std(temp))",
    },
    {
      id: "ds-numpy-03",
      worldId: "refinaria-dados",
      title: "Arrays Especiais",
      description: "Crie um array de zeros com shape (3,) usando np.zeros e imprima.",
      narrative: "Para inicializar buffers ou pesos de modelos, comece com zeros.",
      difficulty: "intermediario",
      setupCode: "import numpy as np",
      expectedOutput: "[0. 0. 0.]",
      testCode: "assert 'np.zeros' in code",
      starterCode: "# Crie array de zeros com 3 elementos\n",
      hints: [
        { text: "np.zeros(shape) cria array preenchido com zeros. shape pode ser int (1D) ou tupla (multi-D).", cost: 20 },
        { text: "Para 3 elementos 1D, passe 3 ou (3,). Por padrão são floats. Análogos: np.ones (uns), np.full(shape, valor).", cost: 25 },
        { text: "print(np.zeros(3))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Inicialização de Arrays",
      conceptExplanation: "NumPy oferece criadores rápidos de arrays: np.zeros(shape) preenche com 0; np.ones(shape) com 1; np.full(shape, valor) com valor arbitrário; np.empty(shape) sem inicializar (mais rápido mas memória aleatória); np.eye(N) matriz identidade NxN. Shape é um inteiro (1D) ou tupla (multi-D): np.zeros((3,4)) cria matriz 3x4. Use dtype para controlar tipo: np.zeros(5, dtype=int). Essenciais para pré-alocar arrays antes de preencher em loops ou inicializar parâmetros de modelos.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Buffer zerado pronto para uso.",
      solution: "import numpy as np\nprint(np.zeros(3))",
    },
    {
      id: "ds-numpy-04",
      worldId: "refinaria-dados",
      title: "Sequências com arange",
      description: "Crie um array com os números 0,1,2,...,9 usando np.arange(10) e imprima.",
      narrative: "Para gerar sequências indexadas (timestamps, IDs), arange é o gerador rápido.",
      difficulty: "intermediario",
      setupCode: "import numpy as np",
      expectedOutput: "[0 1 2 3 4 5 6 7 8 9]",
      testCode: "assert 'np.arange' in code",
      starterCode: "# Crie array 0..9\n",
      hints: [
        { text: "np.arange(N) é como range(N) mas retorna um array NumPy: [0, 1, ..., N-1].", cost: 20 },
        { text: "Sintaxe completa: np.arange(start, stop, step) — exclusive no stop, igual range. Para floats use np.linspace.", cost: 25 },
        { text: "print(np.arange(10))", cost: 30 },
      ],
      xpReward: 600,
      concept: "Sequências (arange/linspace)",
      conceptExplanation: "np.arange(start, stop, step) gera sequências aritméticas (exclusive em stop, igual range do Python) — mas retorna um array NumPy. Aceita float também: np.arange(0, 1, 0.1). Para um número específico de pontos entre dois valores, use np.linspace(start, stop, num) — INCLUSIVE em stop, ideal para gráficos contínuos: np.linspace(0, 2*np.pi, 100). São os geradores padrão para timestamps, eixos de plot, índices de batch e qualquer sequência regular.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Sequência gerada.",
      solution: "import numpy as np\nprint(np.arange(10))",
    },
    {
      id: "ds-numpy-05",
      worldId: "refinaria-dados",
      title: "Reshape",
      description: "Dado arr = np.arange(6), faça reshape para (2, 3) e imprima a matriz resultante.",
      narrative: "Para alimentar uma rede neural, você precisa do shape exato. Reformate o tensor.",
      difficulty: "avancado",
      setupCode: "import numpy as np\narr = np.arange(6)",
      expectedOutput: "[[0 1 2]\n [3 4 5]]",
      testCode: "assert 'reshape' in code",
      starterCode: "# Reshape para (2, 3) e imprima\n",
      hints: [
        { text: "arr.reshape(linhas, colunas) muda o shape sem alterar os dados. O total de elementos precisa bater (2*3=6, igual ao len).", cost: 20 },
        { text: "Para dimensão automática, passe -1: arr.reshape(2, -1) deixa o NumPy calcular a outra dimensão.", cost: 25 },
        { text: "print(arr.reshape(2, 3))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Reshape e Shapes",
      conceptExplanation: "reshape() reorganiza o array em uma nova forma sem alterar os dados subjacentes. O total de elementos precisa bater entre o shape antigo e o novo (arr de 6 → 2x3 ou 3x2 ou 6x1). Use -1 em uma das dimensões para auto-cálculo: arr.reshape(-1, 4) calcula automaticamente quantas linhas dão para 4 colunas. Operação muito comum antes de alimentar modelos (que esperam shapes específicos como (batch, features) ou (batch, altura, largura, canais)). flatten() faz o inverso — colapsa em 1D.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tensor reformatado para entrada do modelo.",
      solution: "import numpy as np\narr = np.arange(6)\nprint(arr.reshape(2, 3))",
    },
    {
      id: "ds-numpy-06",
      worldId: "refinaria-dados",
      title: "Máscara Booleana",
      description: "Dado arr = np.array([1,5,3,8,2]), imprima apenas os elementos maiores que 3.",
      narrative: "Filtros vetorizados no NumPy seguem a mesma lógica do pandas.",
      difficulty: "avancado",
      setupCode: "import numpy as np\narr = np.array([1, 5, 3, 8, 2])",
      expectedOutput: "[5 8]",
      testCode: "assert 'arr >' in code or 'arr[' in code",
      starterCode: "# Filtre elementos > 3\n",
      hints: [
        { text: "Comparação direta gera array booleano: arr > 3 retorna [False, True, False, True, False].", cost: 20 },
        { text: "Indexe o array com esse booleano: arr[arr > 3] mantém só onde a condição é True.", cost: 25 },
        { text: "print(arr[arr > 3])", cost: 30 },
      ],
      xpReward: 800,
      concept: "Boolean Mask",
      conceptExplanation: "Máscaras booleanas são a forma vetorizada de filtrar arrays NumPy: a comparação (arr > 3, arr == 0, np.isnan(arr)) gera um array booleano, e indexar o array original com ele retorna apenas os elementos True. Combinar condições: & e | (com parênteses), assim como em pandas. Outras funções: np.where(cond, valor_true, valor_false) escolhe valor por elemento; np.any(arr) verifica se algum é True; np.all() se todos. Base do filtro vetorizado em performance crítica.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Outliers filtrados vetorialmente.",
      solution: "import numpy as np\narr = np.array([1, 5, 3, 8, 2])\nprint(arr[arr > 3])",
    },
    {
      id: "ds-numpy-07",
      worldId: "refinaria-dados",
      title: "Números Aleatórios",
      description: "Após np.random.seed(0), gere 3 números aleatórios uniformes em [0,1) com np.random.rand(3) e imprima.",
      narrative: "Para simulações, dados sintéticos ou inicialização de pesos, gere ruído controlado.",
      difficulty: "avancado",
      setupCode: "import numpy as np",
      expectedOutput: "[0.5488135  0.71518937 0.60276338]",
      testCode: "assert 'np.random' in code",
      starterCode: "import numpy as np\nnp.random.seed(0)\n# Gere 3 números aleatórios uniformes\n",
      hints: [
        { text: "np.random.rand(N) gera N números aleatórios uniformes em [0, 1). Para distribuição normal: np.random.randn(N).", cost: 25 },
        { text: "Após np.random.seed(0), a sequência é reproduzível — sempre os mesmos números entre execuções.", cost: 30 },
        { text: "print(np.random.rand(3))", cost: 35 },
      ],
      xpReward: 850,
      concept: "Geração Aleatória",
      conceptExplanation: "np.random oferece diversas distribuições: rand(shape) uniforme [0,1); randn(shape) normal padrão (média 0, std 1); randint(low, high, size) inteiros; choice(arr, size) amostragem com/sem reposição. CRUCIAL para reprodutibilidade: chame np.random.seed(N) antes — fixa a semente do gerador, garantindo mesma sequência entre execuções (essencial em ML para resultados comparáveis). Para gerador moderno e isolado: rng = np.random.default_rng(seed) — preferido em código novo.",
      successNpc: "Arquiteto de Sistema",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ruído controlado gerado.",
      solution: "import numpy as np\nnp.random.seed(0)\nprint(np.random.rand(3))",
    },
  ],
};
