import { World } from "../types";

export const SALA_COMANDO_VISUAL_WORLD: World = {
  id: "sala-comando-visual",
  title: "Sala de Comando Visual",
  subtitle: "Visualização de Dados",
  icon: "line-chart",
  color: "#22D3EE",
  bgImage: "/assets/images/worlds/visual_command.png",
  lore: "Transforme números em insights visuais. Construa gráficos, dashboards e mapas de calor que revelam padrões ocultos nos dados da rede.",
  unlockRequirement: 16000,
  challenges: [
    {
      id: "ds-viz-01",
      worldId: "sala-comando-visual",
      title: "O Primeiro Gráfico",
      description: "Importe matplotlib.pyplot como plt. Plote a lista [1, 2, 3] e exiba o gráfico.",
      narrative: "Para entender a taxa de invasão ao Core, precisamos desenhar o crescimento ao longo do tempo. Ative o renderizador gráfico.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(data): print(f'Gráfico gerado com dados: {data}')\n    @staticmethod\n    def show(): print('Gráfico exibido na tela.')\nplt = plt_mock()",
      expectedOutput: "Gráfico gerado com dados: [1, 2, 3]\nGráfico exibido na tela.",
      testCode: "assert 'plt.plot' in code and 'plt.show' in code",
      starterCode: "import matplotlib.pyplot as plt\n# Plote a lista [1, 2, 3] e chame plt.show()\n",
      hints: [
        { text: "O alias 'plt' é convenção universal para matplotlib.pyplot. Toda documentação, livro e tutorial usa esse nome.", cost: 10 },
        { text: "plt.plot(dados) cria a linha; plt.show() é o que faz a janela aparecer na tela. Sem show(), o gráfico é construído mas não renderizado.", cost: 20 },
        { text: "import matplotlib.pyplot as plt\\nplt.plot([1, 2, 3])\\nplt.show()", cost: 30 },
      ],
      xpReward: 500,
      concept: "Matplotlib e Pyplot",
      conceptExplanation: "Matplotlib é a biblioteca de plotagem padrão do Python — todas as outras (seaborn, plotly, pandas .plot()) são construídas sobre ela. A interface mais usada é o módulo pyplot (importado como plt), que segue o paradigma do MATLAB: você chama funções em sequência (plot, title, xlabel) que vão configurando uma 'figura ativa' invisível, e plt.show() finalmente renderiza tudo. A função plot() conecta pontos com linhas — ideal para séries temporais. Outras funções importantes: bar (barras), scatter (pontos isolados), hist (histograma), pie (pizza), boxplot. Em Jupyter Notebooks com %matplotlib inline, o show() não é estritamente necessário porque o notebook renderiza automaticamente, mas é boa prática chamá-lo sempre para garantir consistência entre ambientes.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Projeção gráfica renderizada. A tendência mostra um pico de atividade suspeita nas últimas 2 horas.",
      solution: "import matplotlib.pyplot as plt\nplt.plot([1, 2, 3])\nplt.show()",
    },
    {
      id: "ds-viz-02",
      worldId: "sala-comando-visual",
      title: "Rótulos e Título",
      description: "Use plt.title('Ataques por Hora'), plt.xlabel('Hora') e plt.ylabel('Quantidade'). Depois chame plt.show().",
      narrative: "Um gráfico sem contexto não comunica nada. Adicione título e legendas aos eixos para que a equipe de inteligência possa interpretar o relatório.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def title(t): print(f'Título: {t}')\n    @staticmethod\n    def xlabel(x): print(f'X: {x}')\n    @staticmethod\n    def ylabel(y): print(f'Y: {y}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Título: Ataques por Hora\nX: Hora\nY: Quantidade\nExibido.",
      testCode: "assert 'plt.title' in code and 'plt.xlabel' in code and 'plt.ylabel' in code",
      starterCode: "# Defina título, rótulo X, rótulo Y e exiba\n",
      hints: [
        { text: "Cada função recebe uma string. plt.title define o título do gráfico; plt.xlabel rotula o eixo horizontal; plt.ylabel rotula o vertical.", cost: 10 },
        { text: "A ordem das chamadas não importa entre title/xlabel/ylabel — todas configuram a mesma figura ativa. Só garanta que plt.show() seja a ÚLTIMA.", cost: 20 },
        { text: "plt.title('Ataques por Hora')\\nplt.xlabel('Hora')\\nplt.ylabel('Quantidade')\\nplt.show()", cost: 30 },
      ],
      xpReward: 550,
      concept: "Anotação e Comunicação de Gráficos",
      conceptExplanation: "Um gráfico sem rótulos é tecnicamente uma figura, mas comunicacionalmente é ruído — quem está vendo não sabe o que está olhando. Sempre adicione título (o que estamos vendo no geral), xlabel (o que o eixo horizontal representa, geralmente com unidade) e ylabel (o que o eixo vertical representa). Em matplotlib essas são funções do plt que modificam a figura ativa. Para gráficos publicáveis ou apresentáveis, você também tem: plt.legend() (legenda das séries plotadas), plt.grid() (grade de fundo facilita leitura), plt.figure(figsize=(largura, altura)) controla o tamanho e plt.savefig('grafico.png') salva em arquivo. Quanto mais claro o gráfico, menor o esforço cognitivo de quem está interpretando — e em ambientes profissionais isso muda decisões.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Relatório legível. A diretoria entendeu os padrões em segundos.",
      solution: "plt.title('Ataques por Hora')\nplt.xlabel('Hora')\nplt.ylabel('Quantidade')\nplt.show()",
    },
    {
      id: "ds-viz-03",
      worldId: "sala-comando-visual",
      title: "Gráfico de Barras",
      description: "Plote um gráfico de barras com categorias=['Core','Edge','DMZ'] e valores=[12, 7, 4], depois exiba.",
      narrative: "Compare o volume de tentativas de invasão entre os três setores. Barras facilitam a leitura categórica.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def bar(c, v): print(f'Barras: {c} -> {v}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Barras: ['Core', 'Edge', 'DMZ'] -> [12, 7, 4]\nExibido.",
      testCode: "assert 'plt.bar' in code and 'plt.show' in code",
      starterCode: "categorias = ['Core', 'Edge', 'DMZ']\nvalores = [12, 7, 4]\n# Plote barras e exiba\n",
      hints: [
        { text: "Para barras, use plt.bar(eixo_x, alturas). O eixo_x pode ser strings (categorias) ou números — o matplotlib lida com ambos.", cost: 20 },
        { text: "As duas listas devem ter o mesmo tamanho — cada item de uma corresponde ao item da outra no mesmo índice.", cost: 25 },
        { text: "plt.bar(categorias, valores)\\nplt.show()", cost: 30 },
      ],
      xpReward: 600,
      concept: "Bar Chart (Gráfico de Barras)",
      conceptExplanation: "Gráficos de barras são a melhor escolha para comparar quantidades entre categorias DISCRETAS (setores, produtos, classes, países) — algo que o gráfico de linha não faz bem, porque linha sugere continuidade no tempo. plt.bar(x, height) desenha barras verticais; plt.barh(y, width) desenha horizontais (útil quando há muitas categorias e os rótulos verticais se sobrepõem). Para barras agrupadas (comparando duas séries lado a lado), você desenha duas chamadas de bar() com pequeno offset no eixo x. Para barras empilhadas, use o parâmetro 'bottom' da segunda chamada apontando para os valores da primeira. Personalize com cores (color='red'), bordas (edgecolor='black'), rotulagem de cada barra (plt.text) e rotação dos labels do eixo (plt.xticks(rotation=45)).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição categórica clara. Recursos sendo realocados para o Core.",
      solution: "plt.bar(categorias, valores)\nplt.show()",
    },
    {
      id: "ds-viz-04",
      worldId: "sala-comando-visual",
      title: "Dispersão de Pontos",
      description: "Use plt.scatter para plotar x=[1,2,3,4] versus y=[10,15,13,20] e exibir.",
      narrative: "Cada ponto é um operador detectado na rede. Um scatter plot revela aglomerações e outliers.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def scatter(x, y): print(f'Scatter: {x} x {y}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Scatter: [1, 2, 3, 4] x [10, 15, 13, 20]\nExibido.",
      testCode: "assert 'plt.scatter' in code and 'plt.show' in code",
      starterCode: "x = [1, 2, 3, 4]\ny = [10, 15, 13, 20]\n# Plote os pontos isolados\n",
      hints: [
        { text: "plt.scatter(x, y) desenha um ponto para cada par (x[i], y[i]). Diferente do plt.plot, os pontos NÃO são conectados por linhas.", cost: 20 },
        { text: "É a ferramenta padrão para investigar correlação entre duas variáveis numéricas — se y cresce com x, há correlação positiva; se cai, negativa.", cost: 25 },
        { text: "plt.scatter(x, y)\\nplt.show()", cost: 30 },
      ],
      xpReward: 650,
      concept: "Scatter Plot (Gráfico de Dispersão)",
      conceptExplanation: "Scatter plots são a forma padrão de investigar a relação entre duas variáveis numéricas: se uma cresce conforme a outra (correlação positiva), se cai conforme a outra cresce (correlação negativa), ou se não há padrão visível (sem correlação). Em ciência de dados, é o gráfico mais usado para (1) detecção de outliers — pontos isolados longe do grupo principal, frequentemente erros ou casos extremos — e (2) identificação de clusters — agrupamentos naturais que sugerem segmentos diferentes nos dados. Você pode adicionar mais dimensões visuais via parâmetros: c=lista_de_cores (cada ponto com cor diferente, ótimo para mostrar uma terceira variável categórica), s=lista_de_tamanhos (tamanho proporcional a uma quarta variável) e alpha=0.5 (transparência, essencial quando há muitos pontos sobrepostos).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Outliers identificados na zona DMZ. Investigação iniciada.",
      solution: "plt.scatter(x, y)\nplt.show()",
    },
    {
      id: "ds-viz-05",
      worldId: "sala-comando-visual",
      title: "Mapa de Calor (Seaborn)",
      description: "Importe seaborn como sns. Use sns.heatmap(matriz) e exiba com plt.show().",
      narrative: "Para correlacionar 50 variáveis de log, nada supera um heatmap. Renderize o mapa de calor da matriz de correlação.",
      difficulty: "avancado",
      setupCode: "class sns_mock:\n    @staticmethod\n    def heatmap(m): print(f'Heatmap renderizado: {len(m)}x{len(m[0])}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()\nmatriz = [[1, 0.8], [0.8, 1]]",
      expectedOutput: "Heatmap renderizado: 2x2\nExibido.",
      testCode: "assert 'sns.heatmap' in code and 'plt.show' in code",
      starterCode: "import seaborn as sns\nimport matplotlib.pyplot as plt\n# Desenhe o heatmap da matriz e exiba\n",
      hints: [
        { text: "Seaborn é construído sobre o matplotlib — você importa como 'import seaborn as sns' (alias universal) e ainda usa plt.show() para exibir.", cost: 20 },
        { text: "sns.heatmap(matriz) recebe uma matriz 2D (lista de listas ou DataFrame) e colore cada célula proporcionalmente ao valor.", cost: 25 },
        { text: "import seaborn as sns\\nimport matplotlib.pyplot as plt\\nsns.heatmap(matriz)\\nplt.show()", cost: 30 },
      ],
      xpReward: 800,
      concept: "Seaborn e Heatmaps",
      conceptExplanation: "Seaborn é uma biblioteca de visualização estatística construída SOBRE o matplotlib — ela oferece tipos de gráfico mais sofisticados (boxplot, violin, pairplot, heatmap, regplot) com menos código e estética mais moderna por padrão. Ela é especialmente boa quando você trabalha com DataFrames do pandas. O heatmap é o gráfico ideal para matrizes: matrizes de correlação (revelando quais variáveis se relacionam — o caso mais comum em análise exploratória, gerado por df.corr()), matrizes de confusão (avaliando modelos de classificação), ou qualquer dado tabular 2D onde a cor comunica intensidade. Parâmetros importantes do heatmap: annot=True mostra os valores numéricos em cada célula; cmap='coolwarm' usa paleta com cores intuitivas (vermelho positivo, azul negativo); fmt='.2f' formata os números mostrados. Para uma visão rápida de correlações em um DataFrame: sns.heatmap(df.corr(), annot=True).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Correlações fortes identificadas entre IPs estrangeiros e horários de pico.",
      solution: "import seaborn as sns\nimport matplotlib.pyplot as plt\nsns.heatmap(matriz)\nplt.show()",
    },
  ],
};
