import { World } from "../types";

export const SALA_COMANDO_VISUAL_WORLD: World = {
  id: "sala-comando-visual",
  title: "Sala de Comando Visual",
  subtitle: "Visualização de Dados",
  icon: "line-chart",
  color: "#22D3EE",
  bgImage: "/assets/images/worlds/visual_command.png",
  lore: "Transforme números em insights visuais. Construa gráficos, dashboards e mapas de calor que revelam padrões ocultos nos dados da rede.",
  unlockRequirement: 16000,
  challenges: [
    {
      id: "ds-viz-01",
      worldId: "sala-comando-visual",
      title: "Primeiro Gráfico",
      description: "Importe matplotlib.pyplot como plt. Plote [1,2,3] e exiba com plt.show().",
      narrative: "Ative o renderizador gráfico do sistema de defesa.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print(f'Gráfico: {d}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Gráfico: [1, 2, 3]\nExibido.",
      testCode: "assert 'plt.plot' in code and 'plt.show' in code",
      starterCode: "import matplotlib.pyplot as plt\n# Plote [1,2,3] e exiba\n",
      hints: [
        { text: "O alias 'plt' é convenção universal para matplotlib.pyplot.", cost: 10 },
        { text: "plt.plot(dados) cria a linha; plt.show() renderiza a janela.", cost: 20 },
        { text: "plt.plot([1, 2, 3])\\nplt.show()", cost: 30 },
      ],
      xpReward: 500,
      concept: "Matplotlib e Pyplot",
      conceptExplanation: "Matplotlib é a biblioteca de plotagem padrão do Python — todas as outras (seaborn, pandas .plot) rodam sobre ela. O módulo pyplot (importado como plt) segue o paradigma MATLAB: você chama funções em sequência (plot, title, xlabel) que configuram uma 'figura ativa' invisível, e plt.show() renderiza tudo. plot() conecta pontos com linha; outros: bar, scatter, hist, pie, boxplot. Em Jupyter com %matplotlib inline o show() não é estritamente necessário, mas é boa prática.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Renderização ativa.",
      solution: "plt.plot([1, 2, 3])\nplt.show()",
    },
    {
      id: "ds-viz-02",
      worldId: "sala-comando-visual",
      title: "Título e Rótulos",
      description: "Defina título 'Ataques por Hora', xlabel 'Hora', ylabel 'Quantidade' e exiba.",
      narrative: "Um gráfico sem contexto não comunica nada.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def title(t): print(f'T: {t}')\n    @staticmethod\n    def xlabel(x): print(f'X: {x}')\n    @staticmethod\n    def ylabel(y): print(f'Y: {y}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "T: Ataques por Hora\nX: Hora\nY: Quantidade\nExibido.",
      testCode: "assert 'plt.title' in code and 'plt.xlabel' in code and 'plt.ylabel' in code",
      starterCode: "# Título, rótulos X e Y, depois show()\n",
      hints: [
        { text: "Cada função recebe uma string. plt.title (título), plt.xlabel (eixo X), plt.ylabel (eixo Y).", cost: 10 },
        { text: "A ordem entre title/xlabel/ylabel não importa; só garanta que plt.show() seja a ÚLTIMA chamada.", cost: 20 },
        { text: "plt.title('Ataques por Hora')\\nplt.xlabel('Hora')\\nplt.ylabel('Quantidade')\\nplt.show()", cost: 30 },
      ],
      xpReward: 550,
      concept: "Anotação de Gráficos",
      conceptExplanation: "Gráfico sem rótulos é ruído. Sempre adicione título (o que estamos vendo), xlabel (eixo horizontal com unidade) e ylabel (eixo vertical). Funções relacionadas: plt.legend() (legenda das séries), plt.grid() (grade de fundo), plt.figure(figsize=(w,h)) controla tamanho, plt.savefig('arq.png') salva em arquivo. Quanto mais claro, menor o esforço cognitivo para interpretar.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Relatório legível.",
      solution: "plt.title('Ataques por Hora')\nplt.xlabel('Hora')\nplt.ylabel('Quantidade')\nplt.show()",
    },
    {
      id: "ds-viz-03",
      worldId: "sala-comando-visual",
      title: "Gráfico de Barras",
      description: "Plote barras com categorias=['Core','Edge','DMZ'] e valores=[12,7,4]. Exiba.",
      narrative: "Compare volume de invasão entre setores.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def bar(c, v): print(f'Bar: {c} -> {v}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Bar: ['Core', 'Edge', 'DMZ'] -> [12, 7, 4]\nExibido.",
      testCode: "assert 'plt.bar' in code",
      starterCode: "categorias = ['Core', 'Edge', 'DMZ']\nvalores = [12, 7, 4]\n# plt.bar e plt.show\n",
      hints: [
        { text: "plt.bar(eixo_x, alturas). x pode ser strings ou números — matplotlib lida com ambos.", cost: 20 },
        { text: "As duas listas precisam ter o mesmo tamanho.", cost: 25 },
        { text: "plt.bar(categorias, valores)\\nplt.show()", cost: 30 },
      ],
      xpReward: 600,
      concept: "Bar Chart",
      conceptExplanation: "Barras são a melhor escolha para comparar quantidades entre categorias DISCRETAS (setores, produtos, classes). plt.bar(x, height) é vertical; plt.barh(y, width) horizontal (melhor com muitas categorias). Para barras agrupadas, faça duas chamadas de bar() com offset no x. Para empilhadas, use o parâmetro 'bottom'. Personalize: color='red', edgecolor='black', plt.xticks(rotation=45) para rotacionar rótulos.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição clara.",
      solution: "plt.bar(categorias, valores)\nplt.show()",
    },
    {
      id: "ds-viz-04",
      worldId: "sala-comando-visual",
      title: "Scatter Plot",
      description: "Plote pontos com x=[1,2,3,4], y=[10,15,13,20] usando scatter. Exiba.",
      narrative: "Cada ponto é um operador detectado. Scatter revela aglomerações e outliers.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def scatter(x, y): print(f'Scatter: {x} x {y}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Scatter: [1, 2, 3, 4] x [10, 15, 13, 20]\nExibido.",
      testCode: "assert 'plt.scatter' in code",
      starterCode: "x = [1, 2, 3, 4]\ny = [10, 15, 13, 20]\n# Plote pontos\n",
      hints: [
        { text: "plt.scatter(x, y) desenha um ponto por par (x[i], y[i]). Diferente de plot, NÃO conecta com linhas.", cost: 20 },
        { text: "É a ferramenta padrão para investigar correlação entre duas variáveis numéricas.", cost: 25 },
        { text: "plt.scatter(x, y)\\nplt.show()", cost: 30 },
      ],
      xpReward: 650,
      concept: "Scatter Plot",
      conceptExplanation: "Scatter plots investigam a relação entre duas variáveis numéricas: correlação positiva (y cresce com x), negativa (y cai), nenhuma. Em DS são essenciais para detecção de outliers (pontos isolados) e clusters (agrupamentos). Parâmetros poderosos: c=cores (terceira dimensão visual via cor), s=tamanhos (quarta via tamanho do ponto), alpha=0.5 (transparência, crucial com muitos pontos sobrepostos).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Outliers identificados.",
      solution: "plt.scatter(x, y)\nplt.show()",
    },
    {
      id: "ds-viz-05",
      worldId: "sala-comando-visual",
      title: "Histograma",
      description: "Plote o histograma de dados=[1,2,2,3,3,3,4,4,5] e exiba.",
      narrative: "Veja como os valores se distribuem em faixas.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def hist(d): print(f'Hist: {d}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Hist: [1, 2, 2, 3, 3, 3, 4, 4, 5]\nExibido.",
      testCode: "assert 'plt.hist' in code",
      starterCode: "dados = [1, 2, 2, 3, 3, 3, 4, 4, 5]\n# Use plt.hist\n",
      hints: [
        { text: "plt.hist(dados) agrupa valores em 'bins' (faixas) e plota a contagem por faixa.", cost: 20 },
        { text: "Parâmetro bins controla quantas faixas: plt.hist(dados, bins=20). Padrão é 10.", cost: 25 },
        { text: "plt.hist(dados)\\nplt.show()", cost: 30 },
      ],
      xpReward: 650,
      concept: "Histograma",
      conceptExplanation: "Histograma mostra a DISTRIBUIÇÃO de uma variável contínua — divide o intervalo em faixas (bins) e conta quantos valores caem em cada uma. Revela formato dos dados: normal (curva de sino), assimétrico, bimodal, uniforme. Parâmetros: bins=N (quantas faixas — muitas = ruidoso, poucas = perde detalhe), density=True (proporção em vez de contagem), alpha=0.5 (transparência para sobrepor distribuições). Pode comparar grupos plotando múltiplos histogramas com alpha.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição mapeada.",
      solution: "plt.hist([1, 2, 2, 3, 3, 3, 4, 4, 5])\nplt.show()",
    },
    {
      id: "ds-viz-06",
      worldId: "sala-comando-visual",
      title: "Gráfico de Pizza",
      description: "Plote um pie chart com valores=[30,20,50] e exiba.",
      narrative: "Mostre a proporção entre as fontes de tráfego.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def pie(v): print(f'Pie: {v}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Pie: [30, 20, 50]\nExibido.",
      testCode: "assert 'plt.pie' in code",
      starterCode: "valores = [30, 20, 50]\n# Use plt.pie\n",
      hints: [
        { text: "plt.pie(valores) desenha fatias proporcionais. As fatias somam o círculo todo.", cost: 20 },
        { text: "Parâmetros úteis: labels=[...] (rótulos por fatia), autopct='%.1f%%' (mostra %).", cost: 25 },
        { text: "plt.pie(valores)\\nplt.show()", cost: 30 },
      ],
      xpReward: 650,
      concept: "Pie Chart",
      conceptExplanation: "Pizza mostra proporções de um todo (cada fatia = fração). plt.pie(valores) — valores não precisam somar 100, o matplotlib normaliza. Parâmetros: labels (rótulos), autopct='%.1f%%' (% nas fatias), colors, explode=[0,0.1,0] (destaca uma fatia). AVISO: pies são frequentemente criticados em DS — barras são mais legíveis para comparar proporções. Use só com poucas categorias (3-5) e quando proporção é a mensagem principal.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Proporções renderizadas.",
      solution: "plt.pie([30, 20, 50])\nplt.show()",
    },
    {
      id: "ds-viz-07",
      worldId: "sala-comando-visual",
      title: "Boxplot",
      description: "Plote o boxplot de dados=[1,2,3,4,5,100] e exiba. (Detecta outliers visualmente.)",
      narrative: "Visualize quartis e identifique outliers em uma única figura.",
      difficulty: "avancado",
      setupCode: "class plt_mock:\n    @staticmethod\n    def boxplot(d): print(f'Box: {d}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Box: [1, 2, 3, 4, 5, 100]\nExibido.",
      testCode: "assert 'plt.boxplot' in code",
      starterCode: "dados = [1, 2, 3, 4, 5, 100]\n# Use plt.boxplot\n",
      hints: [
        { text: "plt.boxplot(dados) desenha a 'caixa' representando quartis 25%-75%, mediana como linha central.", cost: 25 },
        { text: "Pontos fora dos 'whiskers' (geralmente 1.5*IQR) são plotados como outliers individuais.", cost: 30 },
        { text: "plt.boxplot(dados)\\nplt.show()", cost: 35 },
      ],
      xpReward: 750,
      concept: "Boxplot",
      conceptExplanation: "Boxplot (caixa de Tukey) é a forma mais compacta de resumir uma distribuição: a caixa marca o 1º e 3º quartis (50% dos dados); a linha do meio é a mediana; os 'whiskers' (bigodes) estendem até 1.5x o intervalo interquartil; pontos fora aparecem como outliers individuais. É a ferramenta ideal para comparar distribuições de MÚLTIPLOS grupos lado a lado: plt.boxplot([grupo1, grupo2, grupo3]). Mais informativo que histograma para detecção de outliers e comparação entre categorias.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Quartis e anomalias visíveis.",
      solution: "plt.boxplot([1, 2, 3, 4, 5, 100])\nplt.show()",
    },
    {
      id: "ds-viz-08",
      worldId: "sala-comando-visual",
      title: "Múltiplas Linhas",
      description: "Plote duas séries no mesmo gráfico: serie1=[1,3,2,4] e serie2=[2,1,3,5]. Exiba.",
      narrative: "Compare duas tendências sobrepostas na mesma figura.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print(f'Plot: {d}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot: [1, 3, 2, 4]\nPlot: [2, 1, 3, 5]\nExibido.",
      testCode: "assert code.count('plt.plot') >= 2",
      starterCode: "serie1 = [1, 3, 2, 4]\nserie2 = [2, 1, 3, 5]\n# Duas chamadas de plot, depois show\n",
      hints: [
        { text: "Cada chamada de plt.plot() adiciona uma série à mesma figura — não chame show entre elas.", cost: 20 },
        { text: "Faça plt.plot(serie1), depois plt.plot(serie2), por último plt.show().", cost: 25 },
        { text: "plt.plot(serie1)\\nplt.plot(serie2)\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Múltiplas Séries",
      conceptExplanation: "Para sobrepor várias séries no mesmo gráfico, basta chamar plt.plot() múltiplas vezes antes do plt.show() — cada chamada adiciona uma curva à figura ativa. As cores são atribuídas automaticamente pelo ciclo padrão (azul, laranja, verde...). Adicione legenda com plt.legend(['Serie 1', 'Serie 2']) ou passando label='nome' em cada plot e depois plt.legend(). Padrão para análise comparativa: previsto vs realizado, antes vs depois, grupo A vs B.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Séries sobrepostas para comparação.",
      solution: "plt.plot([1, 3, 2, 4])\nplt.plot([2, 1, 3, 5])\nplt.show()",
    },
    {
      id: "ds-viz-09",
      worldId: "sala-comando-visual",
      title: "Cor da Linha",
      description: "Plote [1,2,3] em vermelho usando o parâmetro color='red'. Exiba.",
      narrative: "Use cor para destacar pontos críticos.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d, color=None): print(f'Plot {d} cor={color}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot [1, 2, 3] cor=red\nExibido.",
      testCode: "assert \"color='red'\" in code or 'color=\"red\"' in code",
      starterCode: "# plt.plot com color='red'\n",
      hints: [
        { text: "Passe color='nome_cor' ao plt.plot(). Cores aceitas: 'red', 'blue', 'green', 'black', etc.", cost: 10 },
        { text: "Também aceita códigos hex: color='#FF5733' ou tuplas RGB.", cost: 20 },
        { text: "plt.plot([1, 2, 3], color='red')\\nplt.show()", cost: 30 },
      ],
      xpReward: 500,
      concept: "Cor em Plots",
      conceptExplanation: "Parâmetros de cor no matplotlib aceitam: nomes ('red', 'blue', 'navy'), códigos de letra ('r', 'b', 'g'), hex ('#FF5733'), tuplas RGB (0.2, 0.5, 0.8) ou paletas predefinidas (cmap em scatter). Convenções comuns: vermelho = erro/alerta, verde = sucesso, azul = neutro/positivo. Mantenha consistência entre gráficos do mesmo relatório — leitor reconhece o significado da cor rapidamente.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Destaque visual aplicado.",
      solution: "plt.plot([1, 2, 3], color='red')\nplt.show()",
    },
    {
      id: "ds-viz-10",
      worldId: "sala-comando-visual",
      title: "Linha Tracejada",
      description: "Plote [1,2,3] com linestyle='--' (tracejado). Exiba.",
      narrative: "Linhas tracejadas comunicam previsões ou metas — diferentes de dados reais.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d, linestyle=None): print(f'Plot ls={linestyle}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot ls=--\nExibido.",
      testCode: "assert 'linestyle' in code",
      starterCode: "# plt.plot com linestyle='--'\n",
      hints: [
        { text: "Passe linestyle='--' (tracejado). Outros: '-' (sólido, padrão), ':' (pontilhado), '-.' (traço-ponto).", cost: 15 },
        { text: "Forma curta equivalente: passe direto como segundo argumento: plt.plot(dados, '--').", cost: 20 },
        { text: "plt.plot([1, 2, 3], linestyle='--')\\nplt.show()", cost: 30 },
      ],
      xpReward: 500,
      concept: "Estilos de Linha",
      conceptExplanation: "linestyle controla o padrão da linha: '-' (sólido), '--' (tracejado), ':' (pontilhado), '-.' (traço-ponto). Combine com cor e marker para diferenciar séries: plt.plot(x, y, '--r') é tracejado vermelho. Convenções em DS: tracejado = previsão/baseline/meta, pontilhado = limite/threshold, sólido = dado observado. Em gráficos para daltônicos, varie o linestyle além da cor — garante leitura mesmo em monocromático.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Estilo customizado.",
      solution: "plt.plot([1, 2, 3], linestyle='--')\nplt.show()",
    },
    {
      id: "ds-viz-11",
      worldId: "sala-comando-visual",
      title: "Marcadores",
      description: "Plote [1,2,3] com marker='o' (círculos nos pontos). Exiba.",
      narrative: "Destaque cada ponto observado, especialmente com poucas amostras.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d, marker=None): print(f'Plot m={marker}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot m=o\nExibido.",
      testCode: "assert 'marker' in code",
      starterCode: "# plt.plot com marker='o'\n",
      hints: [
        { text: "marker='o' coloca círculos em cada ponto. Outros: 's' (quadrado), '^' (triângulo), '*' (estrela), 'x' (X), '+' (cruz).", cost: 15 },
        { text: "Ajuste o tamanho com markersize=10. Sem marker (padrão), só a linha aparece.", cost: 20 },
        { text: "plt.plot([1, 2, 3], marker='o')\\nplt.show()", cost: 30 },
      ],
      xpReward: 500,
      concept: "Marcadores",
      conceptExplanation: "Marcadores destacam pontos individuais sobre a linha. Lista comum: 'o' (círculo), 's' (quadrado), '^' (triângulo para cima), 'v' (para baixo), '*' (estrela), 'D' (diamante), 'x' (X), '+' (cruz). Combine com cor e linestyle: plt.plot(x, y, 'o-r') = círculos vermelhos conectados por linha sólida. Essenciais quando você tem poucos pontos (sem marker eles podem se 'esconder' na linha) ou quer destacar observações reais vs interpolação.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Observações destacadas.",
      solution: "plt.plot([1, 2, 3], marker='o')\nplt.show()",
    },
    {
      id: "ds-viz-12",
      worldId: "sala-comando-visual",
      title: "Legenda",
      description: "Plote duas séries com label='A' e label='B', adicione plt.legend() e exiba.",
      narrative: "Sem legenda, ninguém sabe qual linha é qual.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d, label=None): print(f'Plot {d} label={label}')\n    @staticmethod\n    def legend(): print('Legenda OK')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot [1, 2, 3] label=A\nPlot [3, 2, 1] label=B\nLegenda OK\nExibido.",
      testCode: "assert 'plt.legend' in code and 'label' in code",
      starterCode: "# Plote duas séries com labels, chame legend, depois show\n",
      hints: [
        { text: "Passe label='nome' em cada chamada de plot. Depois chame plt.legend() — ele lê os labels e desenha a caixa.", cost: 20 },
        { text: "plt.legend(loc='upper left') posiciona; 'best' (padrão) escolhe automaticamente a melhor região.", cost: 25 },
        { text: "plt.plot([1,2,3], label='A')\\nplt.plot([3,2,1], label='B')\\nplt.legend()\\nplt.show()", cost: 30 },
      ],
      xpReward: 650,
      concept: "Legenda",
      conceptExplanation: "Legendas identificam cada série em gráficos com múltiplas linhas/barras. Fluxo: passe label='nome' em cada plot/bar/scatter, depois chame plt.legend() — ele coleta os labels e desenha a caixa. Parâmetros: loc='upper right' (posição), fontsize, title='Categorias', frameon=False (sem borda), ncol=2 (colunas). Em gráficos densos, ajuste loc para não cobrir dados. Sem labels nos plots, legend() emite warning e fica vazia.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Séries identificadas.",
      solution: "plt.plot([1,2,3], label='A')\nplt.plot([3,2,1], label='B')\nplt.legend()\nplt.show()",
    },
    {
      id: "ds-viz-13",
      worldId: "sala-comando-visual",
      title: "Grid",
      description: "Plote [1,2,3], adicione plt.grid(True) e exiba.",
      narrative: "Grade de fundo facilita leitura precisa dos valores.",
      difficulty: "iniciante",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print(f'Plot {d}')\n    @staticmethod\n    def grid(b): print(f'Grid {b}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot [1, 2, 3]\nGrid True\nExibido.",
      testCode: "assert 'plt.grid' in code",
      starterCode: "# Plote e ative grid\n",
      hints: [
        { text: "plt.grid(True) liga a grade. Falso (padrão) desliga.", cost: 10 },
        { text: "Personalize: plt.grid(True, linestyle='--', alpha=0.5) — grade tracejada semi-transparente.", cost: 20 },
        { text: "plt.plot([1,2,3])\\nplt.grid(True)\\nplt.show()", cost: 30 },
      ],
      xpReward: 450,
      concept: "Grid",
      conceptExplanation: "plt.grid(True) adiciona linhas de grade horizontais e verticais alinhadas com os ticks dos eixos — facilita ler valores específicos do gráfico. Parâmetros: axis='x' ou 'y' (só uma direção), linestyle/color para customizar aparência, alpha=0.3 para deixar discreta. Use grid em gráficos onde leitura precisa de valor importa (séries temporais, performance); evite em gráficos densos (heatmaps, scatter com muitos pontos) onde a grade vira ruído.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Grade ativada.",
      solution: "plt.plot([1,2,3])\nplt.grid(True)\nplt.show()",
    },
    {
      id: "ds-viz-14",
      worldId: "sala-comando-visual",
      title: "Limites de Eixo",
      description: "Plote [1,2,3] e force o eixo Y entre 0 e 10 com plt.ylim(0, 10). Exiba.",
      narrative: "Controle a escala para evitar gráficos enganosos.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print(f'Plot {d}')\n    @staticmethod\n    def ylim(a, b): print(f'ylim {a}-{b}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot [1, 2, 3]\nylim 0-10\nExibido.",
      testCode: "assert 'plt.ylim' in code",
      starterCode: "# Plote e fixe ylim em (0, 10)\n",
      hints: [
        { text: "plt.ylim(min, max) define limites do eixo Y; plt.xlim(min, max) faz o mesmo no X.", cost: 20 },
        { text: "Por padrão, matplotlib ajusta para os dados. Forçar limites é crucial para escala fixa entre gráficos comparáveis.", cost: 25 },
        { text: "plt.plot([1,2,3])\\nplt.ylim(0, 10)\\nplt.show()", cost: 30 },
      ],
      xpReward: 600,
      concept: "Limites de Eixo (xlim/ylim)",
      conceptExplanation: "plt.xlim(min, max) e plt.ylim(min, max) forçam limites fixos para os eixos. Por padrão o matplotlib ajusta automaticamente aos dados, mas escala fixa é essencial: (1) ao comparar gráficos com ESCALAS diferentes — leitor precisa do mesmo referencial; (2) para evitar 'gráficos enganosos' onde uma pequena variação parece dramática por causa do zoom; (3) ao garantir que valores 0 estejam visíveis (relevante em barras — começar em valor não-zero distorce percepção visual de tamanho).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Escala fixada.",
      solution: "plt.plot([1,2,3])\nplt.ylim(0, 10)\nplt.show()",
    },
    {
      id: "ds-viz-15",
      worldId: "sala-comando-visual",
      title: "Rotação de Ticks",
      description: "Plote categorias=['Janeiro','Fevereiro','Marco'] como barras e rotacione os ticks do eixo X em 45 graus.",
      narrative: "Rótulos longos no eixo X se sobrepõem. Rotacione para legibilidade.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def bar(x, y): print(f'Bar')\n    @staticmethod\n    def xticks(rotation=None): print(f'Rot={rotation}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Bar\nRot=45\nExibido.",
      testCode: "assert 'xticks' in code and '45' in code",
      starterCode: "categorias = ['Janeiro', 'Fevereiro', 'Marco']\nvalores = [10, 20, 15]\n# Plote barras e rotacione xticks em 45\n",
      hints: [
        { text: "Após plt.bar(), chame plt.xticks(rotation=45). Pode passar -45 para sentido contrário.", cost: 20 },
        { text: "Para passar rótulos custom junto: plt.xticks(posicoes, rotulos, rotation=45).", cost: 25 },
        { text: "plt.bar(categorias, valores)\\nplt.xticks(rotation=45)\\nplt.show()", cost: 30 },
      ],
      xpReward: 600,
      concept: "Customização de Ticks",
      conceptExplanation: "Ticks são as marcações nos eixos. plt.xticks() e plt.yticks() permitem customização: rotation=45 (rotaciona rótulos longos), fontsize, ou substituir totalmente: plt.xticks([0,1,2], ['baixo','médio','alto']). Para hide completamente: plt.xticks([]). Em séries temporais com datas, use plt.gcf().autofmt_xdate() para auto-rotacionar datas. Rotular bem economiza muito do leitor.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Rótulos legíveis.",
      solution: "plt.bar(categorias, valores)\nplt.xticks(rotation=45)\nplt.show()",
    },
    {
      id: "ds-viz-16",
      worldId: "sala-comando-visual",
      title: "Subplots",
      description: "Crie 1 figura com 2 subplots lado a lado usando plt.subplots(1, 2) e imprima 'Subplots criados.'.",
      narrative: "Dashboard precisa de múltiplos gráficos na mesma figura.",
      difficulty: "avancado",
      setupCode: "class plt_mock:\n    @staticmethod\n    def subplots(r, c):\n        print(f'Subplots {r}x{c}')\n        return None, None\nplt = plt_mock()",
      expectedOutput: "Subplots 1x2\nSubplots criados.",
      testCode: "assert 'subplots' in code",
      starterCode: "# Use plt.subplots(1, 2) e imprima confirmação\n",
      hints: [
        { text: "fig, axes = plt.subplots(nrows, ncols) cria UMA figura com grid de subplots. Retorna a figura e os eixos.", cost: 25 },
        { text: "axes é array (para múltiplos) ou Axes único. Use axes[0].plot(...) para plotar em cada subplot.", cost: 30 },
        { text: "fig, axes = plt.subplots(1, 2)\\nprint('Subplots criados.')", cost: 35 },
      ],
      xpReward: 850,
      concept: "Subplots",
      conceptExplanation: "Para múltiplos gráficos na mesma figura, use plt.subplots(nrows, ncols) — retorna a figura e um array de Axes. Cada Axes tem seus próprios métodos (axes[0].plot(...), axes[1].bar(...)). Para grids maiores, axes é 2D: axes[0,1]. Use sharex=True/sharey=True para alinhar eixos. plt.tight_layout() ajusta espaçamento para não sobrepor labels. Essencial em dashboards e comparações lado a lado. API orientada a objetos (com Axes) é mais robusta que a interface pyplot stateful para gráficos complexos.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Painel composto pronto.",
      solution: "fig, axes = plt.subplots(1, 2)\nprint('Subplots criados.')",
    },
    {
      id: "ds-viz-17",
      worldId: "sala-comando-visual",
      title: "Tamanho da Figura",
      description: "Crie uma figura com figsize=(10, 4) usando plt.figure e imprima 'Figura customizada.'.",
      narrative: "Para relatórios, padronize as dimensões dos gráficos.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def figure(figsize=None): print(f'Figsize={figsize}')\nplt = plt_mock()",
      expectedOutput: "Figsize=(10, 4)\nFigura customizada.",
      testCode: "assert 'figsize' in code",
      starterCode: "# Use plt.figure(figsize=(10, 4)) e imprima confirmação\n",
      hints: [
        { text: "plt.figure(figsize=(largura, altura)) — em polegadas. Padrão geralmente é (6.4, 4.8).", cost: 20 },
        { text: "Chame ANTES de qualquer plot — a próxima plotagem usa essa figura.", cost: 25 },
        { text: "plt.figure(figsize=(10, 4))\\nprint('Figura customizada.')", cost: 30 },
      ],
      xpReward: 600,
      concept: "Tamanho da Figura",
      conceptExplanation: "plt.figure(figsize=(w, h)) define o tamanho em polegadas — afeta a resolução final em pixels (figsize × dpi). Padrão é ~(6.4, 4.8). Aspectos comuns: largo (10, 4) para séries temporais; alto (4, 6) para barras horizontais com muitas categorias; quadrado (8, 8) para heatmaps de correlação. Em plt.subplots também aceita figsize. Para relatórios PDF/print, mantenha proporção 4:3 ou 16:9; para notebooks, use dimensões que caibam na tela sem scroll.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Dimensões padronizadas.",
      solution: "plt.figure(figsize=(10, 4))\nprint('Figura customizada.')",
    },
    {
      id: "ds-viz-18",
      worldId: "sala-comando-visual",
      title: "Salvar Figura",
      description: "Após plotar, chame plt.savefig('grafico.png') para salvar o arquivo.",
      narrative: "Exporte gráficos para incluir em relatórios e apresentações.",
      difficulty: "intermediario",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print(f'Plot')\n    @staticmethod\n    def savefig(f): print(f'Salvo: {f}')\nplt = plt_mock()",
      expectedOutput: "Plot\nSalvo: grafico.png",
      testCode: "assert 'savefig' in code",
      starterCode: "plt.plot([1,2,3])\n# Salve como 'grafico.png'\n",
      hints: [
        { text: "plt.savefig('arquivo.ext') salva no formato pela extensão: .png, .pdf, .svg, .jpg.", cost: 20 },
        { text: "Para alta qualidade: dpi=300. Para fundo transparente: transparent=True.", cost: 25 },
        { text: "plt.savefig('grafico.png')", cost: 30 },
      ],
      xpReward: 600,
      concept: "Exportação",
      conceptExplanation: "plt.savefig('arquivo.ext') exporta a figura. O formato é inferido pela extensão: .png (raster, padrão), .pdf (vetorial, ideal para impressão), .svg (vetorial editável), .jpg. Parâmetros importantes: dpi=300 (alta resolução para print); bbox_inches='tight' (corta espaço em branco em volta); transparent=True (fundo transparente, útil em apresentações). Chame ANTES de plt.show() — em alguns backends, show() limpa a figura.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Gráfico exportado.",
      solution: "plt.plot([1,2,3])\nplt.savefig('grafico.png')",
    },
    {
      id: "ds-viz-19",
      worldId: "sala-comando-visual",
      title: "Anotação",
      description: "Adicione uma anotação 'Pico' na coordenada (2, 10) com plt.annotate.",
      narrative: "Destaque eventos importantes diretamente no gráfico.",
      difficulty: "avancado",
      setupCode: "class plt_mock:\n    @staticmethod\n    def annotate(t, xy): print(f'Anot: {t} em {xy}')\nplt = plt_mock()",
      expectedOutput: "Anot: Pico em (2, 10)",
      testCode: "assert 'annotate' in code",
      starterCode: "# plt.annotate('Pico', xy=(2, 10))\n",
      hints: [
        { text: "plt.annotate('texto', xy=(x, y)) coloca texto no ponto. xy é a coordenada de dados.", cost: 25 },
        { text: "Para seta apontando: arrowprops=dict(arrowstyle='->'). Para posicionar texto longe do ponto: xytext=(x2, y2).", cost: 30 },
        { text: "plt.annotate('Pico', xy=(2, 10))", cost: 35 },
      ],
      xpReward: 750,
      concept: "Anotações",
      conceptExplanation: "plt.annotate('texto', xy=(x,y)) adiciona texto em coordenadas de dados. Para destacar um ponto com seta: xytext=(x2,y2) (onde fica o texto) + arrowprops=dict(arrowstyle='->', color='red'). Use para marcar máximos, eventos importantes, outliers ou marcos temporais. plt.text(x, y, 'texto') é a versão sem seta. Em séries temporais, anotações são essenciais para contexto: 'lançamento do produto', 'crise', 'mudança de algoritmo'.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Evento crítico marcado.",
      solution: "plt.annotate('Pico', xy=(2, 10))",
    },
    {
      id: "ds-viz-20",
      worldId: "sala-comando-visual",
      title: "Escala Log",
      description: "Use plt.yscale('log') para colocar o eixo Y em escala logarítmica.",
      narrative: "Dados que variam por ordens de grandeza pedem escala log para visualização.",
      difficulty: "avancado",
      setupCode: "class plt_mock:\n    @staticmethod\n    def plot(d): print('Plot')\n    @staticmethod\n    def yscale(s): print(f'YScale: {s}')\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Plot\nYScale: log\nExibido.",
      testCode: "assert 'yscale' in code and 'log' in code",
      starterCode: "plt.plot([1, 10, 100, 1000])\n# Ative escala log em Y\n",
      hints: [
        { text: "plt.yscale('log') muda o eixo Y para escala logarítmica. Análogo: plt.xscale('log').", cost: 25 },
        { text: "Útil quando dados cobrem várias ordens de grandeza (1 a 1000000) — em escala linear os pequenos somem.", cost: 30 },
        { text: "plt.yscale('log')\\nplt.show()", cost: 35 },
      ],
      xpReward: 700,
      concept: "Escala Logarítmica",
      conceptExplanation: "plt.yscale('log') (ou xscale) muda o eixo para escala logarítmica — cada divisão representa multiplicação por 10. Crucial quando dados variam por ordens de grandeza (1, 10, 100, 1000): em escala linear, valores pequenos somem; em log, todos ficam visíveis. Comum em: distribuições com cauda longa (renda, tamanhos de cidade), audição/decibéis, terremotos (Richter), tempo de algoritmos. CUIDADO: log de zero é -infinito; log de negativos é indefinido — filtre antes. Para escala 'sinal-log' (com negativos): 'symlog'.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Escala logarítmica revela toda a distribuição.",
      solution: "plt.plot([1, 10, 100, 1000])\nplt.yscale('log')\nplt.show()",
    },
    {
      id: "ds-viz-21",
      worldId: "sala-comando-visual",
      title: "Heatmap (Seaborn)",
      description: "Importe seaborn como sns. Use sns.heatmap(matriz) e exiba com plt.show().",
      narrative: "Visualize correlações entre 50 variáveis em um único quadro.",
      difficulty: "avancado",
      setupCode: "class sns_mock:\n    @staticmethod\n    def heatmap(m): print(f'Heatmap {len(m)}x{len(m[0])}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()\nmatriz = [[1, 0.8], [0.8, 1]]",
      expectedOutput: "Heatmap 2x2\nExibido.",
      testCode: "assert 'sns.heatmap' in code",
      starterCode: "import seaborn as sns\nimport matplotlib.pyplot as plt\n# Desenhe heatmap e exiba\n",
      hints: [
        { text: "import seaborn as sns (alias universal). Seaborn é construído SOBRE matplotlib — ainda usa plt.show().", cost: 20 },
        { text: "sns.heatmap(matriz) colore cada célula proporcionalmente. Aceita lista 2D, DataFrame ou array NumPy.", cost: 25 },
        { text: "sns.heatmap(matriz)\\nplt.show()", cost: 30 },
      ],
      xpReward: 800,
      concept: "Seaborn Heatmap",
      conceptExplanation: "Seaborn é a biblioteca de visualização estatística construída sobre matplotlib — gráficos sofisticados com menos código e estética moderna. Heatmap é o padrão para matrizes: correlação (df.corr()), matriz de confusão, dados tabulares 2D onde cor é intensidade. Parâmetros: annot=True (mostra números nas células), cmap='coolwarm' (paleta intuitiva: vermelho positivo, azul negativo), fmt='.2f' (formato dos números), vmin/vmax (limites de cor). Para correlações: sns.heatmap(df.corr(), annot=True, cmap='coolwarm').",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Correlações fortes identificadas.",
      solution: "import seaborn as sns\nimport matplotlib.pyplot as plt\nsns.heatmap(matriz)\nplt.show()",
    },
    {
      id: "ds-viz-22",
      worldId: "sala-comando-visual",
      title: "Seaborn Countplot",
      description: "Use sns.countplot(x=valores) onde valores=['A','B','A','C']. Exiba.",
      narrative: "Conte ocorrências de cada categoria automaticamente.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def countplot(x): print(f'Count: {x}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Count: ['A', 'B', 'A', 'C']\nExibido.",
      testCode: "assert 'countplot' in code",
      starterCode: "import seaborn as sns\nvalores = ['A', 'B', 'A', 'C']\n# countplot e show\n",
      hints: [
        { text: "sns.countplot(x=lista) conta automaticamente e desenha barras por categoria — sem precisar de value_counts antes.", cost: 20 },
        { text: "Para DataFrame: sns.countplot(data=df, x='coluna'). hue='outra_col' separa por subgrupo.", cost: 25 },
        { text: "sns.countplot(x=valores)\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Seaborn Countplot",
      conceptExplanation: "countplot é a maneira mais rápida de plotar contagem de uma variável categórica: sns.countplot(x=col) conta automaticamente — você não precisa fazer value_counts antes. Para DataFrame: data=df, x='coluna'. Adicione hue='outra_categoria' para separar por subgrupos, com barras coloridas lado a lado. Equivalente a bar plot de value_counts(), mas em uma linha. Use horizontal com y= em vez de x= quando muitas categorias.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição categórica plotada.",
      solution: "import seaborn as sns\nsns.countplot(x=['A', 'B', 'A', 'C'])\nplt.show()",
    },
    {
      id: "ds-viz-23",
      worldId: "sala-comando-visual",
      title: "Seaborn Barplot",
      description: "Com sns.barplot, plote x=['A','B','C'] e y=[10,20,15]. Exiba.",
      narrative: "Compare métricas agregadas por categoria com barras estatísticas.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def barplot(x, y): print(f'Bar: {x} -> {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Bar: ['A', 'B', 'C'] -> [10, 20, 15]\nExibido.",
      testCode: "assert 'barplot' in code",
      starterCode: "import seaborn as sns\nx = ['A', 'B', 'C']\ny = [10, 20, 15]\n# Use sns.barplot\n",
      hints: [
        { text: "sns.barplot(x=..., y=...) — passe duas listas (ou DataFrame com data=, x='col', y='col').", cost: 20 },
        { text: "Diferença vs plt.bar: barplot calcula MÉDIA automaticamente se houver múltiplos y para mesmo x, com intervalo de confiança.", cost: 25 },
        { text: "sns.barplot(x=x, y=y)\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Seaborn Barplot",
      conceptExplanation: "sns.barplot é diferente de plt.bar: quando há múltiplos y para o mesmo x (ex: várias amostras por categoria), barplot AGREGA automaticamente — calcula a média e adiciona barra de erro (intervalo de confiança 95%). Parâmetro estimator='mean' (padrão), 'sum', 'median' ou função custom. ci=None remove barras de erro. Use barplot para análise estatística rápida; plt.bar quando você já tem agregação calculada e só quer plotar.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Médias e intervalos plotados.",
      solution: "import seaborn as sns\nsns.barplot(x=['A','B','C'], y=[10,20,15])\nplt.show()",
    },
    {
      id: "ds-viz-24",
      worldId: "sala-comando-visual",
      title: "Seaborn Histplot",
      description: "Plote o histograma de dados=[1,2,2,3,4,4,5] usando sns.histplot. Exiba.",
      narrative: "Histograma moderno com mais controle estatístico que o do matplotlib.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def histplot(d): print(f'Hist: {d}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Hist: [1, 2, 2, 3, 4, 4, 5]\nExibido.",
      testCode: "assert 'histplot' in code",
      starterCode: "import seaborn as sns\n# Use sns.histplot\n",
      hints: [
        { text: "sns.histplot(dados) é o histograma moderno do seaborn — substitui distplot (deprecated).", cost: 20 },
        { text: "Parâmetros: bins=N, kde=True (adiciona curva de densidade suavizada), hue='col' separa por categoria.", cost: 25 },
        { text: "sns.histplot([1,2,2,3,4,4,5])\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Seaborn Histplot",
      conceptExplanation: "sns.histplot é a versão seaborn de histograma — mais elegante e flexível que plt.hist. Diferenciais: kde=True adiciona curva de densidade suavizada sobreposta (Kernel Density Estimation), hue='categoria' separa o histograma por subgrupos com cores, multiple='stack'/'dodge'/'fill' controla como sobrepor. Para densidade pura sem barras, use sns.kdeplot. Útil quando você quer comparar distribuições entre grupos visualmente.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição refinada.",
      solution: "import seaborn as sns\nsns.histplot([1, 2, 2, 3, 4, 4, 5])\nplt.show()",
    },
    {
      id: "ds-viz-25",
      worldId: "sala-comando-visual",
      title: "Seaborn Boxplot",
      description: "Plote boxplot de dados=[1,2,3,4,5,100] com sns.boxplot. Exiba.",
      narrative: "Boxplot do seaborn é o padrão em relatórios estatísticos modernos.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def boxplot(y): print(f'Box: {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Box: [1, 2, 3, 4, 5, 100]\nExibido.",
      testCode: "assert 'sns.boxplot' in code",
      starterCode: "import seaborn as sns\n# Use sns.boxplot(y=dados)\n",
      hints: [
        { text: "sns.boxplot(y=lista) cria boxplot vertical. Use x= para horizontal.", cost: 20 },
        { text: "Em DataFrame: sns.boxplot(data=df, x='categoria', y='valor') gera múltiplos boxplots lado a lado.", cost: 25 },
        { text: "sns.boxplot(y=[1,2,3,4,5,100])\\nplt.show()", cost: 30 },
      ],
      xpReward: 750,
      concept: "Seaborn Boxplot",
      conceptExplanation: "sns.boxplot é a versão seaborn — visualmente mais limpo que plt.boxplot e com integração nativa a DataFrames. Caixa representa quartis 25-75% (50% dos dados); linha central é mediana; whiskers estendem até 1.5*IQR; pontos fora são outliers. Use x= para categorias e y= para valor: sns.boxplot(data=df, x='setor', y='vendas') compara distribuição de vendas por setor. Adicione hue= para subgrupos. Para violino (mostra densidade junto), use sns.violinplot.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Distribuição quartilizada.",
      solution: "import seaborn as sns\nsns.boxplot(y=[1,2,3,4,5,100])\nplt.show()",
    },
    {
      id: "ds-viz-26",
      worldId: "sala-comando-visual",
      title: "Seaborn Violinplot",
      description: "Plote violino de dados=[1,2,3,4,5] com sns.violinplot. Exiba.",
      narrative: "Violino combina box e densidade em uma forma única.",
      difficulty: "avancado",
      setupCode: "class sns_mock:\n    @staticmethod\n    def violinplot(y): print(f'Violin: {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Violin: [1, 2, 3, 4, 5]\nExibido.",
      testCode: "assert 'violinplot' in code",
      starterCode: "import seaborn as sns\n# Use sns.violinplot(y=dados)\n",
      hints: [
        { text: "sns.violinplot(y=lista) plota o 'violino' — formato é a densidade espelhada, largura = frequência.", cost: 25 },
        { text: "Combina boxplot (quartis no centro) com KDE (curva de densidade nas bordas).", cost: 30 },
        { text: "sns.violinplot(y=[1,2,3,4,5])\\nplt.show()", cost: 35 },
      ],
      xpReward: 800,
      concept: "Seaborn Violinplot",
      conceptExplanation: "Violinplot combina o boxplot com a densidade KDE: a forma do violino mostra ONDE os dados se concentram (largura = frequência), enquanto a caixa interna mostra quartis. Mais informativo que boxplot puro quando a distribuição tem múltiplos picos ou cauda assimétrica — formatos que o boxplot esconde. Para distribuições com poucos pontos, prefira boxplot ou stripplot. Use split=True com hue= para comparar dois subgrupos no mesmo violino.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Densidade visualizada.",
      solution: "import seaborn as sns\nsns.violinplot(y=[1,2,3,4,5])\nplt.show()",
    },
    {
      id: "ds-viz-27",
      worldId: "sala-comando-visual",
      title: "Seaborn Lineplot",
      description: "Use sns.lineplot(x=[1,2,3], y=[1,4,9]) e exiba.",
      narrative: "Lineplot moderno com intervalos de confiança automáticos.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def lineplot(x, y): print(f'Line: {x} x {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Line: [1, 2, 3] x [1, 4, 9]\nExibido.",
      testCode: "assert 'lineplot' in code",
      starterCode: "import seaborn as sns\n# sns.lineplot e show\n",
      hints: [
        { text: "sns.lineplot(x=..., y=...) — assinatura igual a plt.plot mas com features estatísticos.", cost: 20 },
        { text: "Se houver múltiplos y para mesmo x, calcula média + intervalo de confiança automaticamente.", cost: 25 },
        { text: "sns.lineplot(x=[1,2,3], y=[1,4,9])\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Seaborn Lineplot",
      conceptExplanation: "sns.lineplot é o equivalente moderno do plt.plot, com vantagens estatísticas: agregação automática (média + IC quando há múltiplos y por x), suporte nativo a DataFrame (data=df, x='col', y='col', hue='categoria' para várias linhas). Use em séries temporais com múltiplas réplicas (várias execuções de um experimento) — ele já calcula a média e desenha o intervalo de confiança sombreado. Para uma só série, é equivalente ao plt.plot mas com estilo seaborn.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tendência traçada.",
      solution: "import seaborn as sns\nsns.lineplot(x=[1,2,3], y=[1,4,9])\nplt.show()",
    },
    {
      id: "ds-viz-28",
      worldId: "sala-comando-visual",
      title: "Seaborn Scatterplot",
      description: "Use sns.scatterplot(x=[1,2,3], y=[4,5,6]) e exiba.",
      narrative: "Scatter do seaborn aceita mais variáveis visuais.",
      difficulty: "intermediario",
      setupCode: "class sns_mock:\n    @staticmethod\n    def scatterplot(x, y): print(f'Scatter: {x} x {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Scatter: [1, 2, 3] x [4, 5, 6]\nExibido.",
      testCode: "assert 'scatterplot' in code",
      starterCode: "import seaborn as sns\n# sns.scatterplot e show\n",
      hints: [
        { text: "sns.scatterplot(x=..., y=...) — versão seaborn de scatter. Aceita hue, size e style para mapear variáveis em estética.", cost: 20 },
        { text: "Com DataFrame: sns.scatterplot(data=df, x='col1', y='col2', hue='categoria').", cost: 25 },
        { text: "sns.scatterplot(x=[1,2,3], y=[4,5,6])\\nplt.show()", cost: 30 },
      ],
      xpReward: 700,
      concept: "Seaborn Scatterplot",
      conceptExplanation: "sns.scatterplot melhora plt.scatter com mapeamentos estatísticos diretos: hue='col' (cor de cada ponto baseada em uma 3ª variável), size='col' (tamanho baseado em 4ª variável), style='col' (formato do marcador). Ideal quando você quer mostrar 4 dimensões em um único gráfico 2D. Trabalha nativamente com DataFrames e gera legendas automaticamente para cada mapeamento. Para análise exploratória entre variáveis com agrupamento, é o primeiro gráfico a tentar.",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pontos plotados com estética estatística.",
      solution: "import seaborn as sns\nsns.scatterplot(x=[1,2,3], y=[4,5,6])\nplt.show()",
    },
    {
      id: "ds-viz-29",
      worldId: "sala-comando-visual",
      title: "Pairplot",
      description: "Use sns.pairplot(df) para gerar a matriz de scatter plots entre colunas do DataFrame. Imprima 'Pairplot gerado.'.",
      narrative: "Em uma chamada, todas as relações entre variáveis. Ferramenta exploratória definitiva.",
      difficulty: "avancado",
      setupCode: "class sns_mock:\n    @staticmethod\n    def pairplot(df): pass\nsns = sns_mock()\ndf = {'a': [1,2,3], 'b': [4,5,6]}",
      expectedOutput: "Pairplot gerado.",
      testCode: "assert 'pairplot' in code",
      starterCode: "import seaborn as sns\n# Chame pairplot e imprima confirmação\n",
      hints: [
        { text: "sns.pairplot(df) gera UMA matriz: cada par de colunas vira um scatter, diagonal vira histograma.", cost: 30 },
        { text: "Para colorir por categoria: sns.pairplot(df, hue='col_categoria').", cost: 35 },
        { text: "sns.pairplot(df)\\nprint('Pairplot gerado.')", cost: 40 },
      ],
      xpReward: 900,
      concept: "Pairplot",
      conceptExplanation: "sns.pairplot(df) é uma das ferramentas mais poderosas de análise exploratória: gera uma matriz NxN onde cada célula é um gráfico relacionando duas colunas — fora da diagonal são scatter plots (pares de variáveis); na diagonal são histogramas/KDE (distribuição de cada variável). Em uma linha, você vê todas as correlações, distribuições e potenciais clusters. Com hue='categoria', cada cor representa uma classe — revela se as classes são separáveis. Para muitas colunas, fica grande — selecione um subset (df[['a','b','c']]).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Panorama completo de relações.",
      solution: "import seaborn as sns\nsns.pairplot(df)\nprint('Pairplot gerado.')",
    },
    {
      id: "ds-viz-30",
      worldId: "sala-comando-visual",
      title: "Regressão (regplot)",
      description: "Use sns.regplot(x=[1,2,3,4], y=[2,4,6,8]) — plota scatter + linha de regressão linear. Exiba.",
      narrative: "Visualize correlação E tendência linear em um único gráfico.",
      difficulty: "avancado",
      setupCode: "class sns_mock:\n    @staticmethod\n    def regplot(x, y): print(f'Reg: {x} x {y}')\nsns = sns_mock()\nclass plt_mock:\n    @staticmethod\n    def show(): print('Exibido.')\nplt = plt_mock()",
      expectedOutput: "Reg: [1, 2, 3, 4] x [2, 4, 6, 8]\nExibido.",
      testCode: "assert 'regplot' in code",
      starterCode: "import seaborn as sns\n# regplot e show\n",
      hints: [
        { text: "sns.regplot(x=..., y=...) plota scatter MAIS uma linha de regressão linear ajustada, com intervalo de confiança.", cost: 25 },
        { text: "Para regressão polinomial: order=2 (quadrática), 3 (cúbica). Para logística: logistic=True.", cost: 30 },
        { text: "sns.regplot(x=[1,2,3,4], y=[2,4,6,8])\\nplt.show()", cost: 35 },
      ],
      xpReward: 900,
      concept: "Regplot (Regressão Visual)",
      conceptExplanation: "sns.regplot combina scatter plot com regressão linear ajustada — mostra os pontos E a linha de tendência com intervalo de confiança sombreado. Útil para investigação visual rápida de relação linear entre duas variáveis. Parâmetros: order=N para polinomial (curvada), lowess=True para suavização não-paramétrica (sem assumir forma), ci=None remove intervalo de confiança, robust=True para regressão robusta a outliers. Para múltiplos grupos com regressões separadas, use sns.lmplot (versão de facetas do regplot).",
      successNpc: "Estrategista de Dados",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tendência ajustada visualmente.",
      solution: "import seaborn as sns\nsns.regplot(x=[1,2,3,4], y=[2,4,6,8])\nplt.show()",
    },
  ],
};
