import { World } from "../types";

export const SINTETIZADOR_LINGUAGEM_WORLD: World = {
  id: "sintetizador-linguagem",
  title: "Sintetizador de Linguagem",
  subtitle: "Processamento de Linguagem Natural",
  icon: "languages",
  color: "#818CF8",
  bgImage: "/assets/images/worlds/language_synth.png",
  lore: "Texto é o protocolo mais antigo da humanidade. Aqui você aprende a extrair sentido de strings: tokenização, embeddings, classificação e os Transformers que potencializam toda IA moderna.",
  unlockRequirement: 26000,
  challenges: [
    {
      id: "ds-nlp-01",
      worldId: "sintetizador-linguagem",
      title: "Tokenização Básica",
      description: "Divida a frase 'O sistema foi invadido' em tokens com .split() e imprima o resultado.",
      narrative: "Antes de processar texto, é preciso quebrá-lo em unidades elementares.",
      difficulty: "iniciante",
      setupCode: "frase = 'O sistema foi invadido'",
      expectedOutput: "['O', 'sistema', 'foi', 'invadido']",
      testCode: "assert '.split' in code",
      starterCode: "frase = 'O sistema foi invadido'\n# Tokenize com .split() e imprima\n",
      hints: [
        { text: "str.split() (sem argumento) divide a string por espaços em branco. Retorna lista.", cost: 10 },
        { text: "Apenas chame .split() na string e imprima o resultado.", cost: 20 },
        { text: "print(frase.split())", cost: 30 },
      ],
      xpReward: 500,
      concept: "Tokenização",
      conceptExplanation: "TOKENIZAÇÃO é o primeiro passo de qualquer pipeline NLP — divide texto em unidades discretas (tokens) que o modelo consegue processar. O split() do Python é o método mais simples: separa por espaços em branco. Mas é insuficiente para texto real: não lida com pontuação ('Oi!' vira ['Oi!'] em vez de ['Oi','!']), contrações ('don\\'t' vira ['don\\'t']) nem texto sem espaços (chinês, japonês). Bibliotecas profissionais: NLTK word_tokenize, spaCy, e tokenizers SUBWORD (BPE, WordPiece, SentencePiece) — usados em Transformers modernos. Subword é genial: separa palavras raras em pedaços conhecidos ('jogador' → 'jog' + 'ador').",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Texto fragmentado em unidades processáveis.",
      solution: "frase = 'O sistema foi invadido'\nprint(frase.split())",
    },
    {
      id: "ds-nlp-02",
      worldId: "sintetizador-linguagem",
      title: "NLTK Tokenize",
      description: "Use nltk.word_tokenize('Olá, mundo!') e imprima.",
      narrative: "Tokenizador profissional que separa pontuação corretamente.",
      difficulty: "iniciante",
      setupCode: "class nltk_mock:\n    @staticmethod\n    def word_tokenize(s): return ['Olá', ',', 'mundo', '!']\nnltk = nltk_mock()",
      expectedOutput: "['Olá', ',', 'mundo', '!']",
      testCode: "assert 'word_tokenize' in code",
      starterCode: "import nltk\n# nltk.word_tokenize\n",
      hints: [
        { text: "nltk.word_tokenize separa palavras E pontuação em tokens distintos.", cost: 15 },
        { text: "Diferente do split, captura 'Olá' e ',' como tokens separados.", cost: 20 },
        { text: "print(nltk.word_tokenize('Olá, mundo!'))", cost: 30 },
      ],
      xpReward: 550,
      concept: "NLTK Tokenizer",
      conceptExplanation: "NLTK (Natural Language Toolkit) é a biblioteca clássica de NLP em Python — vasta cobertura: tokenização, POS tagging, parsing, classificadores, corpora. word_tokenize é mais robusto que split: lida com pontuação, contrações ('don\\'t' → ['do', \"n't\"]), abreviações. Para iniciar: nltk.download('punkt') uma vez. Alternativas modernas: spaCy (mais rápido, focado em produção) e tokenizers da Hugging Face (BPE, WordPiece — necessário para modelos Transformer). NLTK ainda é referência acadêmica e excelente para experimentação.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Tokens semânticos extraídos.",
      solution: "import nltk\nprint(nltk.word_tokenize('Olá, mundo!'))",
    },
    {
      id: "ds-nlp-03",
      worldId: "sintetizador-linguagem",
      title: "Stopwords",
      description: "Filtre tokens removendo stopwords. Imprima ['sistema', 'invadido'] após remover 'o', 'foi'.",
      narrative: "Palavras vazias adicionam ruído sem significado.",
      difficulty: "intermediario",
      setupCode: "tokens = ['o', 'sistema', 'foi', 'invadido']\nstopwords = {'o', 'foi', 'a', 'de'}",
      expectedOutput: "['sistema', 'invadido']",
      testCode: "assert 'stopwords' in code",
      starterCode: "tokens = ['o', 'sistema', 'foi', 'invadido']\nstopwords = {'o', 'foi', 'a', 'de'}\n# Filtre tokens não-stopword\n",
      hints: [
        { text: "Use list comprehension: [t for t in tokens if t not in stopwords].", cost: 20 },
        { text: "Stopwords em set (não lista) tem busca O(1) — muito mais rápido em vocabulário grande.", cost: 25 },
        { text: "print([t for t in tokens if t not in stopwords])", cost: 30 },
      ],
      xpReward: 650,
      concept: "Remoção de Stopwords",
      conceptExplanation: "STOPWORDS são palavras MUITO frequentes mas SEMANTICAMENTE FRACAS — artigos (o, a, the), preposições (de, em, of), pronomes (eu, ele). Em modelos clássicos (TF-IDF, BoW, LDA), removê-las melhora performance e reduz dimensionalidade. NLTK oferece listas prontas: from nltk.corpus import stopwords; stopwords.words('portuguese'). ATENÇÃO: em modelos Transformer modernos (BERT, GPT), NÃO remova stopwords — o modelo aprende a importância contextualmente, e 'não' (stopword em algumas listas!) inverte sentido. Sempre considere o domínio: 'não' em análise de sentimento é crítico.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Ruído lexical removido.",
      solution: "tokens = ['o', 'sistema', 'foi', 'invadido']\nstopwords = {'o', 'foi', 'a', 'de'}\nprint([t for t in tokens if t not in stopwords])",
    },
    {
      id: "ds-nlp-04",
      worldId: "sintetizador-linguagem",
      title: "Normalização",
      description: "Converta 'SISTEMA INVADIDO' para minúsculas com .lower() e imprima.",
      narrative: "Antes de qualquer comparação, normalize maiúsculas e minúsculas.",
      difficulty: "iniciante",
      setupCode: "texto = 'SISTEMA INVADIDO'",
      expectedOutput: "sistema invadido",
      testCode: "assert '.lower' in code",
      starterCode: "texto = 'SISTEMA INVADIDO'\n# Imprima em minúsculas\n",
      hints: [
        { text: "str.lower() retorna uma cópia em minúsculas. Não modifica o original (strings são imutáveis).", cost: 10 },
        { text: "Aplique direto no print.", cost: 20 },
        { text: "print(texto.lower())", cost: 30 },
      ],
      xpReward: 400,
      concept: "Normalização (Case Folding)",
      conceptExplanation: "Normalização de caso (case folding) é o passo onde 'SISTEMA' e 'sistema' são tratados como mesma palavra — fundamental para qualquer modelo que não distingue. Métodos: .lower() (mais simples e usado), .casefold() (mais agressivo, lida com casos especiais como 'ß' alemão → 'ss'). Outras normalizações importantes: REMOVER ACENTOS (unicodedata.normalize), REMOVER PONTUAÇÃO (string.punctuation, regex), EXPANDIR CONTRAÇÕES, CORRIGIR ORTOGRAFIA. Em Transformers, tokenizers fazem case folding internamente — você passa texto cru e ele resolve.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Texto padronizado.",
      solution: "texto = 'SISTEMA INVADIDO'\nprint(texto.lower())",
    },
    {
      id: "ds-nlp-05",
      worldId: "sintetizador-linguagem",
      title: "Stemming",
      description: "Use stemmer.stem('correndo') e imprima.",
      narrative: "Reduza palavras à raiz removendo sufixos.",
      difficulty: "intermediario",
      setupCode: "class Stemmer:\n    def stem(self, w): return 'corr'\nstemmer = Stemmer()",
      expectedOutput: "corr",
      testCode: "assert 'stem' in code",
      starterCode: "# Imprima stemmer.stem('correndo')\n",
      hints: [
        { text: "stemmer.stem(palavra) corta sufixos mecanicamente.", cost: 20 },
        { text: "NLTK: from nltk.stem import RSLPStemmer (português) ou PorterStemmer (inglês).", cost: 25 },
        { text: "print(stemmer.stem('correndo'))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Stemming",
      conceptExplanation: "STEMMING reduz palavras à RAIZ removendo sufixos mecanicamente — 'correndo', 'correu', 'correrá' viram 'corr'. Vantagem: aglutina formas variantes da mesma palavra (importante para TF-IDF e busca textual). Desvantagem: ALGORITMO MECÂNICO — pode gerar raízes que NÃO são palavras válidas ('univers' de 'universidade'). Stemmers populares: Porter (inglês, clássico), Snowball (multilíngue, melhorado), RSLP (português, Removedor de Sufixos da Língua Portuguesa). Para resultados mais precisos linguisticamente, use LEMATIZAÇÃO em vez de stemming.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Raiz extraída.",
      solution: "print(stemmer.stem('correndo'))",
    },
    {
      id: "ds-nlp-06",
      worldId: "sintetizador-linguagem",
      title: "Lematização",
      description: "Use lemmatizer.lemmatize('running', 'v') e imprima.",
      narrative: "Reduza palavras à forma do dicionário considerando contexto.",
      difficulty: "intermediario",
      setupCode: "class Lemma:\n    def lemmatize(self, w, pos): return 'run'\nlemmatizer = Lemma()",
      expectedOutput: "run",
      testCode: "assert 'lemmatize' in code",
      starterCode: "# Imprima lemmatizer.lemmatize('running', 'v')\n",
      hints: [
        { text: "lemmatize(palavra, pos) — pos é POS tag: 'v' verbo, 'n' substantivo, 'a' adjetivo.", cost: 20 },
        { text: "Diferente de stemming, retorna forma DICIONÁRIO real (lemma).", cost: 25 },
        { text: "print(lemmatizer.lemmatize('running', 'v'))", cost: 30 },
      ],
      xpReward: 750,
      concept: "Lematização",
      conceptExplanation: "LEMATIZAÇÃO é o irmão SOFISTICADO do stemming: reduz palavras à forma do DICIONÁRIO (lemma) considerando contexto morfológico. 'running' → 'run', 'better' → 'good', 'mice' → 'mouse'. Diferenças vs stemming: (1) lemma sempre é palavra válida; (2) requer POS tag (qual classe gramatical?); (3) mais lento mas mais preciso. NLTK: WordNetLemmatizer; spaCy faz lemmatização automaticamente em token.lemma_. Para português, spaCy + modelo pt_core_news é o caminho. Em geral, lemmatização > stemming quando precisão linguística importa; stemming é mais rápido e suficiente em buscas/clustering.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Forma canônica obtida.",
      solution: "print(lemmatizer.lemmatize('running', 'v'))",
    },
    {
      id: "ds-nlp-07",
      worldId: "sintetizador-linguagem",
      title: "N-grams (Bigrams)",
      description: "Gere bigrams de ['o','sistema','foi','invadido']. Imprima [('o','sistema'), ('sistema','foi'), ('foi','invadido')].",
      narrative: "Capture pares de palavras adjacentes para preservar contexto local.",
      difficulty: "intermediario",
      setupCode: "tokens = ['o', 'sistema', 'foi', 'invadido']",
      expectedOutput: "[('o', 'sistema'), ('sistema', 'foi'), ('foi', 'invadido')]",
      testCode: "assert 'zip' in code or 'bigrams' in code or 'ngrams' in code",
      starterCode: "tokens = ['o', 'sistema', 'foi', 'invadido']\n# Gere bigrams com zip(tokens, tokens[1:])\n",
      hints: [
        { text: "Bigrams = pares consecutivos. zip(tokens, tokens[1:]) gera os pares automaticamente.", cost: 25 },
        { text: "Converta o iterador em lista para imprimir: list(zip(...)).", cost: 30 },
        { text: "print(list(zip(tokens, tokens[1:])))", cost: 35 },
      ],
      xpReward: 800,
      concept: "N-grams",
      conceptExplanation: "N-GRAMS são sequências de N tokens consecutivos. UNIGRAM = 1 token, BIGRAM = 2 tokens, TRIGRAM = 3. Capturam CONTEXTO LOCAL que bag-of-words puro perde: 'não bom' em bigram preserva o sentido oposto que unigram destrói. Em TF-IDF: CountVectorizer(ngram_range=(1,2)) inclui unigrams e bigrams. Trade-off: N maior captura mais contexto mas explode dimensionalidade (vocab^N). Em modelos de linguagem clássicos (antes de Transformers), n-grams eram a base — N-gram language models calculavam P(palavra | n-1 palavras anteriores). Modelos modernos aprendem dependências de qualquer distância via atenção.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Contexto local preservado.",
      solution: "tokens = ['o', 'sistema', 'foi', 'invadido']\nprint(list(zip(tokens, tokens[1:])))",
    },
    {
      id: "ds-nlp-08",
      worldId: "sintetizador-linguagem",
      title: "Bag of Words",
      description: "Use CountVectorizer().fit_transform(corpus) e imprima 'BoW gerado.'.",
      narrative: "Representação clássica: cada documento vira vetor de contagens.",
      difficulty: "intermediario",
      setupCode: "class CountVectorizer:\n    def fit_transform(self, c): print('BoW gerado.'); return None\ncorpus = ['o sistema falhou', 'sistema seguro']",
      expectedOutput: "BoW gerado.",
      testCode: "assert 'CountVectorizer' in code",
      starterCode: "from sklearn.feature_extraction.text import CountVectorizer\n# fit_transform no corpus\n",
      hints: [
        { text: "CountVectorizer cria vocabulário automaticamente do corpus e gera matriz de contagens.", cost: 25 },
        { text: "fit_transform recebe lista de strings e retorna matriz esparsa (documentos x vocabulário).", cost: 30 },
        { text: "cv = CountVectorizer()\\ncv.fit_transform(corpus)", cost: 35 },
      ],
      xpReward: 850,
      concept: "Bag of Words",
      conceptExplanation: "BAG OF WORDS (BoW) é a representação mais simples de texto: cada documento vira VETOR de contagens de palavras do vocabulário global. 'A casa azul' vs 'azul casa A' → mesma representação (BoW IGNORA ordem). CountVectorizer do sklearn faz tudo: extrai vocabulário, tokeniza, conta. Parâmetros úteis: ngram_range (incluir bigrams), min_df (palavras em menos de N docs são ignoradas), max_df (palavras em mais de % docs são ignoradas — pega stopwords automaticamente), stop_words='english'. Vantagem: simples, interpretável, funciona bem em classificação básica. Desvantagem: perde ordem, sinônimos, contexto — para isso, vá para TF-IDF, embeddings ou Transformers.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Documentos vetorizados.",
      solution: "from sklearn.feature_extraction.text import CountVectorizer\ncv = CountVectorizer()\ncv.fit_transform(corpus)",
    },
    {
      id: "ds-nlp-09",
      worldId: "sintetizador-linguagem",
      title: "TF-IDF",
      description: "Use TfidfVectorizer().fit_transform(corpus) e imprima 'TF-IDF gerado.'.",
      narrative: "Pondere palavras pela importância — frequentes em um doc, raras no corpus geral.",
      difficulty: "avancado",
      setupCode: "class TfidfVectorizer:\n    def fit_transform(self, c): print('TF-IDF gerado.'); return None\ncorpus = ['sistema falhou', 'sistema seguro']",
      expectedOutput: "TF-IDF gerado.",
      testCode: "assert 'TfidfVectorizer' in code",
      starterCode: "from sklearn.feature_extraction.text import TfidfVectorizer\n# fit_transform no corpus\n",
      hints: [
        { text: "TfidfVectorizer combina TF (Term Frequency) com IDF (Inverse Document Frequency).", cost: 30 },
        { text: "Mesma interface do CountVectorizer — mesmos parâmetros, resultado diferente (pesos em vez de contagens).", cost: 35 },
        { text: "tv = TfidfVectorizer()\\ntv.fit_transform(corpus)", cost: 40 },
      ],
      xpReward: 950,
      concept: "TF-IDF",
      conceptExplanation: "TF-IDF (Term Frequency × Inverse Document Frequency) pondera palavras pela importância — frequente NO DOCUMENTO mas RARA no corpus geral pesa mais. TF = freq da palavra no doc; IDF = log(N_docs / docs_que_contém_a_palavra). 'sistema' aparece em quase todos os docs → IDF baixo → peso baixo (palavra comum). 'criptografia' aparece em poucos → IDF alto → peso alto (palavra discriminativa). Vantagem sobre BoW: penaliza palavras frequentes automaticamente (efeito similar a stopwords, mas baseado no próprio corpus). Base de motores de busca clássicos (Lucene/ElasticSearch) e classificação de texto pré-Transformers. Para similaridade entre docs: cosine_similarity nas vetores TF-IDF.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Importância semântica quantificada.",
      solution: "from sklearn.feature_extraction.text import TfidfVectorizer\ntv = TfidfVectorizer()\ntv.fit_transform(corpus)",
    },
    {
      id: "ds-nlp-10",
      worldId: "sintetizador-linguagem",
      title: "Cosine Similarity",
      description: "Use cosine_similarity(v1, v2) e imprima 'Similaridade calculada.'.",
      narrative: "Quão parecidos são dois vetores de texto?",
      difficulty: "avancado",
      setupCode: "def cosine_similarity(a, b): print('Similaridade calculada.'); return [[0.85]]\nv1 = [[1, 0, 1]]\nv2 = [[1, 1, 0]]",
      expectedOutput: "Similaridade calculada.",
      testCode: "assert 'cosine_similarity' in code",
      starterCode: "from sklearn.metrics.pairwise import cosine_similarity\nv1 = [[1, 0, 1]]\nv2 = [[1, 1, 0]]\n# Calcule similaridade\n",
      hints: [
        { text: "cosine_similarity(v1, v2) calcula o cosseno do ângulo entre vetores — varia de -1 a 1.", cost: 25 },
        { text: "Vetores devem ser 2D (lista de listas). Retorna matriz com as similaridades.", cost: 30 },
        { text: "cosine_similarity(v1, v2)", cost: 35 },
      ],
      xpReward: 900,
      concept: "Similaridade de Cossenos",
      conceptExplanation: "COSINE SIMILARITY mede o COSSENO DO ÂNGULO entre dois vetores — independente do tamanho, só importa a DIREÇÃO. Varia: 1 (mesma direção = idênticos), 0 (perpendiculares = sem relação), -1 (opostos). Por que cosseno em vez de distância euclidiana? Textos longos têm vetores maiores; o cosseno NORMALIZA essa diferença focando em direção semântica. Aplicações: motor de busca (relevância documento-query), sistemas de recomendação (similaridade entre itens), clustering, detecção de plágio. Em vector search moderno (FAISS, Pinecone), cosseno e produto interno são as métricas dominantes.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Proximidade semântica medida.",
      solution: "from sklearn.metrics.pairwise import cosine_similarity\ncosine_similarity([[1,0,1]], [[1,1,0]])",
    },
    {
      id: "ds-nlp-11",
      worldId: "sintetizador-linguagem",
      title: "Regex em Texto",
      description: "Use re.findall(r'\\d+', 'IP 192.168.1.5') e imprima.",
      narrative: "Regex extrai padrões estruturados (números, emails, URLs).",
      difficulty: "intermediario",
      setupCode: "import re",
      expectedOutput: "['192', '168', '1', '5']",
      testCode: "assert 're.findall' in code",
      starterCode: "import re\n# Encontre todos os números\n",
      hints: [
        { text: "re.findall(padrão, texto) retorna LISTA de todas as ocorrências.", cost: 20 },
        { text: "\\d+ = um ou mais dígitos. Outros: \\w (palavra), \\s (espaço), . (qualquer).", cost: 25 },
        { text: "print(re.findall(r'\\d+', 'IP 192.168.1.5'))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Regex em NLP",
      conceptExplanation: "REGEX (Regular Expressions) é a ferramenta fundamental para pré-processamento textual. Casos comuns: extrair emails (r'[\\w.-]+@[\\w.-]+'), URLs (r'https?://\\S+'), telefones, datas, hashtags, menções. Funções principais do módulo re: findall (todas), search (primeira), match (do início), sub (substituir). Em pipelines NLP: limpar texto (remover tags HTML, URLs, números), normalizar (substituir múltiplos espaços por um), extrair entidades estruturadas. Para casos complexos, use named groups: (?P<email>[\\w.-]+@[\\w.-]+). Para texto MUITO complexo, prefira spaCy/Transformers — regex é frágil em linguagem natural.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Padrões extraídos.",
      solution: "import re\nprint(re.findall(r'\\d+', 'IP 192.168.1.5'))",
    },
    {
      id: "ds-nlp-12",
      worldId: "sintetizador-linguagem",
      title: "Limpar HTML",
      description: "Use re.sub(r'<[^>]+>', '', '<p>Olá</p>') para remover tags. Imprima.",
      narrative: "Texto raspado da web vem cheio de tags HTML.",
      difficulty: "intermediario",
      setupCode: "import re",
      expectedOutput: "Olá",
      testCode: "assert 're.sub' in code",
      starterCode: "import re\n# Remova as tags HTML\n",
      hints: [
        { text: "re.sub(padrão, substituto, texto) substitui ocorrências.", cost: 20 },
        { text: "<[^>]+> casa qualquer tag (< seguido de qualquer coisa exceto >, terminado em >).", cost: 25 },
        { text: "print(re.sub(r'<[^>]+>', '', '<p>Olá</p>'))", cost: 30 },
      ],
      xpReward: 700,
      concept: "Limpeza de Texto",
      conceptExplanation: "Limpeza de texto é a fase mais ingrata e crítica de NLP — texto real vem com HTML, JavaScript, emojis, caracteres invisíveis, encoding errado. Pipeline típico: (1) Remover HTML — BeautifulSoup('html.parser') é mais robusto que regex; (2) Remover URLs/emails (regex); (3) Normalizar Unicode (unicodedata.normalize('NFKD', texto)); (4) Remover/preservar emojis (biblioteca 'emoji'); (5) Lowercase; (6) Remover pontuação se for caso; (7) Trim espaços múltiplos (re.sub(r'\\s+', ' ', texto)). NUNCA use regex para HTML em produção — use lxml/BeautifulSoup. Resultado limpo determina qualidade do modelo a jusante.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Texto saneado.",
      solution: "import re\nprint(re.sub(r'<[^>]+>', '', '<p>Olá</p>'))",
    },
    {
      id: "ds-nlp-13",
      worldId: "sintetizador-linguagem",
      title: "POS Tagging",
      description: "Imprima 'POS: noun, verb, adj — classe gramatical de cada palavra.'.",
      narrative: "Identifique substantivos, verbos, adjetivos — base de muito pipeline NLP.",
      difficulty: "intermediario",
      setupCode: "",
      expectedOutput: "POS: noun, verb, adj — classe gramatical de cada palavra.",
      testCode: "assert 'POS' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('POS: noun, verb, adj — classe gramatical de cada palavra.')", cost: 25 },
        { text: "print('POS: noun, verb, adj — classe gramatical de cada palavra.')", cost: 30 },
      ],
      xpReward: 800,
      concept: "POS Tagging",
      conceptExplanation: "POS TAGGING (Part-of-Speech) atribui CLASSE GRAMATICAL a cada token: NOUN (substantivo), VERB (verbo), ADJ (adjetivo), DET (determinante), ADV (advérbio), etc. Útil para: (1) parsing sintático; (2) NER (substantivos próprios viram pistas para entidades); (3) lematização (lemma depende de POS); (4) extração de keywords (substantivos e adjetivos são mais informativos). Padrão atual: Universal POS Tags (17 categorias). Bibliotecas: NLTK pos_tag, spaCy (token.pos_ e token.tag_), Flair. spaCy é geralmente o melhor balanço entre precisão e velocidade para produção. Para português, pt_core_news_sm.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Estrutura gramatical mapeada.",
      solution: "print('POS: noun, verb, adj — classe gramatical de cada palavra.')",
    },
    {
      id: "ds-nlp-14",
      worldId: "sintetizador-linguagem",
      title: "NER",
      description: "Imprima 'NER: extrai pessoas, lugares, organizações de texto livre.'.",
      narrative: "Named Entity Recognition transforma texto livre em dados estruturados.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "NER: extrai pessoas, lugares, organizações de texto livre.",
      testCode: "assert 'NER' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('NER: extrai pessoas, lugares, organizações de texto livre.')", cost: 25 },
        { text: "print('NER: extrai pessoas, lugares, organizações de texto livre.')", cost: 30 },
      ],
      xpReward: 900,
      concept: "Named Entity Recognition",
      conceptExplanation: "NER (Named Entity Recognition) extrai ENTIDADES NOMEADAS de texto: PERSON ('Neo'), GPE/LOC (Geo-Political Entity: 'Brasil'), ORG ('Anthropic'), DATE ('2026-05-13'), MONEY ('R$ 1000'), PRODUCT. Transforma texto livre em DADOS ESTRUTURADOS — útil para: análise de notícias, extração de informação de contratos, automação de CRM, análise de currículos. spaCy: doc = nlp(texto); for ent in doc.ents: print(ent.text, ent.label_). Para português: spacy.load('pt_core_news_lg'). Modelos Transformer (BERT NER) atingem performance ainda maior — Hugging Face tem dezenas prontos.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Entidades isoladas.",
      solution: "print('NER: extrai pessoas, lugares, organizações de texto livre.')",
    },
    {
      id: "ds-nlp-15",
      worldId: "sintetizador-linguagem",
      title: "spaCy Doc",
      description: "Crie doc = nlp('Sistema invadido em São Paulo') e imprima 'Doc processado.'.",
      narrative: "spaCy faz tokenização, POS, NER e parsing em uma única chamada.",
      difficulty: "intermediario",
      setupCode: "def nlp(s): print('Doc processado.'); return None",
      expectedOutput: "Doc processado.",
      testCode: "assert 'nlp(' in code",
      starterCode: "import spacy\nnlp = spacy.load('pt_core_news_sm')\n# Processe o texto e confirme\n",
      hints: [
        { text: "Carregue o modelo: nlp = spacy.load('pt_core_news_sm'). Depois: doc = nlp(texto).", cost: 25 },
        { text: "O doc resultante tem tokens, entidades, POS tags — tudo de uma vez.", cost: 30 },
        { text: "doc = nlp('Sistema invadido em São Paulo')", cost: 35 },
      ],
      xpReward: 900,
      concept: "spaCy Pipeline",
      conceptExplanation: "spaCy é a biblioteca NLP MAIS USADA EM PRODUÇÃO — mais rápida que NLTK, otimizada em Cython, com modelos pré-treinados para dezenas de idiomas. Pipeline padrão: tokenização → POS tagging → lemmatização → parsing sintático → NER, tudo em UMA passagem. Modelo é selecionado com spacy.load(). Para português: 'pt_core_news_sm' (pequeno, rápido) ou 'pt_core_news_lg' (preciso, com word vectors). Acesso ao resultado: doc[0] (primeiro token), doc[0].lemma_, doc[0].pos_, doc.ents (entidades), doc.sents (sentenças). Para customização: adicionar regras (Matcher, PhraseMatcher), treinar componente próprio.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Pipeline NLP em uma chamada.",
      solution: "import spacy\nnlp = spacy.load('pt_core_news_sm')\ndoc = nlp('Sistema invadido em São Paulo')",
    },
    {
      id: "ds-nlp-16",
      worldId: "sintetizador-linguagem",
      title: "Iterar Entidades spaCy",
      description: "Para cada entidade em doc.ents, imprima ent.text. Aqui imprima 'São Paulo'.",
      narrative: "Acesse as entidades reconhecidas pelo modelo.",
      difficulty: "intermediario",
      setupCode: "class Ent:\n    text = 'São Paulo'\nclass Doc:\n    ents = [Ent()]\ndoc = Doc()",
      expectedOutput: "São Paulo",
      testCode: "assert 'doc.ents' in code or '.ents' in code",
      starterCode: "# for ent in doc.ents: print(ent.text)\n",
      hints: [
        { text: "doc.ents retorna iterador de entidades. Cada entidade tem .text e .label_.", cost: 25 },
        { text: "Use um loop for simples.", cost: 30 },
        { text: "for ent in doc.ents:\\n    print(ent.text)", cost: 35 },
      ],
      xpReward: 850,
      concept: "Acessando Entidades",
      conceptExplanation: "Para extrair entidades de um doc spaCy: doc.ents itera sobre todas. Cada entidade tem atributos: .text (string original), .label_ (tipo: PERSON, LOC, ORG, MISC...), .start/.end (índices), .start_char/.end_char (posições em caracteres). Filtre por tipo: [ent for ent in doc.ents if ent.label_ == 'PER']. Para visualização gráfica de entidades coloridas, use displacy.render(doc, style='ent') — incrível em Jupyter. Em produção, exporte para JSON estruturado. Para entidades CUSTOMIZADAS (não cobertas pelo modelo padrão), treine com EntityRuler ou retreine o componente NER com seus dados anotados.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Entidades enumeradas.",
      solution: "for ent in doc.ents:\n    print(ent.text)",
    },
    {
      id: "ds-nlp-17",
      worldId: "sintetizador-linguagem",
      title: "Word2Vec",
      description: "Imprima 'Word2Vec: palavras viram vetores densos onde similar = próximo.'.",
      narrative: "Embeddings transformam palavras em geometria — o salto que mudou NLP.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Word2Vec: palavras viram vetores densos onde similar = próximo.",
      testCode: "assert 'Word2Vec' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('Word2Vec: palavras viram vetores densos onde similar = próximo.')", cost: 25 },
        { text: "print('Word2Vec: palavras viram vetores densos onde similar = próximo.')", cost: 30 },
      ],
      xpReward: 1000,
      concept: "Word Embeddings",
      conceptExplanation: "WORD EMBEDDINGS revolucionaram NLP (2013) — Word2Vec do Mikolov mostrou que treinando uma rede para PREVER palavras vizinhas, os vetores resultantes capturam SEMÂNTICA: 'rei' - 'homem' + 'mulher' ≈ 'rainha'. Palavras semanticamente próximas ficam GEOMETRICAMENTE próximas no espaço (300 dimensões típicas). Algoritmos clássicos: Word2Vec (Skip-gram, CBOW), GloVe (matriz de coocorrência), FastText (subword — funciona com palavras OOV). Em Python: gensim. PROBLEMA: embeddings ESTÁTICOS — 'banco' em 'banco financeiro' e 'banco da praça' têm o mesmo vetor. Resolvido por embeddings CONTEXTUAIS (ELMo, BERT) onde o vetor depende do contexto.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Semântica como geometria.",
      solution: "print('Word2Vec: palavras viram vetores densos onde similar = próximo.')",
    },
    {
      id: "ds-nlp-18",
      worldId: "sintetizador-linguagem",
      title: "Embeddings Gensim",
      description: "Use model.wv['rei'] (mock) e imprima 'Vetor obtido.'.",
      narrative: "Acesse o vetor numérico de uma palavra do modelo treinado.",
      difficulty: "avancado",
      setupCode: "class WV:\n    def __getitem__(self, k): print('Vetor obtido.'); return [0.1, 0.2]\nclass Model:\n    wv = WV()\nmodel = Model()",
      expectedOutput: "Vetor obtido.",
      testCode: "assert 'model.wv' in code",
      starterCode: "# Acesse model.wv['rei']\n",
      hints: [
        { text: "model.wv é o KeyedVectors. Indexar por palavra retorna o vetor.", cost: 25 },
        { text: "model.wv['rei'] retorna array NumPy com a dimensionalidade do embedding.", cost: 30 },
        { text: "model.wv['rei']", cost: 35 },
      ],
      xpReward: 1000,
      concept: "Gensim e KeyedVectors",
      conceptExplanation: "Gensim é a biblioteca padrão para word embeddings em Python. Carregue modelos pré-treinados: from gensim.models import KeyedVectors; wv = KeyedVectors.load_word2vec_format('arquivo.bin', binary=True). Ou treine do zero: Word2Vec(sentences, vector_size=100, window=5, min_count=1). Operações úteis: wv['rei'] (vetor), wv.most_similar('rei') (palavras similares), wv.most_similar(positive=['rei','mulher'], negative=['homem']) (analogia clássica), wv.similarity('rei','rainha') (cosseno). Para português, há embeddings pré-treinados (NILC, Wikipedia). Em pipelines modernos, embeddings de Transformers (BERT, sentence-transformers) tendem a superar Word2Vec.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Palavra vetorizada.",
      solution: "model.wv['rei']",
    },
    {
      id: "ds-nlp-19",
      worldId: "sintetizador-linguagem",
      title: "Palavras Similares",
      description: "Use model.wv.most_similar('rei', topn=3) e imprima 'Similares calculadas.'.",
      narrative: "Encontre as palavras mais próximas no espaço semântico.",
      difficulty: "avancado",
      setupCode: "class WV:\n    def most_similar(self, w, topn=10): print('Similares calculadas.'); return []\nclass Model:\n    wv = WV()\nmodel = Model()",
      expectedOutput: "Similares calculadas.",
      testCode: "assert 'most_similar' in code",
      starterCode: "# model.wv.most_similar('rei', topn=3)\n",
      hints: [
        { text: "most_similar retorna lista de (palavra, similaridade), ordenada decrescentemente.", cost: 25 },
        { text: "topn limita quantos resultados retornar.", cost: 30 },
        { text: "model.wv.most_similar('rei', topn=3)", cost: 35 },
      ],
      xpReward: 950,
      concept: "Busca Semântica em Embeddings",
      conceptExplanation: "most_similar usa cosseno entre vetores para encontrar palavras mais semanticamente próximas. Aplicações: (1) busca de sinônimos automatizada; (2) recomendação de termos; (3) descoberta exploratória de relações; (4) análise de viés (vetores de profissões aprendem viés de gênero do corpus de treino — problema ético importante). Truque clássico: ANALOGIA via aritmética vetorial — most_similar(positive=['paris','italia'], negative=['frança']) → 'roma'. Funciona porque a relação capital-país é codificada como direção no espaço vetorial. Mesma técnica em modelos Transformers, mas pelos pooled embeddings.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Vizinhos semânticos descobertos.",
      solution: "model.wv.most_similar('rei', topn=3)",
    },
    {
      id: "ds-nlp-20",
      worldId: "sintetizador-linguagem",
      title: "Sentiment Analysis",
      description: "Use sentiment(texto) e imprima o resultado (mock retorna 'positivo').",
      narrative: "Texto livre vira polaridade emocional — base de análise de mídia.",
      difficulty: "intermediario",
      setupCode: "def sentiment(t): return 'positivo'",
      expectedOutput: "positivo",
      testCode: "assert 'sentiment' in code",
      starterCode: "# Imprima o resultado de sentiment('Adorei o produto!')\n",
      hints: [
        { text: "Apenas chame a função e imprima.", cost: 20 },
        { text: "print(sentiment('Adorei o produto!'))", cost: 25 },
        { text: "print(sentiment('Adorei o produto!'))", cost: 30 },
      ],
      xpReward: 800,
      concept: "Análise de Sentimento",
      conceptExplanation: "ANÁLISE DE SENTIMENTO classifica texto em positivo/negativo/neutro (ou múltiplas emoções: raiva, alegria, tristeza, surpresa). Aplicações: monitoramento de marca, análise de avaliações de produtos, voice of customer, política. Métodos: (1) Léxicos (VADER, AFINN) — somam scores de palavras, rápido mas frágil em sarcasmo; (2) Classificadores clássicos (Naive Bayes, SVM) sobre TF-IDF — boa baseline; (3) Transformers fine-tuned (BERT, RoBERTa) — estado da arte. Hugging Face pipeline('sentiment-analysis') é a forma mais rápida — modelo zero-config. Para português: 'neuralmind/bert-base-portuguese-cased' fine-tuned em datasets brasileiros.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Emoção decodificada.",
      solution: "print(sentiment('Adorei o produto!'))",
    },
    {
      id: "ds-nlp-21",
      worldId: "sintetizador-linguagem",
      title: "Hugging Face Pipeline",
      description: "Crie classifier = pipeline('sentiment-analysis') e imprima 'Pipeline criado.'.",
      narrative: "Hugging Face: o GitHub dos modelos NLP. Use modelos prontos em uma linha.",
      difficulty: "avancado",
      setupCode: "def pipeline(task): print('Pipeline criado.'); return None",
      expectedOutput: "Pipeline criado.",
      testCode: "assert 'pipeline' in code",
      starterCode: "from transformers import pipeline\n# Crie pipeline('sentiment-analysis')\n",
      hints: [
        { text: "pipeline(task) baixa o modelo padrão para a tarefa automaticamente.", cost: 30 },
        { text: "Tasks disponíveis: 'sentiment-analysis', 'translation', 'summarization', 'ner', 'qa', e dezenas mais.", cost: 35 },
        { text: "classifier = pipeline('sentiment-analysis')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Hugging Face Transformers",
      conceptExplanation: "Hugging Face é A PLATAFORMA DE NLP MODERNO — repositório com 500k+ modelos pré-treinados (BERT, GPT, T5, LLaMA, etc.) e biblioteca transformers para usá-los. pipeline() é a abstração mais alta: você passa só o nome da tarefa e ela baixa o melhor modelo padrão, faz tokenização, inferência e pós-processamento — tudo em uma linha. Tarefas: sentiment-analysis, ner, translation, summarization, question-answering, fill-mask, zero-shot-classification, text-generation, conversational, image-classification. Para usar modelo específico: pipeline('sentiment-analysis', model='nome-do-modelo'). É como ter uma API de IA local.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Acesso a estado da arte conquistado.",
      solution: "from transformers import pipeline\nclassifier = pipeline('sentiment-analysis')",
    },
    {
      id: "ds-nlp-22",
      worldId: "sintetizador-linguagem",
      title: "BERT Tokenizer",
      description: "Use tokenizer('Olá mundo', return_tensors='pt') e imprima 'BERT tokenizado.'.",
      narrative: "BERT usa subword tokenization (WordPiece) — não é só split.",
      difficulty: "avancado",
      setupCode: "def tokenizer(t, return_tensors=None): print('BERT tokenizado.'); return None",
      expectedOutput: "BERT tokenizado.",
      testCode: "assert 'return_tensors' in code",
      starterCode: "# Tokenize 'Olá mundo' com return_tensors='pt'\n",
      hints: [
        { text: "tokenizer(texto, return_tensors='pt') retorna tensores PyTorch prontos para o modelo.", cost: 30 },
        { text: "return_tensors: 'pt' (PyTorch), 'tf' (TensorFlow), 'np' (NumPy).", cost: 35 },
        { text: "tokenizer('Olá mundo', return_tensors='pt')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Tokenizers Modernos",
      conceptExplanation: "Modelos Transformer usam tokenizers SUBWORD: dividem palavras raras em PEDAÇOS conhecidos. 'tokenização' pode virar 'token' + '##ização'. Vantagem: vocabulário pequeno (30k tokens cobre TUDO) sem sofrer com palavras desconhecidas. Algoritmos: BPE (GPT, RoBERTa), WordPiece (BERT), SentencePiece (T5, LLaMA, multilíngue). O tokenizer também adiciona TOKENS ESPECIAIS: [CLS] no início (representação do doc inteiro), [SEP] separador, [PAD] padding, [MASK] para masked language modeling. return_tensors='pt' devolve input_ids, attention_mask e token_type_ids em tensores prontos para o forward pass.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Texto convertido em tokens BERT.",
      solution: "tokenizer('Olá mundo', return_tensors='pt')",
    },
    {
      id: "ds-nlp-23",
      worldId: "sintetizador-linguagem",
      title: "Translation Pipeline",
      description: "Use pipeline('translation', model='Helsinki-NLP/opus-mt-en-pt') e imprima 'Tradutor pronto.'.",
      narrative: "Tradução automática — uma linha, qualquer par de idiomas.",
      difficulty: "avancado",
      setupCode: "def pipeline(task, model=None): print('Tradutor pronto.'); return None",
      expectedOutput: "Tradutor pronto.",
      testCode: "assert 'translation' in code",
      starterCode: "from transformers import pipeline\n# pipeline de tradução en->pt\n",
      hints: [
        { text: "Para tradução, sempre especifique model — modelos cobrem pares específicos (en→pt, pt→en, etc.).", cost: 30 },
        { text: "Helsinki-NLP/opus-mt-* tem modelos para CENTENAS de pares de idiomas.", cost: 35 },
        { text: "tradutor = pipeline('translation', model='Helsinki-NLP/opus-mt-en-pt')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Tradução Automática",
      conceptExplanation: "Tradução automática (Machine Translation) evoluiu de regras → SMT (estatística, com Phrase-Based) → NMT (Neural, com seq2seq) → Transformers. Estado da arte atual: modelos seq2seq como T5, mBART, NLLB (No Language Left Behind, da Meta, 200 idiomas). No Hugging Face, OPUS-MT cobre praticamente qualquer par; M2M100 é multilíngue universal. Para qualidade máxima, GPT-4/Claude geralmente superam modelos especializados (mas com custo). Avaliação: métricas BLEU, METEOR, COMET (mais correlacionada com humano). Em produção, modelos próprios vs APIs (Google Translate, DeepL) é decisão de custo vs latência vs privacidade.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Barreira linguística rompida.",
      solution: "from transformers import pipeline\ntradutor = pipeline('translation', model='Helsinki-NLP/opus-mt-en-pt')",
    },
    {
      id: "ds-nlp-24",
      worldId: "sintetizador-linguagem",
      title: "Question Answering",
      description: "Crie qa = pipeline('question-answering') e imprima 'QA pronto.'.",
      narrative: "Extração de respostas de um contexto fornecido.",
      difficulty: "avancado",
      setupCode: "def pipeline(task): print('QA pronto.'); return None",
      expectedOutput: "QA pronto.",
      testCode: "assert 'question-answering' in code",
      starterCode: "from transformers import pipeline\n# pipeline de QA\n",
      hints: [
        { text: "pipeline('question-answering') usa modelo treinado em SQuAD por padrão.", cost: 30 },
        { text: "Uso: qa(question='...', context='...'). Retorna {'answer': ..., 'score': ...}.", cost: 35 },
        { text: "qa = pipeline('question-answering')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Question Answering Extrativo",
      conceptExplanation: "QA EXTRATIVO: dado um contexto (texto) e uma pergunta, o modelo EXTRAI o trecho que responde — não gera novo texto. Treinado em datasets como SQuAD: pares (pergunta, contexto, span_resposta). Modelo aprende a prever início e fim do span. Diferente do QA GERATIVO (ChatGPT, Claude) que escreve resposta livre — extrativo só copia trechos. Vantagens: respostas SEMPRE fundamentadas no contexto (sem alucinação), interpretável (você vê de onde veio). Aplicações: busca em documentação interna, FAQ automatizada, leitura de contratos. Em RAG modernos, frequentemente combinado: retrieve passages → QA extrativo OU LLM gerativo sobre os passages.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Respostas extraídas de texto.",
      solution: "from transformers import pipeline\nqa = pipeline('question-answering')",
    },
    {
      id: "ds-nlp-25",
      worldId: "sintetizador-linguagem",
      title: "Summarization",
      description: "Crie summarizer = pipeline('summarization') e imprima 'Resumidor pronto.'.",
      narrative: "Comprima documentos longos em resumos curtos.",
      difficulty: "avancado",
      setupCode: "def pipeline(task): print('Resumidor pronto.'); return None",
      expectedOutput: "Resumidor pronto.",
      testCode: "assert 'summarization' in code",
      starterCode: "from transformers import pipeline\n# pipeline de summarization\n",
      hints: [
        { text: "pipeline('summarization') usa BART ou T5 por padrão.", cost: 30 },
        { text: "Uso: summarizer(texto, max_length=130, min_length=30).", cost: 35 },
        { text: "summarizer = pipeline('summarization')", cost: 40 },
      ],
      xpReward: 1100,
      concept: "Sumarização Automática",
      conceptExplanation: "Sumarização tem duas famílias: EXTRATIVA (seleciona frases mais importantes do texto original — TextRank, LexRank) e ABSTRATIVA (gera novo texto reescrevendo — BART, T5, Pegasus). Extrativa é mais segura (texto sempre do original); abstrativa é mais natural mas pode alucinar. Modelos modernos (BART-large-CNN, Pegasus) treinados em CNN/DailyMail — bom para notícias. Para domínios específicos (científico, jurídico), fine-tune ou use modelos especializados. Parâmetros úteis: max_length (limite do resumo), min_length, length_penalty, num_beams (beam search para qualidade). Em produção, LLMs (GPT-4, Claude) frequentemente superam modelos especializados com prompt simples.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Documentos comprimidos.",
      solution: "from transformers import pipeline\nsummarizer = pipeline('summarization')",
    },
    {
      id: "ds-nlp-26",
      worldId: "sintetizador-linguagem",
      title: "Zero-Shot Classification",
      description: "Crie pipeline('zero-shot-classification') e imprima 'Zero-shot pronto.'.",
      narrative: "Classifique texto em categorias SEM treinar — defina as labels no momento.",
      difficulty: "avancado",
      setupCode: "def pipeline(task): print('Zero-shot pronto.'); return None",
      expectedOutput: "Zero-shot pronto.",
      testCode: "assert 'zero-shot' in code",
      starterCode: "from transformers import pipeline\n# pipeline de zero-shot\n",
      hints: [
        { text: "Zero-shot = sem dados de treino para suas labels específicas — usa entailment.", cost: 30 },
        { text: "Uso: classifier(texto, candidate_labels=['esporte','política','tech']).", cost: 35 },
        { text: "classifier = pipeline('zero-shot-classification')", cost: 40 },
      ],
      xpReward: 1200,
      concept: "Zero-Shot Classification",
      conceptExplanation: "ZERO-SHOT permite classificar texto em CATEGORIAS QUE O MODELO NUNCA VIU NO TREINO — você define labels no momento da inferência. Funciona via Natural Language Inference (NLI): o modelo verifica se a hipótese 'Este texto é sobre {label}' é IMPLICADA pelo texto. Vantagens: zero dados rotulados, labels flexíveis (mude a qualquer momento). Limitações: menos preciso que modelo fine-tuned com dados; mais lento (avalia cada label separadamente). Modelos: bart-large-mnli é o padrão. Uso típico: classificar tópicos, detectar intenções em chatbot, triagem inicial. Para volume alto e labels fixas, ainda vale fine-tunar modelo dedicado.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Classificação sem treino.",
      solution: "from transformers import pipeline\nclassifier = pipeline('zero-shot-classification')",
    },
    {
      id: "ds-nlp-27",
      worldId: "sintetizador-linguagem",
      title: "Sentence Embeddings",
      description: "Use model.encode(['Frase 1', 'Frase 2']) e imprima 'Embeddings gerados.'.",
      narrative: "Vetores semânticos de SENTENÇAS inteiras — base de RAG e busca semântica.",
      difficulty: "avancado",
      setupCode: "class Model:\n    def encode(self, l): print('Embeddings gerados.'); return None\nmodel = Model()",
      expectedOutput: "Embeddings gerados.",
      testCode: "assert 'encode' in code",
      starterCode: "from sentence_transformers import SentenceTransformer\nmodel = SentenceTransformer('all-MiniLM-L6-v2')\n# Encode as frases\n",
      hints: [
        { text: "SentenceTransformer transforma sentenças/parágrafos inteiros em vetor único.", cost: 30 },
        { text: "model.encode(lista_de_strings) retorna matriz numpy (N_frases x dim).", cost: 35 },
        { text: "model.encode(['Frase 1', 'Frase 2'])", cost: 40 },
      ],
      xpReward: 1200,
      concept: "Sentence Embeddings",
      conceptExplanation: "Sentence Embeddings transformam SENTENÇAS/PARÁGRAFOS em UM ÚNICO vetor — diferente de Word2Vec (palavras isoladas) ou pooling de BERT cru (resultado ruim). Biblioteca padrão: sentence-transformers (também chamado SBERT). Modelos populares: all-MiniLM-L6-v2 (rápido, 384 dim), all-mpnet-base-v2 (preciso, 768 dim), multilingual-e5-large (multilíngue, top tier 2024+). USO CENTRAL: RAG (Retrieval-Augmented Generation), busca semântica, deduplicação, clustering de textos, FAQ matching. Métrica: cosine similarity entre embeddings. Sempre teste com seus dados — modelos performam diferente por domínio (jurídico, científico, conversacional).",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Sentenças vetorizadas.",
      solution: "from sentence_transformers import SentenceTransformer\nmodel = SentenceTransformer('all-MiniLM-L6-v2')\nmodel.encode(['Frase 1', 'Frase 2'])",
    },
    {
      id: "ds-nlp-28",
      worldId: "sintetizador-linguagem",
      title: "Vector Search com FAISS",
      description: "Imprima 'FAISS: busca de vizinhos em milhões de vetores.'.",
      narrative: "Quando seu vector DB tem milhões de documentos, FAISS escala.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "FAISS: busca de vizinhos em milhões de vetores.",
      testCode: "assert 'FAISS' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('FAISS: busca de vizinhos em milhões de vetores.')", cost: 25 },
        { text: "print('FAISS: busca de vizinhos em milhões de vetores.')", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Vector Search (FAISS, ANN)",
      conceptExplanation: "Quando você tem MILHÕES de embeddings e precisa achar os mais similares a uma query, busca exata fica inviável (O(N) por consulta). FAISS (Facebook AI Similarity Search) é a biblioteca padrão para BUSCA APROXIMADA de vizinhos (ANN — Approximate Nearest Neighbors): trade-off entre precisão e velocidade. Algoritmos: IVF (Inverted File — agrupa vetores em clusters), PQ (Product Quantization — comprime vetores), HNSW (Hierarchical Navigable Small World — grafos hierárquicos). Alternativas: Annoy (Spotify), ScaNN (Google), e bancos vetoriais gerenciados — Pinecone, Weaviate, Qdrant, Milvus, Chroma. CORE do RAG: query → embedding → ANN search → top-K passages → LLM.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Escala para milhões.",
      solution: "print('FAISS: busca de vizinhos em milhões de vetores.')",
    },
    {
      id: "ds-nlp-29",
      worldId: "sintetizador-linguagem",
      title: "Topic Modeling (LDA)",
      description: "Imprima 'LDA: descobre tópicos latentes em coleção de documentos.'.",
      narrative: "Quais temas estão escondidos em 100 mil artigos?",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "LDA: descobre tópicos latentes em coleção de documentos.",
      testCode: "assert 'LDA' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('LDA: descobre tópicos latentes em coleção de documentos.')", cost: 25 },
        { text: "print('LDA: descobre tópicos latentes em coleção de documentos.')", cost: 30 },
      ],
      xpReward: 1050,
      concept: "Topic Modeling",
      conceptExplanation: "TOPIC MODELING descobre TÓPICOS LATENTES (não rotulados) em coleção de documentos — análise exploratória não-supervisionada. LDA (Latent Dirichlet Allocation) é o algoritmo clássico: assume que cada doc é mistura de tópicos e cada tópico é mistura de palavras. Você define K (número de tópicos); o algoritmo aprende quais palavras pertencem a cada tópico. Bibliotecas: gensim (LDA, LSI), sklearn (LatentDirichletAllocation). Alternativas MODERNAS: BERTopic (usa embeddings BERT + UMAP + HDBSCAN) — frequentemente supera LDA, especialmente em textos curtos. Aplicações: análise de mídia, organização de documentos, monitoramento de redes sociais, descoberta de subgrupos em reviews.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Temas ocultos revelados.",
      solution: "print('LDA: descobre tópicos latentes em coleção de documentos.')",
    },
    {
      id: "ds-nlp-30",
      worldId: "sintetizador-linguagem",
      title: "Fine-tuning Transformers",
      description: "Imprima 'Fine-tuning: adaptar modelo pré-treinado a tarefa específica.'.",
      narrative: "Não treine do zero — comece de BERT e adapte ao seu domínio.",
      difficulty: "avancado",
      setupCode: "",
      expectedOutput: "Fine-tuning: adaptar modelo pré-treinado a tarefa específica.",
      testCode: "assert 'Fine-tuning' in output",
      starterCode: "# Imprima a string exata\n",
      hints: [
        { text: "Copie a string exata.", cost: 15 },
        { text: "print('Fine-tuning: adaptar modelo pré-treinado a tarefa específica.')", cost: 25 },
        { text: "print('Fine-tuning: adaptar modelo pré-treinado a tarefa específica.')", cost: 30 },
      ],
      xpReward: 1200,
      concept: "Fine-Tuning de Transformers",
      conceptExplanation: "FINE-TUNING: pegue um modelo PRÉ-TREINADO (BERT, RoBERTa, T5) em um corpus gigante e ADAPTE para sua tarefa específica com seu dataset (frequentemente pequeno, ~1k-10k exemplos). Diferente de treinar do zero (precisa de bilhões de tokens e dias de GPU), fine-tuning leva minutos/horas e funciona com poucos dados. Workflow Hugging Face: AutoModelForSequenceClassification → Trainer com TrainingArguments. Variantes modernas: PEFT (Parameter-Efficient Fine-Tuning) — só atualiza parte dos pesos (LoRA, adapters, prompt tuning); INSTRUCTION TUNING — treina em pares (instrução, resposta) para seguir comandos; RLHF — alinhamento via preferências humanas. Para muitos casos, prompt engineering em LLM grande supera fine-tuning de modelo menor.",
      successNpc: "Linguista Quântico",
      successAvatar: "/avatars/ai7_guide.png",
      successStory: "Modelo customizado.",
      solution: "print('Fine-tuning: adaptar modelo pré-treinado a tarefa específica.')",
    },
  ],
};
