import { World } from "../types";

export const VALE_CONDICOES_WORLD: World = {
  id: "vale-condicoes",
  title: "Nó de Roteamento",
  subtitle: "Desvios e Bifurcações de Dados",
  icon: "git-branch",
  color: "#22C55E",
  lore: "No Nó de Roteamento, o Sistema Central testa sua lógica. O código não flui apenas em linha reta; ele deve decidir qual trilha seguir baseado em condições pré-definidas.",
  unlockRequirement: 300,
  challenges: [
    {
      id: "py-cond-01",
      worldId: "vale-condicoes",
      title: "Firewall de Acesso",
      description: "Use o operador if para verificar se a idade é maior ou igual a 18. Se for, projete 'Acesso Permitido'.",
      narrative: "Um firewall primário protege os servidores internos. Apenas conexões com a 'Idade de Acesso' correta podem passar. Crie o script validador.",
      difficulty: "iniciante",
      setupCode: "idade = 20",
      expectedOutput: "Acesso Permitido",
      testCode: "assert output.strip() == 'Acesso Permitido'",
      starterCode: "idade = 20\n# Escreva seu script de validação aqui\n",
      hints: [
        { text: "A estrutura começa com if condição: seguido de um novo parágrafo.", cost: 10 },
        { text: "O print precisa estar um passo à frente (indentado) para pertencer ao if.", cost: 20 },
        { text: "if idade >= 18:\n    print('Acesso Permitido')", cost: 30 },
      ],
      xpReward: 200,
      concept: "O Validador Lógico 'if'",
      conceptExplanation: "O comando 'if' (se) permite que o programa tome decisões. Se a condição for verdadeira, o bloco de código abaixo dele é executado.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso liberado. Você fez o primeiro bypass estrutural na rede.",
    },
    {
      id: "py-cond-02",
      worldId: "vale-condicoes",
      title: "Gerenciamento de Energia",
      description: "Use if e else. Se a energia for maior que 50, projete 'Correr'. Caso contrário, projete 'Descansar'.",
      narrative: "Para otimizar o processamento do Node, você deve balancear os recursos. Se a bateria estiver alta, o sistema acelera; se baixa, entra em hibernação.",
      difficulty: "iniciante",
      setupCode: "energia = 30",
      expectedOutput: "Descansar",
      testCode: "assert output.strip() == 'Descansar'",
      starterCode: "energia = 30\n# Equilibre as escolhas com if e else\n",
      hints: [
        { text: "O else (caso contrário) não precisa de uma nova condição.", cost: 10 },
        { text: "Lembre-se de manter a indentação em ambos os caminhos.", cost: 20 },
        { text: "if energia > 50:\n    print('Correr')\nelse:\n    print('Descansar')", cost: 30 },
      ],
      xpReward: 250,
      concept: "Dualidade de Caminhos (if/else)",
      conceptExplanation: "O 'else' complementa o 'if', garantindo que sempre haverá uma ação a ser tomada, mesmo que a condição principal não seja atendida.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Balanceamento restaurado. Seus scripts agora lidam com ambos os fluxos da matriz.",
    },
  ],
};
