import { World } from "../types";

export const VALE_CONDICOES_WORLD: World = {
  id: "vale-condicoes",
  title: "Nó de Roteamento",
  subtitle: "Desvios e Bifurcações de Dados",
  icon: "git-branch",
  color: "#22C55E",
  bgImage: "/assets/images/worlds/routing_node.png",
  lore: "No Nó de Roteamento, o Sistema Central testa sua lógica. O código não flui apenas em linha reta; ele deve decidir qual trilha seguir baseado em condições pré-definidas.",
  unlockRequirement: 1500,
  challenges: [
    {
      id: "py-cond-01",
      worldId: "vale-condicoes",
      title: "Firewall de Acesso",
      description: "Use o operador if para verificar se a idade é maior ou igual a 18. Se for, imprima 'Acesso Permitido'.",
      narrative: "Um firewall primário protege os servidores internos. Apenas conexões com a 'Idade de Acesso' correta podem passar. Crie o script validador.",
      difficulty: "iniciante",
      setupCode: "idade = 20",
      expectedOutput: "Acesso Permitido",
      testCode: "assert output.strip() == 'Acesso Permitido'",
      starterCode: "idade = 20\n# Escreva seu script de validação aqui\n",
      hints: [
        { text: "A estrutura começa com if condição: seguido de um novo parágrafo.", cost: 10 },
        { text: "O print precisa estar um passo à frente (indentado) para pertencer ao if.", cost: 20 },
        { text: "if idade >= 18:\n    print('Acesso Permitido')", cost: 30 },
      ],
      xpReward: 200,
      concept: "O Validador Lógico 'if'",
      conceptExplanation: "O 'if' (que significa 'se' em inglês) ensina o computador a tomar decisões sozinho, baseando-se em uma condição que você define.\n\nPor exemplo:\nif idade >= 18:\n    print('Entrada Liberada')\n\nIsso diz ao programa: 'Se a idade for maior ou igual a 18, execute o comando abaixo'. Tudo que estiver indentado (com espaços) abaixo do 'if' só acontecerá se a condição for verdadeira.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso liberado. Você fez o primeiro bypass estrutural na rede.",
      solution: "if idade >= 18:\n    print('Acesso Permitido')",
    },
    {
      id: "py-cond-02",
      worldId: "vale-condicoes",
      title: "Gerenciamento de Energia",
      description: "Use if e else. Se a energia for maior que 50, imprima 'Correr'. Caso contrário, imprima 'Descansar'.",
      narrative: "Para otimizar o processamento do Node, você deve balancear os recursos. Se a bateria estiver alta, o sistema acelera; se baixa, entra em hibernação.",
      difficulty: "iniciante",
      setupCode: "energia = 30",
      expectedOutput: "Descansar",
      testCode: "assert output.strip() == 'Descansar'",
      starterCode: "energia = 30\n# Equilibre as escolhas com if e else\n",
      hints: [
        { text: "O else (caso contrário) não precisa de uma nova condição.", cost: 10 },
        { text: "Lembre-se de manter a indentação em ambos os caminhos.", cost: 20 },
        { text: "if energia > 50:\n    print('Correr')\nelse:\n    print('Descansar')", cost: 30 },
      ],
      xpReward: 250,
      concept: "Dualidade de Caminhos (if/else)",
      conceptExplanation: "Enquanto o 'if' diz o que fazer se algo for verdade, o 'else' (que significa 'senão') diz o que fazer se for mentira. Ele cria um caminho alternativo para o código!\n\nPor exemplo:\nif chover:\n    print('Leve o guarda-chuva')\nelse:\n    print('Leve óculos de sol')\n\nO computador sempre vai escolher um dos dois caminhos.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Balanceamento restaurado. Seus scripts agora lidam com ambos os fluxos da matriz.",
      solution: "if energia > 50:\n    print('Correr')\nelse:\n    print('Descansar')",
    },
    {
      id: "py-cond-03",
      worldId: "vale-condicoes",
      title: "Níveis de Acesso Multi-Layer",
      description: "Use if e elif. Se 'nivel' for 1, imprima 'Acesso Baixo'. Se for 2, 'Acesso Medio'. Se for 3, 'Acesso Alto'.",
      narrative: "O sistema de segurança possui várias camadas. Você deve identificar em qual camada seu token de acesso se encaixa para abrir as portas corretas.",
      difficulty: "intermediario",
      setupCode: "nivel = 2",
      expectedOutput: "Acesso Medio",
      testCode: "assert output.strip() == 'Acesso Medio'",
      starterCode: "nivel = 2\n# Use elif para verificar multiplas condições\n",
      hints: [
        { text: "O elif é usado para verificar uma nova condição caso a primeira seja falsa.", cost: 10 },
        { text: "Você pode ter vários elifs entre o if e o else.", cost: 20 },
        { text: "if nivel == 1:\n    print('Acesso Baixo')\nelif nivel == 2:\n    print('Acesso Medio')", cost: 30 },
      ],
      xpReward: 300,
      concept: "Múltiplas Condições (elif)",
      conceptExplanation: "O `elif` (abreviação de 'else if') permite que você verifique várias condições em sequência. O computador vai testando uma por uma até achar a primeira que seja verdade.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso médio garantido. Você agora tem permissão para visualizar os logs dos setores internos.",
      solution: "if nivel == 1:\n    print('Acesso Baixo')\nelif nivel == 2:\n    print('Acesso Medio')\nelse:\n    print('Acesso Alto')",
    },
    {
      id: "py-cond-04",
      worldId: "vale-condicoes",
      title: "Verificação de Duplo Fator",
      description: "Use o operador 'and' no if. Se 'has_token' for True E 'has_pass' for True, imprima 'Sistema Desbloqueado'.",
      narrative: "Para desbloquear o Core, não basta um token; você também precisa da senha mestre. Verifique se ambos os requisitos foram atendidos.",
      difficulty: "intermediario",
      setupCode: "has_token = True\nhas_pass = True",
      expectedOutput: "Sistema Desbloqueado",
      testCode: "assert output.strip() == 'Sistema Desbloqueado'",
      starterCode: "has_token = True\nhas_pass = True\n# Use 'and' para verificar as duas condições juntas\n",
      hints: [
        { text: "O operador 'and' retorna True apenas se AMBOS os lados forem verdadeiros.", cost: 10 },
        { text: "Sintaxe: if condicao1 and condicao2:", cost: 20 },
        { text: "if has_token and has_pass:\n    print('Sistema Desbloqueado')", cost: 30 },
      ],
      xpReward: 350,
      concept: "Operadores Lógicos (and)",
      conceptExplanation: "Operadores lógicos permitem combinar condições. O `and` (e) exige que todas as partes sejam verdadeiras para que o resultado final seja verdade.\n\nExemplo: Se você tem ingresso E tem documento, então pode entrar no show.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Autenticação de dois fatores concluída. O bloqueio do Core foi removido.",
      solution: "if has_token and has_pass:\n    print('Sistema Desbloqueado')",
    },
    {
      id: "py-cond-05",
      worldId: "vale-condicoes",
      title: "Protocolo de Redundância",
      description: "Use o operador 'or'. Se 'servidor_a' for True OU 'servidor_b' for True, imprima 'Conexão Estável'.",
      narrative: "Para manter o sistema online, precisamos que ao menos um dos dois servidores de redundância esteja ativo. Verifique a disponibilidade da rede.",
      difficulty: "intermediario",
      setupCode: "servidor_a = False\nservidor_b = True",
      expectedOutput: "Conexão Estável",
      testCode: "assert output.strip() == 'Conexão Estável'",
      starterCode: "servidor_a = False\nservidor_b = True\n# Verifique se pelo menos um servidor está ativo\n",
      hints: [
        { text: "O operador 'or' retorna True se PELO MENOS UM dos lados for verdadeiro.", cost: 10 },
        { text: "if servidor_a or servidor_b:", cost: 20 },
      ],
      xpReward: 380,
      concept: "Operadores Lógicos (or)",
      conceptExplanation: "O operador `or` (ou) é usado quando você tem várias opções e apenas uma delas precisa ser verdade para que tudo funcione. Se qualquer uma das condições for verdadeira, o bloco de código será executado.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Redundância ativada. O tráfego foi redirecionado para o servidor B. A conexão permanece estável.",
      solution: "if servidor_a or servidor_b:\n    print('Conexão Estável')",
    },
    {
      id: "py-cond-06",
      worldId: "vale-condicoes",
      title: "Inversão de Lógica",
      description: "Use o operador 'not'. Se NÃO houver 'virus', imprima 'Sistema Limpo'.",
      narrative: "Às vezes, a melhor defesa é verificar a ausência de ameaças. Inverta a lógica do scanner para confirmar a integridade dos arquivos.",
      difficulty: "intermediario",
      setupCode: "virus = False",
      expectedOutput: "Sistema Limpo",
      testCode: "assert 'not' in code and output.strip() == 'Sistema Limpo'",
      starterCode: "virus = False\n# Use 'not' para verificar se NÃO há vírus\n",
      hints: [
        { text: "O operador 'not' inverte o valor booleano: not True vira False.", cost: 10 },
        { text: "if not virus:", cost: 20 },
      ],
      xpReward: 400,
      concept: "Operador Lógico (not)",
      conceptExplanation: "O `not` (não) inverte uma condição. Se algo é falso, `not algo` vira verdadeiro. É como dizer: 'Se não estiver chovendo, eu vou sair'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Varredura negativa para ameaças. O sistema está operando em modo seguro.",
      solution: "if not virus:\n    print('Sistema Limpo')",
    },
    {
      id: "py-cond-07",
      worldId: "vale-condicoes",
      title: "Scanner de Range de Portas",
      description: "Verifique se a 'porta' está entre 1024 e 65535 (inclusive). Se sim, imprima 'Porta de Usuario'.",
      narrative: "As portas do sistema são divididas em faixas. Portas altas são reservadas para aplicações de usuário. Identifique se o tráfego está vindo de uma dessas portas.",
      difficulty: "intermediario",
      setupCode: "porta = 8080",
      expectedOutput: "Porta de Usuario",
      testCode: "assert ('>=' in code or '<=' in code) and output.strip() == 'Porta de Usuario'",
      starterCode: "porta = 8080\n# Verifique se a porta está no intervalo [1024, 65535]\n",
      hints: [
        { text: "Você pode usar duas condições com 'and' ou a sintaxe simplificada: min <= x <= max.", cost: 10 },
        { text: "if porta >= 1024 and porta <= 65535:", cost: 20 },
      ],
      xpReward: 420,
      concept: "Comparações em Cadeia",
      conceptExplanation: "Python permite verificar se um número está entre dois valores de forma muito elegante, como na matemática: `10 < x < 20`. Isso torna o código mais legível e fácil de entender.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Porta identificada como tráfego de aplicação de usuário. Pacotes autorizados para processamento.",
      solution: "if 1024 <= porta <= 65535:\n    print('Porta de Usuario')",
    },
    {
      id: "py-cond-08",
      worldId: "vale-condicoes",
      title: "Lista Branca de Acesso",
      description: "Verifique se o 'usuario' está na lista 'lista_branca' usando o operador 'in'. Se estiver, imprima 'Acesso VIP'.",
      narrative: "O firewall possui uma lista de operadores de elite. Verifique se o usuário atual possui privilégios administrativos elevados.",
      difficulty: "intermediario",
      setupCode: "lista_branca = ['Neo', 'Trinity', 'Morpheus']\nusuario = 'Trinity'",
      expectedOutput: "Acesso VIP",
      testCode: "assert ' in ' in code and output.strip() == 'Acesso VIP'",
      starterCode: "lista_branca = ['Neo', 'Trinity', 'Morpheus']\nusuario = 'Trinity'\n# Verifique se o usuário está na lista\n",
      hints: [
        { text: "O operador 'in' verifica se um item existe dentro de uma lista.", cost: 10 },
        { text: "if usuario in lista_branca:", cost: 20 },
      ],
      xpReward: 450,
      concept: "Operador de Associação (in)",
      conceptExplanation: "O operador `in` (em) é extremamente poderoso. Ele percorre uma lista e te diz se o que você procura está lá dentro. É como procurar um nome em uma lista de convidados.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Credenciais de elite confirmadas. Você agora tem acesso total ao Nó de Roteamento.",
      solution: "if usuario in lista_branca:\n    print('Acesso VIP')",
    },
    {
      id: "py-cond-09",
      worldId: "vale-condicoes",
      title: "Detector de Anomalias",
      description: "Use o operador '!='. Se o 'sinal' for diferente de 'ERRO', imprima 'Transmissao Limpa'.",
      narrative: "Um receptor monitora o canal de comunicação 24/7. Qualquer sinal que não seja explicitamente um 'ERRO' deve ser considerado válido para análise.",
      difficulty: "intermediario",
      setupCode: "sinal = 'OK'",
      expectedOutput: "Transmissao Limpa",
      testCode: "assert '!=' in code and output.strip() == 'Transmissao Limpa'",
      starterCode: "sinal = 'OK'\n# Use '!=' para verificar diferença\n",
      hints: [
        { text: "O operador '!=' significa 'diferente de'.", cost: 10 },
        { text: "if sinal != 'ERRO':", cost: 20 },
        { text: "if sinal != 'ERRO':\n    print('Transmissao Limpa')", cost: 30 },
      ],
      xpReward: 470,
      concept: "Operador de Diferença (!=)",
      conceptExplanation: "Enquanto `==` verifica se dois valores são iguais, `!=` verifica se eles são diferentes. É útil para detectar mudanças de estado ou identificar anomalias.\n\nExemplo:\nif status != 'offline':\n    print('Sistema ativo')\n\nO bloco só executa se o status NÃO for 'offline'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Canal limpo. O receptor confirma que nenhum ruído anormal foi captado.",
      solution: "if sinal != 'ERRO':\n    print('Transmissao Limpa')",
    },
    {
      id: "py-cond-10",
      worldId: "vale-condicoes",
      title: "Analisador de Paridade",
      description: "Use o operador módulo (%). Se 'porta' for par, imprima 'Porta Par'. Caso contrário, 'Porta Impar'.",
      narrative: "O Sistema separa o tráfego entre canais pares e ímpares para balanceamento de carga. Identifique a paridade da porta para roteá-la corretamente.",
      difficulty: "intermediario",
      setupCode: "porta = 8080",
      expectedOutput: "Porta Par",
      testCode: "assert '%' in code and output.strip() == 'Porta Par'",
      starterCode: "porta = 8080\n# Use o operador % para verificar paridade\n",
      hints: [
        { text: "O operador % retorna o resto da divisão. Um número é par se 'numero % 2' for igual a 0.", cost: 10 },
        { text: "if porta % 2 == 0:", cost: 20 },
        { text: "if porta % 2 == 0:\n    print('Porta Par')\nelse:\n    print('Porta Impar')", cost: 30 },
      ],
      xpReward: 500,
      concept: "Módulo e Paridade",
      conceptExplanation: "O operador `%` (módulo) devolve o resto de uma divisão. Por exemplo, 10 % 2 é 0, mas 11 % 2 é 1.\n\nIsso é a forma clássica de verificar se um número é par (resto 0) ou ímpar (resto 1):\nif n % 2 == 0:\n    print('par')",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tráfego direcionado para o canal par. O balanceador de carga registra a operação.",
      solution: "if porta % 2 == 0:\n    print('Porta Par')\nelse:\n    print('Porta Impar')",
    },
    {
      id: "py-cond-11",
      worldId: "vale-condicoes",
      title: "Comparador de Hash Exato",
      description: "Compare o 'hash_recebido' com 'hash_oficial'. Se forem idênticos, imprima 'Integridade OK'. Strings em Python diferenciam maiúsculas de minúsculas.",
      narrative: "Um pacote chegou criptografado. Para validar sua autenticidade, compare exatamente o hash recebido com o hash oficial gravado no servidor.",
      difficulty: "intermediario",
      setupCode: "hash_oficial = 'a1B2c3'\nhash_recebido = 'a1B2c3'",
      expectedOutput: "Integridade OK",
      testCode: "assert '==' in code and output.strip() == 'Integridade OK'",
      starterCode: "hash_oficial = 'a1B2c3'\nhash_recebido = 'a1B2c3'\n# Compare os dois hashes exatamente\n",
      hints: [
        { text: "Strings podem ser comparadas diretamente com '=='.", cost: 10 },
        { text: "if hash_recebido == hash_oficial:", cost: 20 },
      ],
      xpReward: 520,
      concept: "Comparação de Strings",
      conceptExplanation: "Em Python, strings também podem ser comparadas com `==` e `!=`. A comparação considera cada caractere e diferencia maiúsculas de minúsculas: 'Senha' é diferente de 'senha'.\n\nIsso é fundamental em sistemas de autenticação, onde uma única letra trocada já invalida a operação.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Hashes coincidem. O pacote foi assinado por uma fonte confiável.",
      solution: "if hash_recebido == hash_oficial:\n    print('Integridade OK')",
    },
    {
      id: "py-cond-12",
      worldId: "vale-condicoes",
      title: "Camadas de Permissão Aninhadas",
      description: "Use if dentro de if. Se 'autenticado' for True, verifique 'nivel'. Se nível for 5, imprima 'Acesso Root'. Caso contrário, 'Acesso Limitado'.",
      narrative: "A sala dos servidores tem dois portões: o primeiro valida a autenticação básica, e o segundo verifica o nível de privilégio. Modele essa lógica em camadas.",
      difficulty: "avancado",
      setupCode: "autenticado = True\nnivel = 5",
      expectedOutput: "Acesso Root",
      testCode: "assert output.strip() == 'Acesso Root'",
      starterCode: "autenticado = True\nnivel = 5\n# Aninhe um if dentro de outro if\n",
      hints: [
        { text: "Você pode escrever um novo 'if' dentro do bloco indentado de outro 'if'.", cost: 10 },
        { text: "Cada nível de aninhamento exige mais um nível de indentação.", cost: 20 },
        { text: "if autenticado:\n    if nivel == 5:\n        print('Acesso Root')\n    else:\n        print('Acesso Limitado')", cost: 30 },
      ],
      xpReward: 600,
      concept: "Condicionais Aninhadas",
      conceptExplanation: "Você pode colocar uma condição dentro de outra. O segundo `if` só será avaliado se o primeiro for verdadeiro. Isso permite criar fluxos de decisão em múltiplas camadas.\n\nMas cuidado: aninhar demais deixa o código difícil de ler. Sempre que possível, prefira combinar condições com `and` em uma única linha.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Privilégio máximo concedido. Você está dentro do núcleo do Sistema Central.",
      solution: "if autenticado:\n    if nivel == 5:\n        print('Acesso Root')\n    else:\n        print('Acesso Limitado')",
    },
    {
      id: "py-cond-13",
      worldId: "vale-condicoes",
      title: "Filtro Composto de Tráfego",
      description: "Combine 'and' e 'or'. Se ('admin' for True OU 'vip' for True) E 'banido' for False, imprima 'Trafego Permitido'.",
      narrative: "O firewall principal aceita conexões de admins ou VIPs, mas qualquer usuário banido é bloqueado independentemente do seu status. Codifique essa regra.",
      difficulty: "avancado",
      setupCode: "admin = False\nvip = True\nbanido = False",
      expectedOutput: "Trafego Permitido",
      testCode: "assert ' and ' in code and ' or ' in code and output.strip() == 'Trafego Permitido'",
      starterCode: "admin = False\nvip = True\nbanido = False\n# Combine 'and', 'or' e parênteses\n",
      hints: [
        { text: "Use parênteses para agrupar a parte do 'or' e separá-la do 'and'.", cost: 15 },
        { text: "if (admin or vip) and not banido:", cost: 25 },
      ],
      xpReward: 650,
      concept: "Combinação de Operadores Lógicos",
      conceptExplanation: "Você pode combinar `and`, `or` e `not` em uma mesma expressão. Para evitar ambiguidade, use parênteses: o que está dentro deles é avaliado primeiro, exatamente como na matemática.\n\nExemplo: `(a or b) and not c` significa: 'pelo menos um entre a e b deve ser verdade, E c deve ser falso'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Pacote VIP autenticado e nenhum bloqueio detectado. Tráfego encaminhado.",
      solution: "if (admin or vip) and not banido:\n    print('Trafego Permitido')",
    },
    {
      id: "py-cond-14",
      worldId: "vale-condicoes",
      title: "Roteamento Compacto",
      description: "Use o operador ternário. Atribua à variável 'status' o valor 'Online' se 'ping' for menor que 100, senão 'Offline'. Depois, imprima 'status'.",
      narrative: "Em redes de alta performance, cada linha de código conta. Reduza sua decisão lógica a uma única linha usando a expressão condicional do Python.",
      difficulty: "avancado",
      setupCode: "ping = 50",
      expectedOutput: "Online",
      testCode: "assert 'if' in code and 'else' in code and output.strip() == 'Online'",
      starterCode: "ping = 50\n# Use o ternário: valor_se_verdadeiro if condicao else valor_se_falso\nstatus = \n",
      hints: [
        { text: "A sintaxe é: <valor_true> if <condicao> else <valor_false>", cost: 15 },
        { text: "status = 'Online' if ping < 100 else 'Offline'", cost: 25 },
      ],
      xpReward: 700,
      concept: "Operador Ternário",
      conceptExplanation: "Python permite escrever um if/else inteiro em uma única linha quando o objetivo é simplesmente atribuir um valor.\n\nSintaxe:\nresultado = valor_A if condicao else valor_B\n\nLê-se: 'resultado recebe valor_A se condicao for verdadeira, senão recebe valor_B'. Útil para deixar o código mais limpo em decisões simples.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Latência baixa confirmada. O nó está online e respondendo dentro da janela aceitável.",
      solution: "status = 'Online' if ping < 100 else 'Offline'\nprint(status)",
    },
    {
      id: "py-cond-15",
      worldId: "vale-condicoes",
      title: "Sniffer de Tipos",
      description: "Use 'isinstance()' para verificar se 'dado' é do tipo int. Se for, imprima 'Numero Inteiro'. Caso contrário, 'Tipo Desconhecido'.",
      narrative: "Pacotes desconhecidos chegam pelo canal aberto. Antes de processá-los, é vital identificar o tipo do dado para evitar exceções fatais no Sistema Central.",
      difficulty: "avancado",
      setupCode: "dado = 42",
      expectedOutput: "Numero Inteiro",
      testCode: "assert 'isinstance' in code and output.strip() == 'Numero Inteiro'",
      starterCode: "dado = 42\n# Use isinstance(variavel, tipo)\n",
      hints: [
        { text: "isinstance() recebe dois argumentos: a variável e o tipo desejado (int, str, list...).", cost: 15 },
        { text: "if isinstance(dado, int):", cost: 25 },
      ],
      xpReward: 750,
      concept: "Verificação de Tipo (isinstance)",
      conceptExplanation: "A função `isinstance(valor, tipo)` retorna True se o valor for do tipo informado. É a forma segura e oficial de verificar tipos em Python.\n\nExemplos de tipos comuns: int (inteiro), float (decimal), str (texto), list (lista), bool (booleano).\n\nUse isso para validar entradas antes de operar sobre elas — é uma defesa básica contra erros inesperados.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Pacote tipado com sucesso. O dado foi encaminhado ao módulo de aritmética.",
      solution: "if isinstance(dado, int):\n    print('Numero Inteiro')\nelse:\n    print('Tipo Desconhecido')",
    },
    {
      id: "py-cond-16",
      worldId: "vale-condicoes",
      title: "Despachador de Comandos",
      description: "Use a estrutura match/case. Para 'comando' = 'start', imprima 'Iniciando'. Para 'stop', 'Parando'. Para 'reboot', 'Reiniciando'. Para qualquer outro, 'Comando Desconhecido'.",
      narrative: "O console do Sistema Central recebe comandos textuais. Implemente um despachador que rotule cada instrução à ação correspondente, usando o pattern matching nativo do Python.",
      difficulty: "epico",
      setupCode: "comando = 'reboot'",
      expectedOutput: "Reiniciando",
      testCode: "assert 'match' in code and 'case' in code and output.strip() == 'Reiniciando'",
      starterCode: "comando = 'reboot'\n# Use match/case para despachar o comando\n",
      hints: [
        { text: "A sintaxe é: match variavel: seguido de blocos 'case valor:'.", cost: 20 },
        { text: "Use 'case _:' como caso padrão (default).", cost: 30 },
        { text: "match comando:\n    case 'start':\n        print('Iniciando')\n    case 'stop':\n        print('Parando')\n    case 'reboot':\n        print('Reiniciando')\n    case _:\n        print('Comando Desconhecido')", cost: 40 },
      ],
      xpReward: 900,
      concept: "Pattern Matching (match/case)",
      conceptExplanation: "A partir do Python 3.10, a estrutura `match/case` permite comparar uma variável contra múltiplos padrões de forma elegante — substituindo cadeias longas de `if/elif/else`.\n\nSintaxe básica:\nmatch valor:\n    case 'a':\n        ...\n    case 'b':\n        ...\n    case _:\n        ... # caso padrão\n\nO underline `_` representa qualquer valor que não bateu com os anteriores. É a forma moderna e limpa de fazer despacho por valor.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Despachador operacional. O Sistema Central agora responde a todos os comandos do console com latência mínima.",
      solution: "match comando:\n    case 'start':\n        print('Iniciando')\n    case 'stop':\n        print('Parando')\n    case 'reboot':\n        print('Reiniciando')\n    case _:\n        print('Comando Desconhecido')",
    },
    {
      id: "py-cond-17",
      worldId: "vale-condicoes",
      title: "Detector de Buffer Vazio",
      description: "Em Python, listas vazias são consideradas 'falsas'. Se a lista 'fila' estiver vazia (sem usar len()), imprima 'Buffer Vazio'. Caso contrário, 'Buffer com Dados'.",
      narrative: "Antes de processar pacotes, o sistema precisa saber se há algo no buffer. Use a avaliação implícita do Python — uma lista vazia já vale como False.",
      difficulty: "intermediario",
      setupCode: "fila = []",
      expectedOutput: "Buffer Vazio",
      testCode: "assert 'len' not in code and output.strip() == 'Buffer Vazio'",
      starterCode: "fila = []\n# Use 'if not fila:' — sem len()\n",
      hints: [
        { text: "Uma lista vazia [] é Falsy. Basta 'if not fila:' para detectar vazia.", cost: 10 },
        { text: "if not fila:\n    print('Buffer Vazio')\nelse:\n    print('Buffer com Dados')", cost: 20 },
      ],
      xpReward: 800,
      concept: "Truthy/Falsy",
      conceptExplanation: "Em Python, vários valores são considerados 'falsos' automaticamente sem precisar comparar: 0, '', [], {}, None e False. Todo o resto é 'verdadeiro'. Isso permite escrever 'if lista:' em vez de 'if len(lista) > 0:' — mais limpo e idiomático.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Buffer confirmado vazio. O processador pode aguardar sem desperdiçar ciclos.",
      solution: "fila = []\nif not fila:\n    print('Buffer Vazio')\nelse:\n    print('Buffer com Dados')",
    },
    {
      id: "py-cond-18",
      worldId: "vale-condicoes",
      title: "Verificação de Sinal Ausente (is None)",
      description: "Use 'is None' para verificar se 'resposta' não veio (é None). Se for, imprima 'Sem Resposta'. Caso contrário, imprima o valor.",
      narrative: "Um sensor remoto pode falhar e retornar nada. Identifique o estado 'None' usando o operador de identidade, não o '==' comum.",
      difficulty: "intermediario",
      setupCode: "resposta = None",
      expectedOutput: "Sem Resposta",
      testCode: "assert 'is None' in code and output.strip() == 'Sem Resposta'",
      starterCode: "resposta = None\n# Use 'is None' (não use ==)\n",
      hints: [
        { text: "Por convenção, comparações com None usam 'is' e 'is not', não '==' e '!='.", cost: 10 },
        { text: "if resposta is None:", cost: 20 },
      ],
      xpReward: 820,
      concept: "Operador is (Identidade)",
      conceptExplanation: "'is' compara IDENTIDADE (se são o mesmo objeto na memória), enquanto '==' compara VALOR. Para None, True e False, sempre use 'is'/'is not' — é o estilo oficial recomendado pelo PEP 8 e funciona mais rápido.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Ausência de resposta detectada. Reagendando consulta ao sensor remoto.",
      solution: "resposta = None\nif resposta is None:\n    print('Sem Resposta')\nelse:\n    print(resposta)",
    },
    {
      id: "py-cond-19",
      worldId: "vale-condicoes",
      title: "Lista de Exclusão (not in)",
      description: "Verifique se 'ip' NÃO está na lista 'banidos' usando 'not in'. Se não estiver, imprima 'Conexao Liberada'.",
      narrative: "Antes de aceitar a conexão, confirme que o IP de origem não consta na lista negra do firewall.",
      difficulty: "intermediario",
      setupCode: "banidos = ['10.0.0.7', '10.0.0.99']\nip = '10.0.0.1'",
      expectedOutput: "Conexao Liberada",
      testCode: "assert 'not in' in code and output.strip() == 'Conexao Liberada'",
      starterCode: "banidos = ['10.0.0.7', '10.0.0.99']\nip = '10.0.0.1'\n# Use 'not in' para verificar ausência\n",
      hints: [
        { text: "O operador 'not in' verifica se algo NÃO está em uma coleção.", cost: 10 },
        { text: "if ip not in banidos:", cost: 20 },
      ],
      xpReward: 850,
      concept: "Operador not in",
      conceptExplanation: "'not in' é o oposto de 'in' — devolve True se o item NÃO está na coleção. Equivale a 'not (x in lista)' mas é mais legível. Use sempre que precisar checar exclusão.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "IP fora da blacklist. Pacote encaminhado ao próximo módulo de validação.",
      solution: "banidos = ['10.0.0.7', '10.0.0.99']\nip = '10.0.0.1'\nif ip not in banidos:\n    print('Conexao Liberada')",
    },
    {
      id: "py-cond-20",
      worldId: "vale-condicoes",
      title: "Normalização de Comando",
      description: "Compare o 'comando' contra 'EXIT' ignorando maiúsculas/minúsculas usando .lower(). Se for equivalente, imprima 'Saindo'.",
      narrative: "Operadores cansados digitam de qualquer jeito. Normalize o input antes de comparar — 'exit', 'Exit', 'EXIT' devem todos disparar o mesmo handler.",
      difficulty: "intermediario",
      setupCode: "comando = 'ExIt'",
      expectedOutput: "Saindo",
      testCode: "assert '.lower()' in code and output.strip() == 'Saindo'",
      starterCode: "comando = 'ExIt'\n# Compare comando.lower() com 'exit'\n",
      hints: [
        { text: "Use 'comando.lower() == \"exit\"' para comparação case-insensitive.", cost: 10 },
        { text: "if comando.lower() == 'exit':", cost: 20 },
      ],
      xpReward: 850,
      concept: "Comparação Case-Insensitive",
      conceptExplanation: "Para comparações que ignoram maiúsculas/minúsculas, normalize ambos os lados com .lower() (ou .upper()). É padrão em inputs de usuário, comandos de console e validação de strings que vêm de fontes externas.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Comando reconhecido independente do case. A sessão será encerrada graciosamente.",
      solution: "comando = 'ExIt'\nif comando.lower() == 'exit':\n    print('Saindo')",
    },
    {
      id: "py-cond-21",
      worldId: "vale-condicoes",
      title: "Conversão para Booleano",
      description: "Use bool() para converter o valor 'dado' (uma string vazia) e imprima o resultado. Em seguida, faça o mesmo com 'outro' (string 'ok'). Saída esperada: False / True.",
      narrative: "Para checar se um campo veio preenchido, converta-o explicitamente para booleano. Strings vazias viram False, strings com conteúdo viram True.",
      difficulty: "intermediario",
      setupCode: "dado = ''\noutro = 'ok'",
      expectedOutput: "False\nTrue",
      testCode: "assert 'bool(' in code and output.strip() == 'False\\nTrue'",
      starterCode: "dado = ''\noutro = 'ok'\n# Use bool(dado) e bool(outro)\n",
      hints: [
        { text: "bool('') é False; bool('texto') é True. Mesma regra de truthy/falsy.", cost: 10 },
        { text: "print(bool(dado))\nprint(bool(outro))", cost: 20 },
      ],
      xpReward: 870,
      concept: "Função bool()",
      conceptExplanation: "bool() força a conversão para booleano seguindo as regras de truthy/falsy. Útil quando você precisa de um True/False explícito (para serializar, logar, ou armazenar). Lembre: bool(0) → False, bool(1) → True, bool([]) → False.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Conversão explícita realizada. Os flags booleanos estão prontos para serialização.",
      solution: "dado = ''\noutro = 'ok'\nprint(bool(dado))\nprint(bool(outro))",
    },
    {
      id: "py-cond-22",
      worldId: "vale-condicoes",
      title: "Pelo Menos Um Alerta (any)",
      description: "A lista 'alertas' contém booleanos dos sensores. Use any() para verificar se PELO MENOS UM disparou. Se sim, imprima 'Alerta Ativo'.",
      narrative: "Quando qualquer sensor da rede dispara, o protocolo de defesa precisa ser ativado. Use any() para varrer todos de uma vez.",
      difficulty: "avancado",
      setupCode: "alertas = [False, False, True, False]",
      expectedOutput: "Alerta Ativo",
      testCode: "assert 'any(' in code and output.strip() == 'Alerta Ativo'",
      starterCode: "alertas = [False, False, True, False]\n# Use any(alertas) no if\n",
      hints: [
        { text: "any(iteravel) retorna True se pelo menos um elemento for verdadeiro.", cost: 10 },
        { text: "if any(alertas):\n    print('Alerta Ativo')", cost: 20 },
      ],
      xpReward: 900,
      concept: "Função any()",
      conceptExplanation: "any(iteravel) é o 'OR' coletivo — devolve True se qualquer item for truthy. É muito mais limpo do que escrever 'a or b or c or d'. Combine com generator expressions para checagens complexas: any(x > 100 for x in lista).",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Sensor 3 disparou. O protocolo de defesa foi acionado em todos os módulos.",
      solution: "alertas = [False, False, True, False]\nif any(alertas):\n    print('Alerta Ativo')",
    },
    {
      id: "py-cond-23",
      worldId: "vale-condicoes",
      title: "Todos os Sensores OK (all)",
      description: "A lista 'checks' contém o status dos sistemas críticos. Use all() para confirmar que TODOS estão OK. Se sim, imprima 'Sistema Pronto'. Caso contrário, 'Falha Detectada'.",
      narrative: "Para o lançamento do payload, TODOS os subsistemas precisam estar verdes simultaneamente. Use all() para checagem coletiva.",
      difficulty: "avancado",
      setupCode: "checks = [True, True, True, True]",
      expectedOutput: "Sistema Pronto",
      testCode: "assert 'all(' in code and output.strip() == 'Sistema Pronto'",
      starterCode: "checks = [True, True, True, True]\n# Use all(checks) no if\n",
      hints: [
        { text: "all(iteravel) retorna True só se TODOS os elementos forem verdadeiros.", cost: 10 },
        { text: "if all(checks):\n    print('Sistema Pronto')\nelse:\n    print('Falha Detectada')", cost: 20 },
      ],
      xpReward: 900,
      concept: "Função all()",
      conceptExplanation: "all(iteravel) é o 'AND' coletivo — devolve True só se TODOS forem truthy. Sobre lista vazia, retorna True (princípio matemático: a conjunção do vazio é trivialmente verdadeira). Cuidado com esse caso de borda.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Todos os subsistemas em verde. Autorização para a próxima fase concedida.",
      solution: "checks = [True, True, True, True]\nif all(checks):\n    print('Sistema Pronto')\nelse:\n    print('Falha Detectada')",
    },
    {
      id: "py-cond-24",
      worldId: "vale-condicoes",
      title: "Threshold de Temperatura",
      description: "Dada a 'temperatura', use if/elif/else. Se > 80 imprima 'CRITICO'. Se entre 50 e 80 (inclusive) imprima 'ALTO'. Se entre 20 e 49 imprima 'NORMAL'. Senão, 'BAIXO'.",
      narrative: "O reator opera dentro de janelas de temperatura. Classifique a leitura atual na categoria correta para acionar o protocolo de resfriamento adequado.",
      difficulty: "avancado",
      setupCode: "temperatura = 65",
      expectedOutput: "ALTO",
      testCode: "assert 'elif' in code and output.strip() == 'ALTO'",
      starterCode: "temperatura = 65\n# Use if/elif/elif/else para classificar\n",
      hints: [
        { text: "Lembre que o elif só roda se os ifs anteriores forem falsos — você pode encadear faixas.", cost: 15 },
        { text: "if temperatura > 80:\n    print('CRITICO')\nelif temperatura >= 50:\n    print('ALTO')\nelif temperatura >= 20:\n    print('NORMAL')\nelse:\n    print('BAIXO')", cost: 25 },
      ],
      xpReward: 950,
      concept: "Faixas com elif Encadeado",
      conceptExplanation: "Quando você quer classificar um valor em faixas, encadeie elifs em ordem decrescente (ou crescente) — assim você só precisa testar um lado da faixa em cada elif, já que o anterior já cortou. Cuidado para não inverter a ordem.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Temperatura classificada como ALTO. Protocolo de resfriamento ativado preventivamente.",
      solution: "temperatura = 65\nif temperatura > 80:\n    print('CRITICO')\nelif temperatura >= 50:\n    print('ALTO')\nelif temperatura >= 20:\n    print('NORMAL')\nelse:\n    print('BAIXO')",
    },
    {
      id: "py-cond-25",
      worldId: "vale-condicoes",
      title: "Pico da Telemetria",
      description: "Dada 'leituras = [12, 89, 34, 67, 91, 23]', use max() para encontrar o maior valor. Se for maior que 80, imprima 'PICO_PERIGOSO seguido de espaço e o valor'. Saída esperada: 'PICO_PERIGOSO 91'.",
      narrative: "Os logs registram dezenas de leituras por segundo. Identifique o pico do lote e dispare o alerta se ele cruzar o limite operacional.",
      difficulty: "avancado",
      setupCode: "leituras = [12, 89, 34, 67, 91, 23]",
      expectedOutput: "PICO_PERIGOSO 91",
      testCode: "assert 'max(' in code and output.strip() == 'PICO_PERIGOSO 91'",
      starterCode: "leituras = [12, 89, 34, 67, 91, 23]\n# Use max() e if no resultado\n",
      hints: [
        { text: "max(lista) devolve o maior valor. Use isso dentro do if.", cost: 15 },
        { text: "pico = max(leituras)\nif pico > 80:\n    print(f'PICO_PERIGOSO {pico}')", cost: 25 },
      ],
      xpReward: 950,
      concept: "max/min em Decisões",
      conceptExplanation: "max() e min() são built-ins que aceitam qualquer iterável. Combinados com condicionais, permitem decisões baseadas em extremos do dataset sem precisar de loops manuais. Existe a versão com key= para critérios customizados.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Pico 91 isolado e classificado como perigoso. Equipe de resposta alertada.",
      solution: "leituras = [12, 89, 34, 67, 91, 23]\npico = max(leituras)\nif pico > 80:\n    print(f'PICO_PERIGOSO {pico}')",
    },
    {
      id: "py-cond-26",
      worldId: "vale-condicoes",
      title: "Captura em Linha (Walrus)",
      description: "Use o operador walrus ':=' para atribuir 'len(dados)' à variável 'n' dentro do próprio if. Se n > 5, imprima f'Pacotes:{n}'. Saída esperada: 'Pacotes:7'.",
      narrative: "Otimize: capture o tamanho e teste-o na mesma expressão. O operador walrus reduz repetição em verificações com cálculo intermediário.",
      difficulty: "epico",
      setupCode: "dados = [1, 2, 3, 4, 5, 6, 7]",
      expectedOutput: "Pacotes:7",
      testCode: "assert ':=' in code and output.strip() == 'Pacotes:7'",
      starterCode: "dados = [1, 2, 3, 4, 5, 6, 7]\n# Use 'if (n := len(dados)) > 5:'\n",
      hints: [
        { text: "Sintaxe: if (variavel := expressao) condicao:", cost: 20 },
        { text: "if (n := len(dados)) > 5:\n    print(f'Pacotes:{n}')", cost: 30 },
      ],
      xpReward: 1100,
      concept: "Operador Walrus (:=)",
      conceptExplanation: "Introduzido no Python 3.8, ':=' permite atribuir E avaliar em uma única expressão. Útil quando você precisa do valor calculado tanto na condição quanto no corpo. Use com moderação — abuso prejudica legibilidade.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Atribuição em linha bem-sucedida. Código mais denso, leitura ainda clara.",
      solution: "dados = [1, 2, 3, 4, 5, 6, 7]\nif (n := len(dados)) > 5:\n    print(f'Pacotes:{n}')",
    },
    {
      id: "py-cond-27",
      worldId: "vale-condicoes",
      title: "Match com Cláusula Guard",
      description: "Use match/case com guard (if dentro do case). Dado 'codigo = 200', se for 200 com guard 'if codigo < 300', imprima 'OK'. Se 500+, 'ERRO_SERVIDOR'. Senão, 'OUTRO'.",
      narrative: "Códigos HTTP têm faixas com significado. Combine pattern matching com guards para refinar cada caso sem cair em elif aninhados.",
      difficulty: "epico",
      setupCode: "codigo = 200",
      expectedOutput: "OK",
      testCode: "assert 'match' in code and 'case' in code and 'if' in code and output.strip() == 'OK'",
      starterCode: "codigo = 200\n# Use 'case X if condicao:' para guards\n",
      hints: [
        { text: "Sintaxe: case valor if condicao_extra:", cost: 20 },
        { text: "match codigo:\n    case n if n < 300:\n        print('OK')\n    case n if n >= 500:\n        print('ERRO_SERVIDOR')\n    case _:\n        print('OUTRO')", cost: 30 },
      ],
      xpReward: 1150,
      concept: "Match com Guard",
      conceptExplanation: "Em pattern matching, você pode adicionar 'if' após o padrão (chamado 'guard') para refinar quando aquele case dispara. Combina o poder do match com a flexibilidade do if — ideal para classificar valores numéricos em faixas.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Resposta 200 classificada como sucesso. O fluxo HTTP segue normalmente.",
      solution: "codigo = 200\nmatch codigo:\n    case n if n < 300:\n        print('OK')\n    case n if n >= 500:\n        print('ERRO_SERVIDOR')\n    case _:\n        print('OUTRO')",
    },
    {
      id: "py-cond-28",
      worldId: "vale-condicoes",
      title: "Match Múltiplos Padrões",
      description: "Use match/case com o operador '|' para juntar padrões. Para 'metodo' = 'GET' OU 'HEAD', imprima 'leitura'. Para 'POST' OU 'PUT' OU 'PATCH', 'escrita'. Senão, 'outro'.",
      narrative: "Verbos HTTP se agrupam em famílias de comportamento. Use a sintaxe alternativa do match para tratar múltiplos casos com a mesma resposta.",
      difficulty: "epico",
      setupCode: "metodo = 'POST'",
      expectedOutput: "escrita",
      testCode: "assert '|' in code and 'match' in code and output.strip() == 'escrita'",
      starterCode: "metodo = 'POST'\n# Use 'case A | B | C:' para múltiplos valores no mesmo case\n",
      hints: [
        { text: "case 'A' | 'B': agrupa valores que devem disparar o mesmo bloco.", cost: 20 },
        { text: "match metodo:\n    case 'GET' | 'HEAD':\n        print('leitura')\n    case 'POST' | 'PUT' | 'PATCH':\n        print('escrita')\n    case _:\n        print('outro')", cost: 30 },
      ],
      xpReward: 1200,
      concept: "Match com OR (|)",
      conceptExplanation: "O '|' dentro de um case permite agrupar valores que devem disparar a mesma resposta. Muito mais limpo que repetir o mesmo bloco em vários cases. Funciona com strings, números e até com padrões mais complexos.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Verbo classificado como operação de escrita. Validação adicional ativada para o payload.",
      solution: "metodo = 'POST'\nmatch metodo:\n    case 'GET' | 'HEAD':\n        print('leitura')\n    case 'POST' | 'PUT' | 'PATCH':\n        print('escrita')\n    case _:\n        print('outro')",
    },
    {
      id: "py-cond-29",
      worldId: "vale-condicoes",
      title: "Curto-Circuito Defensivo",
      description: "Imprima 'usuario' SE ele não for None E tiver mais de 3 caracteres. Use 'and' para curto-circuitar (a segunda condição só é avaliada se a primeira passar). Saída esperada: 'admin'.",
      narrative: "Para evitar AttributeError ao chamar len() em None, encadeie as checagens. O Python avalia 'and' da esquerda para a direita e para no primeiro False.",
      difficulty: "avancado",
      setupCode: "usuario = 'admin'",
      expectedOutput: "admin",
      testCode: "assert ' and ' in code and 'is not None' in code and output.strip() == 'admin'",
      starterCode: "usuario = 'admin'\n# if usuario is not None and len(usuario) > 3:\n",
      hints: [
        { text: "Em 'A and B', se A for False, B nem é avaliado — isso evita erros em B.", cost: 15 },
        { text: "if usuario is not None and len(usuario) > 3:\n    print(usuario)", cost: 25 },
      ],
      xpReward: 1000,
      concept: "Short-Circuit Evaluation",
      conceptExplanation: "Operadores 'and' e 'or' avaliam preguiçosamente da esquerda para a direita. Em 'A and B', se A já é False, B nem roda. Em 'A or B', se A já é True, B nem roda. Use isso para checagens defensivas: primeiro o teste seguro, depois o que poderia falhar.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Validação encadeada sem disparar exceção. Operador autenticado com proteção total.",
      solution: "usuario = 'admin'\nif usuario is not None and len(usuario) > 3:\n    print(usuario)",
    },
    {
      id: "py-cond-30",
      worldId: "vale-condicoes",
      title: "Identificador de Protocolo",
      description: "Dada a 'url', use .startswith() para detectar o protocolo. Se começar com 'https://', imprima 'SEGURO'. Se com 'http://', 'INSEGURO'. Senão, 'DESCONHECIDO'.",
      narrative: "O scanner precisa decidir como tratar cada URL — sessões seguras seguem por um pipeline, inseguras por outro. Identifique o prefixo antes de processar.",
      difficulty: "avancado",
      setupCode: "url = 'https://corphq.io/api'",
      expectedOutput: "SEGURO",
      testCode: "assert 'startswith' in code and output.strip() == 'SEGURO'",
      starterCode: "url = 'https://corphq.io/api'\n# Use url.startswith('https://') e elif para 'http://'\n",
      hints: [
        { text: "A ordem importa: teste 'https://' ANTES de 'http://' (senão o segundo casaria primeiro).", cost: 15 },
        { text: "if url.startswith('https://'):\n    print('SEGURO')\nelif url.startswith('http://'):\n    print('INSEGURO')\nelse:\n    print('DESCONHECIDO')", cost: 25 },
      ],
      xpReward: 1050,
      concept: "startswith / endswith",
      conceptExplanation: "str.startswith(prefixo) e str.endswith(sufixo) retornam booleano testando início/fim da string. Mais idiomático e seguro que slicing manual ('s[:5] == \"https\"'). Aceitam tupla para testar vários: 'url.startswith((\"http://\", \"https://\"))'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "URL classificada como segura. Pipeline criptografado ativado para essa sessão.",
      solution: "url = 'https://corphq.io/api'\nif url.startswith('https://'):\n    print('SEGURO')\nelif url.startswith('http://'):\n    print('INSEGURO')\nelse:\n    print('DESCONHECIDO')",
    },
  ],
};
