import { World } from "../types";

export const VALE_CONDICOES_WORLD: World = {
  id: "vale-condicoes",
  title: "Nó de Roteamento",
  subtitle: "Desvios e Bifurcações de Dados",
  icon: "git-branch",
  color: "#22C55E",
  bgImage: "/assets/images/worlds/routing_node.png",
  lore: "No Nó de Roteamento, o Sistema Central testa sua lógica. O código não flui apenas em linha reta; ele deve decidir qual trilha seguir baseado em condições pré-definidas.",
  unlockRequirement: 1500,
  challenges: [
    {
      id: "py-cond-01",
      worldId: "vale-condicoes",
      title: "Firewall de Acesso",
      description: "Use o operador if para verificar se a idade é maior ou igual a 18. Se for, projete 'Acesso Permitido'.",
      narrative: "Um firewall primário protege os servidores internos. Apenas conexões com a 'Idade de Acesso' correta podem passar. Crie o script validador.",
      difficulty: "iniciante",
      setupCode: "idade = 20",
      expectedOutput: "Acesso Permitido",
      testCode: "assert output.strip() == 'Acesso Permitido'",
      starterCode: "idade = 20\n# Escreva seu script de validação aqui\n",
      hints: [
        { text: "A estrutura começa com if condição: seguido de um novo parágrafo.", cost: 10 },
        { text: "O print precisa estar um passo à frente (indentado) para pertencer ao if.", cost: 20 },
        { text: "if idade >= 18:\n    print('Acesso Permitido')", cost: 30 },
      ],
      xpReward: 200,
      concept: "O Validador Lógico 'if'",
      conceptExplanation: "O 'if' (que significa 'se' em inglês) ensina o computador a tomar decisões sozinho, baseando-se em uma condição que você define.\n\nPor exemplo:\nif idade >= 18:\n    print('Entrada Liberada')\n\nIsso diz ao programa: 'Se a idade for maior ou igual a 18, execute o comando abaixo'. Tudo que estiver indentado (com espaços) abaixo do 'if' só acontecerá se a condição for verdadeira.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso liberado. Você fez o primeiro bypass estrutural na rede.",
      solution: "if idade >= 18:\n    print('Acesso Permitido')",
    },
    {
      id: "py-cond-02",
      worldId: "vale-condicoes",
      title: "Gerenciamento de Energia",
      description: "Use if e else. Se a energia for maior que 50, projete 'Correr'. Caso contrário, projete 'Descansar'.",
      narrative: "Para otimizar o processamento do Node, você deve balancear os recursos. Se a bateria estiver alta, o sistema acelera; se baixa, entra em hibernação.",
      difficulty: "iniciante",
      setupCode: "energia = 30",
      expectedOutput: "Descansar",
      testCode: "assert output.strip() == 'Descansar'",
      starterCode: "energia = 30\n# Equilibre as escolhas com if e else\n",
      hints: [
        { text: "O else (caso contrário) não precisa de uma nova condição.", cost: 10 },
        { text: "Lembre-se de manter a indentação em ambos os caminhos.", cost: 20 },
        { text: "if energia > 50:\n    print('Correr')\nelse:\n    print('Descansar')", cost: 30 },
      ],
      xpReward: 250,
      concept: "Dualidade de Caminhos (if/else)",
      conceptExplanation: "Enquanto o 'if' diz o que fazer se algo for verdade, o 'else' (que significa 'senão') diz o que fazer se for mentira. Ele cria um caminho alternativo para o código!\n\nPor exemplo:\nif chover:\n    print('Leve o guarda-chuva')\nelse:\n    print('Leve óculos de sol')\n\nO computador sempre vai escolher um dos dois caminhos.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Balanceamento restaurado. Seus scripts agora lidam com ambos os fluxos da matriz.",
      solution: "if energia > 50:\n    print('Correr')\nelse:\n    print('Descansar')",
    },
    {
      id: "py-cond-03",
      worldId: "vale-condicoes",
      title: "Níveis de Acesso Multi-Layer",
      description: "Use if e elif. Se 'nivel' for 1, printe 'Acesso Baixo'. Se for 2, 'Acesso Medio'. Se for 3, 'Acesso Alto'.",
      narrative: "O sistema de segurança possui várias camadas. Você deve identificar em qual camada seu token de acesso se encaixa para abrir as portas corretas.",
      difficulty: "intermediario",
      setupCode: "nivel = 2",
      expectedOutput: "Acesso Medio",
      testCode: "assert output.strip() == 'Acesso Medio'",
      starterCode: "nivel = 2\n# Use elif para verificar multiplas condições\n",
      hints: [
        { text: "O elif é usado para verificar uma nova condição caso a primeira seja falsa.", cost: 10 },
        { text: "Você pode ter vários elifs entre o if e o else.", cost: 20 },
        { text: "if nivel == 1:\n    print('Acesso Baixo')\nelif nivel == 2:\n    print('Acesso Medio')", cost: 30 },
      ],
      xpReward: 300,
      concept: "Múltiplas Condições (elif)",
      conceptExplanation: "O `elif` (abreviação de 'else if') permite que você verifique várias condições em sequência. O computador vai testando uma por uma até achar a primeira que seja verdade.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Acesso médio garantido. Você agora tem permissão para visualizar os logs dos setores internos.",
      solution: "if nivel == 1:\n    print('Acesso Baixo')\nelif nivel == 2:\n    print('Acesso Medio')\nelse:\n    print('Acesso Alto')",
    },
    {
      id: "py-cond-04",
      worldId: "vale-condicoes",
      title: "Verificação de Duplo Fator",
      description: "Use o operador 'and' no if. Se 'has_token' for True E 'has_pass' for True, printe 'Sistema Desbloqueado'.",
      narrative: "Para desbloquear o Core, não basta um token; você também precisa da senha mestre. Verifique se ambos os requisitos foram atendidos.",
      difficulty: "intermediario",
      setupCode: "has_token = True\nhas_pass = True",
      expectedOutput: "Sistema Desbloqueado",
      testCode: "assert output.strip() == 'Sistema Desbloqueado'",
      starterCode: "has_token = True\nhas_pass = True\n# Use 'and' para verificar as duas condições juntas\n",
      hints: [
        { text: "O operador 'and' retorna True apenas se AMBOS os lados forem verdadeiros.", cost: 10 },
        { text: "Sintaxe: if condicao1 and condicao2:", cost: 20 },
        { text: "if has_token and has_pass:\n    print('Sistema Desbloqueado')", cost: 30 },
      ],
      xpReward: 350,
      concept: "Operadores Lógicos (and)",
      conceptExplanation: "Operadores lógicos permitem combinar condições. O `and` (e) exige que todas as partes sejam verdadeiras para que o resultado final seja verdade.\n\nExemplo: Se você tem ingresso E tem documento, então pode entrar no show.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Autenticação de dois fatores concluída. O bloqueio do Core foi removido.",
      solution: "if has_token and has_pass:\n    print('Sistema Desbloqueado')",
    },
    {
      id: "py-cond-05",
      worldId: "vale-condicoes",
      title: "Protocolo de Redundância",
      description: "Use o operador 'or'. Se 'servidor_a' for True OU 'servidor_b' for True, printe 'Conexão Estável'.",
      narrative: "Para manter o sistema online, precisamos que ao menos um dos dois servidores de redundância esteja ativo. Verifique a disponibilidade da rede.",
      difficulty: "intermediario",
      setupCode: "servidor_a = False\nservidor_b = True",
      expectedOutput: "Conexão Estável",
      testCode: "assert output.strip() == 'Conexão Estável'",
      starterCode: "servidor_a = False\nservidor_b = True\n# Verifique se pelo menos um servidor está ativo\n",
      hints: [
        { text: "O operador 'or' retorna True se PELO MENOS UM dos lados for verdadeiro.", cost: 10 },
        { text: "if servidor_a or servidor_b:", cost: 20 },
      ],
      xpReward: 380,
      concept: "Operadores Lógicos (or)",
      conceptExplanation: "O operador `or` (ou) é usado quando você tem várias opções e apenas uma delas precisa ser verdade para que tudo funcione. Se qualquer uma das condições for verdadeira, o bloco de código será executado.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Redundância ativada. O tráfego foi redirecionado para o servidor B. A conexão permanece estável.",
      solution: "if servidor_a or servidor_b:\n    print('Conexão Estável')",
    },
    {
      id: "py-cond-06",
      worldId: "vale-condicoes",
      title: "Inversão de Lógica",
      description: "Use o operador 'not'. Se NÃO houver 'virus', printe 'Sistema Limpo'.",
      narrative: "Às vezes, a melhor defesa é verificar a ausência de ameaças. Inverta a lógica do scanner para confirmar a integridade dos arquivos.",
      difficulty: "intermediario",
      setupCode: "virus = False",
      expectedOutput: "Sistema Limpo",
      testCode: "assert 'not' in code and output.strip() == 'Sistema Limpo'",
      starterCode: "virus = False\n# Use 'not' para verificar se NÃO há vírus\n",
      hints: [
        { text: "O operador 'not' inverte o valor booleano: not True vira False.", cost: 10 },
        { text: "if not virus:", cost: 20 },
      ],
      xpReward: 400,
      concept: "Operador Lógico (not)",
      conceptExplanation: "O `not` (não) inverte uma condição. Se algo é falso, `not algo` vira verdadeiro. É como dizer: 'Se não estiver chovendo, eu vou sair'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Varredura negativa para ameaças. O sistema está operando em modo seguro.",
      solution: "if not virus:\n    print('Sistema Limpo')",
    },
    {
      id: "py-cond-07",
      worldId: "vale-condicoes",
      title: "Scanner de Range de Portas",
      description: "Verifique se a 'porta' está entre 1024 e 65535 (inclusive). Se sim, printe 'Porta de Usuario'.",
      narrative: "As portas do sistema são divididas em faixas. Portas altas são reservadas para aplicações de usuário. Identifique se o tráfego está vindo de uma dessas portas.",
      difficulty: "intermediario",
      setupCode: "porta = 8080",
      expectedOutput: "Porta de Usuario",
      testCode: "assert ('>=' in code or '<=' in code) and output.strip() == 'Porta de Usuario'",
      starterCode: "porta = 8080\n# Verifique se a porta está no intervalo [1024, 65535]\n",
      hints: [
        { text: "Você pode usar duas condições com 'and' ou a sintaxe simplificada: min <= x <= max.", cost: 10 },
        { text: "if porta >= 1024 and porta <= 65535:", cost: 20 },
      ],
      xpReward: 420,
      concept: "Comparações em Cadeia",
      conceptExplanation: "Python permite verificar se um número está entre dois valores de forma muito elegante, como na matemática: `10 < x < 20`. Isso torna o código mais legível e fácil de entender.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Porta identificada como tráfego de aplicação de usuário. Pacotes autorizados para processamento.",
      solution: "if 1024 <= porta <= 65535:\n    print('Porta de Usuario')",
    },
    {
      id: "py-cond-08",
      worldId: "vale-condicoes",
      title: "Lista Branca de Acesso",
      description: "Verifique se o 'usuario' está na lista 'lista_branca' usando o operador 'in'. Se estiver, printe 'Acesso VIP'.",
      narrative: "O firewall possui uma lista de operadores de elite. Verifique se o usuário atual possui privilégios administrativos elevados.",
      difficulty: "intermediario",
      setupCode: "lista_branca = ['Neo', 'Trinity', 'Morpheus']\nusuario = 'Trinity'",
      expectedOutput: "Acesso VIP",
      testCode: "assert ' in ' in code and output.strip() == 'Acesso VIP'",
      starterCode: "lista_branca = ['Neo', 'Trinity', 'Morpheus']\nusuario = 'Trinity'\n# Verifique se o usuário está na lista\n",
      hints: [
        { text: "O operador 'in' verifica se um item existe dentro de uma lista.", cost: 10 },
        { text: "if usuario in lista_branca:", cost: 20 },
      ],
      xpReward: 450,
      concept: "Operador de Associação (in)",
      conceptExplanation: "O operador `in` (em) é extremamente poderoso. Ele percorre uma lista e te diz se o que você procura está lá dentro. É como procurar um nome em uma lista de convidados.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Credenciais de elite confirmadas. Você agora tem acesso total ao Nó de Roteamento.",
      solution: "if usuario in lista_branca:\n    print('Acesso VIP')",
    },
    {
      id: "py-cond-09",
      worldId: "vale-condicoes",
      title: "Detector de Anomalias",
      description: "Use o operador '!='. Se o 'sinal' for diferente de 'ERRO', printe 'Transmissao Limpa'.",
      narrative: "Um receptor monitora o canal de comunicação 24/7. Qualquer sinal que não seja explicitamente um 'ERRO' deve ser considerado válido para análise.",
      difficulty: "intermediario",
      setupCode: "sinal = 'OK'",
      expectedOutput: "Transmissao Limpa",
      testCode: "assert '!=' in code and output.strip() == 'Transmissao Limpa'",
      starterCode: "sinal = 'OK'\n# Use '!=' para verificar diferença\n",
      hints: [
        { text: "O operador '!=' significa 'diferente de'.", cost: 10 },
        { text: "if sinal != 'ERRO':", cost: 20 },
        { text: "if sinal != 'ERRO':\n    print('Transmissao Limpa')", cost: 30 },
      ],
      xpReward: 470,
      concept: "Operador de Diferença (!=)",
      conceptExplanation: "Enquanto `==` verifica se dois valores são iguais, `!=` verifica se eles são diferentes. É útil para detectar mudanças de estado ou identificar anomalias.\n\nExemplo:\nif status != 'offline':\n    print('Sistema ativo')\n\nO bloco só executa se o status NÃO for 'offline'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Canal limpo. O receptor confirma que nenhum ruído anormal foi captado.",
      solution: "if sinal != 'ERRO':\n    print('Transmissao Limpa')",
    },
    {
      id: "py-cond-10",
      worldId: "vale-condicoes",
      title: "Analisador de Paridade",
      description: "Use o operador módulo (%). Se 'porta' for par, printe 'Porta Par'. Caso contrário, 'Porta Impar'.",
      narrative: "O Sistema separa o tráfego entre canais pares e ímpares para balanceamento de carga. Identifique a paridade da porta para roteá-la corretamente.",
      difficulty: "intermediario",
      setupCode: "porta = 8080",
      expectedOutput: "Porta Par",
      testCode: "assert '%' in code and output.strip() == 'Porta Par'",
      starterCode: "porta = 8080\n# Use o operador % para verificar paridade\n",
      hints: [
        { text: "O operador % retorna o resto da divisão. Um número é par se 'numero % 2' for igual a 0.", cost: 10 },
        { text: "if porta % 2 == 0:", cost: 20 },
        { text: "if porta % 2 == 0:\n    print('Porta Par')\nelse:\n    print('Porta Impar')", cost: 30 },
      ],
      xpReward: 500,
      concept: "Módulo e Paridade",
      conceptExplanation: "O operador `%` (módulo) devolve o resto de uma divisão. Por exemplo, 10 % 2 é 0, mas 11 % 2 é 1.\n\nIsso é a forma clássica de verificar se um número é par (resto 0) ou ímpar (resto 1):\nif n % 2 == 0:\n    print('par')",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Tráfego direcionado para o canal par. O balanceador de carga registra a operação.",
      solution: "if porta % 2 == 0:\n    print('Porta Par')\nelse:\n    print('Porta Impar')",
    },
    {
      id: "py-cond-11",
      worldId: "vale-condicoes",
      title: "Comparador de Hash Exato",
      description: "Compare o 'hash_recebido' com 'hash_oficial'. Se forem idênticos, printe 'Integridade OK'. Strings em Python diferenciam maiúsculas de minúsculas.",
      narrative: "Um pacote chegou criptografado. Para validar sua autenticidade, compare exatamente o hash recebido com o hash oficial gravado no servidor.",
      difficulty: "intermediario",
      setupCode: "hash_oficial = 'a1B2c3'\nhash_recebido = 'a1B2c3'",
      expectedOutput: "Integridade OK",
      testCode: "assert '==' in code and output.strip() == 'Integridade OK'",
      starterCode: "hash_oficial = 'a1B2c3'\nhash_recebido = 'a1B2c3'\n# Compare os dois hashes exatamente\n",
      hints: [
        { text: "Strings podem ser comparadas diretamente com '=='.", cost: 10 },
        { text: "if hash_recebido == hash_oficial:", cost: 20 },
      ],
      xpReward: 520,
      concept: "Comparação de Strings",
      conceptExplanation: "Em Python, strings também podem ser comparadas com `==` e `!=`. A comparação considera cada caractere e diferencia maiúsculas de minúsculas: 'Senha' é diferente de 'senha'.\n\nIsso é fundamental em sistemas de autenticação, onde uma única letra trocada já invalida a operação.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Hashes coincidem. O pacote foi assinado por uma fonte confiável.",
      solution: "if hash_recebido == hash_oficial:\n    print('Integridade OK')",
    },
    {
      id: "py-cond-12",
      worldId: "vale-condicoes",
      title: "Camadas de Permissão Aninhadas",
      description: "Use if dentro de if. Se 'autenticado' for True, verifique 'nivel'. Se nível for 5, printe 'Acesso Root'. Caso contrário, 'Acesso Limitado'.",
      narrative: "A sala dos servidores tem dois portões: o primeiro valida a autenticação básica, e o segundo verifica o nível de privilégio. Modele essa lógica em camadas.",
      difficulty: "avancado",
      setupCode: "autenticado = True\nnivel = 5",
      expectedOutput: "Acesso Root",
      testCode: "assert output.strip() == 'Acesso Root'",
      starterCode: "autenticado = True\nnivel = 5\n# Aninhe um if dentro de outro if\n",
      hints: [
        { text: "Você pode escrever um novo 'if' dentro do bloco indentado de outro 'if'.", cost: 10 },
        { text: "Cada nível de aninhamento exige mais um nível de indentação.", cost: 20 },
        { text: "if autenticado:\n    if nivel == 5:\n        print('Acesso Root')\n    else:\n        print('Acesso Limitado')", cost: 30 },
      ],
      xpReward: 600,
      concept: "Condicionais Aninhadas",
      conceptExplanation: "Você pode colocar uma condição dentro de outra. O segundo `if` só será avaliado se o primeiro for verdadeiro. Isso permite criar fluxos de decisão em múltiplas camadas.\n\nMas cuidado: aninhar demais deixa o código difícil de ler. Sempre que possível, prefira combinar condições com `and` em uma única linha.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Privilégio máximo concedido. Você está dentro do núcleo do Sistema Central.",
      solution: "if autenticado:\n    if nivel == 5:\n        print('Acesso Root')\n    else:\n        print('Acesso Limitado')",
    },
    {
      id: "py-cond-13",
      worldId: "vale-condicoes",
      title: "Filtro Composto de Tráfego",
      description: "Combine 'and' e 'or'. Se ('admin' for True OU 'vip' for True) E 'banido' for False, printe 'Trafego Permitido'.",
      narrative: "O firewall principal aceita conexões de admins ou VIPs, mas qualquer usuário banido é bloqueado independentemente do seu status. Codifique essa regra.",
      difficulty: "avancado",
      setupCode: "admin = False\nvip = True\nbanido = False",
      expectedOutput: "Trafego Permitido",
      testCode: "assert ' and ' in code and ' or ' in code and output.strip() == 'Trafego Permitido'",
      starterCode: "admin = False\nvip = True\nbanido = False\n# Combine 'and', 'or' e parênteses\n",
      hints: [
        { text: "Use parênteses para agrupar a parte do 'or' e separá-la do 'and'.", cost: 15 },
        { text: "if (admin or vip) and not banido:", cost: 25 },
      ],
      xpReward: 650,
      concept: "Combinação de Operadores Lógicos",
      conceptExplanation: "Você pode combinar `and`, `or` e `not` em uma mesma expressão. Para evitar ambiguidade, use parênteses: o que está dentro deles é avaliado primeiro, exatamente como na matemática.\n\nExemplo: `(a or b) and not c` significa: 'pelo menos um entre a e b deve ser verdade, E c deve ser falso'.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Pacote VIP autenticado e nenhum bloqueio detectado. Tráfego encaminhado.",
      solution: "if (admin or vip) and not banido:\n    print('Trafego Permitido')",
    },
    {
      id: "py-cond-14",
      worldId: "vale-condicoes",
      title: "Roteamento Compacto",
      description: "Use o operador ternário. Atribua à variável 'status' o valor 'Online' se 'ping' for menor que 100, senão 'Offline'. Depois, printe 'status'.",
      narrative: "Em redes de alta performance, cada linha de código conta. Reduza sua decisão lógica a uma única linha usando a expressão condicional do Python.",
      difficulty: "avancado",
      setupCode: "ping = 50",
      expectedOutput: "Online",
      testCode: "assert 'if' in code and 'else' in code and output.strip() == 'Online'",
      starterCode: "ping = 50\n# Use o ternário: valor_se_verdadeiro if condicao else valor_se_falso\nstatus = \n",
      hints: [
        { text: "A sintaxe é: <valor_true> if <condicao> else <valor_false>", cost: 15 },
        { text: "status = 'Online' if ping < 100 else 'Offline'", cost: 25 },
      ],
      xpReward: 700,
      concept: "Operador Ternário",
      conceptExplanation: "Python permite escrever um if/else inteiro em uma única linha quando o objetivo é simplesmente atribuir um valor.\n\nSintaxe:\nresultado = valor_A if condicao else valor_B\n\nLê-se: 'resultado recebe valor_A se condicao for verdadeira, senão recebe valor_B'. Útil para deixar o código mais limpo em decisões simples.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Latência baixa confirmada. O nó está online e respondendo dentro da janela aceitável.",
      solution: "status = 'Online' if ping < 100 else 'Offline'\nprint(status)",
    },
    {
      id: "py-cond-15",
      worldId: "vale-condicoes",
      title: "Sniffer de Tipos",
      description: "Use 'isinstance()' para verificar se 'dado' é do tipo int. Se for, printe 'Numero Inteiro'. Caso contrário, 'Tipo Desconhecido'.",
      narrative: "Pacotes desconhecidos chegam pelo canal aberto. Antes de processá-los, é vital identificar o tipo do dado para evitar exceções fatais no Sistema Central.",
      difficulty: "avancado",
      setupCode: "dado = 42",
      expectedOutput: "Numero Inteiro",
      testCode: "assert 'isinstance' in code and output.strip() == 'Numero Inteiro'",
      starterCode: "dado = 42\n# Use isinstance(variavel, tipo)\n",
      hints: [
        { text: "isinstance() recebe dois argumentos: a variável e o tipo desejado (int, str, list...).", cost: 15 },
        { text: "if isinstance(dado, int):", cost: 25 },
      ],
      xpReward: 750,
      concept: "Verificação de Tipo (isinstance)",
      conceptExplanation: "A função `isinstance(valor, tipo)` retorna True se o valor for do tipo informado. É a forma segura e oficial de verificar tipos em Python.\n\nExemplos de tipos comuns: int (inteiro), float (decimal), str (texto), list (lista), bool (booleano).\n\nUse isso para validar entradas antes de operar sobre elas — é uma defesa básica contra erros inesperados.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Pacote tipado com sucesso. O dado foi encaminhado ao módulo de aritmética.",
      solution: "if isinstance(dado, int):\n    print('Numero Inteiro')\nelse:\n    print('Tipo Desconhecido')",
    },
    {
      id: "py-cond-16",
      worldId: "vale-condicoes",
      title: "Despachador de Comandos",
      description: "Use a estrutura match/case. Para 'comando' = 'start', printe 'Iniciando'. Para 'stop', 'Parando'. Para 'reboot', 'Reiniciando'. Para qualquer outro, 'Comando Desconhecido'.",
      narrative: "O console do Sistema Central recebe comandos textuais. Implemente um despachador que rotule cada instrução à ação correspondente, usando o pattern matching nativo do Python.",
      difficulty: "epico",
      setupCode: "comando = 'reboot'",
      expectedOutput: "Reiniciando",
      testCode: "assert 'match' in code and 'case' in code and output.strip() == 'Reiniciando'",
      starterCode: "comando = 'reboot'\n# Use match/case para despachar o comando\n",
      hints: [
        { text: "A sintaxe é: match variavel: seguido de blocos 'case valor:'.", cost: 20 },
        { text: "Use 'case _:' como caso padrão (default).", cost: 30 },
        { text: "match comando:\n    case 'start':\n        print('Iniciando')\n    case 'stop':\n        print('Parando')\n    case 'reboot':\n        print('Reiniciando')\n    case _:\n        print('Comando Desconhecido')", cost: 40 },
      ],
      xpReward: 900,
      concept: "Pattern Matching (match/case)",
      conceptExplanation: "A partir do Python 3.10, a estrutura `match/case` permite comparar uma variável contra múltiplos padrões de forma elegante — substituindo cadeias longas de `if/elif/else`.\n\nSintaxe básica:\nmatch valor:\n    case 'a':\n        ...\n    case 'b':\n        ...\n    case _:\n        ... # caso padrão\n\nO underline `_` representa qualquer valor que não bateu com os anteriores. É a forma moderna e limpa de fazer despacho por valor.",
      successNpc: "Proxy-01, Validador de Pacotes",
      successAvatar: "/avatars/golem.webp",
      successStory: "Despachador operacional. O Sistema Central agora responde a todos os comandos do console com latência mínima.",
      solution: "match comando:\n    case 'start':\n        print('Iniciando')\n    case 'stop':\n        print('Parando')\n    case 'reboot':\n        print('Reiniciando')\n    case _:\n        print('Comando Desconhecido')",
    },
  ],
};
