import { World } from "../types";

export const VILA_VARIAVEIS_WORLD: World = {
  id: "vila-variaveis",
  title: "Terminal Alpha",
  subtitle: "Conexão Estabelecida",
  icon: "anchor",
  color: "#0EA5E9",
  bgImage: "/assets/images/worlds/terminal_alpha.png",
  lore: "O sistema de segurança isolou o núcleo da cidade (Core). Aqui no Terminal Alpha, você deve inicializar o Protocolo de Alocação: definir variáveis e manipular a memória local para dar o primeiro bypass no firewall primário.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-01",
      worldId: "vila-variaveis",
      title: "Ping de Reconhecimento",
      description: "Use print() para enviar a string 'Ola, Python!' ao terminal.",
      narrative: "Para estabelecer handshake com o Core, você deve emitir um sinal de reconhecimento. O comando print() projeta sua assinatura digital no log do sistema.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Ola, Python!",
      testCode: "assert output.strip() == 'Ola, Python!'",
      starterCode: "# Envie seu primeiro ping para o console\n",
      hints: [
        { text: "A instrução print() exibe dados na saída padrão do terminal.", cost: 10 },
        { text: "Strings (textos) devem ser encapsuladas em aspas simples ou duplas.", cost: 20 },
        { text: "Tente: print('Ola, Python!')", cost: 30 },
      ],
      xpReward: 100,
      concept: "Comando de Saída (print)",
      conceptExplanation: "Imagine o print() como um megafone ou uma tela de projeção. Tudo que você coloca dentro dos parênteses do print() será exibido na tela (o Console) para que você ou outros operadores possam ler.\n\nPor exemplo:\nprint('Acesso Liberado!')\n\nFará com que essa frase apareça na tela do terminal.",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Ping recebido. A porta de entrada registrou sua presença na rede. O acesso ao terminal local foi garantido.",
    },
    {
      id: "py-02",
      worldId: "vila-variaveis",
      title: "Alocação de Memória",
      description: "Declare uma variável chamada nome com o valor 'Python' e imprima-a no console.",
      narrative: "Um Hacker não manipula apenas dados brutos, mas sim endereços nomeados na RAM. Guarde o identificador do sistema em uma variável e leia o seu conteúdo.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Python",
      testCode: "assert 'nome' in locals() and nome == 'Python' and output.strip() == 'Python'",
      starterCode: "# Aloque os dados e exiba o resultado\n",
      hints: [
        { text: "Variáveis são espaços na memória: nome = valor.", cost: 10 },
        { text: "Para exibir os dados, passe o nome da variável no comando print(), sem aspas.", cost: 20 },
        { text: "nome = 'Python'\nprint(nome)", cost: 30 },
      ],
      xpReward: 120,
      concept: "Endereçamento de Dados (Variáveis)",
      conceptExplanation: "Imagine uma variável como uma 'caixa' etiquetada onde você guarda uma informação para usar depois. Para criar uma, basta dar um nome para a etiqueta e usar o sinal '=' para guardar o valor dentro.\n\nPor exemplo:\nidade = 25\n\nIsso cria uma caixa chamada 'idade' guardando o número 25. Depois, você pode usar esse nome no código e o computador lembrará o que tem lá dentro!",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Bloco de memória alocado com sucesso. O sistema agora reconhece o identificador 'Python' no seu escopo local.",
    },
    {
      id: "py-03",
      worldId: "vila-variaveis",
      title: "Sincronização de Threads",
      description: "A variável a tem valor 5, e b tem valor 10. Imprima a soma desses dois valores.",
      narrative: "Dois pacotes de processamento criptografados chegaram à sua thread. Some suas cargas numéricas para gerar a chave de acesso ao próximo Node.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "15",
      testCode: "assert a == 5 and b == 10 and output.strip() == '15'",
      starterCode: "# Processe a soma de a e b\na = 5\nb = 10\n",
      hints: [
        { text: "Use o operador + para somar valores inteiros.", cost: 10 },
        { text: "O resultado da soma deve ser passado para dentro do print().", cost: 20 },
        { text: "print(a + b)", cost: 30 },
      ],
      xpReward: 150,
      concept: "Processamento Aritmético (Operadores)",
      conceptExplanation: "Você pode usar o Python como uma super-calculadora. O símbolo '+' soma, '-' subtrai, '*' multiplica e '/' divide. Você pode usar essas operações direto com suas variáveis!\n\nPor exemplo, se:\na = 10\nb = 5\n\nEntão escrever print(a + b) vai mostrar 15 na tela.",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Sincronização concluída! A chave numérica estabilizou a conexão. O Node Primário está online. Você está pronto para avançar na rede.",
    },
    {
      id: "py-04",
      worldId: "vila-variaveis",
      title: "Fusão de Protocolos",
      description: "Concatene a variável 'base' com a variável 'versao' e imprima o resultado. O resultado esperado é 'Python3'.",
      narrative: "Para atualizar seu software de intrusão, você deve unir o nome do software com o número da versão em uma única string de comando.",
      difficulty: "iniciante",
      setupCode: "base = 'Python'\nversao = '3'",
      expectedOutput: "Python3",
      testCode: "assert base == 'Python' and versao == '3' and output.strip() == 'Python3'",
      starterCode: "base = 'Python'\nversao = '3'\n# Una base e versao no comando print\n",
      hints: [
        { text: "Você pode unir duas strings usando o operador +.", cost: 10 },
        { text: "Exemplo: 'Cyber' + 'Punk' resulta em 'CyberPunk'.", cost: 20 },
        { text: "print(base + versao)", cost: 30 },
      ],
      xpReward: 160,
      concept: "Concatenação de Strings",
      conceptExplanation: "Concatenação é o termo técnico para 'grudar' uma string na outra. No Python, usamos o sinal de + para unir textos, como se estivéssemos montando um quebra-cabeça de dados.\n\nExemplo:\nnome = 'Ciber' + 'Operador'\nprint(nome)  # Mostra CiberOperador",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Fusão completa. O protocolo Python3 foi carregado no seu buffer de execução.",
    },
    {
      id: "py-05",
      worldId: "vila-variaveis",
      title: "Análise de Carga Útil",
      description: "Descubra o tipo da variável 'carga' usando a função type() e imprima o resultado.",
      narrative: "Antes de processar um pacote interceptado, você deve identificar se ele contém texto bruto (str) ou dados numéricos (int). Use o scanner de tipo do sistema.",
      difficulty: "iniciante",
      setupCode: "carga = 1010",
      expectedOutput: "<class 'int'>",
      testCode: "assert \"int\" in output",
      starterCode: "carga = 1010\n# Identifique o tipo de 'carga'\n",
      hints: [
        { text: "A função type(variavel) retorna o tipo do dado.", cost: 10 },
        { text: "Lembre-se de colocar o type() dentro de um print() para ver o resultado.", cost: 20 },
        { text: "print(type(carga))", cost: 30 },
      ],
      xpReward: 180,
      concept: "Tipos de Dados",
      conceptExplanation: "Nem toda informação é igual. O Python diferencia números inteiros (int), textos (str), números decimais (float) e muito mais. A função type() é como um raio-x que revela a natureza secreta de uma variável.\n\nExemplo:\nprint(type(42))      # <class 'int'>\nprint(type('Oi'))    # <class 'str'>",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Scanner finalizado. Os dados foram identificados como 'int'. O sistema de decodificação está ajustado.",
    },
  ],
};
