import { World } from "../types";

export const VILA_VARIAVEIS_WORLD: World = {
  id: "vila-variaveis",
  title: "Cais da Identidade",
  subtitle: "O despertar do Scriptweaver",
  icon: "anchor",
  color: "#0EA5E9",
  lore: "No Cais da Identidade, as brumas do esquecimento começam a se dissipar. Aqui, você deve aprender o Ritual da Atribuição: dar nomes e formas aos fragmentos de energia conhecidos como Variáveis.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-01",
      worldId: "vila-variaveis",
      title: "O Primeiro Eco",
      description: "Use print() para invocar a mensagem 'Ola, Python!'.",
      narrative: "Para acordar a Grande Serpente, você deve emitir um sinal de reconhecimento. O comando print() projeta sua voz no vazio da memória.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Ola, Python!",
      testCode: "assert output.strip() == 'Ola, Python!'",
      starterCode: "# Invoque o primeiro eco no console\n",
      hints: [
        { text: "O ritual print() projeta luz (texto) no console.", cost: 10 },
        { text: "Textos são selados entre aspas simples ou duplas.", cost: 20 },
        { text: "Tente: print('Ola, Python!')", cost: 30 },
      ],
      xpReward: 100,
      concept: "O Ritual do Eco (print)",
      conceptExplanation: "print() é a função mais fundamental. Ela permite que o Scriptweaver visualize o estado do mundo e confira se seus encantamentos estão funcionando corretamente.",
      successNpc: "Lina, Guardiã do Cais",
      successAvatar: "/avatars/guido.webp",
      successStory: "O eco retornou! O Arquipélago sentiu sua presença. O caminho agora está aberto.",
    },
    {
      id: "py-02",
      worldId: "vila-variaveis",
      title: "O Selo da Nomeação",
      description: "Crie uma variável chamada nome com o valor 'Python' e projete-a no console.",
      narrative: "Um Scriptweaver não manipula apenas energia bruta, mas sim essências nomeadas. Guarde o nome da Grande Serpente em um receptáculo e revele-o.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Python",
      testCode: "assert 'nome' in locals() and nome == 'Python' and output.strip() == 'Python'",
      starterCode: "# Sele o nome e revele-o\n",
      hints: [
        { text: "Variáveis são receptáculos: nome = valor.", cost: 10 },
        { text: "Para revelar o conteúdo, chame o ritual print() passando o nome do receptáculo, sem aspas.", cost: 20 },
        { text: "nome = 'Python'\nprint(nome)", cost: 30 },
      ],
      xpReward: 120,
      concept: "Receptáculos de Dados (Variáveis)",
      conceptExplanation: "Variáveis permitem que você capture fragmentos de informação e os rotule. Isso é essencial para que o código 'lembre' de algo mais tarde.",
      successNpc: "Lina, Guardiã do Cais",
      successAvatar: "/avatars/guido.webp",
      successStory: "O selo foi aplicado com perfeição. O nome 'Python' agora vibra em sincronia com o seu poder.",
    },
    {
      id: "py-03",
      worldId: "vila-variaveis",
      title: "A Sincronia das Cargas",
      description: "Crie o receptáculo a com 5, o receptáculo b com 10 e projete a soma das duas energias.",
      narrative: "Dois cristais de energia chegaram ao porto. Combine suas potências para carregar o Farol de Aurora.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "15",
      testCode: "assert a == 5 and b == 10 and output.strip() == '15'",
      starterCode: "# Combine as energias de a e b\na = 5\nb = 10\n",
      hints: [
        { text: "Use o operador + para fundir valores numéricos.", cost: 10 },
        { text: "A fusão deve ser projetada pelo print().", cost: 20 },
        { text: "print(a + b)", cost: 30 },
      ],
      xpReward: 150,
      concept: "Fusão Aritmética (Operadores)",
      conceptExplanation: "Python permite realizar operações matemáticas entre receptáculos. +, -, * e / são as ferramentas básicas de alquimia numérica.",
      successNpc: "Lina, Guardiã do Cais",
      successAvatar: "/avatars/guido.webp",
      successStory: "O Farol de Aurora brilhou intensamente! A soma das energias estabilizou o cais. Você está pronto para navegar.",
    },
  ],
};
