import { World } from "../types";

export const VILA_VARIAVEIS_WORLD: World = {
  id: "vila-variaveis",
  title: "Terminal Alpha",
  subtitle: "Conexão Estabelecida",
  icon: "anchor",
  color: "#0EA5E9",
  lore: "O sistema de segurança isolou o núcleo da cidade (Core). Aqui no Terminal Alpha, você deve inicializar o Protocolo de Alocação: definir variáveis e manipular a memória local para dar o primeiro bypass no firewall primário.",
  unlockRequirement: 0,
  challenges: [
    {
      id: "py-01",
      worldId: "vila-variaveis",
      title: "Ping de Reconhecimento",
      description: "Use print() para enviar a string 'Ola, Python!' ao terminal.",
      narrative: "Para estabelecer handshake com o Core, você deve emitir um sinal de reconhecimento. O comando print() projeta sua assinatura digital no log do sistema.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Ola, Python!",
      testCode: "assert output.strip() == 'Ola, Python!'",
      starterCode: "# Envie seu primeiro ping para o console\n",
      hints: [
        { text: "A instrução print() exibe dados na saída padrão do terminal.", cost: 10 },
        { text: "Strings (textos) devem ser encapsuladas em aspas simples ou duplas.", cost: 20 },
        { text: "Tente: print('Ola, Python!')", cost: 30 },
      ],
      xpReward: 100,
      concept: "Comando de Saída (print)",
      conceptExplanation: "print() é a função mais fundamental da linguagem. Ela permite que o Operador visualize o estado do sistema e confirme se os scripts de intrusão estão rodando como esperado.",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Ping recebido. A porta de entrada registrou sua presença na rede. O acesso ao terminal local foi garantido.",
    },
    {
      id: "py-02",
      worldId: "vila-variaveis",
      title: "Alocação de Memória",
      description: "Declare uma variável chamada nome com o valor 'Python' e imprima-a no console.",
      narrative: "Um Hacker não manipula apenas dados brutos, mas sim endereços nomeados na RAM. Guarde o identificador do sistema em uma variável e leia o seu conteúdo.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "Python",
      testCode: "assert 'nome' in locals() and nome == 'Python' and output.strip() == 'Python'",
      starterCode: "# Aloque os dados e exiba o resultado\n",
      hints: [
        { text: "Variáveis são espaços na memória: nome = valor.", cost: 10 },
        { text: "Para exibir os dados, passe o nome da variável no comando print(), sem aspas.", cost: 20 },
        { text: "nome = 'Python'\nprint(nome)", cost: 30 },
      ],
      xpReward: 120,
      concept: "Endereçamento de Dados (Variáveis)",
      conceptExplanation: "Variáveis permitem capturar pacotes de informação e armazená-los temporariamente sob um rótulo. Isso é essencial para que seu script processe dados posteriormente.",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Bloco de memória alocado com sucesso. O sistema agora reconhece o identificador 'Python' no seu escopo local.",
    },
    {
      id: "py-03",
      worldId: "vila-variaveis",
      title: "Sincronização de Threads",
      description: "A variável a tem valor 5, e b tem valor 10. Imprima a soma desses dois valores.",
      narrative: "Dois pacotes de processamento criptografados chegaram à sua thread. Some suas cargas numéricas para gerar a chave de acesso ao próximo Node.",
      difficulty: "iniciante",
      setupCode: "",
      expectedOutput: "15",
      testCode: "assert a == 5 and b == 10 and output.strip() == '15'",
      starterCode: "# Processe a soma de a e b\na = 5\nb = 10\n",
      hints: [
        { text: "Use o operador + para somar valores inteiros.", cost: 10 },
        { text: "O resultado da soma deve ser passado para dentro do print().", cost: 20 },
        { text: "print(a + b)", cost: 30 },
      ],
      xpReward: 150,
      concept: "Processamento Aritmético (Operadores)",
      conceptExplanation: "O motor do Python permite executar cálculos complexos instantaneamente. +, -, * e / são as operações básicas de hardware que sua sintaxe controla diretamente.",
      successNpc: "AI-7, Módulo Guia",
      successAvatar: "/avatars/guido.webp",
      successStory: "Sincronização concluída! A chave numérica estabilizou a conexão. O Node Primário está online. Você está pronto para avançar na rede.",
    },
  ],
};

